 
input_paths: ["/data/nlahaye/output/Learnergy/No_Data/",
              "/data/nlahaye/output/Learnergy/No_Data/",
              "/mnt/data/GOES_18_CA_COASTAL_FINAL/GOES_CLOUD/"]

 
 
fname_str: "total_phytoplankton.tif"
out_dir: "/mnt/data/GOES_18_CA_COASTAL_FINAL/GOES_CLOUD/DAILY/"
num_classes: 8
re_index: 6

gen_daily: true
gen_monthly: false

