 
input_paths: ["/data/nlahaye/output/Learnergy/No_Data/",
              "/data/nlahaye/output/Learnergy/No_Data/",
              "/mnt/data/HAB_MODEL_WEIGHTS/OC_SIF_HABs_2025/PACE_S_CA/"]

 
 
fname_str: "RRS.V3_0.Rrs.4km.pseudo_nitzschia_delicatissima_bloom.tif"
out_dir: "/mnt/data/HAB_MODEL_WEIGHTS/OC_SIF_HABs_2025/MERGED_HAB/PACE/"
num_classes: 9
re_index: 4

gen_daily: true
gen_monthly: false

