 
input_paths: ["/data/nlahaye/output/Learnergy/No_Data/",
              "/data/nlahaye/output/Learnergy/No_Data/",
              "/mnt/data/GOES_18_CA_COASTAL_FINAL/GOES_CLOUD/"]

 
 
fname_str: "DAY.pseudo_nitzschia_seriata_bloom.tif"
out_dir: "/mnt/data/GOES_18_CA_COASTAL_FINAL/GOES_CLOUD/DAILY/"
num_classes: 9
re_index: 3

gen_daily: true
gen_monthly: false

