
analysis:
 tsne:
  perplexity: 2200
  niter: 5000
  njobs: 50
  exaggeration: 4
  metric: "euclidean"
  patience: 1000
  lr: 200
 embed_func: "clay_init"
 build_knn_graphs: True



data:
 tile: True #True
 tile_size: [16,16,25]
 tile_step: [10,10,25] #128,128
 val_percent: 0.1
 num_loader_workers: 10
 scale_data: True
 pixel_padding: 1
 number_channels: 25 #34
 fill_value: -9999.0
 valid_min:  -900.0
 valid_max: 100000000
 subset_count: 1
 output_subset_count: 1
 reader_type: "gtiff"
 reader_kwargs:
  #none: "none"
  #start_line: 100
  #end_line: 1200
  #start_sample: 2000
  #end_sample: 4000
  no_arg: ''
 chan_dim: 0
 delete_chans: [25,26,27,28,29,30,31,32,33,34,35,36,37]
 transform_default:
  chans: []
  transform: []



 files_train: [
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_20_20190806_2052_2106_V03.tif",
'/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_10_20190806_1858_1910_V03.tif',
'/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19911_10_20190807_2004_2016_V03.tif',
'/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19911_09_20190807_1947_2002_V03.tif',
'/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19912_07_20190808_1806_1821_V03.tif',
"/data//nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_06_20190806_1815_1824_V03.tif",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_20_20190806_2052_2106_V03.tif"
]

 final_labels: [
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_4/eMASL1B_19910_20_20190806_2052_2106_V03.tif.clust.data_78999clusters.zarr.full_geo.tif.fire_smoke.tif.Contours.tif"
]

 files_test: [
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_20_20190806_2052_2106_V03.tif"
]



scaler:
 name: "standard" 

output:
 out_dir: "/data/nlahaye/output/Learnergy/eMAS_Clay_Small/"
 generate_train_output: True
 generate_intermediate_output: False

logger:
 use_wandb: True
 log_model: True
 log_out_dir: "wandb_full"
 project: "SIT-FUSE"

ijepa:
 patch_size: 16
 embed_dim: 1024
 encoder_heads: 8
 encoder_depth: 8
 decoder_depth: 8
 target_aspect_ratio: [0.75,1.5]
 target_scale: [0.15, .2]
 context_aspect_ratio: 1
 context_scale: [0.85,1.0]
 number_target_blocks: 4

encoder_type: "clay"
encoder:
 subset_training: 5000 #-1 #2300000
 overwrite_model: False
 tune_scaler: False
 training:
  weight_decay: 0.05
  momentum: 0.996
  momentum_start_end: [0.996, 1.0] 
  learning_rate: 0.001
  batch_size: 10
  epochs: 100
  accelerator: "gpu"
  devices: 4
  gradient_clip_val: 0.1
  precision: "16-mixed"
  save_dir: "wandb_ijepa_full"
  stratify_data:
   kmeans: True

cluster:
 gsd: 50
 waves: [0.465, 0.549, 0.655, 0.703, 0.743, 0.825, 0.867, 0.908, 0.947, 1.619, 1.675, 1.727, 1.779, 1.832, 1.882, 1.932, 1.982, 2.032, 2.081, 2.130, 2.179, 2.229, 2.279, 2.328, 2.378]
 gauss_noise_stdev:  [0.01]
 lambda: 1.0
 num_classes: 800
 training:
  finetune_encoder: False
  learning_rate: 0.0001
  batch_size: 2
  epochs: 10 
  accelerator: "gpu"
  devices: 1
  gradient_clip_val: 0.01
  precision: "16-mixed"
  save_dir: "wandb_ijepa_full"

 heir:
  tiers: 1
  gauss_noise_stdev:  [0.01]
  lambda: 1.0
  num_classes: 100
  training:
   accelerator: "gpu"
   devices: 1
   gradient_clip_val: 0.1
   precision: "32"
   save_dir: "wandb_ijepa_full"
   batch_size: 4
   min_samples: 1000
   epochs: 5
   lambda: 1.0
 
