
data:
 tile: False
 val_percent: 0.1
 num_loader_workers: 10
 scale_data: True
 pixel_padding: 1
 number_channels: 92
 fill_value: -9999.0
 valid_min:  -900.0
 valid_max: 100000000
 reader_type: "gtiff"
 reader_kwargs:
  no_arg: "no_arg"
 chan_dim: 0
 delete_chans: [25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,81,82,83,84,85,86,87,88,89,80,91] 
 transform_default:
  chans: []
  transform: []

 files_train: [
"/data/nlahaye/remoteSensing/MSPI_SAS_eMAS_Fuse/MSPI_eMAS_20190806_183632Z.tif",
"/data/nlahaye/remoteSensing/MSPI_SAS_eMAS_Fuse/MSPI_eMAS_20190806_190054Z.tif",
"/data/nlahaye/remoteSensing/MSPI_SAS_eMAS_Fuse/MSPI_eMAS_20190806_200308Z.tif",
"/data/nlahaye/remoteSensing/MSPI_SAS_eMAS_Fuse/MSPI_eMAS_20190806_202139Z.tif",
"/data/nlahaye/remoteSensing/MSPI_SAS_eMAS_Fuse/MSPI_eMAS_20190806_205617Z.tif",
"/data/nlahaye/remoteSensing/MSPI_SAS_eMAS_Fuse/MSPI_eMAS_20190806_211454Z.tif",
"/data/nlahaye/remoteSensing/MSPI_SAS_eMAS_Fuse/MSPI_eMAS_20190807_182404Z.tif",
"/data/nlahaye/remoteSensing/MSPI_SAS_eMAS_Fuse/MSPI_eMAS_20190807_193214Z.tif",
"/data/nlahaye/remoteSensing/MSPI_SAS_eMAS_Fuse/MSPI_eMAS_20190807_195226Z.tif",
"/data/nlahaye/remoteSensing/MSPI_SAS_eMAS_Fuse/MSPI_eMAS_20190807_200717Z.tif",
"/data/nlahaye/remoteSensing/MSPI_SAS_eMAS_Fuse/MSPI_eMAS_20190807_202502Z.tif",
"/data/nlahaye/remoteSensing/MSPI_SAS_eMAS_Fuse/MSPI_eMAS_20190807_204231Z.tif"
]

 files_test: [
"/data/nlahaye/remoteSensing/MSPI_SAS_eMAS_Fuse/MSPI_eMAS_20190808_174846Z.tif",
"/data/nlahaye/remoteSensing/MSPI_SAS_eMAS_Fuse/MSPI_eMAS_20190808_181151Z.tif",
"/data/nlahaye/remoteSensing/MSPI_SAS_eMAS_Fuse/MSPI_eMAS_20190821_224247Z.tif",
]


scaler:
 name: "standard" 

output:
 out_dir: "/data/nlahaye/output/Learnergy/DBN_eMAS_MSPI_SAS/"
 generate_intermediate_output: True


dbn:
 model_type: ["gaussian_selu", "gaussian_selu", "gaussian_selu"]
 dbn_arch: [3000, 2000, 1000] #[250, 500, 2000] #, 2000]
 gibbs_steps: [1,1,1] #, 7, 7] #, 10] #, 25]
 temp: [1.0, 1.0, 1.0] #, 1.0, 1.0] ##[0.9, 0.75, 0.5] #, 1.0] #, 0.5] #, 0.5] 
 normalize_learnergy: [False, True, True]
 batch_normalize: [False, False, False]

encoder_type: "dbn"
encoder:
 tiled: False
 tune_scaler: False
 subset_training: 2000000
 overwrite_model: False
 training:
  learning_rate: [0.00001, 0.00001, 0.00001]
  momentum: [0.95,0.95, 0.95]
  weight_decay: [0.0001, 0.0001, 0.0001]
  nesterov_accel: [True, True, True]
  batch_size: 128
  epochs: 30
  accelerator: "gpu"
  devices: 1
  gradient_clip_val: 0.1
  precision: "16-mixed"
  save_dir: "wandb_encoder"
  stratify_data:
   kmeans: True


logger:
 use_wandb: True
 log_model: True
 log_out_dir: "wandb_dbn"
 project: "SIT-FUSE"

cluster:
 gauss_noise_stdev:  [0.01]
 lambda: 1.0
 num_classes: 800
 training:
  learning_rate: 0.0001
  batch_size: 1000
  epochs: 30
  accelerator: "gpu"
  devices: 1
  gradient_clip_val: 0.1
  precision: "16-mixed"
  save_dir: "wandb_full_model"

 heir:
  tiers: 1
  gauss_noise_stdev:  [0.01]
  lambda: 1.0
  num_classes: 100
  training:
   accelerator: "gpu"
   devices: 1
   gradient_clip_val: 0.1
   precision: "16-mixed"
   save_dir: "wandb_dbn_full_model_heir"
   batch_size: 100
   min_samples: 1000
   learning_rate: 0.0001
   batch_size: 1000
   epochs: 30



