
data:
 tile: False
 val_percent: 0.1
 num_loader_workers: 10
 scale_data: True
 pixel_padding: 1
 number_channels: 35
 fill_value: -9999.0
 valid_min:  -900.0
 valid_max: 100000000
 reader_type: "emas_hdf"
 reader_kwargs:
  no_arg: "no_arg"
 chan_dim: 0
 delete_chans: [25,26,36,37]
 transform_default:
  chans: []
  transform: []


 files_train: [
'/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_10_20190806_1858_1910_V03.hdf',
'/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19911_10_20190807_2004_2016_V03.hdf',
'/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19911_09_20190807_1947_2002_V03.hdf',
'/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19912_07_20190808_1806_1821_V03.hdf'
]

 files_test: [
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19916_01_20190816_2008_2012_V03.hdf",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19916_02_20190816_2012_2018_V03.hdf",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19916_03_20190816_2019_2036_V03.hdf",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19916_04_20190816_2037_2044_V03.hdf",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19916_05_20190816_2044_2100_V03.hdf",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19916_06_20190816_2104_2118_V03.hdf",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19916_07_20190816_2122_2135_V03.hdf",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19916_08_20190816_2138_2150_V03.hdf",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19916_09_20190816_2152_2200_V03.hdf",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19916_10_20190816_2201_2214_V03.hdf",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19916_11_20190816_2219_2234_V03.hdf",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19916_12_20190816_2238_2252_V03.hdf",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19916_13_20190816_2255_2310_V03.hdf",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19916_14_20190816_2313_2327_V03.hdf",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19916_15_20190816_2330_2345_V03.hdf",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19916_16_20190816_2349_0002_V03.hdf",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19916_17_20190817_0006_0020_V03.hdf",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19916_18_20190817_0023_0036_V03.hdf",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19916_19_20190817_0040_0054_V03.hdf",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19916_20_20190817_0057_0108_V03.hdf"
]

scaler:
 name: "standard" 

output:
 out_dir: "/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/"
 generate_intermediate_output: True


dbn:
 model_type: ["gaussian_selu", "gaussian_selu"]
 dbn_arch: [2000, 1000] #[250, 500, 2000] #, 2000]
 gibbs_steps: [1,1] #, 7, 7] #, 10] #, 25]
 temp: [1.0, 1.0] #, 1.0, 1.0] ##[0.9, 0.75, 0.5] #, 1.0] #, 0.5] #, 0.5] 
 normalize_learnergy: [False, True]
 batch_normalize: [False, False]

encoder_type: "dbn"
encoder:
 tiled: False
 tune_scaler: False
 subset_training: 2000000
 overwrite_model: False
 training:
  learning_rate: [0.00001, 0.00001]
  momentum: [0.95,0.95]
  weight_decay: [0.0001, 0.0001]
  nesterov_accel: [True, True]
  batch_size: 128
  epochs: 30
  accelerator: "gpu"
  devices: 1
  gradient_clip_val: 0.1
  precision: "16-mixed"
  save_dir: "wandb_encoder"
  stratify_data:
   kmeans: True


logger:
 use_wandb: True
 log_model: True
 log_out_dir: "wandb_dbn"
 project: "SIT-FUSE"

cluster:
 gauss_noise_stdev:  [0.01]
 lambda: 1.0
 num_classes: 800
 training:
  learning_rate: 0.0001
  batch_size: 1000
  epochs: 30
  accelerator: "gpu"
  devices: 1
  gradient_clip_val: 0.1
  precision: "16-mixed"
  save_dir: "wandb_full_model"

 heir:
  tiers: 1
  gauss_noise_stdev:  [0.01]
  lambda: 1.0
  num_classes: 100
  training:
   accelerator: "gpu"
   devices: 1
   gradient_clip_val: 0.1
   precision: "16-mixed"
   save_dir: "wandb_dbn_full_model_heir"
   batch_size: 100
   min_samples: 1000
   learning_rate: 0.0001
   batch_size: 1000
   epochs: 30



