
analysis:
 tsne:
  perplexity: 2200
  niter: 5000
  njobs: 50
  exaggeration: 4
  metric: "euclidean"
  patience: 1000
  lr: 200
 embed_func: "dbn_conv_2_layer_2000"
 build_knn_graphs: True


data:
 tile: True 
 tile_size: [16,16,25]
 tile_step: [10,10,25]
 val_percent: 0.1
 num_loader_workers: 10
 scale_data: True
 pixel_padding: 1
 fill_value: -9999.0
 valid_min:  -900.0
 valid_max: 100000000
 subset_count: 1
 output_subset_count: 1
 reader_type: "gtiff"
 number_channels: 25
 reader_type: "gtiff"
 reader_kwargs:
  no_arg: "no_arg"
 chan_dim: 0
 delete_chans: [25,26,27,28,29,30,31,32,33,34,35,36,37]
 transform_default:
  chans: []
  transform: []


 files_train: [
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19909_01_20190802_1929_1943_V03.tif",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19909_02_20190802_1944_1959_V03.tif",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19909_03_20190802_2004_2018_V03.tif",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19909_04_20190802_2019_2028_V03.tif",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19909_05_20190802_2029_2043_V03.tif",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19909_06_20190802_2056_2108_V03.tif",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19909_07_20190802_2116_2128_V03.tif",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19909_08_20190802_2129_2151_V03.tif",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19909_09_20190802_2152_2205_V03.tif",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19909_10_20190802_2210_2223_V03.tif",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_01_20190806_1633_1707_V03.tif",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_02_20190806_1708_1734_V03.tif",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_03_20190806_1734_1801_V03.tif",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_04_20190806_1801_1811_V03.tif",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_05_20190806_1811_1815_V03.tif",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_06_20190806_1815_1824_V03.tif",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_07_20190806_1826_1831_V03.tif",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_08_20190806_1834_1846_V03.tif",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_09_20190806_1849_1855_V03.tif",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_10_20190806_1858_1910_V03.tif",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_11_20190806_1912_1918_V03.tif",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_12_20190806_1920_1922_V03.tif",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_13_20190806_1923_1925_V03.tif",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_14_20190806_1926_1929_V03.tif",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_15_20190806_1931_1938_V03.tif",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_16_20190806_1941_1956_V03.tif",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_17_20190806_2000_2010_V03.tif",
]

 files_test: [
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_20_20190806_2052_2106_V03.tif"
]

 final_labels: [
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_4/eMASL1B_19910_20_20190806_2052_2106_V03.tif.clust.data_78999clusters.zarr.full_geo.tif.fire_smoke.tif.Contours.tif"
]



scaler:
 name: "standard" 

output:
 out_dir: "/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3_CONV/"
 generate_intermediate_output: True


dbn:
 model_type: "gaussian"
 dbn_arch: [[100,200],[[3,3],[3,3]]]
 gibbs_steps: [3,3] #, 7, 7] #, 10] #, 25]
 temp: [1.0, 1.0] #, 1.0, 1.0] ##[0.9, 0.75, 0.5] #, 1.0] #, 0.5] #, 0.5] 
 normalize_learnergy: [True, True]
 batch_normalize: [True, True]
 stride: [1,1]
 padding: [1,1]
 
encoder_type: "conv_dbn"
encoder:
 tiled: True
 tune_scaler: False
 subset_training: -1
 overwrite_model: False
 training:
  learning_rate: [0.00005, 0.00005]
  momentum: [0.95,0.95]
  weight_decay: [0.0001, 0.0001]
  nesterov_accel: [True, True]
  batch_size: 8
  epochs: 30
  accelerator: "gpu"
  devices: 1
  gradient_clip_val: 0.1
  precision: "16-mixed"
  save_dir: "wandb_encoder"
  stratify_data:

logger:
 use_wandb: True
 log_model: True
 log_out_dir: "wandb_dbn"
 project: "SIT-FUSE"

cluster:
 gauss_noise_stdev:  [0.01]
 lambda: 1.0
 num_classes: 200
 training:
  learning_rate: 0.0001
  batch_size: 10
  epochs: 30
  accelerator: "gpu"
  devices: 1
  gradient_clip_val: 0.1
  precision: "16-mixed"
  save_dir: "wandb_full_model"

 heir:
  tiers: 1
  gauss_noise_stdev:  [0.01]
  lambda: 1.0
  num_classes: 200
  training:
   accelerator: "gpu"
   devices: 1
   gradient_clip_val: 0.1
   precision: "16-mixed"
   save_dir: "wandb_dbn_full_model_heir"
   batch_size: 10
   min_samples: 1000
   learning_rate: 0.0001
   epochs: 10



