
data:
 tile: True 
 tile_size: [224,224,34]
 tile_step: [224,224,34]
 val_percent: 0.1
 num_loader_workers: 10
 scale_data: True
 pixel_padding: 1
 fill_value: -9999.0
 valid_min:  -900.0
 valid_max: 100000000
 subset_count: 1
 output_subset_count: 1
 reader_type: "gtiff"
 number_channels: 34
 reader_type: "emas_hdf"
 reader_kwargs:
  no_arg: "no_arg"
 chan_dim: 0
 delete_chans: [25,26,36,37]
 transform_default:
  chans: []
  transform: []


 files_train: [
'/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_10_20190806_1858_1910_V03.hdf',
'/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19911_10_20190807_2004_2016_V03.hdf',
'/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19911_09_20190807_1947_2002_V03.hdf',
'/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19912_07_20190808_1806_1821_V03.hdf'
]

 files_test: [
'/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19911_05_20190807_1817_1833_V03.hdf',
'/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_06_20190806_1815_1824_V03.hdf',
'/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19912_07_20190808_1806_1821_V03.hdf',
'/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_21_20190806_2111_2125_V03.hdf',
'/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_19_20190806_2035_2048_V03.hdf',
'/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19911_08_20190807_1928_1942_V03.hdf',
'/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19911_12_20190807_2039_2051_V03.hdf',
'/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19911_11_20190807_2021_2035_V03.hdf',
'/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_17_20190806_2000_2010_V03.hdf',
'/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_16_20190806_1941_1956_V03.hdf',
'/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_13_20190806_1923_1925_V03.hdf',
'/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_20_20190806_2052_2106_V03.hdf',
'/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_06_20190806_1815_1824_V03.hdf',
'/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_08_20190806_1834_1846_V03.hdf',
'/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_18_20190806_2018_2031_V03.hdf',
'/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_15_20190806_1931_1938_V03.hdf',
'/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_14_20190806_1926_1929_V03.hdf',
'/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_10_20190806_1858_1910_V03.hdf',
'/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19911_10_20190807_2004_2016_V03.hdf',
'/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19911_09_20190807_1947_2002_V03.hdf'
]

scaler:
 name: "standard" 

output:
 out_dir: "/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3_CONV/"
 generate_intermediate_output: True


dbn:
 model_type: "gaussian"
 dbn_arch: [[100,200],[[3,3],[3,3]]]
 gibbs_steps: [3,3] #, 7, 7] #, 10] #, 25]
 temp: [1.0, 1.0] #, 1.0, 1.0] ##[0.9, 0.75, 0.5] #, 1.0] #, 0.5] #, 0.5] 
 normalize_learnergy: [True, True]
 batch_normalize: [True, True]
 stride: [1,1]
 padding: [1,1]
 
encoder_type: "conv_dbn"
encoder:
 tiled: False
 tune_scaler: False
 subset_training: -1
 overwrite_model: False
 training:
  learning_rate: [0.00005, 0.00005]
  momentum: [0.95,0.95]
  weight_decay: [0.0001, 0.0001]
  nesterov_accel: [True, True]
  batch_size: 8
  epochs: 30
  accelerator: "gpu"
  devices: 3
  gradient_clip_val: 0.1
  precision: "16-mixed"
  save_dir: "wandb_encoder"
  stratify_data:

logger:
 use_wandb: True
 log_model: True
 log_out_dir: "wandb_dbn"
 project: "SIT-FUSE"

cluster:
 gauss_noise_stdev:  [0.01]
 lambda: 1.0
 num_classes: 200
 training:
  learning_rate: 0.0001
  batch_size: 1
  epochs: 30
  accelerator: "gpu"
  devices: 1
  gradient_clip_val: 0.1
  precision: "16-mixed"
  save_dir: "wandb_full_model"

 heir:
  tiers: 1
  gauss_noise_stdev:  [0.01]
  lambda: 1.0
  num_classes: 200
  training:
   accelerator: "gpu"
   devices: 1
   gradient_clip_val: 0.1
   precision: "16-mixed"
   save_dir: "wandb_dbn_full_model_heir"
   batch_size: 1
   min_samples: 1000
   learning_rate: 0.0001
   epochs: 30



