
data:
 tile: False
 val_percent: 0.1
 num_loader_workers: 10
 scale_data: True
 pixel_padding: 2
 number_channels: 6
 fill_value: 0.0
 valid_min: 0.0000001
 valid_max: 100000000
 subset_count: 1
 output_subset_count: 1
 reader_type: "gtiff"
 reader_kwargs:
  no_arg: ''
 chan_dim: 0
 delete_chans: []
 transform_default:
  chans: []
  transform: []
 files_train: [
"/mnt/data/PV_Mapping/urban_small_road_clipped.tif",
"/mnt/data/PV_Mapping/large_urban_gambia_clipped_4.tif",
]


 files_test: [
"/mnt/data/PV_Mapping/large_urban_gambia_clipped_5.tif",
         "/mnt/data/PV_Mapping/large_urban_gambia_clipped_2.tif",
"/mnt/data/PV_Mapping/large_urban_gambia_clipped_6.tif",
         "/mnt/data/PV_Mapping/large_urban_gambia_clipped_0.tif",
"/mnt/data/PV_Mapping/large_urban_gambia_clipped_1.tif",
"/mnt/data/PV_Mapping/large_urban_gambia_clipped_10.tif",
"/mnt/data/PV_Mapping/large_urban_gambia_clipped_12.tif",
"/mnt/data/PV_Mapping/large_urban_gambia_clipped_13.tif",
"/mnt/data/PV_Mapping/large_urban_gambia_clipped_14.tif",
"/mnt/data/PV_Mapping/large_urban_gambia_clipped_7.tif",
"/mnt/data/PV_Mapping/large_urban_gambia_clipped_8.tif",
"/mnt/data/PV_Mapping/large_urban_gambia_clipped_9.tif",
"/mnt/data/PV_Mapping/large_urban_gambia_clipped_11.tif",
"/mnt/data/PV_Mapping/large_urban_gambia_clipped_15.tif",
"/mnt/data/PV_Mapping/large_urban_gambia_clipped_3.tif",
]


scaler:
 name: "standard" 

output:
 out_dir: "/mnt/data/DBN_PV_MAPPING_WIDE_ROAD_CLIP/"
 generate_intermediate_output: True


dbn:
 model_type: ["gaussian_selu", "gaussian_selu", "gaussian_selu"]
 dbn_arch: [3000, 2500, 2000] #[250, 500, 2000] #, 2000]
 gibbs_steps: [1,1,1] #, 7, 7] #, 10] #, 25]
 temp: [1.0, 1.0,1.0] #, 1.0, 1.0] ##[0.9, 0.75, 0.5] #, 1.0] #, 0.5] #, 0.5] 
 normalize_learnergy: [False, True, True]
 batch_normalize: [False, False, False]

encoder_type: "dbn"
encoder:
 tiled: False
 tune_scaler: False
 subset_training: 10000000
 overwrite_model: False
 training:
  learning_rate: [0.00001, 0.00001, 0.00001]
  momentum: [0.95,0.95,0.95]
  weight_decay: [0.0001, 0.0001,0.0001]
  nesterov_accel: [True, True, True]
  batch_size: 128
  epochs: 100
  accelerator: "gpu"
  devices: 1
  gradient_clip_val: 0.1
  precision: "16-mixed"
  save_dir: "wandb_encoder"
  stratify_data:
   kmeans: True


logger:
 use_wandb: True
 log_model: True
 log_out_dir: "wandb_dbn"
 project: "SIT-FUSE"

cluster:
 gauss_noise_stdev:  [0.01]
 lambda: 1.0
 num_classes: 800
 training:
  learning_rate: 0.0001
  batch_size: 1000
  epochs: 100
  accelerator: "gpu"
  devices: 1
  gradient_clip_val: 0.1
  precision: "16-mixed"
  save_dir: "wandb_full_model"

 heir:
  tiers: 1
  gauss_noise_stdev:  [0.01]
  lambda: 1.0
  num_classes: 100
  training:
   accelerator: "gpu"
   devices: 1
   gradient_clip_val: 0.1
   precision: "16-mixed"
   save_dir: "wandb_dbn_full_model_heir"
   batch_size: 100
   min_samples: 1000
   learning_rate: 0.0001
   batch_size: 1000
   epochs: 100



