
data:
 tile: True
 tile_size: [16,16,6]
 tile_step: [4,4,6]
 val_percent: 0.1
 num_loader_workers: 10
 scale_data: True
 pixel_padding: 1
 number_channels: 6
 fill_value: 0.0
 valid_min: 0.0000001
 valid_max: 100000000
 subset_count: 1
 output_subset_count: 1
 reader_type: "gtiff"
 reader_kwargs:
  no_arg: ''
 chan_dim: 0
 delete_chans: []
 transform_default:
  chans: []
  transform: []
 files_train: [
"/mnt/data/PV_Mapping/gambia_6_band_test.tif"
]


 files_test: [
"/mnt/data/PV_Mapping/gambia_6_band_test.tif"
]


scaler:
 name: "standard" 

output:
 out_dir: "/mnt/data/DBN_PV_MAPPING_CDBN/"
 generate_intermediate_output: True


dbn:
 model_type: "gaussian"
 dbn_arch: [[100,200],[[3,3],[3,3]]]
 gibbs_steps: [3,3] #, 7, 7] #, 10] #, 25]
 temp: [1.0, 1.0] #, 1.0, 1.0] ##[0.9, 0.75, 0.5] #, 1.0] #, 0.5] #, 0.5] 
 normalize_learnergy: [True, True]
 batch_normalize: [True, True]
 stride: [1,1]
 padding: [1,1]

encoder_type: "conv_dbn"
encoder:
 tiled: True
 tune_scaler: False
 subset_training: -1 #8000000
 overwrite_model: False
 training:
  learning_rate: [0.00005, 0.00005]
  momentum: [0.95,0.95]
  weight_decay: [0.0001, 0.0001]
  nesterov_accel: [True, True]
  batch_size: 128
  epochs: 100
  accelerator: "gpu"
  devices: 1
  gradient_clip_val: 0.1
  precision: "16-mixed"
  save_dir: "wandb_encoder"
  stratify_data:



logger:
 use_wandb: True
 log_model: True
 log_out_dir: "wandb_dbn"
 project: "SIT-FUSE"

cluster:
 gauss_noise_stdev:  [0.01]
 lambda: 1.0
 num_classes: 800
 training:
  learning_rate: 0.0001
  batch_size: 100
  epochs: 10 
  accelerator: "gpu"
  devices: 1
  gradient_clip_val: 0.1
  precision: "16-mixed"
  save_dir: "wandb_full_model"

 heir:
  tiers: 1
  gauss_noise_stdev:  [0.01]
  lambda: 1.0
  num_classes: 100
  training:
   accelerator: "gpu"
   devices: 1
   gradient_clip_val: 0.1
   precision: "16-mixed"
   save_dir: "wandb_dbn_full_model_heir"
   batch_size: 100
   min_samples: 1000
   learning_rate: 0.0001
   epochs: 10



