


/home/nlahaye/SIT_FUSE/src/sit_fuse/config/model/pace_only_gulf_of_mexico_multi_layer_pl_s_ca_embed.yaml
/home/nlahaye/SIT_FUSE/src/sit_fuse/config/model/pace_only_gulf_of_mexico_no_encoder_s_ca_embed_.yaml
/home/nlahaye/SIT_FUSE/src/sit_fuse/config/model/pace_only_gulf_of_mexico_pca_s_ca_embed.yaml





