
scaler:
 name: "standard"

data:
 tile: false
 val_percent: 0.1
 num_loader_workers: 10
 scale_data: True
 pixel_padding: 1
 number_channels: 23
 fill_value: -9999.0
 valid_min: -1000.0
 valid_max: 1000000
 reader_type: "gtiff_multifile"
 reader_kwargs:
  grayscale: True
 chan_dim: 0
 delete_chans: []
 transform_default:
  chans: []
  transform: []
 files_test: [
["/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_vis01_20190807_181000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_vis02_20190807_181000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_vis03_20190807_181000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_vis04_20190807_181000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_vis05_20190807_181000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_vis06_20190807_181000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_vis07_20190807_181000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_vis26_20190807_181000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt20_20190807_181000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt22_20190807_181000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt23_20190807_181000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt24_20190807_181000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt25_20190807_181000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt27_20190807_181000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt28_20190807_181000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt29_20190807_181000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt30_20190807_181000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt31_20190807_181000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt32_20190807_181000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt33_20190807_181000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt34_20190807_181000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt35_20190807_181000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt36_20190807_181000_wgs84_fit.tif"],
["/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_vis01_20190808_185000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_vis02_20190808_185000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_vis03_20190808_185000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_vis04_20190808_185000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_vis05_20190808_185000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_vis06_20190808_185000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_vis07_20190808_185000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_vis26_20190808_185000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt20_20190808_185000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt22_20190808_185000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt23_20190808_185000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt24_20190808_185000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt25_20190808_185000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt27_20190808_185000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt28_20190808_185000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt29_20190808_185000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt30_20190808_185000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt31_20190808_185000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt32_20190808_185000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt33_20190808_185000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt34_20190808_185000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt35_20190808_185000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt36_20190808_185000_wgs84_fit.tif"],
["/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_vis01_20190806_205000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_vis02_20190806_205000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_vis03_20190806_205000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_vis04_20190806_205000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_vis05_20190806_205000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_vis06_20190806_205000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_vis07_20190806_205000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_vis26_20190806_205000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt20_20190806_205000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt22_20190806_205000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt23_20190806_205000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt24_20190806_205000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt25_20190806_205000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt27_20190806_205000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt28_20190806_205000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt29_20190806_205000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt30_20190806_205000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt31_20190806_205000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt32_20190806_205000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt33_20190806_205000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt34_20190806_205000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt35_20190806_205000_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt36_20190806_205000_wgs84_fit.tif"],
]





 files_train: [
["/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_vis01_20190807_194500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_vis02_20190807_194500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_vis03_20190807_194500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_vis04_20190807_194500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_vis05_20190807_194500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_vis06_20190807_194500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_vis07_20190807_194500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_vis26_20190807_194500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt20_20190807_194500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt22_20190807_194500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt23_20190807_194500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt24_20190807_194500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt25_20190807_194500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt27_20190807_194500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt28_20190807_194500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt29_20190807_194500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt30_20190807_194500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt31_20190807_194500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt32_20190807_194500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt33_20190807_194500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt34_20190807_194500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt35_20190807_194500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/terra_modis_bt36_20190807_194500_wgs84_fit.tif"],
["/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_vis01_20190807_195500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_vis02_20190807_195500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_vis03_20190807_195500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_vis04_20190807_195500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_vis05_20190807_195500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_vis06_20190807_195500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_vis07_20190807_195500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_vis26_20190807_195500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt20_20190807_195500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt22_20190807_195500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt23_20190807_195500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt24_20190807_195500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt25_20190807_195500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt27_20190807_195500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt28_20190807_195500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt29_20190807_195500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt30_20190807_195500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt31_20190807_195500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt32_20190807_195500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt33_20190807_195500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt34_20190807_195500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt35_20190807_195500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt36_20190807_195500_wgs84_fit.tif"],
["/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_vis01_20190808_203500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_vis02_20190808_203500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_vis03_20190808_203500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_vis04_20190808_203500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_vis05_20190808_203500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_vis06_20190808_203500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_vis07_20190808_203500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_vis26_20190808_203500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt20_20190808_203500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt22_20190808_203500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt23_20190808_203500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt24_20190808_203500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt25_20190808_203500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt27_20190808_203500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt28_20190808_203500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt29_20190808_203500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt30_20190808_203500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt31_20190808_203500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt32_20190808_203500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt33_20190808_203500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt34_20190808_203500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt35_20190808_203500_wgs84_fit.tif",
"/data/nlahaye/remoteSensing/CSDSA/MISR_MODIS_VIIRS_WF/MODIS/inputs/cropped/aqua_modis_bt36_20190808_203500_wgs84_fit.tif"],
]



output:
 out_dir: "/data/nlahaye/output/Learnergy/MODIS_FIREX/"
 generate_train_output: True
 generate_intermediate_output: True


dbn:
 model_type: ["gaussian_selu", "gaussian_selu"]
 dbn_arch: [2000, 1000] #[250, 500, 2000] #, 2000]
 gibbs_steps: [1,1] #, 7, 7] #, 10] #, 25]
 temp: [1.0, 1.0] #, 1.0, 1.0] ##[0.9, 0.75, 0.5] #, 1.0] #, 0.5] #, 0.5] 
 normalize_learnergy: [False, True]
 batch_normalize: [False, False]

encoder_type: "dbn"
encoder:
 tiled: False
 tune_scaler: False
 subset_training: -1 #2500000
 overwrite_model: False
 training:
  learning_rate: [0.00001, 0.00001]
  momentum: [0.95,0.95]
  weight_decay: [0.0001, 0.0001]
  nesterov_accel: [True, True]
  batch_size: 128
  epochs: 100
  accelerator: "gpu"
  devices: 1
  gradient_clip_val: 0.1
  precision: "16-mixed"
  save_dir: "wandb_encoder"
  stratify_data:
   kmeans: True


logger:
 use_wandb: True
 log_model: True
 log_out_dir: "wandb_dbn"
 project: "SIT-FUSE"

cluster:
 gauss_noise_stdev:  [0.01]
 lambda: 1.0
 num_classes: 800
 training:
  learning_rate: 0.0001
  batch_size: 1000
  epochs: 100
  accelerator: "gpu"
  devices: 1
  gradient_clip_val: 0.1
  precision: "16-mixed"
  save_dir: "wandb_full_model"

 heir:
  tiers: 1
  gauss_noise_stdev:  [0.01]
  lambda: 1.0
  num_classes: 100
  training:
   accelerator: "gpu"
   devices: 1
   gradient_clip_val: 0.1
   precision: "16-mixed"
   save_dir: "wandb_dbn_full_model_heir"
   batch_size: 100
   min_samples: 1000
   learning_rate: 0.0001
   batch_size: 1000
   epochs: 100



