analysis:
 tsne:
  perplexity: 2200
  niter: 5000
  njobs: 50
  exaggeration: 4
  metric: "euclidean"
  patience: 1000
  lr: 200
 run_projection: True
 embed_func: "dbn_2_layer_2000"
 build_knn_graphs: True


data:
 tile: False
 tile_size: [3,3,32]
 tile_step: [1,1,32]
 num_loader_workers: 10
 val_percent: 0.1
 scale_data: True
 pixel_padding: 1
 number_channels: 5
 fill_value: -999999.0
 valid_min: -10000.0
 valid_max: 6400000
 subset_count: 1
 output_subset_count: 1
 reader_type: "oc_and_trop"
 reader_kwargs: 
  start_lon: -97.8985
  end_lon: -80.5301
  start_lat: 18.1599
  end_lat: 30.4159
  #mask_shp: "/data/nlahaye/remoteSensing/Lakes/glwd_1.shp"
  mask_oceans: True
 chan_dim: 0
 delete_chans: []
 transform_default:
  chans: []
  transform: []

 files_train: [
["/data/nlahaye/remoteSensing/Multi_Year_WQ/AQUA_MODIS.20180807.L3m.DAY.","/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_redSIF_2018-08-07_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/AQUA_MODIS.20190831.L3m.DAY.","/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_redSIF_2019-08-31_ungridded.nc"]]

 files_test: [
["/data/nlahaye/remoteSensing/Multi_Year_WQ/AQUA_MODIS.20190901.L3m.DAY.","/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_redSIF_2019-09-01_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/AQUA_MODIS.20190902.L3m.DAY.","/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_redSIF_2019-09-02_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/AQUA_MODIS.20190903.L3m.DAY.","/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_redSIF_2019-09-03_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/AQUA_MODIS.20190904.L3m.DAY.","/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_redSIF_2019-09-04_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/AQUA_MODIS.20190905.L3m.DAY.","/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_redSIF_2019-09-05_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/AQUA_MODIS.20190906.L3m.DAY.","/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_redSIF_2019-09-06_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/AQUA_MODIS.20190907.L3m.DAY.","/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_redSIF_2019-09-07_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/AQUA_MODIS.20190908.L3m.DAY.","/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_redSIF_2019-09-08_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/AQUA_MODIS.20190909.L3m.DAY.","/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_redSIF_2019-09-09_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/AQUA_MODIS.20190910.L3m.DAY.","/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_redSIF_2019-09-10_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/AQUA_MODIS.20190911.L3m.DAY.","/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_redSIF_2019-09-11_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/AQUA_MODIS.20190912.L3m.DAY.","/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_redSIF_2019-09-12_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/AQUA_MODIS.20190913.L3m.DAY.","/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_redSIF_2019-09-13_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/AQUA_MODIS.20190914.L3m.DAY.","/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_redSIF_2019-09-14_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/AQUA_MODIS.20190915.L3m.DAY.","/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_redSIF_2019-09-15_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/AQUA_MODIS.20190916.L3m.DAY.","/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_redSIF_2019-09-16_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/AQUA_MODIS.20190917.L3m.DAY.","/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_redSIF_2019-09-17_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/AQUA_MODIS.20190918.L3m.DAY.","/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_redSIF_2019-09-18_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/AQUA_MODIS.20190919.L3m.DAY.","/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_redSIF_2019-09-19_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/AQUA_MODIS.20190920.L3m.DAY.","/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_redSIF_2019-09-20_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/AQUA_MODIS.20190921.L3m.DAY.","/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_redSIF_2019-09-21_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/AQUA_MODIS.20190922.L3m.DAY.","/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_redSIF_2019-09-22_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/AQUA_MODIS.20190923.L3m.DAY.","/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_redSIF_2019-09-23_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/AQUA_MODIS.20190924.L3m.DAY.","/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_redSIF_2019-09-24_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/AQUA_MODIS.20190925.L3m.DAY.","/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_redSIF_2019-09-25_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/AQUA_MODIS.20190926.L3m.DAY.","/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_redSIF_2019-09-26_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/AQUA_MODIS.20190927.L3m.DAY.","/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_redSIF_2019-09-27_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/AQUA_MODIS.20190928.L3m.DAY.","/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_redSIF_2019-09-28_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/AQUA_MODIS.20190929.L3m.DAY.","/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_redSIF_2019-09-29_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/AQUA_MODIS.20190930.L3m.DAY.","/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_redSIF_2019-09-30_ungridded.nc"],
]


scaler:
 name: "standard" 

output:
 out_dir: "/data/nlahaye/output/Learnergy/MODIS_Gulf_of_Mexico/"
 generate_intermediate_output: True


dbn:
 model_type: ["gaussian_selu", "gaussian_selu"]
 dbn_arch: [2000, 1000] #[250, 500, 2000] #, 2000]
 gibbs_steps: [1,1] #, 7, 7] #, 10] #, 25]
 temp: [1.0, 1.0] #, 1.0, 1.0] ##[0.9, 0.75, 0.5] #, 1.0] #, 0.5] #, 0.5] 
 normalize_learnergy: [False, True]
 batch_normalize: [False, False]

encoder_type: "dbn"
encoder:
 tiled: False
 tune_scaler: False
 subset_training: 2000000
 overwrite_model: False
 training:
  learning_rate: [0.00001, 0.00001]
  momentum: [0.95,0.95]
  weight_decay: [0.0001, 0.0001]
  nesterov_accel: [True, True]
  batch_size: 128
  epochs: 30
  accelerator: "gpu"
  devices: 1
  gradient_clip_val: 0.1
  precision: "16-mixed"
  save_dir: "wandb_encoder"
  stratify_data:
   kmeans: True


logger:
 use_wandb: True
 log_model: True
 log_out_dir: "wandb_dbn"
 project: "SIT-FUSE"

cluster:
 gauss_noise_stdev:  [0.01]
 lambda: 1.0
 num_classes: 800
 training:
  learning_rate: 0.0001
  batch_size: 1000
  epochs: 30
  accelerator: "gpu"
  devices: 1
  gradient_clip_val: 0.1
  precision: "16-mixed"
  save_dir: "wandb_full_model"

 heir:
  tiers: 1
  gauss_noise_stdev:  [0.01]
  lambda: 1.0
  num_classes: 100
  training:
   accelerator: "gpu"
   devices: 1
   gradient_clip_val: 0.1
   precision: "16-mixed"
   save_dir: "wandb_dbn_full_model_heir"
   batch_size: 100
   min_samples: 1000
   learning_rate: 0.0001
   batch_size: 1000
   epochs: 30



