
data:
 tile: False
 tile_size: [3,3,32]
 tile_step: [1,1,32]
 num_loader_workers: 10
 val_percent: 0.1
 scale_data: True
 pixel_padding: 1
 number_channels: 11
 fill_value: -999999.0
 valid_min: -30000.0
 valid_max: 64000000
 subset_count: 1
 output_subset_count: 1
 reader_type: "pace_oc"
 reader_kwargs: 
  start_lon: -97.8985
  end_lon: -80.5301
  start_lat: 18.1599
  end_lat: 30.4159
  #mask_shp: "/data/nlahaye/remoteSensing/Lakes/glwd_1.shp"
  mask_oceans: True
 chan_dim: 0
 delete_chans: []
 transform_default:
  chans: []
  transform: []

 files_train: [
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240305.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240306.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240307.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240308.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240309.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240310.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240311.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240312.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240315.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240316.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240317.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240318.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240319.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240320.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240321.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240322.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240323.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240324.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240325.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240328.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240329.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240330.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240331.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240401.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240402.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240403.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240404.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240405.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240406.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240407.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240408.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240409.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240410.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240411.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240412.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240413.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240414.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240415.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240416.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240417.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240418.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240419.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240420.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240421.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240422.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240423.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240424.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240425.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240426.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240427.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240428.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240429.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240430.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240501.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240502.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240503.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240504.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240505.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240506.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240507.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240508.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240509.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240510.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240511.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240512.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240513.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240514.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240515.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240516.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240517.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240518.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240519.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240520.L3m.DAY.",
]

 files_test: [
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240521.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240522.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240523.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240524.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240530.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240531.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240601.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240602.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240603.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240604.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240605.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240606.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240607.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240608.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240609.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240610.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240611.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240612.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240613.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240614.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240615.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240616.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240617.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240618.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240619.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240620.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240621.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240622.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240623.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240624.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240625.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240626.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240627.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240628.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240629.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240630.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240701.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240702.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240703.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240704.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240705.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240706.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240707.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240708.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240709.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240710.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240711.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240712.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240713.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240714.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240715.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240716.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240717.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240718.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240719.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240720.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240721.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240722.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240723.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240724.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240725.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240726.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240727.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240728.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240729.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240730.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240731.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240801.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240802.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240803.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240804.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240805.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240806.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240807.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240808.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240809.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240810.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240811.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240812.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240813.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240814.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240815.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240816.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240817.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240818.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240819.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240820.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240821.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240822.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240823.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240824.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240825.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240826.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240827.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240828.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240829.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240830.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240831.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240901.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240902.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240903.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240904.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240905.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240906.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240907.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240908.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240911.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240912.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240913.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240914.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240915.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240916.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240917.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240918.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240919.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240920.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240921.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240922.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240923.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240924.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240925.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240926.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240927.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240928.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240929.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240930.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241001.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241002.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241003.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241004.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241005.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241006.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241007.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241008.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241009.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241010.L3m.DAY.",
]



scaler:
 name: "standard" 

output:
 out_dir: "/data/nlahaye/output/Learnergy/PACE_Only_Gulf_of_Mexico/"
 generate_intermediate_output: True


dbn:
 model_type: ["gaussian_selu", "gaussian_selu"]
 dbn_arch: [3000, 1500] #[250, 500, 2000] #, 2000]
 gibbs_steps: [1,1] #, 7, 7] #, 10] #, 25]
 temp: [1.0, 1.0] #, 1.0, 1.0] ##[0.9, 0.75, 0.5] #, 1.0] #, 0.5] #, 0.5] 
 normalize_learnergy: [False, True]
 batch_normalize: [False, False]

encoder_type: "dbn"
encoder:
 tiled: False
 tune_scaler: False
 subset_training: 2000000
 overwrite_model: False
 training:
  learning_rate: [0.00001, 0.00001]
  momentum: [0.95,0.95]
  weight_decay: [0.0001, 0.0001]
  nesterov_accel: [True, True]
  batch_size: 128
  epochs: 30
  accelerator: "gpu"
  devices: 1
  gradient_clip_val: 0.1
  precision: "16-mixed"
  save_dir: "wandb_encoder"
  stratify_data:
   kmeans: True


logger:
 use_wandb: True
 log_model: True
 log_out_dir: "wandb_dbn"
 project: "SIT-FUSE"

cluster:
 gauss_noise_stdev:  [0.01]
 lambda: 1.0
 num_classes: 800
 training:
  learning_rate: 0.0001
  batch_size: 1000
  epochs: 30
  accelerator: "gpu"
  devices: 1
  gradient_clip_val: 0.1
  precision: "16-mixed"
  save_dir: "wandb_full_model"

 heir:
  tiers: 1
  gauss_noise_stdev:  [0.01]
  lambda: 1.0
  num_classes: 100
  training:
   accelerator: "gpu"
   devices: 1
   gradient_clip_val: 0.1
   precision: "16-mixed"
   save_dir: "wandb_dbn_full_model_heir"
   batch_size: 100
   min_samples: 1000
   learning_rate: 0.0001
   batch_size: 1000
   epochs: 30



