
data:
 tile: False
 tile_size: [3,3,32]
 tile_step: [1,1,32]
 num_loader_workers: 10
 val_percent: 0.1
 scale_data: True
 pixel_padding: 1
 number_channels: 11
 fill_value: -999999.0
 valid_min: -30000.0
 valid_max: 64000000
 subset_count: 1
 output_subset_count: 1
 reader_type: "pace_oc"
 reader_kwargs: 
  start_lon: -128.00
  end_lon: -116.00
  start_lat: 30.00
  end_lat: 38.94
  #mask_shp: "/data/nlahaye/remoteSensing/Lakes/glwd_1.shp"
  mask_oceans: True
 chan_dim: 0
 delete_chans: []
 transform_default:
  chans: []
  transform: []

 files_train: [
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240904.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240905.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240906.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240907.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240908.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240911.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240912.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240913.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240914.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240915.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240916.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240917.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240918.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240919.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240920.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240921.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240922.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240923.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240924.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240925.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240926.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240927.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240928.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240929.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240930.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241001.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241002.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241003.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241004.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241005.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241006.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241007.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241008.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241009.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241010.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241011.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241012.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241013.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241014.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241015.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241016.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241018.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241019.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241020.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241021.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241022.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241023.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241024.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241025.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241026.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241027.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241028.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241029.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241030.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241031.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241101.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241102.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241103.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241104.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241105.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241106.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241107.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241108.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241109.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241110.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241111.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241112.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241113.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241114.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241115.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241116.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241117.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241118.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241119.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241120.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241121.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241122.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241123.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241124.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241125.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241126.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241127.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241128.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241129.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241130.L3m.DAY.",
]

 files_test: [
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241201.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241202.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241203.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241205.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241206.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241207.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241208.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241209.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241210.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241211.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241212.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241213.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241214.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241215.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241216.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241217.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241218.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241219.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241220.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241221.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241222.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241223.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241224.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241225.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241226.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241227.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241228.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241229.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241230.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241231.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250101.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250103.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250104.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250105.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250106.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250107.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250108.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250109.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250110.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250111.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250112.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250113.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250114.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250115.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250116.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250117.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250118.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250119.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250120.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250121.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250122.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250123.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250124.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250125.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250126.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250127.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250128.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250129.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250130.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250131.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250201.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250202.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250203.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250204.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250205.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250206.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250207.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250208.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250209.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250210.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250211.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250212.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250213.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250214.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250215.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250216.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250217.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250218.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250219.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250220.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250221.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250222.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250223.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250224.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250225.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250226.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250227.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250228.L3m.DAY.",
]


scaler:
 name: "standard" 

output:
 out_dir: "/data/nlahaye/output/Learnergy/PACE_Only_S_CA/"
 generate_intermediate_output: True


dbn:
 model_type: ["gaussian_selu", "gaussian_selu"]
 dbn_arch: [3000, 1500] #[250, 500, 2000] #, 2000]
 gibbs_steps: [1,1] #, 7, 7] #, 10] #, 25]
 temp: [1.0, 1.0] #, 1.0, 1.0] ##[0.9, 0.75, 0.5] #, 1.0] #, 0.5] #, 0.5] 
 normalize_learnergy: [False, True]
 batch_normalize: [False, False]

encoder_type: "dbn"
encoder:
 tiled: False
 tune_scaler: False
 subset_training: 2000000
 overwrite_model: False
 training:
  learning_rate: [0.00001, 0.00001]
  momentum: [0.95,0.95]
  weight_decay: [0.0001, 0.0001]
  nesterov_accel: [True, True]
  batch_size: 128
  epochs: 30
  accelerator: "gpu"
  devices: 1
  gradient_clip_val: 0.1
  precision: "16-mixed"
  save_dir: "wandb_encoder"
  stratify_data:
   kmeans: True


logger:
 use_wandb: True
 log_model: True
 log_out_dir: "wandb_dbn"
 project: "SIT-FUSE"

cluster:
 gauss_noise_stdev:  [0.01]
 lambda: 1.0
 num_classes: 800
 training:
  learning_rate: 0.0001
  batch_size: 1000
  epochs: 30
  accelerator: "gpu"
  devices: 1
  gradient_clip_val: 0.1
  precision: "16-mixed"
  save_dir: "wandb_full_model"

 heir:
  tiers: 1
  gauss_noise_stdev:  [0.01]
  lambda: 1.0
  num_classes: 100
  training:
   accelerator: "gpu"
   devices: 1
   gradient_clip_val: 0.1
   precision: "16-mixed"
   save_dir: "wandb_dbn_full_model_heir"
   batch_size: 100
   min_samples: 1000
   learning_rate: 0.0001
   batch_size: 1000
   epochs: 30



