analysis:
 tsne:
  perplexity: 2200
  niter: 5000
  njobs: 50
  exaggeration: 4
  metric: "euclidean"
  patience: 1000
  lr: 200
 run_projection: True
 embed_func: "pca"
 build_knn_graphs: True

data:
 tile: False
 tile_size: [3,3,172]
 tile_step: [1,1,32]
 num_loader_workers: 10
 val_percent: 0.1
 scale_data: True
 pixel_padding: 1
 number_channels: 172
 fill_value: -999999.0
 valid_min: -30000.0
 valid_max: 64000000
 subset_count: 1
 output_subset_count: 1
 reader_type: "pace_oc"
 reader_kwargs:
  start_lon: -128.00
  end_lon: -116.00
  start_lat: 30.00
  end_lat: 37.00
  #mask_shp: "/data/nlahaye/remoteSensing/Lakes/glwd_1.shp"
  mask_oceans: True
 chan_dim: 0
 delete_chans: []
 transform_default:
  chans: []
  transform: []



 files_train: [
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240904.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240905.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240906.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240907.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240908.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240911.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240912.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240913.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240914.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240915.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240916.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240917.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240918.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240919.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240920.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240921.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240922.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240923.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240924.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240925.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240926.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240927.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240928.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240929.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20240930.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241001.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241002.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241003.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241004.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241005.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241006.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241007.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241008.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241009.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241010.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241011.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241012.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241013.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241014.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241015.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241016.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241018.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241019.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241020.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241021.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241022.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241023.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241024.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241025.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241026.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241027.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241028.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241029.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241030.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241031.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241101.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241102.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241103.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241104.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241105.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241106.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241107.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241108.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241109.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241110.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241111.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241112.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241113.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241114.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241115.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241116.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241117.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241118.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241119.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241120.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241121.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241122.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241123.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241124.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241125.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241126.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241127.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241128.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241129.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20241130.L3m.DAY.",
]

 final_labels: [
#"/data/nlahaye/output/MERGED_HAB_20250225/PACE/20250220_DAY.karenia_brevis_bloom.tif",
#"/data/nlahaye/output/MERGED_HAB_20250225/PACE/20250221_DAY.karenia_brevis_bloom.tif",
#"/data/nlahaye/output/MERGED_HAB_20250225/PACE/20250222_DAY.karenia_brevis_bloom.tif",
#"/data/nlahaye/output/MERGED_HAB_20250225/PACE/20250223_DAY.karenia_brevis_bloom.tif",
#"/data/nlahaye/output/MERGED_HAB_20250225/PACE/20250224_DAY.karenia_brevis_bloom.tif",
#"/data/nlahaye/output/MERGED_HAB_20250225/PACE/20250225_DAY.karenia_brevis_bloom.tif",
#"/data/nlahaye/output/MERGED_HAB_20250225/PACE/20250226_DAY.karenia_brevis_bloom.tif",
#"/data/nlahaye/output/MERGED_HAB_20250225/PACE/20250227_DAY.karenia_brevis_bloom.tif",
#"/data/nlahaye/output/MERGED_HAB_20250225/PACE/20250228_DAY.karenia_brevis_bloom.tif",
"/data/nlahaye/output/Learnergy/PACE_Only_S_CA/PACE_OCI.20250220.L3m.DAY..clust.data_73298clusters.no_geo.pseudo_nitzschia_seriata_bloom.tif",
"/data/nlahaye/output/Learnergy/PACE_Only_S_CA/PACE_OCI.20250221.L3m.DAY..clust.data_73299clusters.no_geo.pseudo_nitzschia_seriata_bloom.tif",
"/data/nlahaye/output/Learnergy/PACE_Only_S_CA/PACE_OCI.20250222.L3m.DAY..clust.data_73299clusters.no_geo.pseudo_nitzschia_seriata_bloom.tif",
"/data/nlahaye/output/Learnergy/PACE_Only_S_CA/PACE_OCI.20250223.L3m.DAY..clust.data_73299clusters.no_geo.pseudo_nitzschia_seriata_bloom.tif",
"/data/nlahaye/output/Learnergy/PACE_Only_S_CA/PACE_OCI.20250224.L3m.DAY..clust.data_73299clusters.no_geo.pseudo_nitzschia_seriata_bloom.tif",
"/data/nlahaye/output/Learnergy/PACE_Only_S_CA/PACE_OCI.20250225.L3m.DAY..clust.data_73299clusters.no_geo.pseudo_nitzschia_seriata_bloom.tif",
"/data/nlahaye/output/Learnergy/PACE_Only_S_CA/PACE_OCI.20250226.L3m.DAY..clust.data_73299clusters.no_geo.pseudo_nitzschia_seriata_bloom.tif",
"/data/nlahaye/output/Learnergy/PACE_Only_S_CA/PACE_OCI.20250227.L3m.DAY..clust.data_73299clusters.no_geo.pseudo_nitzschia_seriata_bloom.tif",
"/data/nlahaye/output/Learnergy/PACE_Only_S_CA/PACE_OCI.20250228.L3m.DAY..clust.data_73299clusters.no_geo.pseudo_nitzschia_seriata_bloom.tif"
]

 files_test: [
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250220.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250221.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250222.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250223.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250224.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250225.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250226.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250227.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250228.L3m.DAY.",
]

output:
 out_dir: "/data/nlahaye/output/Learnergy/PACE_Only_S_CA_PCA/"
 generate_intermediate_output: True


conv: False
encoder:
 tiled: False
 tune_scaler: False
 subset_training: 2000000
 overwrite_model: False
 training:
  learning_rate: [0.00001, 0.00001]
  momentum: [0.95,0.95]
  weight_decay: [0.0001, 0.0001]
  nesterov_accel: [True, True]
  batch_size: 128
  epochs: 30
  accelerator: "gpu"
  devices: 1
  gradient_clip_val: 0.1
  precision: "16-mixed"
  save_dir: "wandb_encoder"
  stratify_data:
   kmeans: True


logger:
 use_wandb: True
 log_model: True
 log_out_dir: "wandb_dbn"
 project: "SIT-FUSE"

cluster:
 gauss_noise_stdev:  [0.01]
 lambda: 1.0
 num_classes: 800
 training:
  learning_rate: 0.0001
  batch_size: 1000
  epochs: 30
  accelerator: "gpu"
  devices: 1
  gradient_clip_val: 0.1
  precision: "16-mixed"
  save_dir: "wandb_full_model"
  finetune_encoder: False

 heir:
  tiers: 1
  gauss_noise_stdev:  [0.01]
  lambda: 1.0
  num_classes: 100
  training:
   accelerator: "gpu"
   devices: 1
   gradient_clip_val: 0.1
   precision: "16-mixed"
   save_dir: "wandb_dbn_full_model_heir"
   batch_size: 100
   min_samples: 1000
   learning_rate: 0.0001
   batch_size: 1000
   epochs: 30


encoder_type: "pca"
scaler:
 name: "standard"







