
data:
 tile: False
 tile_size: [3,3,32]
 tile_step: [1,1,32]
 num_loader_workers: 10
 val_percent: 0.1
 scale_data: True
 pixel_padding: 1
 number_channels: 11
 fill_value: -999999.0
 valid_min: -30000.0
 valid_max: 64000000
 subset_count: 1
 output_subset_count: 1
 reader_type: "pace_oc"
 reader_kwargs: 
  nrt: True
  start_lon: -128.00
  end_lon: -116.00
  start_lat: 30.00
  end_lat: 37.00

  #mask_shp: "/data/nlahaye/remoteSensing/Lakes/glwd_1.shp"
  mask_oceans: True
 chan_dim: 0
 delete_chans: []
 transform_default:
  chans: []
  transform: []

 files_train: [
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250301.L3m.DAY.",
]

 files_test: [
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250301.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250302.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250303.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250304.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250305.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250306.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250307.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250308.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250309.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250310.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250311.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250312.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250313.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250314.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250315.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250316.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250317.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250318.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250319.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250320.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250321.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250322.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250323.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250324.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250325.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250326.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250327.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250328.L3m.DAY.",
"/data/nlahaye/remoteSensing/PACE/PACE_OCI.20250329.L3m.DAY.",

]



scaler:
 name: "standard" 

output:
 out_dir: "/data/nlahaye/output/Learnergy/PACE_Only_S_CA/"
 generate_intermediate_output: True


dbn:
 model_type: ["gaussian_selu", "gaussian_selu"]
 dbn_arch: [3000, 1500] #[250, 500, 2000] #, 2000]
 gibbs_steps: [1,1] #, 7, 7] #, 10] #, 25]
 temp: [1.0, 1.0] #, 1.0, 1.0] ##[0.9, 0.75, 0.5] #, 1.0] #, 0.5] #, 0.5] 
 normalize_learnergy: [False, True]
 batch_normalize: [False, False]

encoder_type: "dbn"
encoder:
 tiled: False
 tune_scaler: False
 subset_training: 2000000
 overwrite_model: False
 training:
  learning_rate: [0.00001, 0.00001]
  momentum: [0.95,0.95]
  weight_decay: [0.0001, 0.0001]
  nesterov_accel: [True, True]
  batch_size: 128
  epochs: 30
  accelerator: "gpu"
  devices: 1
  gradient_clip_val: 0.1
  precision: "16-mixed"
  save_dir: "wandb_encoder"
  stratify_data:
   kmeans: True


logger:
 use_wandb: True
 log_model: True
 log_out_dir: "wandb_dbn"
 project: "SIT-FUSE"

cluster:
 gauss_noise_stdev:  [0.01]
 lambda: 1.0
 num_classes: 800
 training:
  learning_rate: 0.0001
  batch_size: 1000
  epochs: 30
  accelerator: "gpu"
  devices: 1
  gradient_clip_val: 0.1
  precision: "16-mixed"
  save_dir: "wandb_full_model"

 heir:
  tiers: 1
  gauss_noise_stdev:  [0.01]
  lambda: 1.0
  num_classes: 100
  training:
   accelerator: "gpu"
   devices: 1
   gradient_clip_val: 0.1
   precision: "16-mixed"
   save_dir: "wandb_dbn_full_model_heir"
   batch_size: 100
   min_samples: 1000
   learning_rate: 0.0001
   batch_size: 1000
   epochs: 30



