
data:
 tile: True
 val_percent: 0.1
 tile_size: [16,16,8]
 tile_step: [10,10,8]
 val_percent: 0.1
 num_loader_workers: 10
 scale_data: True
 pixel_padding: 1
 number_channels: 8
 fill_value: -99999.0
 valid_min: -900.0
 valid_max: 100000000
 reader_type: "gtiff"
 reader_kwargs:
  no_arg: ''
 chan_dim: 0
 delete_chans: []
 transform_default:
  chans: []
  transform: []

 files_train: [
"/data/nlahaye/remoteSensing/Palm_Oil/ucayali_stacks_2020_h1v1.tif",
"/data/nlahaye/remoteSensing/Palm_Oil/ucayali_stacks_2020_h0v2.tif",
"/data/nlahaye/remoteSensing/Palm_Oil/ucayali_stacks_2020_h1v3.tif",
]


 files_test: [
"/data/nlahaye/remoteSensing/Palm_Oil/ucayali_stacks_2020_h1v1.tif",
"/data/nlahaye/remoteSensing/Palm_Oil/ucayali_stacks_2020_h0v1.tif",
"/data/nlahaye/remoteSensing/Palm_Oil/ucayali_stacks_2020_h0v2.tif",
"/data/nlahaye/remoteSensing/Palm_Oil/ucayali_stacks_2020_h1v0.tif",
"/data/nlahaye/remoteSensing/Palm_Oil/ucayali_stacks_2020_h1v1.tif",
"/data/nlahaye/remoteSensing/Palm_Oil/ucayali_stacks_2020_h1v2.tif",
"/data/nlahaye/remoteSensing/Palm_Oil/ucayali_stacks_2020_h1v3.tif",
"/data/nlahaye/remoteSensing/Palm_Oil/ucayali_stacks_2020_h2v0.tif",
"/data/nlahaye/remoteSensing/Palm_Oil/ucayali_stacks_2020_h2v1.tif",
"/data/nlahaye/remoteSensing/Palm_Oil/ucayali_stacks_2020_h2v2.tif",
"/data/nlahaye/remoteSensing/Palm_Oil/ucayali_stacks_2020_h2v3.tif",
"/data/nlahaye/remoteSensing/Palm_Oil/ucayali_stacks_2020_h4v2.tif",
"/data/nlahaye/remoteSensing/Palm_Oil/ucayali_stacks_2020_h4v3.tif"]


scaler:
 name: "standard" 

output:
 out_dir: "/data/nlahaye/output/Learnergy/DBN_OIL_PALM_CONV_DBN/"
 generate_intermediate_output: True
 generate_train_output: True



#dbn:
# model_type: "gaussian"
# dbn_arch: [[100,300,300],[[7,7],[5,5],[3,3]]]
# gibbs_steps: [1,1,1] #, 7, 7] #, 10] #, 25]
# temp: [1.0, 1.0, 1.0] #, 1.0, 1.0] ##[0.9, 0.75, 0.5] #, 1.0] #, 0.5] #, 0.5] 
# normalize_learnergy: [False, True, True]
# batch_normalize: [False, True, True]
# stride: [1,1,1]
# padding: [3,2,1]

dbn:
 model_type: "gaussian"
 dbn_arch: [[100,200],[[3,3],[3,3]]]
 gibbs_steps: [3,3] #, 7, 7] #, 10] #, 25]
 temp: [1.0, 1.0] #, 1.0, 1.0] ##[0.9, 0.75, 0.5] #, 1.0] #, 0.5] #, 0.5] 
 normalize_learnergy: [True, True]
 batch_normalize: [True, True]
 stride: [1,1]
 padding: [1,1]

encoder_type: "conv_dbn"
encoder:
 tiled: True
 tune_scaler: False
 subset_training: -1
 overwrite_model: False
 training:
  learning_rate: [0.00005, 0.00005]
  momentum: [0.95,0.95]
  weight_decay: [0.0001, 0.0001]
  nesterov_accel: [True, True]
  batch_size: 8
  epochs: 30
  accelerator: "gpu"
  devices: 1
  gradient_clip_val: 0.1
  precision: "16-mixed"
  save_dir: "wandb_encoder"
  stratify_data:

logger:
 use_wandb: True
 log_model: True
 log_out_dir: "wandb_dbn"
 project: "SIT-FUSE"
 

#encoder_type: "conv_dbn"
#encoder:
# tiled: True
# tune_scaler: False
# subset_training: -1
# overwrite_model: False
# training:
#  learning_rate: [0.00005, 0.00005, 0.00005]
#  momentum: [0.95,0.95, 0.95]
#  weight_decay: [0.0001, 0.0001, 0.0001]
#  nesterov_accel: [True, True, True]
#  batch_size: 128
#  epochs: 10
#  accelerator: "gpu"
#  devices: 1
#  gradient_clip_val: 0.1
#  precision: "16-mixed"
#  save_dir: "wandb_encoder"
#  stratify_data:


cluster:
 gauss_noise_stdev:  [0.01]
 lambda: 1.0
 num_classes: 800
 training:
  learning_rate: 0.0001
  batch_size: 10
  epochs: 5
  accelerator: "gpu"
  devices: 1
  gradient_clip_val: 0.1
  precision: "16-mixed"
  save_dir: "wandb_full_model"

 heir:
  tiers: 1
  gauss_noise_stdev:  [0.01]
  lambda: 1.0
  num_classes: 100
  training:
   accelerator: "gpu"
   devices: 1
   gradient_clip_val: 0.1
   precision: "16-mixed"
   save_dir: "wandb_dbn_full_model_heir"
   batch_size: 10
   min_samples: 1000
   learning_rate: 0.0001
   epochs: 5



