
data:
 tile: False
 num_loader_workers: 10
 val_percent: 0.1
 scale_data: True
 pixel_padding: 0
 no_window: False #True
 number_channels: 2056
 fill_value: -999999.0
 valid_min:  -9.0e+35
 valid_max: 9.03e+36
 subset_count: 1
 output_subset_count: 10
 reader_type: "gtiff"
 reader_kwargs:
  no_arg: "no_arg"
 chan_dim: 0
 delete_chans: [] #103, 107, 108, 109, 110, 111, 112, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168]
 transform_default:
  chans: []
  transform: []
 
 files_train: [
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240725T163105Z_S008G07.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240725T163742Z_S008G08.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240725T164419Z_S008G09.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T143122Z_S006G07.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T143759Z_S006G08.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T144436Z_S006G09.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240730T163226Z_S008G07.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240730T163903Z_S008G08.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240730T164540Z_S008G09.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240731T144556Z_S006G09.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240731T163242Z_S008G07.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240731T163919Z_S008G08.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240731T164556Z_S008G09.tif",
]


 files_test: [
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T163122Z_S008G07.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T163759Z_S008G08.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T164436Z_S008G09.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240727T143137Z_S006G07.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240727T143814Z_S006G08.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240727T144451Z_S006G09.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240728T163154Z_S008G07.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240728T163831Z_S008G08.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240728T164508Z_S008G09.tif",
]



scaler:
 name: "standard" 

output:
 out_dir: "/data/nlahaye/output/Learnergy/TEMPO_TEST_Spatial_Paper/"
 generate_intermediate_output: True


dbn:
 model_type: ["gaussian_selu", "gaussian_selu", "gaussian_selu"]
 dbn_arch: [4000, 3000, 2000] #[250, 500, 2000] #, 2000]
 gibbs_steps: [1,1,1] #, 7, 7] #, 10] #, 25]
 temp: [1.0, 1.0, 1.0] #, 1.0, 1.0] ##[0.9, 0.75, 0.5] #, 1.0] #, 0.5] #, 0.5] 
 normalize_learnergy: [False, True, True]
 batch_normalize: [False, False, False]

encoder_type: "dbn"
encoder:
 tiled: False
 tune_scaler: False
 subset_training: -1 #10000000
 overwrite_model: False
 training:
  learning_rate: [0.00001, 0.00001, 0.00001]
  momentum: [0.95,0.95,0.95]
  weight_decay: [0.0001, 0.0001, 0.0001]
  nesterov_accel: [True, True, True]
  batch_size: 128
  epochs: 100
  accelerator: "gpu"
  devices: 1
  gradient_clip_val: 0.1
  precision: "16-mixed"
  save_dir: "wandb_encoder"
  stratify_data:
   kmeans: True


logger:
 use_wandb: True
 log_model: True
 log_out_dir: "wandb_dbn"
 project: "SIT-FUSE"

cluster:
 gauss_noise_stdev:  [0.01]
 lambda: 1.0
 num_classes: 1000
 training:
  learning_rate: 0.0001
  batch_size: 1000
  epochs: 100
  accelerator: "gpu"
  devices: 1
  gradient_clip_val: 0.1
  precision: "16-mixed"
  save_dir: "wandb_full_model"

 heir:
  tiers: 1
  gauss_noise_stdev:  [0.01]
  lambda: 1.0
  num_classes: 200
  training:
   accelerator: "gpu"
   devices: 1
   gradient_clip_val: 0.1
   precision: "16-mixed"
   save_dir: "wandb_dbn_full_model_heir"
   batch_size: 100
   min_samples: 1000
   learning_rate: 0.0001
   batch_size: 100
   epochs: 100



