
data:
 tile: False
 num_loader_workers: 10
 val_percent: 0.1
 scale_data: True
 pixel_padding: 0
 no_window: False #True
 number_channels: 2056
 fill_value: -999999.0
 valid_min:  -9.0e+35
 valid_max: 9.03e+36
 subset_count: 1
 output_subset_count: 10
 reader_type: "gtiff"
 reader_kwargs:
  no_arg: "no_arg"
 chan_dim: 0
 delete_chans: [] #103, 107, 108, 109, 110, 111, 112, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168]
 transform_default:
  chans: []
  transform: []
 
 files_train: [
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250106T214347Z_S011G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250108T184439Z_S008G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250108T204439Z_S010G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250109T214504Z_S011G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250109T230520Z_S013G06.tif",

"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250106T174347Z_S007G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250106T184347Z_S008G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250106T194347Z_S009G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250106T204347Z_S010G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250106T214347Z_S011G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250106T222355Z_S012G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250106T230403Z_S013G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250106T234411Z_S014G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250107T174414Z_S007G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250107T184414Z_S008G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250107T194414Z_S009G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250107T204414Z_S010G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250107T214414Z_S011G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250107T222252Z_S012G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250108T174439Z_S007G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250108T184439Z_S008G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250108T194439Z_S009G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250108T204439Z_S010G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250108T214439Z_S011G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250108T222447Z_S012G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250108T230455Z_S013G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250108T234503Z_S014G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250109T174504Z_S007G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250109T184504Z_S008G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250109T194504Z_S009G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250109T204504Z_S010G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250109T214504Z_S011G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250109T222512Z_S012G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250109T230520Z_S013G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250109T234528Z_S014G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250110T174529Z_S007G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250110T184529Z_S008G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250110T194529Z_S009G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250110T204529Z_S010G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250110T214529Z_S011G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250110T222537Z_S012G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250110T230545Z_S013G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250110T234553Z_S014G06.tif",

]

 files_test: [
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250111T174553Z_S007G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250111T184553Z_S008G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250111T194553Z_S009G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250111T204553Z_S010G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250111T214553Z_S011G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250111T222601Z_S012G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250111T230609Z_S013G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250111T234617Z_S014G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250112T174616Z_S007G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250112T184616Z_S008G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250112T194616Z_S009G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250112T204616Z_S010G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250112T214616Z_S011G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250112T222624Z_S012G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250112T230632Z_S013G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250112T234640Z_S014G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250113T174639Z_S007G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250113T184639Z_S008G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250113T194639Z_S009G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250113T204639Z_S010G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250113T214639Z_S011G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250113T222647Z_S012G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250113T230655Z_S013G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250113T234703Z_S014G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250111T184553Z_S008G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250111T194553Z_S009G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250112T174616Z_S007G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250112T234640Z_S014G06.tif",
]



scaler:
 name: "standard" 

output:
 out_dir: "/data/nlahaye/output/Learnergy/TEMPO_LA_2/"
 generate_intermediate_output: True


dbn:
 model_type: ["gaussian_selu", "gaussian_selu"]
 dbn_arch: [8000, 4000] #[250, 500, 2000] #, 2000]
 gibbs_steps: [1,1] #, 7, 7] #, 10] #, 25]
 temp: [1.0, 1.0] #, 1.0, 1.0] ##[0.9, 0.75, 0.5] #, 1.0] #, 0.5] #, 0.5] 
 normalize_learnergy: [False, True]
 batch_normalize: [False, False]

encoder_type: "dbn"
encoder:
 tiled: False
 tune_scaler: False
 subset_training: -1 #10000000
 overwrite_model: False
 training:
  learning_rate: [0.00001, 0.00001]
  momentum: [0.95,0.95]
  weight_decay: [0.0001, 0.0001]
  nesterov_accel: [True, True]
  batch_size: 128
  epochs: 150
  accelerator: "gpu"
  devices: 1
  gradient_clip_val: 0.1
  precision: "16-mixed"
  save_dir: "wandb_encoder"
  stratify_data:
   kmeans: True


logger:
 use_wandb: True
 log_model: True
 log_out_dir: "wandb_dbn"
 project: "SIT-FUSE"

cluster:
 gauss_noise_stdev:  [0.01]
 lambda: 1.0
 num_classes: 1000
 training:
  learning_rate: 0.0001
  batch_size: 1000
  epochs: 150
  accelerator: "gpu"
  devices: 1
  gradient_clip_val: 0.1
  precision: "16-mixed"
  save_dir: "wandb_full_model"

 heir:
  tiers: 1
  gauss_noise_stdev:  [0.01]
  lambda: 1.0
  num_classes: 200
  training:
   accelerator: "gpu"
   devices: 1
   gradient_clip_val: 0.1
   precision: "16-mixed"
   save_dir: "wandb_dbn_full_model_heir"
   batch_size: 100
   min_samples: 1000
   learning_rate: 0.0001
   batch_size: 100
   epochs: 150



