
data:
 tile: False
 num_loader_workers: 10
 val_percent: 0.1
 scale_data: True
 pixel_padding: 0
 no_window: False #True
 number_channels: 2056
 fill_value: -999999.0
 valid_min:  -9.0e+35
 valid_max: 9.03e+36
 subset_count: 1
 output_subset_count: 10
 reader_type: "gtiff"
 reader_kwargs:
  mask_oceans: False
 chan_dim: 0
 delete_chans: [] #103, 107, 108, 109, 110, 111, 112, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168]
 transform_default:
  chans: []
  transform: []
 
 files_train: [
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240725T163105Z_S008G07.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240725T163742Z_S008G08.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240725T164419Z_S008G09.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T143122Z_S006G07.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T143759Z_S006G08.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T144436Z_S006G09.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T163122Z_S008G07.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T163759Z_S008G08.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T164436Z_S008G09.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240730T163226Z_S008G07.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240730T163903Z_S008G08.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240730T164540Z_S008G09.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240731T144556Z_S006G09.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240731T163242Z_S008G07.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240731T163919Z_S008G08.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240731T164556Z_S008G09.tif",



"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240725T173105Z_S009G07.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240725T173742Z_S009G08.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240725T174419Z_S009G09.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240725T183105Z_S010G07.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240725T183742Z_S010G08.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240725T184419Z_S010G09.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240725T193105Z_S011G07.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240725T193742Z_S011G08.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240725T194419Z_S011G09.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240725T203105Z_S012G07.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240725T203742Z_S012G08.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240725T204419Z_S012G09.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240725T213105Z_S013G07.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240725T213742Z_S013G08.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240725T214419Z_S013G09.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240725T223105Z_S014G07.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240725T223742Z_S014G08.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240725T224419Z_S014G09.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240725T231110Z_S015G04.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240725T231747Z_S015G05.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240725T232424Z_S015G06.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240725T235115Z_S016G04.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240725T235752Z_S016G05.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T173122Z_S009G07.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T173759Z_S009G08.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T174436Z_S009G09.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T183122Z_S010G07.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T183759Z_S010G08.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T184436Z_S010G09.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T193122Z_S011G07.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T193759Z_S011G08.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T194436Z_S011G09.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T203122Z_S012G07.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T203759Z_S012G08.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T204436Z_S012G09.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T213122Z_S013G07.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T213759Z_S013G08.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T214436Z_S013G09.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T223122Z_S014G07.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T223759Z_S014G08.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T224436Z_S014G09.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T231127Z_S015G04.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T231804Z_S015G05.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T232441Z_S015G06.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T235132Z_S016G04.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T235809Z_S016G05.tif",

"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240730T173226Z_S009G07.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240730T173903Z_S009G08.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240730T174540Z_S009G09.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240730T183226Z_S010G07.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240730T183903Z_S010G08.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240730T184540Z_S010G09.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240730T193226Z_S011G07.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240730T193903Z_S011G08.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240730T194540Z_S011G09.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240730T203226Z_S012G07.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240730T203903Z_S012G08.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240730T204540Z_S012G09.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240730T213415Z_S013G07.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240731T173242Z_S009G07.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240731T173919Z_S009G08.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240731T174556Z_S009G09.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240731T183242Z_S010G07.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240731T183919Z_S010G08.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240731T184556Z_S010G09.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240731T193242Z_S011G07.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240731T193919Z_S011G08.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240731T194556Z_S011G09.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240731T203242Z_S012G07.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240731T203919Z_S012G08.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240731T204556Z_S012G09.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240731T213242Z_S013G07.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240731T213919Z_S013G08.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240731T214556Z_S013G09.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240731T223242Z_S014G07.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240731T223919Z_S014G08.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240731T224556Z_S014G09.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240731T231247Z_S015G04.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240731T231924Z_S015G05.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240731T232601Z_S015G06.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240731T235252Z_S016G04.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240731T235929Z_S016G05.tif",

]


 files_test: [
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240727T143137Z_S006G07.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240727T143814Z_S006G08.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240727T144451Z_S006G09.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240728T163154Z_S008G07.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240728T163831Z_S008G08.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240728T164508Z_S008G09.tif",
]


scaler:
 name: "standard" 

output:
 out_dir: "/data/nlahaye/output/Learnergy/TEMPO_TEST_Spatial_Paper_FIRE/"
 generate_intermediate_output: True


dbn:
 model_type: ["gaussian_selu", "gaussian_selu", "gaussian_selu"]
 dbn_arch: [4000, 3000, 2000] #[250, 500, 2000] #, 2000]
 gibbs_steps: [1,1,1] #, 7, 7] #, 10] #, 25]
 temp: [1.0, 1.0, 1.0] #, 1.0, 1.0] ##[0.9, 0.75, 0.5] #, 1.0] #, 0.5] #, 0.5] 
 normalize_learnergy: [False, True, True]
 batch_normalize: [False, False, False]

encoder_type: "dbn"
encoder:
 tiled: False
 tune_scaler: False
 subset_training: -1 #10000000
 overwrite_model: False
 training:
  learning_rate: [0.00001, 0.00001, 0.00001]
  momentum: [0.95,0.95,0.95]
  weight_decay: [0.0001, 0.0001, 0.0001]
  nesterov_accel: [True, True, True]
  batch_size: 128
  epochs: 100
  accelerator: "gpu"
  devices: 1
  gradient_clip_val: 0.1
  precision: "16-mixed"
  save_dir: "wandb_encoder"
  stratify_data:
   kmeans: True


logger:
 use_wandb: True
 log_model: True
 log_out_dir: "wandb_dbn"
 project: "SIT-FUSE"

cluster:
 gauss_noise_stdev:  [0.01]
 lambda: 1.0
 num_classes: 1000
 training:
  learning_rate: 0.0001
  batch_size: 1000
  epochs: 100
  accelerator: "gpu"
  devices: 1
  gradient_clip_val: 0.1
  precision: "16-mixed"
  save_dir: "wandb_full_model"

 heir:
  tiers: 1
  gauss_noise_stdev:  [0.01]
  lambda: 1.0
  num_classes: 200
  training:
   accelerator: "gpu"
   devices: 1
   gradient_clip_val: 0.1
   precision: "16-mixed"
   save_dir: "wandb_dbn_full_model_heir"
   batch_size: 100
   min_samples: 1000
   learning_rate: 0.0001
   batch_size: 100
   epochs: 100



