high_res:
 data:
  valid_min: 0.0
  valid_max: 100000000
  reader_type: "numpy"
  reader_kwargs:
   no_arg: "no_arg"
  geo_reader_type: "numpy"
  geo_reader_kwargs:
   no_arg: "no_arg"
  filenames: ["/data/nlahaye/remoteSensing/GERD_DAM/VIIRS/npp_viirs_i01_20220322_100600_wgs84_fit.tif.npy",
"/data/nlahaye/remoteSensing/GERD_DAM/VIIRS/npp_viirs_i01_20220322_114800_wgs84_fit.tif.npy",
"/data/nlahaye/remoteSensing/GERD_DAM/VIIRS/npp_viirs_i01_20220323_113000_wgs84_fit.tif.npy",
"/data/nlahaye/remoteSensing/GERD_DAM/VIIRS/npp_viirs_i01_20220324_111200_wgs84_fit.tif.npy",
"/data/nlahaye/remoteSensing/GERD_DAM/VIIRS/npp_viirs_i01_20220325_105400_wgs84_fit.tif.npy"]
  geo_filenames: ["/data/nlahaye/remoteSensing/GERD_DAM/VIIRS/npp_viirs_i01_20220322_100600_wgs84_fit.tif.lonlat.npy",
"/data/nlahaye/remoteSensing/GERD_DAM/VIIRS/npp_viirs_i01_20220322_114800_wgs84_fit.tif.lonlat.npy",
"/data/nlahaye/remoteSensing/GERD_DAM/VIIRS/npp_viirs_i01_20220323_113000_wgs84_fit.tif.lonlat.npy",
"/data/nlahaye/remoteSensing/GERD_DAM/VIIRS/npp_viirs_i01_20220324_111200_wgs84_fit.tif.lonlat.npy",
"/data/nlahaye/remoteSensing/GERD_DAM/VIIRS/npp_viirs_i01_20220325_105400_wgs84_fit.tif.lonlat.npy"
]
  chan_dim: 0
  geo_coord_dim: 2
  geo_lat_index: 1
  geo_lon_index: 0

low_res:
 data:
  valid_min: 0.0
  valid_max: 100000000
  reader_type: "numpy"
  reader_kwargs:
   no_arg: "no_arg"
  geo_reader_type: "numpy"
  geo_reader_kwargs:
   no_arg: "no_arg"
  filenames: ["/data/nlahaye/remoteSensing/GERD_DAM/VIIRS/npp_viirs_m01_20220322_100600_wgs84_fit.tif.npy",
"/data/nlahaye/remoteSensing/GERD_DAM/VIIRS/npp_viirs_m01_20220322_114800_wgs84_fit.tif.npy",
"/data/nlahaye/remoteSensing/GERD_DAM/VIIRS/npp_viirs_m01_20220323_113000_wgs84_fit.tif.npy",
"/data/nlahaye/remoteSensing/GERD_DAM/VIIRS/npp_viirs_m01_20220324_111200_wgs84_fit.tif.npy",
"/data/nlahaye/remoteSensing/GERD_DAM/VIIRS/npp_viirs_m01_20220325_105400_wgs84_fit.tif.npy"]
  geo_filenames: ["/data/nlahaye/remoteSensing/GERD_DAM/VIIRS/npp_viirs_m01_20220322_100600_wgs84_fit.tif.lonlat.npy",
"/data/nlahaye/remoteSensing/GERD_DAM/VIIRS/npp_viirs_m01_20220322_114800_wgs84_fit.tif.lonlat.npy",
"/data/nlahaye/remoteSensing/GERD_DAM/VIIRS/npp_viirs_m01_20220323_113000_wgs84_fit.tif.lonlat.npy",
"/data/nlahaye/remoteSensing/GERD_DAM/VIIRS/npp_viirs_m01_20220324_111200_wgs84_fit.tif.lonlat.npy",
"/data/nlahaye/remoteSensing/GERD_DAM/VIIRS/npp_viirs_m01_20220325_105400_wgs84_fit.tif.lonlat.npy"]
  chan_dim: 0
  geo_coord_dim: 2
  geo_lat_index: 1
  geo_lon_index: 0


fusion:
 projection_id: 4326
 description: "resampling high res VIIRS channels to moderate resolution"
 area_id: "GERD Dam"
 projection_proj4:
  proj: "longlat"
  datum: "WGS84" 
 final_resolution: 0.007
 projection_units: "degrees"
 resample_radius: 5000
 resample_n_neighbors: 64
 resample_n_procs: 10
 resample_epsilon: 1.6
 use_bilinear: True
       
output_files: ["/data/nlahaye/remoteSensing/GERD_DAM/VIIRS/npp_viirs_20220322_100600_FULL.npy",
"/data/nlahaye/remoteSensing/GERD_DAM/VIIRS/npp_viirs_20220322_114800_FULL.npy",
"/data/nlahaye/remoteSensing/GERD_DAM/VIIRS/npp_viirs_20220323_113000_FULL.npy",
"/data/nlahaye/remoteSensing/GERD_DAM/VIIRS/npp_viirs_20220324_111200_FULL.npy",
"/data/nlahaye/remoteSensing/GERD_DAM/VIIRS/npp_viirs_20220325_105400_FULL.npy",
"/data/nlahaye/remoteSensing/GERD_DAM/VIIRS/npp_viirs_20220322_100600_FULL.npy"]



