 
input_paths: ["/data/nlahaye/output/Learnergy/No_Data/",
              "/data/nlahaye/output/Learnergy/No_Data/",
              "/mnt/data/HAB_MODEL_WEIGHTS/OC_SIF_HABs_2025/SNPP_VIIRS_S_CA/"]

 
 
fname_str: "DAY.total_phytoplankton.tif"
out_dir: "/mnt/data/HAB_MODEL_WEIGHTS/OC_SIF_HABs_2025/MERGED_HAB/SNPP_VIIRS/"
num_classes: 8
re_index: 1

gen_daily: true
gen_monthly: false

