
low_res:
 data:
  fill_value: -999999.0
  valid_min: -900.0 #0.0000001
  valid_max: 100000000
  reader_type: "emit_l2"
  reader_kwargs:
   no_arg: "no_arg"
  geo_reader_type: "emit_geo"
  geo_reader_kwargs:
   no_arg: ''
  filenames: [
"/mnt/data/EMIT_L2A_RFL_001_20250225T112411_2505608_002.nc",
]

  geo_filenames: [
"/mnt/data/EMIT_L2A_RFL_001_20250225T112411_2505608_002.nc",
]

  chan_dim: 2
  geo_coord_dim: 0
  geo_lat_index: 1
  geo_lon_index: 0


high_res:
 data:
  valid_min: 0.0
  valid_max: 100000000
  reader_type: "numpy"
  reader_kwargs:
   no_arg: "no_arg"
  geo_reader_type: "numpy"
  geo_reader_kwargs:
   no_arg: "no_arg"
  filenames: []
  geo_filenames: []
  chan_dim: 0
  geo_coord_dim: 2
  geo_lat_index: 1
  geo_lon_index: 0


fusion:
 projection_id: 4326
 description: "Generating EMIT GeoTiffs"
 area_id: "EMIT"
 projection_proj4:
  #proj: "utm"
  #zone: 11
  proj: "longlat"
  datum: "WGS84" 
 final_resolution: 0.00027 #0.00225 #0.000225
 projection_units: "degrees"
 resample_radius: 50
 resample_n_neighbors: 8
 resample_n_procs: 10
 resample_epsilon: 1.6
 use_bilinear: False      
 lon_bounds: [-16.75, -16.5]
 lat_bounds: [13.42, 13.47]


output_files: [
"/mnt/data/EMIT_L2A_RFL_001_20250225T112411_2505608_002.tif",
  ]



