
low_res:
 data:
  fill_value: -9.96921e+36
  valid_min: -9.0e+35 #0.0000001
  valid_max: 9.0e+36
  reader_type: "tempo_netcdf"
  reader_kwargs:
   no_arg: ''
  geo_reader_type: "tempo_netcdf_geo"
  geo_reader_kwargs:
   no_arg: "no_arg"
  filenames: [
#"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T163759Z_S008G08.nc",
#"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T164436Z_S008G09.nc",
#"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T163122Z_S008G07.nc"
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T143122Z_S006G07.nc",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T143759Z_S006G08.nc",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T144436Z_S006G09.nc",
]

  geo_filenames: [
#"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T163759Z_S008G08.nc",
#"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T164436Z_S008G09.nc",
#"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T163122Z_S008G07.nc"
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T143122Z_S006G07.nc",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T143759Z_S006G08.nc",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T144436Z_S006G09.nc",
]

  chan_dim: 2
  geo_coord_dim: 0
  geo_lat_index: 0
  geo_lon_index: 1


high_res:
 data:
  valid_min: 0.0
  valid_max: 100000000
  reader_type: "numpy"
  reader_kwargs:
   no_arg: "no_arg"
  geo_reader_type: "numpy"
  geo_reader_kwargs:
   no_arg: "no_arg"
  filenames: []
  geo_filenames: []
  chan_dim: 0
  geo_coord_dim: 2
  geo_lat_index: 1
  geo_lon_index: 0


fusion:
 projection_id: 4326
 description: "Generating eMAS GeoTiffs"
 area_id: "eMAS"
 projection_proj4:
  #proj: "utm"
  #zone: 11
  proj: "longlat"
  datum: "WGS84" 
 final_resolution: 0.09 #0.00225 #0.000225
 projection_units: "degrees"
 resample_radius: 50000
 resample_n_neighbors: 128
 resample_n_procs: 10
 resample_epsilon: 1.6
 use_bilinear: True 
 lon_bounds: [-125.45, -109.75]
 lat_bounds: [35.0, 44.95]

       
output_files: [
#"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T163759Z_S008G08.tif",
#"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T164436Z_S008G09.tif",
#"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T163122Z_S008G07.tif"
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T143122Z_S006G07.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T143759Z_S006G08.tif",
"/data/nlahaye/remoteSensing/TEMPO/TEMPO_RAD_L1_V03_20240726T144436Z_S006G09.tif", 
]



