
low_res:
 data:
  fill_value: -9.96921e+36
  valid_min: -9.0e+35 #0.0000001
  valid_max: 9.0e+36
  reader_type: "tempo_netcdf"
  reader_kwargs:
   no_arg: ''
  geo_reader_type: "tempo_netcdf_geo"
  geo_reader_kwargs:
   no_arg: "no_arg"
  filenames: [
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250106T174347Z_S007G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250106T184347Z_S008G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250106T194347Z_S009G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250106T204347Z_S010G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250106T214347Z_S011G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250106T222355Z_S012G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250106T230403Z_S013G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250106T234411Z_S014G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250107T174414Z_S007G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250107T184414Z_S008G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250107T194414Z_S009G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250107T204414Z_S010G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250107T214414Z_S011G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250107T222252Z_S012G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250108T174439Z_S007G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250108T184439Z_S008G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250108T194439Z_S009G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250108T204439Z_S010G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250108T214439Z_S011G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250108T222447Z_S012G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250108T230455Z_S013G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250108T234503Z_S014G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250109T174504Z_S007G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250109T184504Z_S008G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250109T194504Z_S009G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250109T204504Z_S010G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250109T214504Z_S011G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250109T222512Z_S012G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250109T230520Z_S013G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250109T234528Z_S014G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250110T174529Z_S007G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250110T184529Z_S008G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250110T194529Z_S009G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250110T204529Z_S010G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250110T214529Z_S011G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250110T222537Z_S012G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250110T230545Z_S013G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250110T234553Z_S014G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250111T174553Z_S007G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250111T184553Z_S008G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250111T194553Z_S009G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250111T204553Z_S010G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250111T214553Z_S011G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250111T222601Z_S012G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250111T230609Z_S013G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250111T234617Z_S014G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250112T174616Z_S007G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250112T184616Z_S008G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250112T194616Z_S009G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250112T204616Z_S010G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250112T214616Z_S011G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250112T222624Z_S012G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250112T230632Z_S013G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250112T234640Z_S014G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250113T174639Z_S007G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250113T184639Z_S008G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250113T194639Z_S009G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250113T204639Z_S010G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250113T214639Z_S011G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250113T222647Z_S012G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250113T230655Z_S013G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250113T234703Z_S014G06.nc",
]

  geo_filenames: [
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250106T174347Z_S007G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250106T184347Z_S008G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250106T194347Z_S009G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250106T204347Z_S010G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250106T214347Z_S011G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250106T222355Z_S012G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250106T230403Z_S013G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250106T234411Z_S014G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250107T174414Z_S007G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250107T184414Z_S008G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250107T194414Z_S009G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250107T204414Z_S010G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250107T214414Z_S011G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250107T222252Z_S012G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250108T174439Z_S007G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250108T184439Z_S008G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250108T194439Z_S009G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250108T204439Z_S010G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250108T214439Z_S011G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250108T222447Z_S012G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250108T230455Z_S013G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250108T234503Z_S014G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250109T174504Z_S007G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250109T184504Z_S008G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250109T194504Z_S009G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250109T204504Z_S010G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250109T214504Z_S011G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250109T222512Z_S012G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250109T230520Z_S013G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250109T234528Z_S014G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250110T174529Z_S007G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250110T184529Z_S008G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250110T194529Z_S009G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250110T204529Z_S010G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250110T214529Z_S011G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250110T222537Z_S012G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250110T230545Z_S013G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250110T234553Z_S014G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250111T174553Z_S007G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250111T184553Z_S008G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250111T194553Z_S009G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250111T204553Z_S010G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250111T214553Z_S011G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250111T222601Z_S012G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250111T230609Z_S013G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250111T234617Z_S014G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250112T174616Z_S007G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250112T184616Z_S008G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250112T194616Z_S009G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250112T204616Z_S010G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250112T214616Z_S011G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250112T222624Z_S012G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250112T230632Z_S013G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250112T234640Z_S014G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250113T174639Z_S007G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250113T184639Z_S008G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250113T194639Z_S009G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250113T204639Z_S010G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250113T214639Z_S011G09.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250113T222647Z_S012G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250113T230655Z_S013G06.nc",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250113T234703Z_S014G06.nc",
]


  chan_dim: 2
  geo_coord_dim: 0
  geo_lat_index: 0
  geo_lon_index: 1


high_res:
 data:
  valid_min: 0.0
  valid_max: 100000000
  reader_type: "numpy"
  reader_kwargs:
   no_arg: "no_arg"
  geo_reader_type: "numpy"
  geo_reader_kwargs:
   no_arg: "no_arg"
  filenames: []
  geo_filenames: []
  chan_dim: 0
  geo_coord_dim: 2
  geo_lat_index: 1
  geo_lon_index: 0


fusion:
 projection_id: 4326
 description: "Generating eMAS GeoTiffs"
 area_id: "eMAS"
 projection_proj4:
  #proj: "utm"
  #zone: 11
  proj: "longlat"
  datum: "WGS84" 
 final_resolution: 0.09 #0.00225 #0.000225
 projection_units: "degrees"
 resample_radius: 50000
 resample_n_neighbors: 128
 resample_n_procs: 10
 resample_epsilon: 1.6
 use_bilinear: True 
 lon_bounds: [-124.0, -114.0]
 lat_bounds: [28.0, 38.0]
 
output_files: [
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250106T174347Z_S007G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250106T184347Z_S008G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250106T194347Z_S009G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250106T204347Z_S010G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250106T214347Z_S011G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250106T222355Z_S012G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250106T230403Z_S013G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250106T234411Z_S014G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250107T174414Z_S007G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250107T184414Z_S008G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250107T194414Z_S009G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250107T204414Z_S010G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250107T214414Z_S011G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250107T222252Z_S012G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250108T174439Z_S007G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250108T184439Z_S008G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250108T194439Z_S009G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250108T204439Z_S010G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250108T214439Z_S011G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250108T222447Z_S012G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250108T230455Z_S013G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250108T234503Z_S014G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250109T174504Z_S007G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250109T184504Z_S008G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250109T194504Z_S009G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250109T204504Z_S010G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250109T214504Z_S011G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250109T222512Z_S012G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250109T230520Z_S013G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250109T234528Z_S014G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250110T174529Z_S007G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250110T184529Z_S008G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250110T194529Z_S009G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250110T204529Z_S010G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250110T214529Z_S011G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250110T222537Z_S012G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250110T230545Z_S013G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250110T234553Z_S014G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250111T174553Z_S007G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250111T184553Z_S008G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250111T194553Z_S009G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250111T204553Z_S010G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250111T214553Z_S011G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250111T222601Z_S012G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250111T230609Z_S013G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250111T234617Z_S014G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250112T174616Z_S007G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250112T184616Z_S008G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250112T194616Z_S009G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250112T204616Z_S010G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250112T214616Z_S011G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250112T222624Z_S012G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250112T230632Z_S013G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250112T234640Z_S014G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250113T174639Z_S007G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250113T184639Z_S008G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250113T194639Z_S009G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250113T204639Z_S010G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250113T214639Z_S011G09.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250113T222647Z_S012G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250113T230655Z_S013G06.tif",
"/data/nlahaye/remoteSensing/TEMPO_LA/TEMPO_RAD_L1_V03_20250113T234703Z_S014G06.tif",
]



