
low_res:
 data:
  valid_min: 0.0000001
  valid_max: 100000000
  reader_type: "gk2a_netcdf"
  reader_kwargs:
   no_arg: ''
  geo_reader_type: "gk2a_netcdf_geo"
  geo_reader_kwargs:
   no_arg: "no_arg"
  filenames: [
["/data/nlahaye/remoteSensing/GK2A/GK2A/L1B/EA/202203/06/00/gk2a_ami_le1b_ir087_ea020lc_202203060020.nc"]
]
  geo_filenames: [
"/data/nlahaye/remoteSensing/GK2A/gk2a_ami_ea020lc_latlon.nc",
]
  chan_dim: 0
  geo_coord_dim: 0
  geo_lat_index: 0
  geo_lon_index: 1


high_res:
 data:
  valid_min: 0.0
  valid_max: 100000000
  reader_type: "numpy"
  reader_kwargs:
   no_arg: "no_arg"
  geo_reader_type: "numpy"
  geo_reader_kwargs:
   no_arg: "no_arg"
  filenames: []
  geo_filenames: []
  chan_dim: 0
  geo_coord_dim: 2
  geo_lat_index: 0
  geo_lon_index: 1


fusion:
 projection_id: 4326
 description: "Generating GK2A GeoTiffs"
 area_id: "GERD Dam"
 projection_proj4:
  proj: "longlat"
  datum: "WGS84" 
 final_resolution: 0.01
 projection_units: "degrees"
 resample_radius: 5000
 resample_n_neighbors: 64
 resample_n_procs: 10
 resample_epsilon: 1.6
 use_bilinear: True 
       
output_files: [
"/data/nlahaye/remoteSensing/GK2A/GK2A/L1B/EA/202203/06/00/gk2a_ami_le1b_ir087_ea020lc_202203060020.nc.tif"]




