[tool.black]
line-length = 88

[project]
name = "sit_fuse"
dynamic = ["version"]


[build-system]
requires = ["setuptools>=43.0.0"]


[tool.setuptools]
packages = ["sit_fuse"]
py-modules = ["__init__"]

