
# Purpose of this script is to automate validation analysis for SIT FUSE products 
# from output_vals.pkl file generated by running hab_post_inference_pipeline.py
#
# Notes on output_vals.pkl file:
#   context_data['validation'] is a list of tuples, where
#   each tuple is a row in the confusion matrix structured like this: 
    #     ([row_vector], [bin_edges], severity_bin * 1000)
    #       row_vector is a given severity class's row of the confusion matrix (prediction counts), 
    #       bin_edges is the upper limit of cell/toxin concentration that defines that severity bin,
    #       severity_bin gives the bin index (#)
    #       
    #       Example: 
    #       x['validation']['Total_Phytoplankton']['s3a']['no_trop']

    #       {'validation': [[(array([0, 0, 3, 0, 0, 0]), array([        0,      1000,     10000,    100000,   1000000,  10000000,
    #        100000000]), 3000), (array([ 0,  2,  6, 14,  0,  0]), array([        0,      1000,     10000,    100000,   1000000,  10000000,
    #        100000000]), 4000), (array([0, 0, 0, 0, 1, 0]), array([        0,      1000,     10000,    100000,   1000000,  10000000,
    #        100000000]), 5000)]]}
    #
    #       [0, 0, 3, 0, 0, 0] is the row vector, 
    #       [        0,      1000,     10000,    100000,   1000000,  10000000,  100000000] is the bin edges,
    #       3 is the severity bin 

#Example command line prompt: 
#python src/sit_fuse/pipelines/habs/hab_validation_analysis_ERDA.py "D:\Users\charlotte.rhoads\Downloads\output_vals.pkl"

# Terminology in this script: 
# instrument = the satellite platform carrying the ocean color sensor, i.e ['pace', 'aqua_modis', 's3a', 's3b', 'jpss1', 'snpp']
# product = the specific SIT FUSE phytoplankton product, i.e ['pDA', 'Pseudo_nitzschia_delicatissima_group', 'Pseudo_nitzschia_seriata_group', 'Total_Phytoplankton']
# bin (also severity, severity class) = severity classification predicted by SIT FUSE, derived from each row tuple's third value (severity * 1000)
# context = either no tropomi or tropomi ['no_trop', 'trop], set in hab_post_inference_pipeline.py

import argparse
import csv
import json
import pickle
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import matplotlib
import yaml
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

#EDIT THESE if you want to change the display labels for the boxplots
# Severity classification scheme, hard-coded here to avoid dropping severity classes not predicted by SIT FUSE 
XLABEL_INSTRUMENT = ['Pace OCI', 'Aqua MODIS', 'Sentinel-3A OLCI', 'Sentinel-3B OLCI', 'JPSS-1 VIIRS','JPSS-2 VIIRS', 'SNPP VIIRS']
XLABEL_PRODUCT = ["Particulate Domoic Acid", r'$\mathit{P. Delicatissima}$', r'$\mathit{P. Seriata}$', "Total Phytoplankton"]
XLABEL_SEVERITY = ["0", "1", "2", "3", "4", "5"]
 
# EDIT THESE if your validation keys differ from what's is here
# Maps from the raw dictionary keys found in the pickle to the display labels set above
# To check the actual strings of the validation keys in your file:
    # with open(r"D:\Users\charlotte.rhoads\Downloads\output_vals.pkl", "rb") as f:
    #        x = pickle.load(f)
    # list(x["validation"].keys())

PRODUCT_LABEL_MAP = {
    "pDA": XLABEL_PRODUCT[0],
    "Pseudo_nitzschia_delicatissima_group": XLABEL_PRODUCT[1],
    "Pseudo_nitzschia_seriata_group": XLABEL_PRODUCT[2],
    "Total_Phytoplankton": XLABEL_PRODUCT[3],
}

# EDIT THESE if your instrument keys differ from what's is here
# To check the actual strings of the validation keys in your file:
    # with open(r"D:\Users\charlotte.rhoads\Downloads\output_vals.pkl", "rb") as f:
    #        x = pickle.load(f)
    # list(x["instrument"].keys())

INSTRUMENT_LABEL_MAP = {
    "pace": XLABEL_INSTRUMENT[0],
    "modis": XLABEL_INSTRUMENT[1],
    "s3a": XLABEL_INSTRUMENT[2],
    "s3b": XLABEL_INSTRUMENT[3],
    "jpss1": XLABEL_INSTRUMENT[4],
    "jpss2": XLABEL_INSTRUMENT[5],
    "snpp": XLABEL_INSTRUMENT[6],
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Create F1 box-and-whisker plots and csv from HAB validation pickle output.")
    parser.add_argument("pickle_file", default=None, nargs="?")
    parser.add_argument("--output-dir", default=None, help="Directory for output plots and csv. Defaults to the pickle file's parent directory.")
    return parser.parse_args()


def load_validation_payload(pickle_path: Path) -> Dict[str, Any]:
    with pickle_path.open("rb") as handle:
        payload = pickle.load(handle)

    if not isinstance(payload, dict) or "validation" not in payload:
        raise ValueError("The pickle file does not contain a top-level 'validation' dictionary.")

    return payload


def iter_validation_rows(context_data: Dict[str, Any]):
    """Extract the raw (row_vector, bin_edges, severity*1000) tuples for one species/instrument/context.
    """
    validation_entries = context_data.get("validation", [])
    if isinstance(validation_entries, dict):
        validation_entries = [validation_entries]
    if not isinstance(validation_entries, (list, tuple)):
        validation_entries = [validation_entries]

    for entry in validation_entries:
        if isinstance(entry, (list, tuple)):
            for item in entry:
                yield item
        else:
            yield entry


def build_confusion_matrix(rows: List[Any]) -> Optional[np.ndarray]:
    """Stack row vectors into a full confusion matrix.
    """
    row_vectors: Dict[int, np.ndarray] = {}

    for entry in rows:
        if not isinstance(entry, tuple) or len(entry) < 3:
           continue

        raw_bin = entry[2] #third element of tuple is the severity bin * 1000
        if not isinstance(raw_bin, (int, float, np.integer, np.floating)):
            continue
        #new validation output_vals.pk use 1-6 for severity no longer 0-5
        bin_index = int(round(float(raw_bin) / 1000.0)-1)
        #print(bin_index, raw_bin, flush=True)

        vector = np.asarray(entry[0], dtype=float).ravel()
        if vector.size == 0:
            continue

        if bin_index in row_vectors and row_vectors[bin_index].size == vector.size:
            row_vectors[bin_index] = row_vectors[bin_index] + vector
        
        else:
            row_vectors[bin_index] = vector

    if not row_vectors:
        return None

    num_bins = max(max(row_vectors) + 1, max(v.size for v in row_vectors.values()))
    matrix = np.zeros((num_bins, num_bins), dtype=float)
    for bin_index, vector in row_vectors.items():
        matrix[bin_index, : vector.size] = vector

    return matrix


def bin_scores_with_support(matrix: np.ndarray) -> Dict[int, Any]:
    """Per-bin F1 and support/weight (total count: tp + fn) for bins that pass a skip rule.
        A bin is skipped: if it has no true instances at all (total_count == 0)
        or if it has true instances but zero correct predictions (tp == 0)
    """
    results: Dict[int, Any] = {}
    for j in range(matrix.shape[0]):
        tp = matrix[j, j]
        fp = matrix[j, :].sum() - tp
        fn = matrix[:, j].sum() - tp
        # check for negative values due to floating point errors
        assert fp >= -1e-9 and fn >= -1e-9, (j, tp, fp, fn, matrix[j, :], matrix[:, j])
        total_count = tp + fn

        if total_count == 0:
            continue
        elif tp == 0:
            f1 = 0.0
        else:
            precision = tp / (tp + fp)
            recall = tp / (tp + fn)
            f1 = 2 * ((precision * recall) / (precision + recall))
            results[j] = {"f1": f1, "support": float(total_count)}
            #print(f"Bin {j}: F1 = {f1}, Support = {total_count}")

    return results


def per_bin_f1_from_confusion_matrix(matrix: np.ndarray) -> Dict[int, float]:
    """F1 score for each severity class, keyed by bin index.
    """
    return {j: scores["f1"] for j, scores in bin_scores_with_support(matrix).items()}


def macro_f1_from_bin_scores(bin_scores: Dict[int, Any]) -> Optional[float]:
    """Average F1 across bins, given an already-computed bin_scores dict."""
    if not bin_scores:
        return None
    return float(np.mean([scores["f1"] for scores in bin_scores.values()]))


def weighted_f1_from_bin_scores(bin_scores: Dict[int, Any]) -> Optional[float]:
    """Weighted average F1 across bins (weight = each class's total_count), given
    an already-computed bin_scores dict."""
    if not bin_scores:
        return None
    f1_values = [scores["f1"] for scores in bin_scores.values()]
    weights = [scores["support"] for scores in bin_scores.values()]
    return float(np.average(f1_values, weights=weights))


def total_support_from_bin_scores(bin_scores: Dict[int, Any]) -> float:
    """Total N (true count, tp + fn) summed across all bins used in a confusion matrix."""
    return float(sum(scores["support"] for scores in bin_scores.values()))


def macro_f1_from_confusion_matrix(matrix: np.ndarray) -> Optional[float]:
    """Average F1 across bins for single matrix F1 score."""
    return macro_f1_from_bin_scores(bin_scores_with_support(matrix))


def weighted_f1_from_confusion_matrix(matrix: np.ndarray) -> Optional[float]:
    """Weighted average F1 across bins for single matrix F1 score (weight = each class's total_count).
    """
    return weighted_f1_from_bin_scores(bin_scores_with_support(matrix))


def collect_grouped_series(payload: Dict[str, Any]) -> Tuple[Dict[str, Dict[str, List[float]]], Dict[str, Dict[str, List[float]]]]:
    """Macro-F1 and weighted-F1 grouped per species/instrument/severity bin.
    Returns a (grouped_scores, grouped_n) pair of dict-of-dict-of-list
    structures of f1 scores and total counts.
    """
    grouped: Dict[str, Dict[str, List[float]]] = {
        "products": {},
        "instrument": {},
        "products_weighted": {},
        "instrument_weighted": {},
        "severity": {label: [] for label in XLABEL_SEVERITY},
        "severity_weighted": {label: [] for label in XLABEL_SEVERITY},
    }
    
    grouped_n: Dict[str, Dict[str, List[float]]] = {
        "products": {},
        "instrument": {},
        "products_weighted": {},
        "instrument_weighted": {},
        "severity": {label: [] for label in XLABEL_SEVERITY},
        "severity_weighted": {label: [] for label in XLABEL_SEVERITY},
    }

    validation_payload = payload["validation"]
    for product_name, product_data in validation_payload.items():
        if not isinstance(product_data, dict):
            continue

        product_label = PRODUCT_LABEL_MAP.get(product_name, product_name)

        for instrument_name, instrument_data in product_data.items():
            if not isinstance(instrument_data, dict):
                continue

            instrument_label = INSTRUMENT_LABEL_MAP.get(instrument_name, instrument_name)

            for context_name, context_data in instrument_data.items():
                if not isinstance(context_data, dict):
                    continue

                rows = list(iter_validation_rows(context_data))
                confusion_matrix = build_confusion_matrix(rows)
                if confusion_matrix is None:
                    continue

                bin_scores = bin_scores_with_support(confusion_matrix)
                if not bin_scores:
                    continue

                total_n = total_support_from_bin_scores(bin_scores)

                macro_score = macro_f1_from_bin_scores(bin_scores)
                if macro_score is not None:
                    grouped["products"].setdefault(product_label, []).append(macro_score)
                    grouped_n["products"].setdefault(product_label, []).append(total_n)
                    grouped["instrument"].setdefault(instrument_label, []).append(macro_score)
                    grouped_n["instrument"].setdefault(instrument_label, []).append(total_n)

                weighted_score = weighted_f1_from_bin_scores(bin_scores)
                if weighted_score is not None:
                    grouped["products_weighted"].setdefault(product_label, []).append(weighted_score)
                    grouped_n["products_weighted"].setdefault(product_label, []).append(total_n)
                    grouped["instrument_weighted"].setdefault(instrument_label, []).append(weighted_score)
                    grouped_n["instrument_weighted"].setdefault(instrument_label, []).append(total_n)

                for bin_index, scores in bin_scores.items():
                    if 0 <= bin_index < len(XLABEL_SEVERITY):
                        label = XLABEL_SEVERITY[bin_index]
                    else:
                        # If bin index outside the expected 0-5 range; still keep the data
                        label = str(bin_index)
                    grouped["severity"].setdefault(label, [])
                    grouped["severity_weighted"].setdefault(label, [])
                    grouped_n["severity"].setdefault(label, [])
                    grouped_n["severity_weighted"].setdefault(label, [])
                    grouped["severity"][label].append(scores["f1"])
                    grouped["severity_weighted"][label].append(scores["f1"])
                    grouped_n["severity"][label].append(scores["support"])
                    grouped_n["severity_weighted"][label].append(scores["support"])

    return grouped, grouped_n


def make_boxplot(
    data_by_label: Dict[str, List[float]],
    n_by_label: Dict[str, List[float]],
    title: str,
    ylabel: str,
    xlabel: str,
    output_path: Path,
) -> None:
    labels = list(data_by_label.keys())
    values = [data_by_label[label] for label in labels]

    fig, ax = plt.subplots(figsize=(max(8, 0.9 * len(labels)), 6))
    ax.boxplot(values)
    ax.set_xticks(range(1, len(labels) + 1))
    ax.set_xticklabels(labels, rotation=45, ha="right")
    #ax.set_title(title)
    ax.set_ylabel(ylabel)
    ax.set_xlabel(xlabel)
    ax.set_ylim(0.3, 1.05)  #set based on range of F1 scores, can be updated

    # Annotate each box with n
    for i, label in enumerate(labels, start=1):
        box_values = data_by_label[label]
        box_n = n_by_label.get(label, [])
        total_n = int(round(sum(box_n))) if box_n else 0
        top_of_box = max(box_values) if box_values else 0.3
        ax.text(
            i,
            min(top_of_box + 0.02, 1.03),
            f"n={total_n}",
            ha="center",
            va="bottom",
            fontsize=8,
        )

    fig.tight_layout()
    fig.savefig(output_path, dpi=300)
    plt.close(fig)


def save_confusion_matrix_csv(payload: Dict[str, Any], output_path: Path) -> None:
    """Write confusion matrices, F1 scores, and n (count) to a CSV file.
    """
    validation_payload = payload["validation"]
    fieldnames = ["product", "instrument", "context", "macro_f1", "weighted_f1", "n", "confusion_matrix"]

    with output_path.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()

        for product_name, product_data in validation_payload.items():
            if not isinstance(product_data, dict):
                continue

            product_label = PRODUCT_LABEL_MAP.get(product_name, product_name)

            for instrument_name, instrument_data in product_data.items():
                if not isinstance(instrument_data, dict):
                    continue

                instrument_label = INSTRUMENT_LABEL_MAP.get(instrument_name, instrument_name)

                for context_name, context_data in instrument_data.items():
                    if not isinstance(context_data, dict):
                        continue

                    rows = list(iter_validation_rows(context_data))
                    confusion_matrix = build_confusion_matrix(rows)
                    if confusion_matrix is None:
                        continue

                    bin_scores = bin_scores_with_support(confusion_matrix)
                    macro_score = macro_f1_from_bin_scores(bin_scores)
                    weighted_score = weighted_f1_from_bin_scores(bin_scores)
                    total_n = total_support_from_bin_scores(bin_scores)

                    writer.writerow(
                        {
                            "product": product_label,
                            "instrument": instrument_label,
                            "context": context_name,
                            "macro_f1": "" if macro_score is None else macro_score,
                            "weighted_f1": "" if weighted_score is None else weighted_score,
                            "n": total_n,
                            "confusion_matrix": json.dumps(confusion_matrix.tolist()),
                        }
                    )


def main() -> None:
    args = parse_args()
    pickle_path = Path(args.pickle_file).expanduser()
    output_dir = Path(args.output_dir).expanduser() if args.output_dir else pickle_path.parent
    output_dir.mkdir(parents=True, exist_ok=True)

    payload = load_validation_payload(pickle_path)
    grouped_series, grouped_n = collect_grouped_series(payload)

    #EDIT THESE for (title, ylabel, xlabel) for each group of boxplots
    titles = {
        "products": (" ", "Macro F1 score", "Product"),
        "instrument": ("  ", "Macro F1 score", "Satellite sensor"),
        "products_weighted": (" ", "Weighted F1 score", "Product"),
        "instrument_weighted": ("  ", "Weighted F1 score", "Satellite sensor"),
        "severity": ("  ", "Macro F1 score", "Severity"),
        "severity_weighted": ("  ", "Weighted F1 score", "Severity"),
    }

    for group_name, data_by_label in grouped_series.items():
        if not data_by_label:
            continue

        title, ylabel, xlabel = titles.get(group_name, (f"F1 score by {group_name}", "F1 score", "Group"))

        output_path = output_dir / f"validation_boxplot_{group_name}.png"
        make_boxplot(data_by_label, grouped_n.get(group_name, {}), title, ylabel, xlabel, output_path)
        print(f"Saved {output_path}")

    csv_output_path = output_dir / "confusion_matrices.csv"
    save_confusion_matrix_csv(payload, csv_output_path)
    print(f"Saved {csv_output_path}")


if __name__ == "__main__":
    main()