
# Purpose of this script is to automate validation analysis for SIT FUSE products 
# from output_vals.pkl file generated by the hab_post_inference_pipeline.py
#
# Notes on output_vals.pkl:
# context_data['validation'] is a list of tuples, where
#  each tuple is a row in the confusion matrix structured like this: 
#     ([row_vector], [bin_edges], severity_bin * 1000)
#     The severity_bin gives the bin index,
#     bin_edges is the upper limit of cell concentration that defines that severity bin
#     row_vector is that class's row of predicted-class counts. 

#Example command line prompt: 
#python src/sit_fuse/pipelines/habs/validation_test_ERDA.py "D:\Users\charlotte.rhoads\Downloads\output_vals.pkl"

# Terminology in this script: 
# instrument = the satellite carrying the ocean color sensor, i.e ['pace', 'aqua_modis', 's3a', 's3b', 'jpss1', 'snpp']
# product = the specific SIT FUSE phytoplankton product, i.e ['Pseudo_nitzschia_delicatissima_group', 'Pseudo_nitzschia_seriata_group', 'Total_Phytoplankton']
# bin (also severity, severity class) = severity classification predicted by SIT FUSE, derived from each row tuple's third value (severity * 1000)
# context = either no tropomi or tropomi ['no_trop', 'trop] 

import argparse
import csv
import json
import pickle
from pathlib import Path
from typing import Any, Dict, List, Optional

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np


#  Severity classification scheme, hard-coded here to avoid dropping severity classes not predicted by SIT FUSE 
XLABEL_SEVERITY = ["0", "1", "2", "3", "4", "5"]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Create macro-F1 box-and-whisker plots from HAB validation pickle output.")
    parser.add_argument("pickle_file", default=None, nargs="?")
    parser.add_argument("--output-dir", default=None, help="Directory for output plots. Defaults to the pickle file's parent directory.")
    return parser.parse_args()


def load_validation_payload(pickle_path: Path) -> Dict[str, Any]:
    with pickle_path.open("rb") as handle:
        payload = pickle.load(handle)

    if not isinstance(payload, dict) or "validation" not in payload:
        raise ValueError("The pickle file does not contain a top-level 'validation' dictionary.")

    return payload


def iter_validation_rows(context_data: Dict[str, Any]):
    """Extract the raw (row_vector, bin_edges, severity*1000) tuples for one species/instrument/context.
    """
    validation_entries = context_data.get("validation", [])
    if isinstance(validation_entries, dict):
        validation_entries = [validation_entries]
    if not isinstance(validation_entries, (list, tuple)):
        validation_entries = [validation_entries]

    for entry in validation_entries:
        if isinstance(entry, (list, tuple)):
            for item in entry:
                yield item
        else:
            yield entry

    #print(list(context_data["validation"]), flush=True)


def build_confusion_matrix(rows: List[Any]) -> Optional[np.ndarray]:
    """Stack row vectors into a full confusion matrix.
    """
    row_vectors: Dict[int, np.ndarray] = {}

    for entry in rows:
        if not isinstance(entry, tuple) or len(entry) < 3:
            continue

        raw_bin = entry[2]
        if not isinstance(raw_bin, (int, float, np.integer, np.floating)):
            continue
        bin_index = int(round(float(raw_bin) / 1000.0))

        vector = np.asarray(entry[0], dtype=float).ravel()
        if vector.size == 0:
            continue

        if bin_index in row_vectors and row_vectors[bin_index].size == vector.size:
            row_vectors[bin_index] = row_vectors[bin_index] + vector
        else:
            row_vectors[bin_index] = vector

    if not row_vectors:
        return None

    num_bins = max(max(row_vectors) + 1, max(v.size for v in row_vectors.values()))
    matrix = np.zeros((num_bins, num_bins), dtype=float)
    for bin_index, vector in row_vectors.items():
        matrix[bin_index, : vector.size] = vector

   #de-bugging notes: 
    #print(bin_index, vector, flush=True)
    #bin_index corresponds to severity bin index (0-5),
    #print(matrix, flush=True) #fills empty rows with zeros for missing classes
    #print(num_bins, flush=True)
    #print(matrix.shape, vector.shape, flush=True)
    #shape of matrix: (6, 6), vector (6,),num_bins; 6 -- filled empty rows correctly

    return matrix


def bin_scores_with_support(matrix: np.ndarray) -> Dict[int, Any]:
    """Per-bin F1 and support/total count (tp + fn) for bins that pass a skip rule.
        A bin is skipped: if it has no true instances at all (total_count == 0)
        or if it has true instances but zero correct predictions (tp == 0)
    """
    results: Dict[int, Any] = {}
    for j in range(matrix.shape[0]):
        tp = matrix[j, j]
        fp = matrix[j, :].sum() - tp
        fn = matrix[:, j].sum() - tp
        total_count = tp + fn

        if total_count == 0 or tp == 0:
            continue

        precision = tp / (tp + fp)
        recall = tp / (tp + fn)
        f1 = 2 * ((precision * recall) / (precision + recall))
        results[j] = {"f1": f1, "support": float(total_count)} 

    return results


def per_bin_f1_from_confusion_matrix(matrix: np.ndarray) -> Dict[int, float]:
    """F1 score for each severity class, keyed by bin index.
    """
    return {j: scores["f1"] for j, scores in bin_scores_with_support(matrix).items()}


def macro_f1_from_confusion_matrix(matrix: np.ndarray) -> Optional[float]:
    """Average F1 across bins for whole matrix F1 score."""
    scores = per_bin_f1_from_confusion_matrix(matrix)
    if not scores:
        return None
    return float(np.mean(list(scores.values())))

def weighted_f1_from_confusion_matrix(matrix: np.ndarray) -> Optional[float]:
    """Weighted average F1 across bins for whole matrix F1 score (weight = each class's total_count).
    """
    bin_scores = bin_scores_with_support(matrix)
    if not bin_scores:
        return None
    f1_values = [scores["f1"] for scores in bin_scores.values()]
    weights = [scores["support"] for scores in bin_scores.values()]
    return float(np.average(f1_values, weights=weights))
 
 
def collect_grouped_series(payload: Dict[str, Any]) -> Dict[str, Dict[str, List[float]]]:
    """Macro-F1 and weighted-F1 grouped per species/instrument/severity bin.
    """
    grouped: Dict[str, Dict[str, List[float]]] = {
        "products": {},
        "instrument": {},
        "products_weighted": {},
        "instrument_weighted": {},
        "severity": {label: [] for label in XLABEL_SEVERITY},
        "severity_weighted": {label: [] for label in XLABEL_SEVERITY},
    }
 
    validation_payload = payload["validation"]
    for product_name, product_data in validation_payload.items():
        if not isinstance(product_data, dict):
            continue
 
        for instrument_name, instrument_data in product_data.items():
            if not isinstance(instrument_data, dict):
                continue
 
            for context_name, context_data in instrument_data.items():
                if not isinstance(context_data, dict):
                    continue
 
                rows = list(iter_validation_rows(context_data))
                confusion_matrix = build_confusion_matrix(rows)
                if confusion_matrix is None:
                    continue
 
                macro_score = macro_f1_from_confusion_matrix(confusion_matrix)
                if macro_score is not None:
                    grouped["products"].setdefault(product_name, []).append(macro_score)
                    grouped["instrument"].setdefault(instrument_name, []).append(macro_score)
 
                weighted_score = weighted_f1_from_confusion_matrix(confusion_matrix)
                if weighted_score is not None:
                    grouped["products_weighted"].setdefault(product_name, []).append(weighted_score)
                    grouped["instrument_weighted"].setdefault(instrument_name, []).append(weighted_score)
 
                for bin_index, bin_score in per_bin_f1_from_confusion_matrix(confusion_matrix).items():
                    if 0 <= bin_index < len(XLABEL_SEVERITY):
                        label = XLABEL_SEVERITY[bin_index]
                    else:
                        # If bin index outside the expected 0-5 range; still keep the data
                        label = str(bin_index)
                    grouped["severity"].setdefault(label, [])
                    grouped["severity_weighted"].setdefault(label, [])
                grouped["severity"][label].append(bin_score)
                grouped["severity_weighted"][label].append(bin_score)
 
    return grouped
 
 
def make_boxplot(data_by_label: Dict[str, List[float]], title: str, ylabel: str, output_path: Path) -> None:
    labels = list(data_by_label.keys())
    values = [data_by_label[label] for label in labels]
 
    fig, ax = plt.subplots(figsize=(max(8, 0.9 * len(labels)), 6))
    ax.boxplot(values)
    ax.set_xticks(range(1, len(labels) + 1))
    ax.set_xticklabels(labels, rotation=45, ha="right")
    ax.set_title(title)
    ax.set_ylabel(ylabel)
    ax.set_xlabel("Group")
    ax.set_ylim(0, 1)
    fig.tight_layout()
    fig.savefig(output_path, dpi=300)
    plt.close(fig)


def save_confusion_matrix_csv(payload: Dict[str, Any], output_path: Path) -> None:
    """Write confusion matrices and F1 scores to a CSV file.
    """
    validation_payload = payload["validation"]
    fieldnames = ["product", "instrument", "context", "macro_f1", "weighted_f1", "confusion_matrix"]

    with output_path.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()

        for product_name, product_data in validation_payload.items():
            if not isinstance(product_data, dict):
                continue

            for instrument_name, instrument_data in product_data.items():
                if not isinstance(instrument_data, dict):
                    continue

                for context_name, context_data in instrument_data.items():
                    if not isinstance(context_data, dict):
                        continue

                    rows = list(iter_validation_rows(context_data))
                    confusion_matrix = build_confusion_matrix(rows)
                    if confusion_matrix is None:
                        continue

                    macro_score = macro_f1_from_confusion_matrix(confusion_matrix)
                    weighted_score = weighted_f1_from_confusion_matrix(confusion_matrix)

                    writer.writerow(
                        {
                            "product": product_name,
                            "instrument": instrument_name,
                            "context": context_name,
                            "macro_f1": "" if macro_score is None else macro_score,
                            "weighted_f1": "" if weighted_score is None else weighted_score,
                            "confusion_matrix": json.dumps(confusion_matrix.tolist()),
                        }
                    )
 
 
def main() -> None:
    args = parse_args()
    pickle_path = Path(args.pickle_file).expanduser()
    output_dir = Path(args.output_dir).expanduser() if args.output_dir else pickle_path.parent
    output_dir.mkdir(parents=True, exist_ok=True)
 
    payload = load_validation_payload(pickle_path)
    grouped_series = collect_grouped_series(payload)
 
    titles = {
        "products": ("Macro F1 score by product", "Macro F1 score"),
        "instrument": ("Macro F1 score by instrument", "Macro F1 score"),
        "products_weighted": ("Weighted F1 score by product", "Weighted F1 score"),
        "instrument_weighted": ("Weighted F1 score by instrument", "Weighted F1 score"),
        "severity": ("F1 score by severity level", "Macro F1 score)"),
        "severity_weighted": ("F1 score by severity level (weighted)", "Weighted F1 score"),
    }
 
    for group_name, data_by_label in grouped_series.items():
        if not data_by_label:
            continue
 
        title, ylabel = titles.get(group_name, (f"F1 score by {group_name}", "F1 score"))
 
        output_path = output_dir / f"validation_boxplot_{group_name}.png"
        make_boxplot(data_by_label, title, ylabel, output_path)
        print(f"Saved {output_path}")

    csv_output_path = output_dir / "confusion_matrices.csv"
    save_confusion_matrix_csv(payload, csv_output_path)
    print(f"Saved {csv_output_path}")
 
 
if __name__ == "__main__":
    main()