output:
 out_dir: "/data/nlahaye/output/Learnergy/DBN_PALM_OIL_AUTO_CLUST_NEW_3/"
 training_output: "output.data"
 training_mse: "rec_mse.data"
 testing_output: "output_test.data"
 testing_mse: "rec_mse_test.data"
 generate_train_output: False
 generate_output: False
 model: "dbn"

dbn:
 conv: False
 subset_training: -1 #2000000 #10000000
 deep_cluster: 800
 heir_tiers: 1
 overwrite_model: False
 tune_clust: False # True
 tune_dbn: False
 tune_scaler: False
 params:
  model_type: ["gaussian_selu"] #, 'gaussian_relu_dropout', 'gaussian_relu_dropout'] #'variance_gaussian_dropout' "gaussian_dropout"
  dbn_arch: [2000] #[2000] [250, 500, 2000] #, 2000]
  gibbs_steps: [15] #, 7, 7] #, 10] #, 25]
  learning_rate: [0.0001] #, 0.0001, 0.0001] #, 0.01] #, 0.01]
  momentum: [0.0] #, 0.95, 0.95] #, 0.95] #, 0.95]
  decay: [0.0001] #, 0.0001, 0.0001] #, 0.0001] #, 0.0001]
  temp: [1.0] #, 1.0, 1.0] [0.9, 0.75, 0.5] #, 1.0] #, 0.5] #, 0.5] 
  nesterov_accel: [False]
  normalize_learnergy: [False]
  batch_normalize: [False]


 training:
  use_gpu: True
  use_gpu_preprocessing: False
  world_size: 1
  rank: 0
  device_ids: ["7"] #["3", "4"]
  batch_size: 128
  epochs: [50] #[8] #, 1, 1] #, 5] #, 10]
  cluster_batch_size: 900
  cluster_epochs: 100
  cluster_gauss_noise_stdev:  [0.01]
  cluster_lambda: 1.0

  heir_cluster_min_samples: 1000
  heir_cluster_gauss_noise_stdev: [0.01] #[0.001, 0.0001, 0.00001, 0.000001, 0.0]
  heir_epochs: 100
  heir_tune_subtrees: False
  heir_tune_subtree_list: []
  heir_deep_cluster: 100


  #stratify_data: 
  # reader: "gtiff"
  # filename: ["/data/nlahaye/remoteSensing/Palm_Oil_Test_V2.Filled.tif"]
  # reader_kwargs:
  #  start_sample: 1000
  #  end_sample: 4000
  #  start_line: 1000
  #  end_line: 4000


scaler:
 name: "standard"

data:
 tile: True #True
 tile_size: [16,16,4]
 tile_step: [1,1,4]
 num_loader_workers: 10
 scale_data: True
 pixel_padding: 0
 number_channels: 4
 fill_value: -999999.0
 valid_min: -10000.0
 valid_max: 100000000
 subset_count: 1
 output_subset_count: 1
 reader_type: "gtiff"
 reader_kwargs:
  no_arg: ''
 chan_dim: 0
 delete_chans: []
 transform_default:
  chans: []
  transform: []
 
 files_train: [
"/data/nlahaye/remoteSensing/Palm_Oil/ucayali_condensed_stacks_2020_h1v1.tiff"]


 files_test: [
"/data/nlahaye/remoteSensing/Palm_Oil/ucayali_condensed_stacks_2020_h1v1.tiff"]

