
output:
 out_dir: "/data/nlahaye/output/Learnergy/DBN_TROP_RED_SIF_AUTO_CLUST_TEST/"
 training_output: "output.data"
 training_mse: "rec_mse.data"
 testing_output: "output_test.data"
 testing_mse: "rec_mse_test.data"
 model: "dbn"
 generate_train_output: True
 generate_output: True

dbn:
 conv: False
 subset_training: -1 #10000000
 deep_cluster: 800
 heir_tiers: 2
 overwrite_model: False
 tune_clust: False
 tune_dbn: False
 tune_scaler: False
 params:
  model_type: ["gaussian_selu"] #["gaussian_selu"] #, 'gaussian_relu_dropout', 'gaussian_relu_dropout'] #'variance_gaussian_dropout' "gaussian_dropout"
  dbn_arch: [2000] #[2000] [250, 500, 2000] #, 2000]
  gibbs_steps: [15] #, 7, 7] #, 10] #, 25]
  learning_rate: [0.0001] #, 0.0001, 0.0001] #, 0.01] #, 0.01]
  momentum: [0.0] #, 0.95, 0.95] #, 0.95] #, 0.95]
  decay: [0.0001] #, 0.0001, 0.0001] #, 0.0001] #, 0.0001]
  temp: [1.0] #, 1.0, 1.0] [0.9, 0.75, 0.5] #, 1.0] #, 0.5] #, 0.5] 
  nesterov_accel: [False]
  normalize_learnergy: [False]
  batch_normalize: [False]

 training:
  use_gpu: True
  use_gpu_preprocessing: False
  world_size: 1
  rank: 0
  device_ids: ["3"]
  batch_size: 128
  epochs: [50] #[8] #, 1, 1] #, 5] #, 10]
  cluster_batch_size: 700
  cluster_epochs: 100
  cluster_gauss_noise_stdev: [0.01] #[0.001, 0.0001, 0.00001, 0.000001, 0.0]
  cluster_lambda: 1.0

  heir_cluster_min_samples: 1000
  heir_cluster_gauss_noise_stdev: [0.01] #[0.001, 0.0001, 0.00001, 0.000001, 0.0]
  heir_epochs: 100
  heir_tune_subtrees: False
  heir_tune_subtree_list: []
  heir_deep_cluster: 100


scaler:
 name: "standard"



data:
 tile: True
 tile_size: [3,3,32]
 tile_step: [1,1,32]
 num_loader_workers: 10
 scale_data: True
 pixel_padding: 1
 number_channels: 1
 fill_value: -999.0
 valid_min: -900.0
 valid_max: 100000000
 subset_count: 1
 output_subset_count: 1
 reader_type: "trop_nc"
 reader_kwargs:
  mask_shp: "/data/nlahaye/remoteSensing/Lakes/glwd_1.shp"
 chan_dim: 0

 delete_chans: [] #[3,7,8,9,10,11,12,15]
 transform_default:
  chans: []
  transform: []
 files_test: [ 
"/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-09-01_ungridded.nc",
"/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-09-02_ungridded.nc"
]

 files_train: [
"/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-09-03_ungridded.nc",
"/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-09-04_ungridded.nc",
"/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-09-05_ungridded.nc",
"/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-09-06_ungridded.nc",
"/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-09-07_ungridded.nc",
"/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-09-08_ungridded.nc",
"/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-09-09_ungridded.nc",
"/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-09-10_ungridded.nc",
"/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-09-11_ungridded.nc",
"/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-09-12_ungridded.nc",
"/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-09-13_ungridded.nc",
"/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-09-14_ungridded.nc",
"/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-09-15_ungridded.nc",
"/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-09-16_ungridded.nc",
"/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-09-17_ungridded.nc",
"/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-09-18_ungridded.nc",
"/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-09-19_ungridded.nc",
"/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-09-20_ungridded.nc",
"/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-09-21_ungridded.nc",
"/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-09-22_ungridded.nc",
"/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-09-23_ungridded.nc",
"/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-09-24_ungridded.nc",
"/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-09-25_ungridded.nc",
"/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-09-26_ungridded.nc",
"/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-09-27_ungridded.nc",
"/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-09-28_ungridded.nc",
"/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-09-29_ungridded.nc",
"/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-09-30_ungridded.nc"
]








