
output:
 out_dir: "/data/nlahaye/output/Learnergy/DBN_VIIRS_TROP_OC_C_FLA/"
 training_output: "output.data"
 training_mse: "rec_mse.data"
 testing_output: "output_test.data"
 testing_mse: "rec_mse_test.data"
 model: "dbn"
 generate_train_output: True
 generate_output: True


dbn:
 conv: False
 subset_training: -1 #2000000
 deep_cluster: 800
 heir_tiers: 1
 overwrite_model: False
 tune_clust: False
 tune_dbn: False
 tune_scaler: False
 params:
  model_type: ["gaussian_selu"] #, 'gaussian_relu_dropout', 'gaussian_relu_dropout'] #'variance_gaussian_dropout' "gaussian_dropout"
  dbn_arch: [2000] #[2000] [250, 500, 2000] #, 2000]
  gibbs_steps: [1] #, 7, 7] #, 10] #, 25]
  learning_rate: [0.00001] #, 0.0001, 0.0001] #, 0.01] #, 0.01]
  momentum: [0.95] #, 0.95, 0.95] #, 0.95] #, 0.95]
  decay: [0.0001] #, 0.0001, 0.0001] #, 0.0001] #, 0.0001]
  temp: [1.0] #, 1.0, 1.0] [0.9, 0.75, 0.5] #, 1.0] #, 0.5] #, 0.5] 
  nesterov_accel: [True]
  normalize_learnergy: [False]
  batch_normalize: [False]

 training:
  use_gpu: True
  use_gpu_preprocessing: False
  world_size: 1
  rank: 0
  device_ids: ["6"]
  batch_size: 1000
  epochs: [10] #[40] #[8] #, 1, 1] #, 5] #, 10]
  cluster_batch_size: 1000
  cluster_epochs: 30
  cluster_gauss_noise_stdev: [0.01] #[0.001, 0.0001, 0.00001, 0.000001, 0.0]
  cluster_lambda: 1.0

  heir_cluster_min_samples: 1000
  heir_cluster_gauss_noise_stdev: [0.01] #[0.001, 0.0001, 0.00001, 0.000001, 0.0]
  heir_epochs: 30
  heir_tune_subtrees: False
  heir_tune_subtree_list: []
  heir_deep_cluster: 150
  #stratify_data:
  # kmeans: True

scaler:
 name: "standard"

data:
 tile: True
 tile_size: [3,3,32]
 tile_step: [1,1,32]
 num_loader_workers: 10
 scale_data: True
 pixel_padding: 1
 number_channels: 7
 fill_value: -999999.0
 valid_min: -10000.0
 valid_max: 6400000
 subset_count: 1
 output_subset_count: 1
 reader_type: "viirs_oc"
 reader_kwargs:
  start_lon: -83.491547
  end_lon: -81.637247
  start_lat: 25.905156
  end_lat: 28.314978
  #mask_shp: "/data/nlahaye/remoteSensing/Lakes/glwd_1.shp"
  mask_oceans: True
 chan_dim: 0
 delete_chans: []
 transform_default:
  chans: []
  transform: []



 files_test: ["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180601.L3m.DAY.", 
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180819.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180820.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180821.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181001.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181002.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181003.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181004.L3m.DAY."]

 files_train: ["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180601.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180602.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180603.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180604.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180605.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180606.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180607.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180608.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180609.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180610.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180611.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180612.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180613.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180614.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180615.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180616.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180617.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180618.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180619.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180620.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180621.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180622.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180623.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180624.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180625.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180626.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180627.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180628.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180629.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180630.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180701.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180702.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180703.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180704.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180705.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180706.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180707.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180708.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180709.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180710.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180711.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180712.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180713.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180714.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180715.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180716.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180717.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180718.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180719.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180720.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180721.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180722.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180723.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180724.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180725.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180726.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180727.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180728.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180729.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180730.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180731.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180801.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180802.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180803.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180804.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180805.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180806.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180807.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180808.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180809.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180810.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180811.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180812.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180813.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180814.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180815.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180816.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180817.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180818.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180819.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180820.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180821.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180822.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180823.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180824.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180825.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180826.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180827.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180828.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180829.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180830.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180831.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180901.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180902.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180903.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180904.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180905.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180906.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180907.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180908.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180909.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180910.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180911.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180912.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180913.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180914.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180915.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180916.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180917.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180918.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180919.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180920.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180921.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180922.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180923.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180924.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180925.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180926.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180927.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180928.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180929.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180930.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181001.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181002.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181003.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181004.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181005.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181006.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181007.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181008.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181009.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181010.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181011.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181012.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181013.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181014.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181015.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181016.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181017.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181018.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181019.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181020.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181021.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181022.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181023.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181024.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181025.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181026.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181027.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181028.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181029.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181030.L3m.DAY.",
"/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181031.L3m.DAY."]


