
low_res:
 data:
  fill_value: -999999.0
  valid_min: -900.0 #0.0000001
  valid_max: 100000000
  reader_type: "zarr_to_numpy"
  reader_kwargs:
   no_arg: ''
  geo_reader_type: "emas_master_hdf_geo"
  geo_reader_kwargs:
   no_arg: "no_arg"
  filenames: [
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19910_06_20190806_1815_1824_V03.hdf.no_heir.clust.data_800clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19910_08_20190806_1834_1846_V03.hdf.no_heir.clust.data_800clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19910_10_20190806_1858_1910_V03.hdf.no_heir.clust.data_800clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19910_13_20190806_1923_1925_V03.hdf.no_heir.clust.data_800clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19910_14_20190806_1926_1929_V03.hdf.no_heir.clust.data_800clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19910_15_20190806_1931_1938_V03.hdf.no_heir.clust.data_800clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19910_16_20190806_1941_1956_V03.hdf.no_heir.clust.data_800clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19910_17_20190806_2000_2010_V03.hdf.no_heir.clust.data_800clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19910_18_20190806_2018_2031_V03.hdf.no_heir.clust.data_800clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19910_19_20190806_2035_2048_V03.hdf.no_heir.clust.data_800clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19910_20_20190806_2052_2106_V03.hdf.no_heir.clust.data_800clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19910_21_20190806_2111_2125_V03.hdf.no_heir.clust.data_800clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19911_05_20190807_1817_1833_V03.hdf.no_heir.clust.data_800clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19911_08_20190807_1928_1942_V03.hdf.no_heir.clust.data_800clusters.zarr",
#"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19911_09_20190807_1947_2002_V03.hdf.no_heir.clust.data_800clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19911_09_20190807_1947_2002_V03.hdf.no_heir.clust.data_800clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19911_10_20190807_2004_2016_V03.hdf.no_heir.clust.data_800clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19911_11_20190807_2021_2035_V03.hdf.no_heir.clust.data_800clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19911_12_20190807_2039_2051_V03.hdf.no_heir.clust.data_800clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19912_07_20190808_1806_1821_V03.hdf.no_heir.clust.data_800clusters.zarr"
]

  geo_filenames: [
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_06_20190806_1815_1824_V03.hdf",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_08_20190806_1834_1846_V03.hdf",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_10_20190806_1858_1910_V03.hdf",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_13_20190806_1923_1925_V03.hdf",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_14_20190806_1926_1929_V03.hdf",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_15_20190806_1931_1938_V03.hdf",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_16_20190806_1941_1956_V03.hdf",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_17_20190806_2000_2010_V03.hdf",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_18_20190806_2018_2031_V03.hdf",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_19_20190806_2035_2048_V03.hdf",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_20_20190806_2052_2106_V03.hdf",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19910_21_20190806_2111_2125_V03.hdf",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19911_05_20190807_1817_1833_V03.hdf",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19911_08_20190807_1928_1942_V03.hdf",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19911_09_20190807_1947_2002_V03.hdf",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19911_10_20190807_2004_2016_V03.hdf",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19911_11_20190807_2021_2035_V03.hdf",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19911_12_20190807_2039_2051_V03.hdf",
"/data/nlahaye/remoteSensing/eMAS_new/eMASL1B_19912_07_20190808_1806_1821_V03.hdf"
]

  chan_dim: 0
  geo_coord_dim: 0
  geo_lat_index: 1
  geo_lon_index: 0


high_res:
 data:
  valid_min: 0.0
  valid_max: 100000000
  reader_type: "numpy"
  reader_kwargs:
   no_arg: "no_arg"
  geo_reader_type: "numpy"
  geo_reader_kwargs:
   no_arg: "no_arg"
  filenames: []
  geo_filenames: []
  chan_dim: 0
  geo_coord_dim: 2
  geo_lat_index: 1
  geo_lon_index: 0


fusion:
 projection_id: 4326
 description: "Generating eMAS GeoTiffs"
 area_id: "eMAS"
 projection_proj4:
  #proj: "utm"
  #zone: 11
  proj: "longlat"
  datum: "WGS84" 
 final_resolution: 0.00045 #0.00225 #0.000225
 projection_units: "degrees"
 resample_radius: 50
 resample_n_neighbors: 8
 resample_n_procs: 10
 resample_epsilon: 1.6
 use_bilinear: False      
 
output_files: [
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19910_06_20190806_1815_1824_V03.hdf.no_heir.clust.data_800clusters.tif",
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19910_08_20190806_1834_1846_V03.hdf.no_heir.clust.data_800clusters.tif",
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19910_10_20190806_1858_1910_V03.hdf.no_heir.clust.data_800clusters.tif",
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19910_13_20190806_1923_1925_V03.hdf.no_heir.clust.data_800clusters.tif",
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19910_14_20190806_1926_1929_V03.hdf.no_heir.clust.data_800clusters.tif",
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19910_15_20190806_1931_1938_V03.hdf.no_heir.clust.data_800clusters.tif",
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19910_16_20190806_1941_1956_V03.hdf.no_heir.clust.data_800clusters.tif",
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19910_17_20190806_2000_2010_V03.hdf.no_heir.clust.data_800clusters.tif",
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19910_18_20190806_2018_2031_V03.hdf.no_heir.clust.data_800clusters.tif",
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19910_19_20190806_2035_2048_V03.hdf.no_heir.clust.data_800clusters.tif",
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19910_20_20190806_2052_2106_V03.hdf.no_heir.clust.data_800clusters.tif",
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19910_21_20190806_2111_2125_V03.hdf.no_heir.clust.data_800clusters.tif",
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19911_05_20190807_1817_1833_V03.hdf.no_heir.clust.data_800clusters.tif",
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19911_08_20190807_1928_1942_V03.hdf.no_heir.clust.data_800clusters.tif",
#"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19911_09_20190807_1947_2002_V03.hdf.no_heir.clust.data_800clusters.tif",
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19911_09_20190807_1947_2002_V03.hdf.no_heir.clust.data_800clusters.tif",
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19911_10_20190807_2004_2016_V03.hdf.no_heir.clust.data_800clusters.tif",
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19911_11_20190807_2021_2035_V03.hdf.no_heir.clust.data_800clusters.tif",
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19911_12_20190807_2039_2051_V03.hdf.no_heir.clust.data_800clusters.tif",
"/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL_3/eMASL1B_19912_07_20190808_1806_1821_V03.hdf.no_heir.clust.data_800clusters.tif"
]



