
low_res:
 data:
  valid_min: -100.0
  valid_max: 99999999999
  reader_type: "zarr_to_numpy"
  reader_kwargs:
   none: "None"
  geo_reader_type: "zarr_to_numpy"
  geo_reader_kwargs:
   no_arg: "no_arg"
  filenames: [
"/mnt/data/HAB_MODEL_WEIGHTS/OC_SIF_HABs_2025/S3A_OLCI_S_CA/S3A_OLCI_ERRNT.20250112.L3m.DAY..clust.data_78299clusters.zarr",
"/mnt/data/HAB_MODEL_WEIGHTS/OC_SIF_HABs_2025/S3A_OLCI_S_CA/S3A_OLCI_ERRNT.20250113.L3m.DAY..clust.data_78299clusters.zarr",
"/mnt/data/HAB_MODEL_WEIGHTS/OC_SIF_HABs_2025/S3A_OLCI_S_CA/S3A_OLCI_ERRNT.20250115.L3m.DAY..clust.data_78284clusters.zarr",
]


  geo_filenames: [
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
"/mnt/data/red_sea.zarr",
]

  chan_dim: 2
  geo_coord_dim: 2
  geo_lat_index: 0
  geo_lon_index: 1


high_res:
 data:
  valid_min: 0.0
  valid_max: 99999999999
  reader_type: "zarr_to_numpy"
  reader_kwargs:
   no_arg: "no_arg"
  geo_reader_type: "zarr_to_numpy"
  geo_reader_kwargs:
   no_arg: "no_arg"
  filenames: []
  geo_filenames: []
  chan_dim: 0
  geo_coord_dim: 2
  geo_lat_index: 0
  geo_lon_index: 1


fusion:
 projection_id: 4326
 description: "Generating S3A GeoTiffs"
 area_id: "GERD Dam"
 projection_proj4:
  proj: "longlat"
  datum: "WGS84"
 final_resolution: 0.055
 projection_units: "degrees"
 resample_radius: 5000
 resample_n_neighbors: 64
 resample_n_procs: 10
 resample_epsilon: 1.6
 use_bilinear: False




output_files: [
"/mnt/data/HAB_MODEL_WEIGHTS/OC_SIF_HABs_2025/S3A_OLCI_S_CA/S3A_OLCI_ERRNT.20250112.L3m.DAY.tif",
"/mnt/data/HAB_MODEL_WEIGHTS/OC_SIF_HABs_2025/S3A_OLCI_S_CA/S3A_OLCI_ERRNT.20250113.L3m.DAY.tif",
"/mnt/data/HAB_MODEL_WEIGHTS/OC_SIF_HABs_2025/S3A_OLCI_S_CA/S3A_OLCI_ERRNT.20250115.L3m.DAY.tif",
]


 
