
reuse_context: False

prob: False
no_heir: True
config_dir: "/home/nlahaye/SIT_FUSE/src/sit_fuse/config/"
geo_zarr: "/mnt/data/cal_coast_geo.zarr"
 
insitu_file: "/mnt/data/la_hab_data/combined_full_init.csv"
insitu_matchup_circle_max_radius: [0.09]
start_date: "2024-01-01"
end_date: "2025-08-01"
clusters: 120000

roi: "california"

final_product_dir: "/mnt/data/HAB_MODEL_WEIGHTS/OC_SIF_HABs_2025/MERGED_TEST_10082025/"
 
instruments: 
 #pace:
 #  no_trop: 
 #     "out_dir": "/data/nlahaye/output/Learnergy/PACE_Only_S_CA/"
 #s3a: 
 # no_trop:  
 #     "out_dir": "/data/nlahaye/output/Learnergy/S3A_Only_S_CA/"
 #s3b:
 # no_trop:  
 #     "out_dir": "/data/nlahaye/output/Learnergy/S3B_Only_S_CA/"
 #jpss1:
 # no_trop:  
 #     "out_dir": "/data/nlahaye/output/Learnergy/JPSS1_VIIRS_ONLY_S_CA/"
 jpss2:
  no_trop:  
      "out_dir": "/mnt/data/HAB_MODEL_WEIGHTS/OC_SIF_HABs_2025/JPSS2_VIIRS/JPSS2_VIIRS_no_trop/"
 #snpp:
 # no_trop:  
 #     "out_dir": "/data/nlahaye/output/Learnergy/SNPP_VIIRS_ONLY_S_CA/"
 #troposif: No SIF data for 2024-2025 cases
 #goes18:  
 # no_trop: 
 #'     "out_dir": "/data/nlahaye/output/Learnergy/GOES18_ABI_ONLY_S_CA/"




