
data:
 num_loader_workers: 10
 scale_data: True
 pixel_padding: 0
 number_channels: 285
 fill_value: -9999.0
 valid_min:  -9000.0
 valid_max: 100000000
 subset_count: 1
 output_subset_count: 10
 reader_type: "emit"
 reader_kwargs:
  no_arg: "no_arg"
 chan_dim: 2
 delete_chans: []
 transform_default:
  chans: []
  transform: []

 
 files_train: [
"/data/nlahaye/remoteSensing/EMIT/EMIT_L1B_RAD_001_20230419T065212_2310905_031.nc",
"/data/nlahaye/remoteSensing/EMIT/EMIT_L1B_RAD_001_20230419T065137_2310905_028.nc",
"/data/nlahaye/remoteSensing/EMIT/EMIT_L1B_RAD_001_20230419T051750_2310904_019.nc"
]

 files_test: [
"/data/nlahaye/remoteSensing/EMIT/EMIT_L1B_RAD_001_20230419T051750_2310904_019.nc",
"/data/nlahaye/remoteSensing/EMIT/EMIT_L1B_RAD_001_20230419T065236_2310905_033.nc",
"/data/nlahaye/remoteSensing/EMIT/EMIT_L1B_RAD_001_20230419T065224_2310905_032.nc",
"/data/nlahaye/remoteSensing/EMIT/EMIT_L1B_RAD_001_20230419T051739_2310904_018.nc"
]

scaler:
 name: "standard" 

output:
 out_dir: "/data/nlahaye/output/Learnergy/DBN_EMIT/"
 training_output: "output.data"
 training_mse: "rec_mse.data"
 testing_output: "output_test.data"
 testing_mse: "rec_mse_test.data"
 generate_train_output: True
 model: "dbn"


dbn:
 subset_training: -1 #1000000
 deep_cluster: 100
 overwrite_model: False
 tune_clust: False
 tune_dbn: False
 tune_scaler: False
 params:
  model_type: ["gaussian_selu"] 
  dbn_arch: [2000] #[250, 500, 2000] #, 2000]
  gibbs_steps: [10] #, 7, 7] #, 10] #, 25]
  learning_rate: [0.0001] #, 0.0001, 0.0001] #, 0.01] #, 0.01]
  momentum: [0.0] #, 0.95, 0.95] #, 0.95] #, 0.95]
  decay: [0.0001] #, 0.0001, 0.0001] #, 0.0001] #, 0.0001]
  temp: [1.0] #, 1.0, 1.0] ##[0.9, 0.75, 0.5] #, 1.0] #, 0.5] #, 0.5] 
  nesterov_accel: [False]
  normalize_learnergy: [False]
  batch_normalize: [False]

 training:
  use_gpu_preprocessing: False
  use_gpu: True
  world_size: 1
  rank: 0
  device_ids: ["1","2","3"]
  batch_size: 128
  epochs: [30] #[10]#[8] #, 1, 1] #, 5] #, 10]
  cluster_batch_size: 700
  cluster_epochs: 24  #[10]#[8] #, 1, 1] #, 5] #, 10]
  cluster_gauss_noise_stdev: [0.01, 0.001, 0.0001, 0.00001, 0.0000001, 0.0]
  cluster_lambda: 1.0


