

output:
 out_dir: "/data/nlahaye/output/Learnergy/DBN_LS8_BENCHMARK_2/"
 training_output: "output.data"
 training_mse: "rec_mse.data"
 testing_output: "output_test.data"
 testing_mse: "rec_mse_test.data"
 model: "dbn"

dbn:
 subset_training: 10000000
 deep_cluster: 5000
 overwrite_model: True
 params:
  model_type: ["gaussian_selu"] #, 'gaussian_relu_dropout', 'gaussian_relu_dropout'] #'variance_gaussian_dropout' "gaussian_dropout"
  dbn_arch: [10000] #[2000] [250, 500, 2000] #, 2000]
  gibbs_steps: [5] #, 7, 7] #, 10] #, 25]
  learning_rate: [0.0001] #, 0.0001, 0.0001] #, 0.01] #, 0.01]
  momentum: [0.5] #, 0.95, 0.95] #, 0.95] #, 0.95]
  decay: [0.0001] #, 0.0001, 0.0001] #, 0.0001] #, 0.0001]
  temp: [1.0] #, 1.0, 1.0] [0.9, 0.75, 0.5] #, 1.0] #, 0.5] #, 0.5] 
  nesterov_accel: [True]
  normalize_learnergy: [False]
  batch_normalize: [False]

 training:
  use_gpu: True
  use_gpu_preprocessing: False
  world_size: 1
  rank: 0
  device_ids: ["6","7"]
  batch_size: 512
  epochs: [100] #[8] #, 1, 1] #, 5] #, 10]

scaler:
 name: "standard"

data:
 num_loader_workers: 10
 scale_data: True
 pixel_padding: 1
 number_channels: 10
 fill_value: -9999.0
 valid_min: -100.0
 valid_max: 100000000
 subset_count: 1
 output_subset_count: 20
 reader_type: "gtiff_multifile"
 reader_kwargs:
  no_arg: ''
 chan_dim: 0
 delete_chans: []
 transform_default:
  chans: []
  transform: []
 files_train: [
["/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPN.2022245T183127.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPN.2022245T183127.v2.0.B02.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPN.2022245T183127.v2.0.B03.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPN.2022245T183127.v2.0.B04.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPN.2022245T183127.v2.0.B05.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPN.2022245T183127.v2.0.B06.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPN.2022245T183127.v2.0.B07.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPN.2022245T183127.v2.0.B09.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPN.2022245T183127.v2.0.B10.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPN.2022245T183127.v2.0.B11.tif"],
["/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPM.2022245T183127.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPM.2022245T183127.v2.0.B02.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPM.2022245T183127.v2.0.B03.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPM.2022245T183127.v2.0.B04.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPM.2022245T183127.v2.0.B05.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPM.2022245T183127.v2.0.B06.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPM.2022245T183127.v2.0.B07.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPM.2022245T183127.v2.0.B09.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPM.2022245T183127.v2.0.B10.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPM.2022245T183127.v2.0.B11.tif"],
["/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPL.2022261T183158.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPL.2022261T183158.v2.0.B02.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPL.2022261T183158.v2.0.B03.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPL.2022261T183158.v2.0.B04.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPL.2022261T183158.v2.0.B05.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPL.2022261T183158.v2.0.B06.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPL.2022261T183158.v2.0.B07.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPL.2022261T183158.v2.0.B09.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPL.2022261T183158.v2.0.B10.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPL.2022261T183158.v2.0.B11.tif"]]
 files_test: [["/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPL.2022262T182528.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPL.2022262T182528.v2.0.B02.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPL.2022262T182528.v2.0.B03.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPL.2022262T182528.v2.0.B04.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPL.2022262T182528.v2.0.B05.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPL.2022262T182528.v2.0.B06.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPL.2022262T182528.v2.0.B07.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPL.2022262T182528.v2.0.B09.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPL.2022262T182528.v2.0.B10.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11TPL.2022262T182528.v2.0.B11.tif"]]
 


