
data:
 num_loader_workers: 10
 scale_data: True
 pixel_padding: 0
 number_channels: 58
 fill_value: -9999.0
 valid_min:  -900.0
 valid_max: 100000000
 subset_count: 1
 output_subset_count: 10
 reader_type: "numpy"
 reader_kwargs:
  no_arg: "no_arg"
 chan_dim: 0
 delete_chans: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,50,51,52,53,54,55,56,57,58,75,76,84,86,87]
 transform_default:
  chans: []
  transform: []

 files_train: ["/data/nlahaye/remoteSensing/MASTER/MASTER_EMAS_Fuse2.npy"]

 files_test: ["/data/nlahaye/remoteSensing/MASTER/MASTER_EMAS_Fuse1.npy"]

scaler:
 name: "standard" 

output:
 out_dir: "/data/nlahaye/output/Learnergy/DBN_MASTER_EMAS_FUSE_FIRE/"
 training_output: "output.data"
 training_mse: "rec_mse.data"
 testing_output: "output_test.data"
 testing_mse: "rec_mse_test.data"
 generate_train_output: False
 generate_output: False
 model: "dbn"

dbn:
 conv: False
 subset_training: 2000000
 deep_cluster: 800
 overwrite_model: True
 overwrite_model: False
 tune_clust: False
 tune_dbn: False
 tune_scaler: False
 heir_tiers: 1
 params:
  model_type: ["gaussian_selu"] #, 'gaussian_relu_dropout', 'gaussian_relu_dropout'] #'variance_gaussian_dropout' "gaussian_dropout"
  dbn_arch: [2000] #[2000] [250, 500, 2000] #, 2000]
  gibbs_steps: [1] #, 7, 7] #, 10] #, 25]
  learning_rate: [0.00001] #, 0.0001, 0.0001] #, 0.01] #, 0.01]
  momentum: [0.95] #, 0.95, 0.95] #, 0.95] #, 0.95]
  decay: [0.0001] #, 0.0001, 0.0001] #, 0.0001] #, 0.0001]
  temp: [1.0] #, 1.0, 1.0] [0.9, 0.75, 0.5] #, 1.0] #, 0.5] #, 0.5] 
  nesterov_accel: [True]
  normalize_learnergy: [False]
  batch_normalize: [False]


 training:
  use_gpu: True
  use_gpu_preprocessing: False
  world_size: 1
  rank: 0
  device_ids: ["7"]
  batch_size: 1000
  epochs: [10] #[8] #, 1, 1] #, 5] #, 10]
  cluster_batch_size: 1000
  cluster_epochs: 30
  cluster_gauss_noise_stdev: [0.01]
  cluster_lambda: 1.0

  heir_cluster_min_samples: 1000
  heir_cluster_gauss_noise_stdev: [0.01] #[0.001, 0.0001, 0.00001, 0.000001, 0.0]
  heir_epochs: 30
  heir_tune_subtrees: False
  heir_tune_subtree_list: []
  heir_deep_cluster: 100
  stratify_data:
  # kmeans: True



