
output:
 out_dir: "/data/nlahaye/output/Learnergy/DBN_MISR_SIMULATED/"
 training_output: "output.data"
 training_mse: "rec_mse.data"
 testing_output: "output_test.data"
 testing_mse: "rec_mse_test.data"
 model: "dbn"

dbn:
 subset_training: 500000
 deep_cluster: False
 overwrite_model: True
 params:
  model_type: ["gaussian_selu"] #, 'gaussian_relu_dropout', 'gaussian_relu_dropout'] #'variance_gaussian_dropout' "gaussian_dropout"
  dbn_arch: [100] #[2000] [250, 500, 2000] #, 2000]
  gibbs_steps: [5] #, 7, 7] #, 10] #, 25]
  learning_rate: [0.0001] #, 0.0001, 0.0001] #, 0.01] #, 0.01]
  momentum: [0.95] #, 0.95, 0.95] #, 0.95] #, 0.95]
  decay: [0.0001] #, 0.0001, 0.0001] #, 0.0001] #, 0.0001]
  temp: [1.0] #, 1.0, 1.0] [0.9, 0.75, 0.5] #, 1.0] #, 0.5] #, 0.5] 
  nesterov_accel: [True]
  normalize_learnergy: [False]
  batch_normalize: [False]

 training:
  use_gpu: True
  use_gpu_preprocessing: False
  world_size: 1
  rank: 0
  device_ids: ["0","1","2","3","4","5","6","7"]
  batch_size: 1000
  epochs: [100] #[8] #, 1, 1] #, 5] #, 10]

scaler:
 name: "standard"

data:
 num_loader_workers: 10
 scale_data: True
 pixel_padding: 1
 number_channels: 1
 fill_value: -9999.0
 valid_min: -10000.0
 valid_max: 100000000
 subset_count: 1
 output_subset_count: 100
 reader_type: "zarr_to_numpy"
 reader_kwargs:
  no_arg: ''
 chan_dim: 2
 delete_chans: []
 transform_default:
  chans: []
  transform: []
 
 files_train: [
"/data/nlahaye/remoteSensing/MISR_Simulated/MISR_20m_radiances_phi0_SZA46_RICO_21600s.band0.zarr",
"/data/nlahaye/remoteSensing/MISR_Simulated/MISR_20m_radiances_phi0_SZA46_RICO_21600s.band1.zarr",
"/data/nlahaye/remoteSensing/MISR_Simulated/MISR_20m_radiances_phi0_SZA46_RICO_21600s.band2.zarr",
"/data/nlahaye/remoteSensing/MISR_Simulated/MISR_20m_radiances_phi0_SZA46_RICO_21600s.band3.zarr",
"/data/nlahaye/remoteSensing/MISR_Simulated/MISR_20m_radiances_phi0_SZA46_RICO_21600s.band4.zarr",
"/data/nlahaye/remoteSensing/MISR_Simulated/MISR_20m_radiances_phi0_SZA46_RICO_21600s.band5.zarr",
"/data/nlahaye/remoteSensing/MISR_Simulated/MISR_20m_radiances_phi0_SZA46_RICO_21600s.band6.zarr",
"/data/nlahaye/remoteSensing/MISR_Simulated/MISR_20m_radiances_phi0_SZA46_RICO_21600s.band7.zarr",
"/data/nlahaye/remoteSensing/MISR_Simulated/MISR_20m_radiances_phi0_SZA46_RICO_21600s.band8.zarr"]
 
 
 files_test: ["/data/nlahaye/remoteSensing/MISR_Simulated/MISR_20m_radiances_phi0_SZA46_RICO_21600s.band0.zarr",
"/data/nlahaye/remoteSensing/MISR_Simulated/MISR_20m_radiances_phi0_SZA46_RICO_21600s.band1.zarr",
"/data/nlahaye/remoteSensing/MISR_Simulated/MISR_20m_radiances_phi0_SZA46_RICO_21600s.band2.zarr",
"/data/nlahaye/remoteSensing/MISR_Simulated/MISR_20m_radiances_phi0_SZA46_RICO_21600s.band3.zarr",
"/data/nlahaye/remoteSensing/MISR_Simulated/MISR_20m_radiances_phi0_SZA46_RICO_21600s.band4.zarr",
"/data/nlahaye/remoteSensing/MISR_Simulated/MISR_20m_radiances_phi0_SZA46_RICO_21600s.band5.zarr",
"/data/nlahaye/remoteSensing/MISR_Simulated/MISR_20m_radiances_phi0_SZA46_RICO_21600s.band6.zarr",
"/data/nlahaye/remoteSensing/MISR_Simulated/MISR_20m_radiances_phi0_SZA46_RICO_21600s.band7.zarr",
"/data/nlahaye/remoteSensing/MISR_Simulated/MISR_20m_radiances_phi0_SZA46_RICO_21600s.band8.zarr"]

