output:
 out_dir: "/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_8B_CANADA_STRAT_MULTI_LAYER/"
 training_output: "output.data"
 training_mse: "rec_mse.data"
 testing_output: "output_test.data"
 testing_mse: "rec_mse_test.data"
 generate_train_output: True
 generate_output: True
 model: "dbn"

dbn:
 conv: False
 subset_training: 2000000
 deep_cluster: 800
 heir_tiers: 1
 overwrite_model: False
 tune_clust: False
 tune_dbn: False
 tune_scaler: False
 params:
  model_type: ["gaussian_selu", "gaussian_selu"]
  dbn_arch: [2000, 1000] #[2000] [250, 500, 2000] #, 2000]
  gibbs_steps: [1,1] #, 7, 7] #, 10] #, 25]
  learning_rate: [0.00001, 0.00001] #, 0.0001, 0.0001] #, 0.01] #, 0.01]
  momentum: [0.95, 0.95] #, 0.95, 0.95] #, 0.95] #, 0.95]
  decay: [0.0001, 0.0001] #, 0.0001, 0.0001] #, 0.0001] #, 0.0001]
  temp: [1.0, 1.0] #, 1.0, 1.0] [0.9, 0.75, 0.5] #, 1.0] #, 0.5] #, 0.5] 
  nesterov_accel: [True, True]
  normalize_learnergy: [False, True]
  batch_normalize: [False, False]

 training:
  use_gpu: True
  use_gpu_preprocessing: False
  world_size: 1
  rank: 0
  device_ids: ["5"]
  batch_size: 1000
  epochs: [10, 10] #[15] #[8] #, 1, 1] #, 5] #, 10]
  cluster_batch_size: 1000
  cluster_epochs: 30
  cluster_gauss_noise_stdev: [0.01] #[0.001, 0.0001, 0.00001, 0.000001, 0.0]
  cluster_lambda: 1.0

  heir_cluster_min_samples: 1000
  heir_cluster_gauss_noise_stdev: [0.01] #[0.001, 0.0001, 0.00001, 0.000001, 0.0]
  heir_epochs: 30
  heir_tune_subtrees: False
  heir_tune_subtree_list: []
  heir_deep_cluster: 100
  stratify_data:
   kmeans: True

scaler:
 name: "standard"

data:
 num_loader_workers: 10
 scale_data: True
 pixel_padding: 1
 number_channels: 8
 fill_value: 0.0
 valid_min: 0.0000001
 valid_max: 100000000
 subset_count: 1
 output_subset_count: 1
 reader_type: "gtiff"
 reader_kwargs:
  no_arg: ''
 chan_dim: 0
 delete_chans: []
 transform_default:
  chans: []
  transform: []
 files_train: [
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_150453_45_24c8_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_150001_66_2421_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_154941_99_2481_3B_AnalyticMS_8b.tif"
]

 files_test: [
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_150505_27_24c8_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_154920_88_2481_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_151148_90_24cc_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_150510_00_24c8_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_154705_63_247f_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_150514_73_24c8_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_151120_79_24b9_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_151118_43_24b9_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_150455_82_24c8_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_151125_51_24b9_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_151139_57_24cc_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_154937_77_2481_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_154707_77_247f_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_151123_25_24cc_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_150512_37_24c8_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_154722_77_247f_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_151059_56_24b9_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_151127_87_24b9_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_154659_20_247f_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_151151_23_24cc_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_151134_91_24cc_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_154652_77_247f_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_150448_72_24c8_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_154944_11_2481_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_154642_31_2276_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_154939_88_2481_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_154709_91_247f_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_154718_49_247f_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_151153_56_24cc_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_154657_05_247f_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_154935_66_2481_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_150517_10_24c8_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_154644_15_2276_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_150507_64_24c8_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_154712_06_247f_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_151132_58_24b9_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_154701_34_247f_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_145955_33_2421_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_154914_54_2481_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_151106_63_24b9_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_154925_10_2481_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_150500_55_24c8_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_150502_91_24c8_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_150446_36_24c8_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_154645_98_2276_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_154933_55_2481_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_154929_32_2481_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_151141_90_24cc_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_151130_23_24b9_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_150458_18_24c8_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_154946_22_2481_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_151127_91_24cc_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_154927_21_2481_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_151146_57_24cc_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_145959_55_2421_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_151116_07_24b9_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_151144_24_24cc_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_154649_66_2276_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_151137_24_24cc_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_154654_91_247f_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_154922_99_2481_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_151104_27_24b9_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_151101_92_24b9_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_154720_63_247f_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_145957_44_2421_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_154647_82_2276_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_150519_46_24c8_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_151111_35_24b9_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_151125_58_24cc_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_150451_09_24c8_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_151155_90_24cc_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_154724_92_247f_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_154931_44_2481_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_154703_48_247f_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_154918_77_2481_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_151130_24_24cc_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_151108_99_24b9_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_151123_15_24b9_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_151113_71_24b9_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_154714_20_247f_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_151132_57_24cc_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_154716_34_247f_3B_AnalyticMS_8b.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene_Canada/20230622_154916_65_2481_3B_AnalyticMS_8b.tif"
]

