


data:
 filenames: [
"/data/nlahaye/output/Learnergy/DBN_MASTER_EMAS_FUSE_MULTI_LAYER/MASTER_EMAS_Fuse1.npy.heir_clust1output_test.data",
"/data/nlahaye/output/Learnergy/DBN_MASTER_EMAS_FUSE_MULTI_LAYER/MASTER_EMAS_Fuse2.npy.heir_clust1output.data"
]


