

data:
  filenames: [
"/data/nlahaye/output/Learnergy/DBN_GK2A_CLIPPED_9_PAD/gk2a_ami_le1b_vi004_ea010lc_202203050100.nc.heir_clust2output.data",
"/data/nlahaye/output/Learnergy/DBN_GK2A_CLIPPED_9_PAD/gk2a_ami_le1b_vi004_ea010lc_202203050110.nc.heir_clust2output_test.data"
]




