data:
 filenames: [
"/data/nlahaye/output/Learnergy/S2_KOREA_2/T52SDF_20220305T020701_B01_clip.tif.heir_clust2output_test.data",
"/data/nlahaye/output/Learnergy/S2_KOREA_2/T52SDG_20220305T020701_B01_clip.tif.heir_clust2output_test.data",
"/data/nlahaye/output/Learnergy/S2_KOREA_2/T52SEF_20220305T020701_B01_clip.tif.heir_clust2output_test.data",
"/data/nlahaye/output/Learnergy/S2_KOREA_2/T52SEG_20220305T020701_B01_clip.tif.heir_clust2output.data"
]


