
xl_fname: '/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/InSitu/W_FL_Karenia_brevis_abundance_2002-2021.04.05.updated.csv'
#/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/InSitu/W_FL_Karenia_brevis_abundance_2002-2021.04.05.xlsx'
start_date: "2018-08-01"
end_date: "2020-12-31"
clusters: 80000
 
clusters_dir: '/data/nlahaye/output/Learnergy/DBN_MOD_TROP_AUTO_CLUST_MODIS_ONLY_4_PAD/'
radius_degrees: 0.0225
#0.045 degrees = 5km
global_max: 10000000
ranges: [0,1000,10000,100000,1000000,10000000]
input_file_type: 'sif'

