
gen_from_geotiffs: false

data:
 clust_reader_type: "zarr_to_numpy"
 reader_kwargs:
   no_arg: "no_arg" 
 subset_inds: [[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]]
 create_separate: true
  

 
 gtiff_data: [
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190806_182857_0f34_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190806_182859_0f34_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190807_165439_1054_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190807_165441_1054_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190807_165442_1054_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190807_182618_1035_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190807_182620_1035_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190807_182621_1035_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190807_182622_1035_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190807_183158_0f22_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190807_183159_0f22_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190807_183200_0f22_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190807_183201_0f22_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190807_183228_25_1065_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190808_182604_101f_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190808_182606_101f_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190808_182953_1001_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190808_182954_1001_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190808_182955_1001_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190808_182956_1001_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190808_182957_1001_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190808_183352_07_1067_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190808_183356_19_1067_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190810_165416_0f4d_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190810_165417_0f4d_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190810_165418_0f4d_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190810_165807_104e_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190810_165807_1_104e_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190810_181730_0e3a_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190810_183047_0f34_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190810_183049_0f34_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190810_184311_16_1066_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190812_165921_0f44_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190812_165922_0f44_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190812_165925_0f44_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190812_182347_1021_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190812_182348_1021_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190812_182350_1021_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190812_182859_1003_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190812_182904_1003_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190812_183148_35_106b_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190812_183150_41_106b_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190812_183904_96_105d_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190812_183907_00_105d_3B_AnalyticMS_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/PSScene/20190812_183909_04_105d_3B_AnalyticMS_clip.tif"
]


 cluster_fnames: [
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190806_182857_0f34_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67397clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190806_182859_0f34_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67397clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190807_165439_1054_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67391clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190807_165441_1054_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_61697clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190807_182618_1035_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67397clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190807_182620_1035_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67397clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190807_182621_1035_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67397clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190807_182622_1035_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67397clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190807_183158_0f22_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67397clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190807_183200_0f22_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67397clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190807_183201_0f22_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67397clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190807_183228_25_1065_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67397clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190808_182604_101f_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67308clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190808_182606_101f_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67308clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190808_182953_1001_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67397clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190808_182954_1001_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67397clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190808_182955_1001_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67397clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190808_182956_1001_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67397clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190808_182957_1001_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67397clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190808_183352_07_1067_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67397clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190808_183356_19_1067_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67397clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190810_165416_0f4d_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67397clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190810_165417_0f4d_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67397clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190810_165418_0f4d_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67397clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190810_165807_104e_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67397clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190810_165807_1_104e_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67397clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190810_181730_0e3a_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67397clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190810_183047_0f34_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67397clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190810_183049_0f34_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67397clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190810_184311_16_1066_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67397clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190812_165921_0f44_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67397clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190812_165922_0f44_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67397clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190812_165925_0f44_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67390clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190812_182347_1021_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67397clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190812_182348_1021_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67397clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190812_182350_1021_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67397clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190812_182859_1003_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67397clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190812_182904_1003_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67397clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190812_183148_35_106b_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67397clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190812_183150_41_106b_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67397clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190812_183904_96_105d_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67397clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190812_183907_00_105d_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67397clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PLANET_PSS_AUTO_CLUST_STRAT_MULTI_LAYER/20190812_183909_04_105d_3B_AnalyticMS_clip.tif.heir_clust1output_test.data_67397clusters.zarr"
]


 
context:
 apply_context: false
 clusters: [] #i.e. smoke clusters
 name: "" #i.e. smoke
 compare_truth: false
 generate_union: false

