
gen_from_geotiffs: false

data:
 clust_reader_type: "zarr_to_numpy"
 reader_kwargs:
   no_arg: "no_arg" 
 subset_inds: [[3021,7522,1,5502],[],[],[],[],[],[],[]]
 create_separate: true
  

 
 gtiff_data: [
"/data/nlahaye/remoteSensing/CSDSA/Korea/PSScene/20220305_011431_11_242b_3B_AnalyticMS_clip.tif"
]


 cluster_fnames: [
"/data/nlahaye/output/Learnergy/DBN_PLANET_KOREA_CLIPPED/20220305_011431_11_242b_3B_AnalyticMS_clip.tif.heir_clust2output_test.data_7930000clusters.zarr"
]


 
context:
 apply_context: false
 clusters: [] #i.e. smoke clusters
 name: "" #i.e. smoke
 compare_truth: false
 generate_union: false

