#!/usr/bin/env python3
"""
Build training matchups between context-free SIT-FUSE GeoTIFFs and timestamped
GOES ABI-L2-FDCC fire-mask GeoTIFFs generated by pull_goes_abi_fdcc_fire_mask.py.

Expected FDCC fire-mask filename:
    fdcc_fire_mask_YYYYMMDDTHHMMSSZ.tif

Example:
    fdcc_fire_mask_20240728T000501Z.tif

Usage:
    python build_sit_fuse_fdcc_fire_matchups.py config.yaml
"""

from __future__ import annotations

import argparse
import copy
import csv
import datetime as dt
import logging
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable

import yaml


LOG = logging.getLogger("build-sit-fuse-fdcc-fire-matchups")
GEOTIFF_SUFFIXES = {".tif", ".tiff"}


@dataclass(frozen=True)
class RasterRecord:
    """One timestamped raster used as SIT-FUSE input or FDCC truth."""

    path: Path
    timestamp: dt.datetime
    source: str

    @property
    def date(self) -> dt.date:
        return self.timestamp.date()


def load_yaml(path: Path) -> dict[str, Any]:
    """Load a YAML configuration mapping."""
    with path.open("r", encoding="utf-8") as handle:
        config = yaml.safe_load(handle)

    if not isinstance(config, dict):
        raise ValueError("Configuration must parse to a YAML mapping.")

    return config


def write_yaml(data: dict[str, Any], path: Path) -> None:
    """Write a YAML mapping and create output directories if needed."""
    path.parent.mkdir(parents=True, exist_ok=True)

    with path.open("w", encoding="utf-8") as handle:
        yaml.safe_dump(
            data,
            handle,
            sort_keys=False,
            default_flow_style=False,
        )


def parse_datetime(value: str) -> dt.datetime:
    """
    Parse a UTC-naive datetime from the configuration.

    Accepted forms:
      YYYY-MM-DD
      YYYY-MM-DDTHH:MM:SS
      YYYY-MM-DDTHH:MM:SSZ
    """
    for fmt in (
        "%Y-%m-%dT%H:%M:%SZ",
        "%Y-%m-%dT%H:%M:%S",
        "%Y-%m-%d",
    ):
        try:
            return dt.datetime.strptime(value, fmt)
        except ValueError:
            continue

    raise ValueError(
        f"Could not parse {value!r}. "
        "Use YYYY-MM-DD or YYYY-MM-DDTHH:MM:SSZ."
    )


def find_geotiffs(root: Path) -> Iterable[Path]:
    """Yield all GeoTIFF files beneath a directory tree."""
    if not root.exists():
        raise FileNotFoundError(f"Directory does not exist: {root}")

    for path in root.rglob("*"):
        if path.is_file() and path.suffix.lower() in GEOTIFF_SUFFIXES:
            yield path


def parse_timestamp_from_filename(
    filename: str,
    patterns: list[str],
    source_name: str,
) -> dt.datetime | None:
    """
    Parse a timestamp from a file name.

    Every pattern must include one capture group holding:
      YYYYMMDDTHHMMSSZ
    or:
      YYYYMMDDTHHMMSS
    """
    for pattern in patterns:
        match = re.search(pattern, filename, flags=re.IGNORECASE)

        if match is None:
            continue

        if not match.groups():
            raise ValueError(
                f"{source_name} timestamp pattern needs one capture group. "
                f"Pattern: {pattern!r}"
            )

        token = match.group(1)

        for fmt in ("%Y%m%dT%H%M%SZ", "%Y%m%dT%H%M%S"):
            try:
                return dt.datetime.strptime(token, fmt)
            except ValueError:
                continue

        raise ValueError(
            f"Could not parse timestamp token {token!r} from "
            f"{filename!r}."
        )

    return None


def is_context_free(
    path: Path,
    include_patterns: list[str],
    exclude_patterns: list[str],
) -> bool:
    """
    Identify context-free SIT-FUSE cluster rasters by filename.

    The final include/exclude expressions must be adapted to the stable
    naming convention of the local SIT-FUSE output files.
    """
    filename = path.name

    if any(
        re.search(pattern, filename, flags=re.IGNORECASE)
        for pattern in exclude_patterns
    ):
        return False

    return any(
        re.search(pattern, filename, flags=re.IGNORECASE)
        for pattern in include_patterns
    )


def collect_sit_fuse_records(
    config: dict[str, Any],
    start: dt.datetime,
    end: dt.datetime,
) -> tuple[list[RasterRecord], list[dict[str, str]]]:
    """Collect timestamped context-free SIT-FUSE cluster rasters."""
    root = Path(config["directory"])
    timestamp_patterns = config["patterns"]["timestamp_patterns"]
    filters = config["context_free_filters"]

    records: list[RasterRecord] = []
    skipped: list[dict[str, str]] = []

    for path in find_geotiffs(root):
        if not is_context_free(
            path=path,
            include_patterns=filters["include_patterns"],
            exclude_patterns=filters.get("exclude_patterns", []),
        ):
            skipped.append(
                {
                    "path": str(path.resolve()),
                    "reason": "not_context_free_output",
                }
            )
            continue

        timestamp = parse_timestamp_from_filename(
            filename=path.name,
            patterns=timestamp_patterns,
            source_name="SIT-FUSE",
        )

        if timestamp is None:
            skipped.append(
                {
                    "path": str(path.resolve()),
                    "reason": "could_not_parse_sit_fuse_timestamp",
                }
            )
            continue

        if start <= timestamp <= end:
            records.append(
                RasterRecord(
                    path=path.resolve(),
                    timestamp=timestamp,
                    source="sit_fuse_context_free",
                )
            )

    records.sort(key=lambda record: (record.timestamp, str(record.path)))
    return records, skipped


def collect_fdcc_fire_records(
    config: dict[str, Any],
    start: dt.datetime,
    end: dt.datetime,
) -> tuple[list[RasterRecord], list[dict[str, str]]]:
    """
    Collect rasterized ABI-L2-FDCC fire-mask GeoTIFFs.

    Default filename convention:
      fdcc_fire_mask_YYYYMMDDTHHMMSSZ.tif
    """
    root = Path(config["directory"])
    patterns = config["patterns"]

    include_patterns = patterns.get(
        "include_patterns",
        [r"(?i)^fdcc_fire_mask_"],
    )

    timestamp_patterns = patterns.get(
        "timestamp_patterns",
        [r"(?i)^fdcc_fire_mask_(\d{8}T\d{6}Z)\.tiff?$"],
    )

    records: list[RasterRecord] = []
    skipped: list[dict[str, str]] = []

    for path in find_geotiffs(root):
        if not any(
            re.search(pattern, path.name, flags=re.IGNORECASE)
            for pattern in include_patterns
        ):
            skipped.append(
                {
                    "path": str(path.resolve()),
                    "reason": "not_fdcc_fire_mask",
                }
            )
            continue

        timestamp = parse_timestamp_from_filename(
            filename=path.name,
            patterns=timestamp_patterns,
            source_name="FDCC fire mask",
        )

        if timestamp is None:
            skipped.append(
                {
                    "path": str(path.resolve()),
                    "reason": "could_not_parse_fdcc_timestamp",
                }
            )
            continue

        if start <= timestamp <= end:
            records.append(
                RasterRecord(
                    path=path.resolve(),
                    timestamp=timestamp,
                    source="goes_abi_fdcc_fire_mask",
                )
            )

    records.sort(key=lambda record: (record.timestamp, str(record.path)))
    return records, skipped


def seconds_offset(
    first: dt.datetime,
    second: dt.datetime,
) -> int:
    """Return absolute temporal difference in seconds."""
    return int(abs((first - second).total_seconds()))


def choose_fdcc_match(
    sit_fuse_record: RasterRecord,
    fdcc_records: list[RasterRecord],
    max_time_difference_seconds: int,
    allow_fdcc_reuse: bool,
    used_fdcc_paths: set[str],
) -> tuple[RasterRecord | None, int | None]:
    """
    Select the closest FDCC fire mask in time.

    Matching is accepted only if the nearest FDCC file falls within
    max_time_difference_seconds. Ties are deterministic: smallest offset,
    earlier FDCC time, then lexical path.
    """
    candidates = [
        record
        for record in fdcc_records
        if allow_fdcc_reuse or str(record.path) not in used_fdcc_paths
    ]

    if not candidates:
        return None, None

    candidates.sort(
        key=lambda record: (
            seconds_offset(sit_fuse_record.timestamp, record.timestamp),
            record.timestamp,
            str(record.path),
        )
    )

    selected = candidates[0]
    offset_seconds = seconds_offset(
        sit_fuse_record.timestamp,
        selected.timestamp,
    )

    if offset_seconds > max_time_difference_seconds:
        return None, None

    return selected, offset_seconds


def build_pair_id(
    sit_fuse: RasterRecord,
    fdcc: RasterRecord,
    group_by: str,
) -> str:
    """
    Construct the downstream group ID.

    `fdcc_timestamp` is recommended: every SIT-FUSE raster matched to the same
    FDCC truth image remains in the same group for train/holdout and grouped CV.
    """
    if group_by == "fdcc_timestamp":
        return f"fire_{fdcc.timestamp:%Y%m%dT%H%M%SZ}"

    if group_by == "fdcc_day":
        return f"fire_{fdcc.timestamp:%Y%m%d}"

    if group_by == "sit_fuse_timestamp":
        return f"fire_{sit_fuse.timestamp:%Y%m%dT%H%M%SZ}"

    if group_by == "sit_fuse_day":
        return f"fire_{sit_fuse.timestamp:%Y%m%d}"

    raise ValueError(
        "matching.group_by must be one of: "
        "fdcc_timestamp, fdcc_day, sit_fuse_timestamp, sit_fuse_day"
    )


def build_matchups(
    sit_fuse_records: list[RasterRecord],
    fdcc_records: list[RasterRecord],
    config: dict[str, Any],
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    """
    Build classifier-ready matchups and audit rows.

    The generated records use:
      - sit_fuse_context_free: SIT-FUSE input cluster raster
      - truth_fdcc_fire: FDCC fire truth raster
      - sit_fuse_timestamp: SIT-FUSE acquisition time
      - fdcc_timestamp: FDCC acquisition time
    """
    matching_config = config["matching"]

    max_time_difference_seconds = int(
        matching_config.get("max_time_difference_seconds", 900)
    )
    allow_fdcc_reuse = bool(
        matching_config.get("allow_fdcc_reuse", True)
    )
    group_by = str(
        matching_config.get("group_by", "fdcc_timestamp")
    ).lower()

    used_fdcc_paths: set[str] = set()
    matchups: list[dict[str, Any]] = []
    audit: list[dict[str, Any]] = []

    for sit_fuse in sit_fuse_records:
        fdcc, offset_seconds = choose_fdcc_match(
            sit_fuse_record=sit_fuse,
            fdcc_records=fdcc_records,
            max_time_difference_seconds=max_time_difference_seconds,
            allow_fdcc_reuse=allow_fdcc_reuse,
            used_fdcc_paths=used_fdcc_paths,
        )

        if fdcc is None:
            audit.append(
                {
                    "sit_fuse_path": str(sit_fuse.path),
                    "sit_fuse_timestamp": sit_fuse.timestamp.strftime(
                        "%Y-%m-%dT%H:%M:%SZ"
                    ),
                    "fdcc_fire_path": "",
                    "fdcc_timestamp": "",
                    "time_offset_seconds": "",
                    "pair_id": "",
                    "status": "no_fdcc_match",
                    "notes": (
                        "No FDCC fire mask was found within "
                        f"{max_time_difference_seconds} seconds."
                    ),
                }
            )
            continue

        if not allow_fdcc_reuse:
            used_fdcc_paths.add(str(fdcc.path))

        pair_id = build_pair_id(
            sit_fuse=sit_fuse,
            fdcc=fdcc,
            group_by=group_by,
        )

        matchup = {
            "pair_id": pair_id,
            "label": "fire",
            "product": "fire",
            "sit_fuse_context_free": str(sit_fuse.path),
            "truth_fdcc_fire": str(fdcc.path),
            "sit_fuse_timestamp": sit_fuse.timestamp.strftime(
                "%Y-%m-%dT%H:%M:%SZ"
            ),
            "fdcc_timestamp": fdcc.timestamp.strftime(
                "%Y-%m-%dT%H:%M:%SZ"
            ),
            "fdcc_date": fdcc.date.isoformat(),
            "time_offset_seconds": offset_seconds,
            "match_method": "nearest_timestamp",
        }

        matchups.append(matchup)

        audit.append(
            {
                "sit_fuse_path": str(sit_fuse.path),
                "sit_fuse_timestamp": matchup["sit_fuse_timestamp"],
                "fdcc_fire_path": str(fdcc.path),
                "fdcc_timestamp": matchup["fdcc_timestamp"],
                "time_offset_seconds": offset_seconds,
                "pair_id": pair_id,
                "status": "matched",
                "notes": "",
            }
        )

    return matchups, audit


def write_csv(
    rows: list[dict[str, Any]],
    output_path: Path,
) -> None:
    """Write match, skip, and no-match audit rows."""
    output_path.parent.mkdir(parents=True, exist_ok=True)

    fieldnames = [
        "sit_fuse_path",
        "sit_fuse_timestamp",
        "fdcc_fire_path",
        "fdcc_timestamp",
        "time_offset_seconds",
        "pair_id",
        "status",
        "notes",
    ]

    with output_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def set_nested_value(
    data: dict[str, Any],
    dotted_key: str,
    value: Any,
) -> None:
    """Assign a value into a nested configuration mapping."""
    keys = dotted_key.split(".")
    current = data

    for key in keys[:-1]:
        if key not in current:
            current[key] = {}

        if not isinstance(current[key], dict):
            raise ValueError(
                f"Cannot assign to {dotted_key!r}: "
                f"{key!r} is not a YAML mapping."
            )

        current = current[key]

    current[keys[-1]] = value


def render_classifier_config(
    base_classifier_config: dict[str, Any],
    matchups: list[dict[str, Any]],
    generator_config: dict[str, Any],
) -> dict[str, Any]:
    """
    Copy a classifier template and inject FDCC matchup records.

    The updated `build_training_dataset()` should resolve:
      sit_fuse_context_free -> cluster/SIT-FUSE raster
      truth_fdcc_fire       -> annotation raster
      sit_fuse_timestamp    -> date-based splitting field
      pair_id               -> grouped split field
    """
    classifier_config = copy.deepcopy(base_classifier_config)

    matchup_key = generator_config["output"].get(
        "matchup_key",
        "matchups",
    )
    set_nested_value(
        classifier_config,
        matchup_key,
        matchups,
    )

    classifier_config.setdefault("label_column", "label")
    classifier_config.setdefault("group_column", "pair_id")

    classifier_config.setdefault("matchup_metadata", {})
    classifier_config["matchup_metadata"].update(
        {
            "sit_fuse_source": "context_free_geotiff",
            "truth_source": "goes_abi_fdcc_fire_mask_geotiff",
            "n_matchups": len(matchups),
            "sample_schema": {
                "sit_fuse_feature_path": "sit_fuse_context_free",
                "truth_mask_path": "truth_fdcc_fire",
                "label_column": "label",
                "group_column": "pair_id",
            },
        }
    )

    return classifier_config


def validate_config(config: dict[str, Any]) -> None:
    """Validate necessary configuration sections before processing."""
    required_top_level = [
        "time_range",
        "sit_fuse",
        "fdcc_fire",
        "matching",
        "classifier_config",
        "output",
    ]

    for key in required_top_level:
        if key not in config:
            raise ValueError(
                f"Missing required top-level configuration key: {key!r}"
            )

    for key in ("start", "end"):
        if key not in config["time_range"]:
            raise ValueError(f"Missing time_range.{key}")

    if "directory" not in config["sit_fuse"]:
        raise ValueError("Missing sit_fuse.directory")
    if "patterns" not in config["sit_fuse"]:
        raise ValueError("Missing sit_fuse.patterns")
    if "context_free_filters" not in config["sit_fuse"]:
        raise ValueError("Missing sit_fuse.context_free_filters")

    if "directory" not in config["fdcc_fire"]:
        raise ValueError("Missing fdcc_fire.directory")
    if "patterns" not in config["fdcc_fire"]:
        raise ValueError("Missing fdcc_fire.patterns")

    if "base_yaml" not in config["classifier_config"]:
        raise ValueError("Missing classifier_config.base_yaml")

    for key in ("classifier_yaml", "audit_csv"):
        if key not in config["output"]:
            raise ValueError(f"Missing output.{key}")


def main(config_path: Path) -> None:
    """Run FDCC matchup discovery, matching, and output generation."""
    config = load_yaml(config_path)
    validate_config(config)

    start = parse_datetime(config["time_range"]["start"])
    end = parse_datetime(config["time_range"]["end"])

    if end < start:
        raise ValueError(
            "time_range.end must be on or after time_range.start."
        )

    sit_fuse_records, sit_fuse_skipped = collect_sit_fuse_records(
        config=config["sit_fuse"],
        start=start,
        end=end,
    )

    fdcc_records, fdcc_skipped = collect_fdcc_fire_records(
        config=config["fdcc_fire"],
        start=start,
        end=end,
    )

    LOG.info(
        "Context-free SIT-FUSE rasters found: %d",
        len(sit_fuse_records),
    )
    LOG.info(
        "FDCC fire-mask rasters found: %d",
        len(fdcc_records),
    )

    matchups, audit = build_matchups(
        sit_fuse_records=sit_fuse_records,
        fdcc_records=fdcc_records,
        config=config,
    )

    for skipped in sit_fuse_skipped:
        audit.append(
            {
                "sit_fuse_path": skipped["path"],
                "sit_fuse_timestamp": "",
                "fdcc_fire_path": "",
                "fdcc_timestamp": "",
                "time_offset_seconds": "",
                "pair_id": "",
                "status": "skipped_sit_fuse",
                "notes": skipped["reason"],
            }
        )

    for skipped in fdcc_skipped:
        audit.append(
            {
                "sit_fuse_path": "",
                "sit_fuse_timestamp": "",
                "fdcc_fire_path": skipped["path"],
                "fdcc_timestamp": "",
                "time_offset_seconds": "",
                "pair_id": "",
                "status": "skipped_fdcc_fire",
                "notes": skipped["reason"],
            }
        )

    base_classifier_config = load_yaml(
        Path(config["classifier_config"]["base_yaml"])
    )

    classifier_config = render_classifier_config(
        base_classifier_config=base_classifier_config,
        matchups=matchups,
        generator_config=config,
    )

    classifier_yaml_path = Path(config["output"]["classifier_yaml"])
    audit_csv_path = Path(config["output"]["audit_csv"])

    write_yaml(classifier_config, classifier_yaml_path)
    write_csv(audit, audit_csv_path)

    n_matched = sum(row["status"] == "matched" for row in audit)
    n_unmatched = sum(row["status"] == "no_fdcc_match" for row in audit)

    LOG.info("Matched SIT-FUSE/FDCC fire pairs: %d", n_matched)
    LOG.info("Unmatched SIT-FUSE rasters: %d", n_unmatched)
    LOG.info(
        "Classifier configuration written: %s",
        classifier_yaml_path.resolve(),
    )
    LOG.info("Audit CSV written: %s", audit_csv_path.resolve())


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
    )

    parser = argparse.ArgumentParser(
        description=(
            "Generate context-free SIT-FUSE/GOES FDCC fire matchups and "
            "a classifier-ready YAML configuration."
        )
    )

    parser.add_argument(
        "yaml_config",
        type=Path,
        help="Path to matchup-generator YAML configuration.",
    )

    args = parser.parse_args()

    try:
        main(args.yaml_config)
    except Exception as exc:
        LOG.exception("FDCC matchup generation failed: %s", exc)
        sys.exit(1)



