


pixel_size: 0.0001
vector_fn: [
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_J1V-C2_353151.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_J1V-C2_353153.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_J1V-C2_353155.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_J1V-C2_353157.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_J1V-C2_353159.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_J1V-C2_353161.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_J1V-C2_353163.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_J1V-C2_353165.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_J1V-C2_353167.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_J1V-C2_353169.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_J1V-C2_353171.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_J1V-C2_353173.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_J1V-C2_353178.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_J1V-C2_353180.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_J1V-C2_353182.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_J1V-C2_353184.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_J1V-C2_353186.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_J1V-C2_353188.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_J1V-C2_353190.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_J1V-C2_353192.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_J1V-C2_353194.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_J1V-C2_353200.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_J1V-C2_353202.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_J1V-C2_353204.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_J1V-C2_353206.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_J1V-C2_353208.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_J1V-C2_353210.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_SV-C2_353152.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_SV-C2_353154.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_SV-C2_353156.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_SV-C2_353158.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_SV-C2_353160.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_SV-C2_353162.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_SV-C2_353164.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_SV-C2_353166.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_SV-C2_353168.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_SV-C2_353170.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_SV-C2_353172.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_SV-C2_353174.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_SV-C2_353179.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_SV-C2_353181.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_SV-C2_353183.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_SV-C2_353187.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_SV-C2_353189.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_SV-C2_353191.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_SV-C2_353193.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_SV-C2_353195.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_SV-C2_353201.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_SV-C2_353203.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_SV-C2_353205.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_SV-C2_353207.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_SV-C2_353209.shp',
'/data/nlahaye/remoteSensing/FIRMS/FULL_MONTH/fire_nrt_SV-C2_353211.shp']
 
#"/data/nlahaye/remoteSensing/FIRMS/MODIS/fire_archive_M-C61_352413.shp",
#"/data/nlahaye/remoteSensing/FIRMS/VIIRS1/fire_nrt_J1V-C2_352414.shp",
#"/data/nlahaye/remoteSensing/FIRMS/VIIRS1/fire_nrt_SV-C2_352415.shp",
#"/data/nlahaye/remoteSensing/FIRMS/M6/fire_archive_M6_166708.shp"]


nodata: -9999

