


pixel_size: 0.01
vector_fn: ["/data/nlahaye/remoteSensing/HMS_FIRE_SMOKE/hms_fire20190810.shp",
"/data/nlahaye/remoteSensing/HMS_FIRE_SMOKE/hms_fire20190809.shp",
"/data/nlahaye/remoteSensing/HMS_FIRE_SMOKE/hms_fire20190808.shp",
"/data/nlahaye/remoteSensing/HMS_FIRE_SMOKE/hms_fire20190807.shp",
"/data/nlahaye/remoteSensing/HMS_FIRE_SMOKE/hms_fire20190806.shp",
"/data/nlahaye/remoteSensing/HMS_FIRE_SMOKE/hms_fire20190805.shp",
"/data/nlahaye/remoteSensing/HMS_FIRE_SMOKE/hms_smoke20190810.shp",
"/data/nlahaye/remoteSensing/HMS_FIRE_SMOKE/hms_smoke20190809.shp",
"/data/nlahaye/remoteSensing/HMS_FIRE_SMOKE/hms_smoke20190808.shp",
"/data/nlahaye/remoteSensing/HMS_FIRE_SMOKE/hms_smoke20190807.shp",
"/data/nlahaye/remoteSensing/HMS_FIRE_SMOKE/hms_smoke20190806.shp",
"/data/nlahaye/remoteSensing/HMS_FIRE_SMOKE/hms_smoke20190805.shp"]


nodata: -9999

