

pixel_size: 0.0002695
vector_fn: [
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER1/MASTERL1B_1981719_01_20190806_1814_1816_V01_background.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER1/MASTERL1B_1981719_01_20190806_1814_1816_V01_burnscar.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER1/MASTERL1B_1981719_01_20190806_1814_1816_V01_burnscar_background.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER1/MASTERL1B_1981719_01_20190806_1814_1816_V01_fire.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER1/MASTERL1B_1981719_01_20190806_1814_1816_V01_fire_background.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER1/MASTERL1B_1981719_01_20190806_1814_1816_V01_smoke.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER1/MASTERL1B_1981719_01_20190806_1814_1816_V01_smoke_background.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER10/MASTERL1B_1981725_01_20190817_0004_0007_V01_background.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER10/MASTERL1B_1981725_01_20190817_0004_0007_V01_burnscar.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER10/MASTERL1B_1981725_01_20190817_0004_0007_V01_fire.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER10/MASTERL1B_1981725_01_20190817_0004_0007_V01_smoke.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER11/MASTERL1B_1981725_02_20190817_0025_0026_V01_background.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER11/MASTERL1B_1981725_02_20190817_0025_0026_V01_burnscar.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER11/MASTERL1B_1981725_02_20190817_0025_0026_V01_fire.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER11/MASTERL1B_1981725_02_20190817_0025_0026_V01_smoke.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER2/MASTERL1B_1981719_02_20190806_1851_1900_V01_background.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER2/MASTERL1B_1981719_02_20190806_1851_1900_V01_burnscar.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER2/MASTERL1B_1981719_02_20190806_1851_1900_V01_burnscar_background.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER2/MASTERL1B_1981719_02_20190806_1851_1900_V01_fire.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER2/MASTERL1B_1981719_02_20190806_1851_1900_V01_fire_background.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER2/MASTERL1B_1981719_02_20190806_1851_1900_V01_smoke.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER2/MASTERL1B_1981719_02_20190806_1851_1900_V01_smoke_background.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER3/MASTERL1B_1981719_05_20190806_2033_2039_V01_background.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER3/MASTERL1B_1981719_05_20190806_2033_2039_V01_burnscar.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER3/MASTERL1B_1981719_05_20190806_2033_2039_V01_burnscar_background.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER3/MASTERL1B_1981719_05_20190806_2033_2039_V01_fire.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER3/MASTERL1B_1981719_05_20190806_2033_2039_V01_fire_background.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER3/MASTERL1B_1981719_05_20190806_2033_2039_V01_smoke.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER3/MASTERL1B_1981719_05_20190806_2033_2039_V01_smoke_background.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER4/MASTERL1B_1981719_07_20190806_2226_2231_V01_background.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER4/MASTERL1B_1981719_07_20190806_2226_2231_V01_burnscar.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER4/MASTERL1B_1981719_07_20190806_2226_2231_V01_fire.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER4/MASTERL1B_1981719_07_20190806_2226_2231_V01_smoke.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER5/MASTERL1B_1981724_02_20190816_0033_0033_V01_background.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER5/MASTERL1B_1981724_02_20190816_0033_0033_V01_burnscar.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER5/MASTERL1B_1981724_02_20190816_0033_0033_V01_fire.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER5/MASTERL1B_1981724_02_20190816_0033_0033_V01_smoke.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER6/MASTERL1B_1981724_04_20190816_0106_0107_V01_background.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER6/MASTERL1B_1981724_04_20190816_0106_0107_V01_burnscar.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER6/MASTERL1B_1981724_04_20190816_0106_0107_V01_fire.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER6/MASTERL1B_1981724_04_20190816_0106_0107_V01_smoke.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER7/MASTERL1B_1981724_05_20190816_0124_0125_V01_background.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER7/MASTERL1B_1981724_05_20190816_0124_0125_V01_burnscar.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER7/MASTERL1B_1981724_05_20190816_0124_0125_V01_fire.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER7/MASTERL1B_1981724_05_20190816_0124_0125_V01_smoke.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER8/MASTERL1B_1981724_06_20190816_0139_0140_V01_background.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER8/MASTERL1B_1981724_06_20190816_0139_0140_V01_burnscar.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER8/MASTERL1B_1981724_06_20190816_0139_0140_V01_fire.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER8/MASTERL1B_1981724_06_20190816_0139_0140_V01_smoke.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER9/MASTERL1B_1981724_08_20190816_0215_0216_V01_background.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER9/MASTERL1B_1981724_08_20190816_0215_0216_V01_burnscar.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER9/MASTERL1B_1981724_08_20190816_0215_0216_V01_fire.shp",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_shapefiles_good_geo/shapes/MASTER9/MASTERL1B_1981724_08_20190816_0215_0216_V01_smoke.shp",
]


nodata: -9999

