
dbf: True
dbf_percentage_thresh: 0.51
dbf_list: [[
 #'/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_ROAD_CLIP_S1/PV_PANEL_hist_dict.pkl' 
#'/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_ROAD_CLIP/PV_PANEL_hist_dict.pkl'
'/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_ROAD_CLIP/PV_PANEL_hist_dict.pkl'
 
]]





