
dbf: True
dbf_percentage_thresh: 0.6
dbf_list: [[
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_DATA_Paper/GOES_TEMPO_SMOKE_OUTPUT_0.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_DATA_Paper/GOES_TEMPO_SMOKE_OUTPUT_1.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_DATA_Paper/GOES_TEMPO_SMOKE_OUTPUT_2.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_DATA_Paper/GOES_TEMPO_SMOKE_OUTPUT_3.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_DATA_Paper/GOES_TEMPO_SMOKE_OUTPUT_4.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_DATA_Paper/GOES_TEMPO_SMOKE_OUTPUT_5.csv",
],
[
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_DATA_Paper/GOES_TEMPO_BACKGROUND_OUTPUT_0.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_DATA_Paper/GOES_TEMPO_BACKGROUND_OUTPUT_1.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_DATA_Paper/GOES_TEMPO_BACKGROUND_OUTPUT_2.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_DATA_Paper/GOES_TEMPO_BACKGROUND_OUTPUT_3.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_DATA_Paper/GOES_TEMPO_BACKGROUND_OUTPUT_4.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_DATA_Paper/GOES_TEMPO_BACKGROUND_OUTPUT_5.csv",
]]





