 
dbf_percentage_thresh: 0.51
dbf: True
dbf_list: [
[
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/20190806_Fire_GOES_OUTPUT_0.csv",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/20190806_Fire_GOES_OUTPUT_1.csv",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/20190806_Fire_GOES_OUTPUT_2.csv",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/20190806_Fire_GOES_OUTPUT_3.csv",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/20190807_Fire_OUTPUT_4.csv",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/20190808_Fire_GOES_OUTPUT_5.csv",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/20190808_Fire_GOES_OUTPUT_6.csv",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/20190808_Fire_GOES_OUTPUT_7.csv",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/20190808_Fire_GOES_OUTPUT_8.csv",
],
[
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/20190806_Background_1_OUTPUT_0.csv",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/20190806_Background_1_OUTPUT_1.csv",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/20190806_Background_1_OUTPUT_2.csv",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/20190806_Background_1_OUTPUT_3.csv",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/20190807_Background_GOES_OUTPUT_4.csv",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/20190808_Background_GOES_OUTPUT_5.csv",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/20190808_Background_GOES_OUTPUT_6.csv",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/20190808_Background_GOES_OUTPUT_7.csv",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/20190808_Background_GOES_OUTPUT_8.csv",
]
] 




