dbf: True
dbf_percentage_thresh: 0.51
dbf_list: [
  [ "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190806_181433Z_WA-Harrington_SWPA_F01_V006.hdf_background_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190806_181534Z_WA-Creston_SWPF_F01_V006.hdf_background_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190806_181635Z_WA-Creston_SWPA_F01_V006.hdf_background_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190806_181736Z_WA-Wilbur_SWPF_F01_V006.hdf_background_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190806_181837Z_WA-Keller_SWPA_F01_V006.hdf_background_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190806_181938Z_WA-Keller_SWPF_F01_V006.hdf_background_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190806_182039Z_WA-Keller_SWPA_F01_V006.hdf_background_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190806_182140Z_WA-Keller_SWPF_F01_V006.hdf_background_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190806_182241Z_WA-Keller_SWPA_F01_V006.hdf_background_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190806_183449Z_WA-Mansfield_SWPA_F01_V006.hdf_background_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190806_183540Z_WA-Mansfield_SWPF_F01_V006.hdf_background_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190806_184409Z_WA-Ford_SWPF_F01_V006.hdf_background_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190806_185910Z_WA-Lamona_SWPA_F01_V006.hdf_background_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190806_190001Z_WA-Harrington_SWPF_F01_V006.hdf_background_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190806_190830Z_WA-Republic_SWPF_F01_V006.hdf_background_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190806_192132Z_WA-LoonLake_SWPA_F01_V006.hdf_background_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190806_192233Z_WA-DeerPark_SWPF_F01_V006.hdf_background_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190806_192334Z_WA-DeerPark_SWPA_F01_V006.hdf_background_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190806_192435Z_WA-Tumtum_SWPF_F01_V006.hdf_background_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190807_182220Z_WA-Mansfield_SWPA_F01_V006.hdf_background_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190807_182311Z_WA-GrandCoulee_SWPF_F01_V006.hdf_background_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190807_183140Z_WA-Springdale_SWPF_F01_V006.hdf_background_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190807_183615Z_ID-TwinLakes_SWPA_F01_V006.hdf_background_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190807_192648Z_WA-Mead_SWPF_F01_V006.hdf_background_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190807_193031Z_WA-NineMileFalls_SWPA_F01_V006.hdf_background_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190807_193122Z_WA-Ford_SWPF_F01_V006.hdf_background_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190807_193951Z_WA-Mansfield_SWPF_F01_V006.hdf_background_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190807_193951Z_WA-Mansfield_SWPF_F01_V006.hdf_background_OUTPUT_1.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190807_193951Z_WA-Mansfield_SWPF_F01_V006.hdf_background_OUTPUT_2.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190807_200002Z_WA-Springdale_SWPF_F01_V006.hdf_background_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190807_200534Z_WA-NineMileFalls_SWPA_F01_V006.hdf_background_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190808_181007Z_WA-Mansfield_SWPA_F01_V006.hdf_background_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190808_181058Z_WA-GrandCoulee_SWPF_F01_V006.hdf_background_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190808_181927Z_WA-Clayton_SWPF_F01_V006.hdf_background_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190808_182400Z_ID-Rathdrum_SWPA_F01_V006.hdf_background_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190808_182451Z_ID-Athol_SWPF_F01_V006.hdf_background_OUTPUT_0.dbf" ],


  [ "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190806_181534Z_WA-Creston_SWPF_F01_V006.hdf_smoke_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190806_181635Z_WA-Creston_SWPA_F01_V006.hdf_smoke_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190806_181736Z_WA-Wilbur_SWPF_F01_V006.hdf_smoke_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190806_181837Z_WA-Keller_SWPA_F01_V006.hdf_smoke_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190806_181938Z_WA-Keller_SWPF_F01_V006.hdf_smoke_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190806_182039Z_WA-Keller_SWPA_F01_V006.hdf_smoke_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190806_182140Z_WA-Keller_SWPF_F01_V006.hdf_smoke_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190806_182241Z_WA-Keller_SWPA_F01_V006.hdf_smoke_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190806_183449Z_WA-Mansfield_SWPA_F01_V006.hdf_smoke_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190806_183540Z_WA-Mansfield_SWPF_F01_V006.hdf_smoke_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190806_184409Z_WA-Ford_SWPF_F01_V006.hdf_smoke_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190806_190830Z_WA-Republic_SWPF_F01_V006.hdf_smoke_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190806_192132Z_WA-LoonLake_SWPA_F01_V006.hdf_smoke_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190806_192233Z_WA-DeerPark_SWPF_F01_V006.hdf_smoke_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190806_192334Z_WA-DeerPark_SWPA_F01_V006.hdf_smoke_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190807_182311Z_WA-GrandCoulee_SWPF_F01_V006.hdf_smoke_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190807_183140Z_WA-Springdale_SWPF_F01_V006.hdf_smoke_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190807_183615Z_ID-TwinLakes_SWPA_F01_V006.hdf_smoke_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190807_192648Z_WA-Mead_SWPF_F01_V006.hdf_smoke_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190807_193031Z_WA-NineMileFalls_SWPA_F01_V006.hdf_smoke_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190807_193122Z_WA-Ford_SWPF_F01_V006.hdf_smoke_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190807_200002Z_WA-Springdale_SWPF_F01_V006.hdf_smoke_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190807_200534Z_WA-NineMileFalls_SWPA_F01_V006.hdf_smoke_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190808_181058Z_WA-GrandCoulee_SWPF_F01_V006.hdf_smoke_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190808_181927Z_WA-Clayton_SWPF_F01_V006.hdf_smoke_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190808_182400Z_ID-Rathdrum_SWPA_F01_V006.hdf_smoke_OUTPUT_0.dbf",
    "/home/stasya/AIRMSPI_dbf/AirMSPI_ER2_GRP_TERRAIN_20190808_182451Z_ID-Athol_SWPF_F01_V006.hdf_smoke_OUTPUT_0.dbf" ]
]