 
dbf_percentage_thresh: 0.51
dbf: True
dbf_list: [
[
"/data/nlahaye/SIT_FUSE_Geo/MODIS_2025/eMAS_20190807_fire_OUTPUT_2.csv",
"/data/nlahaye/SIT_FUSE_Geo/MODIS_2025/eMAS_20190806_fire_OUTPUT_0.csv",
"/data/nlahaye/SIT_FUSE_Geo/MODIS_2025/20190808_Fire_GOES_OUTPUT_5.csv",
"/data/nlahaye/SIT_FUSE_Geo/MODIS_2025/20190806_Fire_GOES_OUTPUT_0.csv",
"/data/nlahaye/SIT_FUSE_Geo/MODIS_2025/eMAS_20190807_fire_OUTPUT_1.csv",
"/data/nlahaye/SIT_FUSE_Geo/MODIS_2025/20190807_Fire_OUTPUT_3.csv",
"/data/nlahaye/SIT_FUSE_Geo/MODIS_2025/eMAS_20190807_fire_OUTPUT_3.csv",
"/data/nlahaye/SIT_FUSE_Geo/MODIS_2025/20190807_Fire_OUTPUT_1.csv",
"/data/nlahaye/SIT_FUSE_Geo/MODIS_2025/20190807_Fire_OUTPUT_2.csv",
"/data/nlahaye/SIT_FUSE_Geo/MODIS_2025/eMAS_20190808_fire_OUTPUT_5.csv",
"/data/nlahaye/SIT_FUSE_Geo/MODIS_2025/eMAS_20190808_fire_OUTPUT_4.csv",
"/data/nlahaye/SIT_FUSE_Geo/MODIS_2025/20190808_Fire_GOES_OUTPUT_4.csv",
],
[
#"/data/nlahaye/SIT_FUSE_Geo/MODIS_2025/20190808_Background_GOES_OUTPUT_5.csv",
"/data/nlahaye/SIT_FUSE_Geo/MODIS_2025/20190807_Background_GOES_OUTPUT_1.csv",
#"/data/nlahaye/SIT_FUSE_Geo/MODIS_2025/20190807_Background_GOES_OUTPUT_2.csv",
"/data/nlahaye/SIT_FUSE_Geo/MODIS_2025/eMASL1B_19911_09_20190807_1947_2002_V03_fire_background_OUTPUT_1.csv",
"/data/nlahaye/SIT_FUSE_Geo/MODIS_2025/eMASL1B_19912_07_20190808_1806_1821_V03_fire_background_OUTPUT_5.csv",
"/data/nlahaye/SIT_FUSE_Geo/MODIS_2025/eMASL1B_19912_07_20190808_1806_1821_V03_fire_background_OUTPUT_4.csv",
#"/data/nlahaye/SIT_FUSE_Geo/MODIS_2025/20190806_Background_1_OUTPUT_0.csv",
#"/data/nlahaye/SIT_FUSE_Geo/MODIS_2025/20190808_Background_GOES_OUTPUT_4.csv",
"/data/nlahaye/SIT_FUSE_Geo/MODIS_2025/eMASL1B_19911_09_20190807_1947_2002_V03_fire_background_OUTPUT_2.csv",
#"/data/nlahaye/SIT_FUSE_Geo/MODIS_2025/eMASL1B_19911_09_20190807_1947_2002_V03_fire_background_OUTPUT_3.csv",
#"/data/nlahaye/SIT_FUSE_Geo/MODIS_2025/eMASL1B_19910_16_20190806_1941_1956_V03_fire_background_OUTPUT_0.csv",
"/data/nlahaye/SIT_FUSE_Geo/MODIS_2025/20190807_Background_GOES_OUTPUT_3.csv",
]
] 




