
dbf: True
dbf_percentage_thresh: 0.51
dbf_list: [[
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/2024213_14_smoke_OUTPUT_19.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/2024212_16_smoke_OUTPUT_15.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/2024213_14_smoke_OUTPUT_20.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_SMOKE_OUTPUT_6.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/2024210_16_smoke_OUTPUT_13.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/2024213_14_smoke_OUTPUT_18.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/2024210_16_smoke_OUTPUT_12.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/2024207_smoke_OUTPUT_2.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_SMOKE_OUTPUT_8.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_SMOKE_OUTPUT_4.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_SMOKE_OUTPUT_3.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/2024212_16_smoke_OUTPUT_16.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/2024210_16_smoke_OUTPUT_14.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/2024212_16_smoke_OUTPUT_17.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/2024207_smoke_OUTPUT_0.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/2024207_smoke_OUTPUT_1.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_SMOKE_OUTPUT_5.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_SMOKE_OUTPUT_7.csv",
],
[
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/2024212_16_smoke_background_OUTPUT_15.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/2024210_16_smoke_background_OUTPUT_13.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/2024209_14_smoke_background_OUTPUT_9.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/2024212_16_smoke_background_OUTPUT_16.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_BACKGROUND_OUTPUT_7.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/2024209_14_smoke_background_OUTPUT_11.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/2024210_16_smoke_background_OUTPUT_12.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_BACKGROUND_OUTPUT_5.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_BACKGROUND_OUTPUT_3.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/2024209_14_smoke_background_OUTPUT_10.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_BACKGROUND_OUTPUT_6.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_BACKGROUND_OUTPUT_8.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/2024207_smoke_background_OUTPUT_1.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/2024207_smoke_background_OUTPUT_0.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_BACKGROUND_OUTPUT_4.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/2024210_16_smoke_background_OUTPUT_14.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/2024207_smoke_background_OUTPUT_2.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/2024213_14_smoke_background_OUTPUT_20.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/2024213_14_smoke_background_OUTPUT_18.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/2024213_14_smoke_background_OUTPUT_19.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/2024212_16_smoke_background_OUTPUT_17.csv",
]]





