
dbf: True
dbf_list: [
["/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220305_output_1.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220305_output_2.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220305_output_3.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220305_output_4.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220305_output_5.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220305_output_6.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220305_output_7.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220306_output_10.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220306_output_11.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220306_output_12.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220306_output_13.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220306_output_1.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220306_output_2.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220306_output_3.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220306_output_4.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220306_output_5.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220306_output_6.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220306_output_7.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220306_output_8.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220306_output_9.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220307_output_1.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220307_output_2.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220307_output_3.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220307_output_4.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220307_output_5.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220307_output_6.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220307_output_7.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220308_background_output_1.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220308_background_output_2.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220308_background_output_3.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220308_background_output_4.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220308_background_output_5.dbf"],
["/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_fire_20220305_output_1.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_fire_20220305_output_2.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_fire_20220305_output_3.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_fire_20220305_output_4.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_fire_20220305_output_5.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_fire_20220305_output_6.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_fire_20220305_output_7.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_fire_20220306_output_10.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_fire_20220306_output_11.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_fire_20220306_output_12.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_fire_20220306_output_13.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_fire_20220306_output_1.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_fire_20220306_output_2.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_fire_20220306_output_3.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_fire_20220306_output_4.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_fire_20220306_output_5.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_fire_20220306_output_6.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_fire_20220306_output_7.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_fire_20220306_output_8.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_fire_20220306_output_9.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_fire_20220307_output_1.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_fire_20220307_output_2.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_fire_20220307_output_3.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_fire_20220307_output_4.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_fire_20220307_output_5.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_fire_20220307_output_6.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_fire_20220307_output_7.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220308_fire_output_1.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220308_fire_output_2.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220308_fire_output_3.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220308_fire_output_4.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220308_fire_output_5.dbf"],
["/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_smoke_20220305_output_1.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_smoke_20220305_output_2.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_smoke_20220305_output_3.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_smoke_20220305_output_4.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_smoke_20220305_output_5.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_smoke_20220305_output_6.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_smoke_20220305_output_7.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_smoke_20220306_output_10.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_smoke_20220306_output_11.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_smoke_20220306_output_12.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_smoke_20220306_output_13.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_smoke_20220306_output_1.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_smoke_20220306_output_2.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_smoke_20220306_output_3.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_smoke_20220306_output_4.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_smoke_20220306_output_5.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_smoke_20220306_output_6.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_smoke_20220306_output_7.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_smoke_20220306_output_8.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_smoke_20220306_output_9.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_smoke_20220307_output_1.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_smoke_20220307_output_2.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_smoke_20220307_output_3.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_smoke_20220307_output_4.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_smoke_20220307_output_5.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_smoke_20220307_output_6.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_smoke_20220307_output_7.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220308_smoke_output_1.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220308_smoke_output_2.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220308_smoke_output_3.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220308_smoke_output_4.dbf",
"/data/nlahaye/output/GK2A_DBFs/output_dbfs/gk2a_background_20220308_smoke_output_5.dbf"]
]


