
dbf: True
dbf_percentage_thresh: 0.6
dbf_list: [[
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_3_OUTPUT_10.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_6_OUTPUT_18.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_4_OUTPUT_14.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_2_OUTPUT_8.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_6_OUTPUT_19.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_6_OUTPUT_17.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_6_OUTPUT_20.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_4_OUTPUT_13.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_OUTPUT_1.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_6_OUTPUT_16.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_2_OUTPUT_3.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_2_OUTPUT_7.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_2_OUTPUT_5.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_2_OUTPUT_4.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_2_OUTPUT_6.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_3_OUTPUT_9.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_4_OUTPUT_12.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_3_OUTPUT_11.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_OUTPUT_2.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_6_OUTPUT_15.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_OUTPUT_0.csv",
],
[
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_BACKGROUND_OUTPUT_1.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_BACKGROUND_OUTPUT_13.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_BACKGROUND_OUTPUT_19.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_BACKGROUND_OUTPUT_12.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_BACKGROUND_OUTPUT_17.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_BACKGROUND_OUTPUT_0.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_BACKGROUND_OUTPUT_16.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_BACKGROUND_OUTPUT_7.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_BACKGROUND_OUTPUT_4.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_BACKGROUND_OUTPUT_18.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_BACKGROUND_OUTPUT_10.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_BACKGROUND_OUTPUT_2.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_BACKGROUND_OUTPUT_9.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_BACKGROUND_OUTPUT_6.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_BACKGROUND_OUTPUT_20.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_BACKGROUND_OUTPUT_3.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_BACKGROUND_OUTPUT_5.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_BACKGROUND_OUTPUT_11.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_BACKGROUND_OUTPUT_14.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_BACKGROUND_OUTPUT_8.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_PARK/GOES_TEMPO_FIRE_BACKGROUND_OUTPUT_15.csv",
]]





