 
 

dbf: True
dbf_percentage_thresh: 0.51
dbf_list: [
[

 "/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190807_181428_0e26_3B_AnalyticMS_clip_fire_OUTPUT_0.dbf",
 "/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190807_181429_0e26_3B_AnalyticMS_clip_fire_OUTPUT_0.dbf",
 "/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190807_183159_0f22_3B_AnalyticMS_clip_fire_OUTPUT_0.dbf",
 "/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190807_183200_0f22_3B_AnalyticMS_clip_fire_OUTPUT_0.dbf",

 "/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190807_181428_0e26_3B_AnalyticMS_clip_fire_OUTPUT_0.dbf",
  "/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190807_181429_0e26_3B_AnalyticMS_clip_fire_OUTPUT_0.dbf",
   "/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190807_183159_0f22_3B_AnalyticMS_clip_fire_OUTPUT_0.dbf",
    "/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190807_183200_0f22_3B_AnalyticMS_clip_fire_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190807_181428_0e26_3B_AnalyticMS_clip_fire_OUTPUT_0.dbf",
 "/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190807_181429_0e26_3B_AnalyticMS_clip_fire_OUTPUT_0.dbf",
  "/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190807_183159_0f22_3B_AnalyticMS_clip_fire_OUTPUT_0.dbf",
   "/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190807_183200_0f22_3B_AnalyticMS_clip_fire_OUTPUT_0.dbf",
   
   
    #"/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190808_182954_1001_3B_AnalyticMS_clip_fire_OUTPUT_0.dbf",
 #"/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190808_182955_1001_3B_AnalyticMS_clip_fire_OUTPUT_0.dbf",
 #"/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190808_182956_1001_3B_AnalyticMS_clip_fire_OUTPUT_0.dbf",
 #"/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190808_183352_07_1067_3B_AnalyticMS_clip_fire_OUTPUT_0.dbf",
 #"/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190808_183354_13_1067_3B_AnalyticMS_clip_fire_OUTPUT_0.dbf",
 #"/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190808_183356_19_1067_3B_AnalyticMS_clip_fire_OUTPUT_0.dbf"
],
[
"/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190807_181428_0e26_3B_AnalyticMS_clip_fire_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190807_181429_0e26_3B_AnalyticMS_clip_fire_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190807_183159_0f22_3B_AnalyticMS_clip_fire_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190807_183200_0f22_3B_AnalyticMS_clip_fire_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190807_165439_1054_3B_AnalyticMS_clip_fire_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190807_165441_1054_3B_AnalyticMS_clip_fire_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190807_181427_0e26_3B_AnalyticMS_clip_fire_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190807_181430_0e26_3B_AnalyticMS_clip_fire_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190807_181431_0e26_3B_AnalyticMS_clip_fire_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190807_182618_1035_3B_AnalyticMS_clip_fire_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190807_182619_1035_3B_AnalyticMS_clip_fire_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190807_182620_1035_3B_AnalyticMS_clip_fire_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190807_182621_1035_3B_AnalyticMS_clip_fire_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190807_182622_1035_3B_AnalyticMS_clip_fire_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190807_183158_0f22_3B_AnalyticMS_clip_fire_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190807_183201_0f22_3B_AnalyticMS_clip_fire_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190807_183202_0f22_3B_AnalyticMS_clip_fire_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190807_183228_25_1065_3B_AnalyticMS_clip_fire_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190807_183230_33_1065_3B_AnalyticMS_clip_fire_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190807_183232_41_1065_3B_AnalyticMS_clip_fire_background_OUTPUT_0.dbf",

"/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190808_182954_1001_3B_AnalyticMS_clip_fire_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190808_182955_1001_3B_AnalyticMS_clip_fire_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190808_182956_1001_3B_AnalyticMS_clip_fire_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190808_183352_07_1067_3B_AnalyticMS_clip_fire_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190808_183354_13_1067_3B_AnalyticMS_clip_fire_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/Planet_REDO/20190808_183356_19_1067_3B_AnalyticMS_clip_fire_background_OUTPUT_0.dbf",
] 

]
 


