
dbf: True
dbf_percentage_thresh: 0.51
dbf_list: [[
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_06_20190806_1815_1824_V03_burnscar_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_08_20190806_1834_1846_V03_burnscar_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_10_20190806_1858_1910_V03_burnscar_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_14_20190806_1926_1929_V03_burnscar_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_16_20190806_1941_1956_V03_burnscar_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_17_20190806_2000_2010_V03_burnscar_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_18_20190806_2018_2031_V03_burnscar_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_19_20190806_2035_2048_V03_burnscar_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_20_20190806_2052_2106_V03_burnscar_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_21_20190806_2111_2125_V03_burnscar_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19911_05_20190807_1817_1833_V03_burnscar_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19911_08_20190807_1928_1942_V03_burnscar_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19911_09_20190807_1947_2002_V03_burnscar_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19911_10_20190807_2004_2016_V03_burnscar_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19911_11_20190807_2021_2035_V03_burnscar_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19911_12_20190807_2039_2051_V03_burnscar_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19912_07_20190808_1806_1821_V03_burnscar_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19915_17_20190815_2122_2143_V03_burnscar_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19915_21_20190815_2216_2225_V03_burnscar_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19915_22_20190815_2231_2241_V03_burnscar_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19915_23_20190815_2247_2256_V03_burnscar_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19919_13_20190821_2324_2339_V03_burnscar_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19919_14_20190821_2343_2356_V03_burnscar_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19919_17_20190822_0036_0104_V03_burnscar_OUTPUT_0.dbf"
],
[
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_06_20190806_1815_1824_V03_burnscar_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_08_20190806_1834_1846_V03_burnscar_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_10_20190806_1858_1910_V03_burnscar_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_14_20190806_1926_1929_V03_burnscar_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_16_20190806_1941_1956_V03_burnscar_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_17_20190806_2000_2010_V03_burnscar_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_18_20190806_2018_2031_V03_burnscar_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_19_20190806_2035_2048_V03_burnscar_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_20_20190806_2052_2106_V03_burnscar_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_21_20190806_2111_2125_V03_burnscar_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19911_05_20190807_1817_1833_V03_burnscar_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19911_08_20190807_1928_1942_V03_burnscar_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19911_09_20190807_1947_2002_V03_burnscar_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19911_10_20190807_2004_2016_V03_burnscar_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19911_11_20190807_2021_2035_V03_burnscar_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19911_12_20190807_2039_2051_V03_burnscar_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19912_07_20190808_1806_1821_V03_burnscar_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19915_17_20190815_2122_2143_V03_burnscar_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19915_21_20190815_2216_2225_V03_burnscar_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19915_22_20190815_2231_2241_V03_burnscar_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19915_23_20190815_2247_2256_V03_burnscar_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19919_13_20190821_2324_2339_V03_burnscar_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19919_14_20190821_2343_2356_V03_burnscar_background_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19919_17_20190822_0036_0104_V03_burnscar_background_OUTPUT_0.dbf"
]
]




