
dbf: True
dbf_list: [
[
"/data/nlahaye/SIT_FUSE_Geo/MASTER_REDO/tiffs/MASTERL1B_1981719_05_20190806_2033_2039_V01_georeferenced_burnscar_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_REDO/tiffs/MASTERL1B_1981719_06_20190806_2153_2156_V01_georeferenced_burnscar_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_REDO/tiffs/MASTERL1B_1981719_07_20190806_2226_2231_V01_georeferenced_burnscar_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_REDO/tiffs/MASTERL1B_1981719_08_20190806_2249_2259_V01_georeferenced_burnscar_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_REDO/tiffs/MASTERL1B_1981720_07_20190808_0055_0103_V01_georeferenced_burnscar_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/MASTER_REDO/tiffs/MASTERL1B_1981720_09_20190808_0237_0238_V01_georeferenced_burnscar_OUTPUT_0.dbf"
],
[
"/data/nlahaye/SIT_FUSE_Geo/zarrs/MASTER_zarrs/burn_scar_redo/MASTER_burnscar_background_redo_1981719_05_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/zarrs/MASTER_zarrs/burn_scar_redo/MASTER_burnscar_background_redo_1981719_06_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/zarrs/MASTER_zarrs/burn_scar_redo/MASTER_burnscar_background_redo_1981719_07_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/zarrs/MASTER_zarrs/burn_scar_redo/MASTER_burnscar_background_redo_1981719_08_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/zarrs/MASTER_zarrs/burn_scar_redo/MASTER_burnscar_background_redo_1981720_07_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/zarrs/MASTER_zarrs/burn_scar_redo/MASTER_burnscar_background_redo_1981720_09_OUTPUT_0.dbf"
]
]




dbf_percentage_thresh: 0.8

