 
 

dbf: True
dbf_percentage_thresh: 0.51
dbf_list: [
[
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190806_Background_OUTPUT_1.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190806_Background_OUTPUT_2.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190806_Background_OUTPUT_3.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190806_Background_OUTPUT_4.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190806_Background_OUTPUT_5.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190806_Background_OUTPUT_6.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Background_Planet_OUTPUT_0.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Background_Planet_OUTPUT_10.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Background_Planet_OUTPUT_11.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Background_Planet_OUTPUT_12.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Background_Planet_OUTPUT_13.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Background_Planet_OUTPUT_14.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Background_Planet_OUTPUT_15.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Background_Planet_OUTPUT_16.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Background_Planet_OUTPUT_17.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Background_Planet_OUTPUT_18.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Background_Planet_OUTPUT_19.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Background_Planet_OUTPUT_1.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Background_Planet_OUTPUT_20.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Background_Planet_OUTPUT_21.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Background_Planet_OUTPUT_2.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Background_Planet_OUTPUT_3.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Background_Planet_OUTPUT_4.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Background_Planet_OUTPUT_5.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Background_Planet_OUTPUT_6.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Background_Planet_OUTPUT_7.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Background_Planet_OUTPUT_8.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Background_Planet_OUTPUT_9.dbf",
],
[
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190806_Smoke_OUTPUT_1.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190806_Smoke_OUTPUT_2.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190806_Smoke_OUTPUT_3.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190806_Smoke_OUTPUT_4.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190806_Smoke_OUTPUT_5.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190806_Smoke_OUTPUT_6.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Smoke_OUTPUT_0.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Smoke_OUTPUT_10.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Smoke_OUTPUT_11.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Smoke_OUTPUT_12.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Smoke_OUTPUT_13.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Smoke_OUTPUT_14.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Smoke_OUTPUT_15.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Smoke_OUTPUT_16.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Smoke_OUTPUT_17.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Smoke_OUTPUT_18.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Smoke_OUTPUT_19.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Smoke_OUTPUT_1.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Smoke_OUTPUT_20.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Smoke_OUTPUT_21.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Smoke_OUTPUT_2.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Smoke_OUTPUT_3.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Smoke_OUTPUT_4.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Smoke_OUTPUT_5.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Smoke_OUTPUT_6.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Smoke_OUTPUT_7.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Smoke_OUTPUT_8.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190807_Smoke_OUTPUT_9.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190808_Smoke_Planet_OUTPUT_0.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190808_Smoke_Planet_OUTPUT_10.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190808_Smoke_Planet_OUTPUT_11.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190808_Smoke_Planet_OUTPUT_12.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190808_Smoke_Planet_OUTPUT_1.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190808_Smoke_Planet_OUTPUT_2.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190808_Smoke_Planet_OUTPUT_3.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190808_Smoke_Planet_OUTPUT_4.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190808_Smoke_Planet_OUTPUT_5.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190808_Smoke_Planet_OUTPUT_6.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190808_Smoke_Planet_OUTPUT_7.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190808_Smoke_Planet_OUTPUT_8.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/20190808_Smoke_Planet_OUTPUT_9.dbf",
],
[
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19910_06_burn_scar_OUTPUT_1.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19910_06_burn_scar_OUTPUT_2.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19910_06_burn_scar_OUTPUT_3.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19910_06_burn_scar_OUTPUT_4.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19910_06_burn_scar_OUTPUT_5.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19910_06_burn_scar_OUTPUT_6.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_burn_scar_OUTPUT_0.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_burn_scar_OUTPUT_10.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_burn_scar_OUTPUT_11.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_burn_scar_OUTPUT_12.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_burn_scar_OUTPUT_13.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_burn_scar_OUTPUT_14.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_burn_scar_OUTPUT_15.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_burn_scar_OUTPUT_16.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_burn_scar_OUTPUT_17.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_burn_scar_OUTPUT_18.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_burn_scar_OUTPUT_19.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_burn_scar_OUTPUT_1.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_burn_scar_OUTPUT_20.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_burn_scar_OUTPUT_21.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_burn_scar_OUTPUT_2.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_burn_scar_OUTPUT_3.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_burn_scar_OUTPUT_4.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_burn_scar_OUTPUT_5.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_burn_scar_OUTPUT_6.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_burn_scar_OUTPUT_7.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_burn_scar_OUTPUT_8.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_burn_scar_OUTPUT_9.dbf",
],
[
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_fire_OUTPUT_0.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_fire_OUTPUT_10.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_fire_OUTPUT_11.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_fire_OUTPUT_12.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_fire_OUTPUT_13.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_fire_OUTPUT_14.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_fire_OUTPUT_15.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_fire_OUTPUT_16.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_fire_OUTPUT_17.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_fire_OUTPUT_18.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_fire_OUTPUT_19.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_fire_OUTPUT_1.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_fire_OUTPUT_20.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_fire_OUTPUT_21.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_fire_OUTPUT_2.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_fire_OUTPUT_3.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_fire_OUTPUT_4.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_fire_OUTPUT_5.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_fire_OUTPUT_6.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_fire_OUTPUT_7.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_fire_OUTPUT_8.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19911_05_fire_OUTPUT_9.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19912_07_fire_OUTPUT_0.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19912_07_fire_OUTPUT_10.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19912_07_fire_OUTPUT_11.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19912_07_fire_OUTPUT_12.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19912_07_fire_OUTPUT_1.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19912_07_fire_OUTPUT_2.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19912_07_fire_OUTPUT_3.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19912_07_fire_OUTPUT_4.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19912_07_fire_OUTPUT_5.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19912_07_fire_OUTPUT_6.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19912_07_fire_OUTPUT_7.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19912_07_fire_OUTPUT_8.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19912_07_fire_OUTPUT_9.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19910_06_fire_OUTPUT_1.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19910_06_fire_OUTPUT_2.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19910_06_fire_OUTPUT_3.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19910_06_fire_OUTPUT_4.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19910_06_fire_OUTPUT_5.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/emas_19910_06_fire_OUTPUT_6.dbf",
]
]
 


