
dbf: True
dbf_percentage_thresh: 0.51
dbf_list: [[
        #"/mnt/data/DBN_PV_MAPPING_WIDE/pv_wide_OUTPUT.csv"
        "/mnt/data/DBN_PV_MAPPING_WIDE/gambia_post_clustering_clip_labels_OUTPUT.csv",
],
[
        "/mnt/data/DBN_PV_MAPPING_WIDE/gambia_post_clustering_clip_background_OUTPUT.csv",
        #"/mnt/data/DBN_PV_MAPPING_WIDE/pv_wide_background_OUTPUT.csv"
]]




