
dbf: True
dbf_percentage_thresh: 0.90
dbf_list: [[
"/mnt/data/DBN_PV_MAPPING_WIDE_ROAD_CLIP/pv_polygons_OUTPUT_0.csv",
"/mnt/data/DBN_PV_MAPPING_WIDE_ROAD_CLIP/pv_polygons_OUTPUT_1.csv",
"/mnt/data/DBN_PV_MAPPING_WIDE_ROAD_CLIP/pv_polygons_OUTPUT_10.csv",
"/mnt/data/DBN_PV_MAPPING_WIDE_ROAD_CLIP/pv_polygons_OUTPUT_11.csv",
"/mnt/data/DBN_PV_MAPPING_WIDE_ROAD_CLIP/pv_polygons_OUTPUT_12.csv",
"/mnt/data/DBN_PV_MAPPING_WIDE_ROAD_CLIP/pv_polygons_OUTPUT_13.csv",
"/mnt/data/DBN_PV_MAPPING_WIDE_ROAD_CLIP/pv_polygons_OUTPUT_14.csv",
"/mnt/data/DBN_PV_MAPPING_WIDE_ROAD_CLIP/pv_polygons_OUTPUT_15.csv",
"/mnt/data/DBN_PV_MAPPING_WIDE_ROAD_CLIP/pv_polygons_OUTPUT_16.csv",
"/mnt/data/DBN_PV_MAPPING_WIDE_ROAD_CLIP/pv_polygons_OUTPUT_2.csv",
"/mnt/data/DBN_PV_MAPPING_WIDE_ROAD_CLIP/pv_polygons_OUTPUT_3.csv",
"/mnt/data/DBN_PV_MAPPING_WIDE_ROAD_CLIP/pv_polygons_OUTPUT_4.csv",
"/mnt/data/DBN_PV_MAPPING_WIDE_ROAD_CLIP/pv_polygons_OUTPUT_5.csv",
"/mnt/data/DBN_PV_MAPPING_WIDE_ROAD_CLIP/pv_polygons_OUTPUT_6.csv",
"/mnt/data/DBN_PV_MAPPING_WIDE_ROAD_CLIP/pv_polygons_OUTPUT_7.csv",
"/mnt/data/DBN_PV_MAPPING_WIDE_ROAD_CLIP/pv_polygons_OUTPUT_8.csv",
"/mnt/data/DBN_PV_MAPPING_WIDE_ROAD_CLIP/pv_polygons_OUTPUT_9.csv",
],
[
"/mnt/data/DBN_PV_MAPPING_WIDE_ROAD_CLIP/background_OUTPUT_0.csv",
"/mnt/data/DBN_PV_MAPPING_WIDE_ROAD_CLIP/background_OUTPUT_1.csv",
"/mnt/data/DBN_PV_MAPPING_WIDE_ROAD_CLIP/background_OUTPUT_10.csv",
"/mnt/data/DBN_PV_MAPPING_WIDE_ROAD_CLIP/background_OUTPUT_11.csv",
"/mnt/data/DBN_PV_MAPPING_WIDE_ROAD_CLIP/background_OUTPUT_12.csv",
"/mnt/data/DBN_PV_MAPPING_WIDE_ROAD_CLIP/background_OUTPUT_13.csv",
"/mnt/data/DBN_PV_MAPPING_WIDE_ROAD_CLIP/background_OUTPUT_14.csv",
"/mnt/data/DBN_PV_MAPPING_WIDE_ROAD_CLIP/background_OUTPUT_15.csv",
"/mnt/data/DBN_PV_MAPPING_WIDE_ROAD_CLIP/background_OUTPUT_16.csv",
"/mnt/data/DBN_PV_MAPPING_WIDE_ROAD_CLIP/background_OUTPUT_2.csv",
"/mnt/data/DBN_PV_MAPPING_WIDE_ROAD_CLIP/background_OUTPUT_3.csv",
"/mnt/data/DBN_PV_MAPPING_WIDE_ROAD_CLIP/background_OUTPUT_4.csv",
"/mnt/data/DBN_PV_MAPPING_WIDE_ROAD_CLIP/background_OUTPUT_5.csv",
"/mnt/data/DBN_PV_MAPPING_WIDE_ROAD_CLIP/background_OUTPUT_6.csv",
"/mnt/data/DBN_PV_MAPPING_WIDE_ROAD_CLIP/background_OUTPUT_7.csv",
"/mnt/data/DBN_PV_MAPPING_WIDE_ROAD_CLIP/background_OUTPUT_8.csv",
"/mnt/data/DBN_PV_MAPPING_WIDE_ROAD_CLIP/background_OUTPUT_9.csv",

]]




