
dbf: True
dbf_percentage_thresh: 0.95
dbf_list: [[
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_DATA/TEMPO_SMOKE_OUTPUT_01.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_DATA/TEMPO_SMOKE_OUTPUT_02.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_DATA/TEMPO_SMOKE_OUTPUT_03.csv",
],
[
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_DATA/TEMPO_BACKGROUND_OUTPUT_01.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_DATA/TEMPO_BACKGROUND_OUTPUT_02.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_DATA/TEMPO_BACKGROUND_OUTPUT_03.csv",
]]





