dbf: True
dbf_percentage_thresh: 0.51
dbf_list: [[
#"/data/nlahaye/SIT_FUSE_Geo/MSPI_REDO/eMAS_20190806_fire_OUTPUT_1.dbf",
#"/data/nlahaye/SIT_FUSE_Geo/MSPI_REDO/eMAS_20190806_fire_OUTPUT_10.dbf",
#"/data/nlahaye/SIT_FUSE_Geo/MSPI_REDO/eMAS_20190806_fire_OUTPUT_11.dbf",
"/data/nlahaye/SIT_FUSE_Geo/MSPI_REDO/eMAS_20190806_fire_OUTPUT_12.dbf",
"/data/nlahaye/SIT_FUSE_Geo/MSPI_REDO/eMAS_20190806_fire_OUTPUT_18.dbf",
#"/data/nlahaye/SIT_FUSE_Geo/MSPI_REDO/eMAS_20190806_fire_OUTPUT_19.dbf",
#"/data/nlahaye/SIT_FUSE_Geo/MSPI_REDO/eMAS_20190806_fire_OUTPUT_2.dbf",
#"/data/nlahaye/SIT_FUSE_Geo/MSPI_REDO/eMAS_20190806_fire_OUTPUT_21.dbf",
],
[ 
"/data/nlahaye/SIT_FUSE_Geo/MSPI_REDO/MSPI_SWP_Fire_Background_1_OUTPUT_1.dbf",
"/data/nlahaye/SIT_FUSE_Geo/MSPI_REDO/MSPI_SWP_Fire_Background_1_OUTPUT_2.dbf",
"/data/nlahaye/SIT_FUSE_Geo/MSPI_REDO/MSPI_SWP_Fire_Background_2_OUTPUT_10.dbf",
"/data/nlahaye/SIT_FUSE_Geo/MSPI_REDO/MSPI_SWP_Fire_Background_2_OUTPUT_11.dbf",
"/data/nlahaye/SIT_FUSE_Geo/MSPI_REDO/MSPI_SWP_Fire_Background_2_OUTPUT_12.dbf",
"/data/nlahaye/SIT_FUSE_Geo/MSPI_REDO/MSPI_SWP_Fire_Background_2_OUTPUT_18.dbf",
"/data/nlahaye/SIT_FUSE_Geo/MSPI_REDO/MSPI_SWP_Fire_Background_2_OUTPUT_19.dbf",
"/data/nlahaye/SIT_FUSE_Geo/MSPI_REDO/MSPI_SWP_Fire_Background_2_OUTPUT_21.dbf",

]]
 


