
dbf: True
dbf_percentage_thresh: 0.7
dbf_list: [[
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_13.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_14.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_15.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_16.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_17.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_18.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_19.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_2.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_20.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_21.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_22.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_23.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_24.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_25.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_26.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_27.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_28.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_29.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_3.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_30.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_31.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_32.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_33.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_34.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_35.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_36.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_37.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_38.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_39.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_4.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_40.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_41.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_42.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_43.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_44.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_45.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_46.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_47.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_48.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_49.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_5.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_50.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_51.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_52.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_53.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_54.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_55.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_56.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_57.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_58.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_59.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_6.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_60.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_7.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_8.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_OUTPUT_9.csv",
],
[
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_0.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_1.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_10.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_11.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_12.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_13.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_14.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_15.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_16.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_17.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_18.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_19.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_2.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_20.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_21.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_22.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_23.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_24.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_25.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_26.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_27.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_28.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_29.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_3.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_30.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_31.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_32.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_33.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_34.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_35.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_36.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_37.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_38.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_39.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_4.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_40.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_41.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_42.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_43.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_44.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_45.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_46.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_47.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_48.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_49.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_5.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_50.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_51.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_52.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_53.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_54.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_55.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_56.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_57.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_58.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_59.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_6.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_60.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_7.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_8.csv",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA/GOES_FIRE_BACKGROUND_OUTPUT_9.csv",
]]





