


dbf: True
dbf_percentage_thresh: 0.51
dbf_list: [
["/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_06_background_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_08_background_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_10_background_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_13_background_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_14_background_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_15_background_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_16_background_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_17_background_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_18_background_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_19_background_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_20_background_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_21_background_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19911_05_background_output.dbf",
#"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19911_08_background_output.dbf",
#"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19911_09_background_output.dbf",
#"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19911_10_background_output.dbf",
#"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19911_11_background_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19911_12_background_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19912_07_background_output.dbf"],

["/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_06_fire_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_08_fire_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_10_fire_output.dbf",
"",
#"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_13_fire_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_14_fire_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_15_fire_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_16_fire_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_17_fire_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_18_fire_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_19_fire_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_20_fire_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_21_fire_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19911_05_fire_output.dbf",
#"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19911_08_fire_output.dbf",
#"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19911_09_fire_output.dbf",
#"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19911_10_fire_output.dbf",
#"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19911_11_fire_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19911_12_fire_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19912_07_fire_output.dbf"],
["/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_06_burn_scar_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_08_burn_scar_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_10_burn_scar_output.dbf",
"",
#"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_13_burn_scar_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_14_burn_scar_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_15_burn_scar_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_16_burn_scar_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_17_burn_scar_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_18_burn_scar_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_19_burn_scar_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_20_burn_scar_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_21_burn_scar_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19911_05_burn_scar_output.dbf",
#"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19911_08_burn_scar_output.dbf",
#"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19911_09_burn_scar_output.dbf",
#"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19911_10_burn_scar_output.dbf",
#"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19911_11_burn_scar_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19911_12_burn_scar_output.dbf",
""],
#"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19912_07_burn_scar_output.dbf"],
["/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_06_smoke_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_08_smoke_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_10_smoke_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_13_smoke_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_14_smoke_output.dbf",
#"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_15_smoke_output.dbf",
"",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_16_smoke_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_17_smoke_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_18_smoke_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_19_smoke_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_20_smoke_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19910_21_smoke_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19911_05_smoke_output.dbf",
#"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19911_08_smoke_output.dbf",
#"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19911_09_smoke_output.dbf",
#"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19911_10_smoke_output.dbf",
#"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19911_11_smoke_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19911_12_smoke_output.dbf",
"/data/nlahaye/output/Context_Assignment_eMAS_V2/output_DBFs/emas_19912_07_smoke_output.dbf"]]
 


