 


dbf: True
dbf_list: [
[
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Background_1_OUTPUT_0.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Background_1_OUTPUT_10.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Background_1_OUTPUT_11.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Background_1_OUTPUT_12.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Background_1_OUTPUT_13.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Background_1_OUTPUT_14.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Background_1_OUTPUT_15.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Background_1_OUTPUT_16.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Background_1_OUTPUT_17.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Background_1_OUTPUT_18.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Background_1_OUTPUT_19.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Background_1_OUTPUT_1.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Background_1_OUTPUT_20.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Background_1_OUTPUT_21.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Background_1_OUTPUT_22.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Background_1_OUTPUT_23.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Background_1_OUTPUT_24.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Background_1_OUTPUT_25.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Background_1_OUTPUT_26.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Background_1_OUTPUT_27.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Background_1_OUTPUT_28.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Background_1_OUTPUT_29.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Background_1_OUTPUT_2.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Background_1_OUTPUT_30.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Background_1_OUTPUT_31.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Background_1_OUTPUT_32.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Background_1_OUTPUT_33.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Background_1_OUTPUT_34.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Background_1_OUTPUT_35.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Background_1_OUTPUT_36.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Background_1_OUTPUT_37.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Background_1_OUTPUT_3.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Background_1_OUTPUT_4.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Background_1_OUTPUT_5.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Background_1_OUTPUT_6.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Background_1_OUTPUT_7.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Background_1_OUTPUT_8.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Background_1_OUTPUT_9.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Background_GOES_OUTPUT_0.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Background_GOES_OUTPUT_1.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Background_GOES_OUTPUT_2.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Background_GOES_OUTPUT_3.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Background_GOES_OUTPUT_4.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Background_GOES_OUTPUT_5.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Background_GOES_OUTPUT_6.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Background_GOES_OUTPUT_7.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Background_GOES_OUTPUT_8.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190807_Bacoground_GOES_OUTPUT_0.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190807_Bacoground_GOES_OUTPUT_1.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190807_Bacoground_GOES_OUTPUT_2.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190807_Bacoground_GOES_OUTPUT_3.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190807_Bacoground_GOES_OUTPUT_4.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190807_Bacoground_GOES_OUTPUT_5.dbf"
],
[
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_OUTPUT_0.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Fire_GOES_OUTPUT_0.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_OUTPUT_10.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_OUTPUT_11.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_OUTPUT_12.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_OUTPUT_13.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_OUTPUT_14.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_OUTPUT_15.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_OUTPUT_16.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_OUTPUT_17.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_OUTPUT_18.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_OUTPUT_19.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_OUTPUT_1.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Fire_GOES_OUTPUT_1.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_OUTPUT_20.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_OUTPUT_21.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_OUTPUT_22.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_OUTPUT_23.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_OUTPUT_24.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_OUTPUT_25.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_OUTPUT_26.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_OUTPUT_27.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_OUTPUT_28.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_OUTPUT_29.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_OUTPUT_2.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Fire_GOES_OUTPUT_2.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_OUTPUT_30.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_OUTPUT_31.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_OUTPUT_32.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_OUTPUT_33.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_OUTPUT_34.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_OUTPUT_35.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_OUTPUT_36.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_OUTPUT_37.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_OUTPUT_3.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Fire_GOES_OUTPUT_3.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_OUTPUT_4.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Fire_GOES_OUTPUT_4.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_OUTPUT_5.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Fire_GOES_OUTPUT_5.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_OUTPUT_6.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Fire_GOES_OUTPUT_6.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_OUTPUT_7.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Fire_GOES_OUTPUT_7.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_OUTPUT_8.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Fire_GOES_OUTPUT_8.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_OUTPUT_9.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190807_Fire_OUTPUT_0.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190807_Fire_OUTPUT_1.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190807_Fire_OUTPUT_2.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190807_Fire_OUTPUT_3.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190807_Fire_OUTPUT_4.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190807_Fire_OUTPUT_5.dbf"
],
[
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_1_OUTPUT_0.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_1_OUTPUT_10.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_1_OUTPUT_11.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_1_OUTPUT_12.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_1_OUTPUT_13.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_1_OUTPUT_14.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_1_OUTPUT_15.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_1_OUTPUT_16.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_1_OUTPUT_17.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_1_OUTPUT_18.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_1_OUTPUT_19.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_1_OUTPUT_1.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_1_OUTPUT_20.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_1_OUTPUT_21.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_1_OUTPUT_22.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_1_OUTPUT_23.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_1_OUTPUT_24.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_1_OUTPUT_25.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_1_OUTPUT_26.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_1_OUTPUT_27.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_1_OUTPUT_28.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_1_OUTPUT_29.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_1_OUTPUT_2.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_1_OUTPUT_30.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_1_OUTPUT_31.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_1_OUTPUT_32.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_1_OUTPUT_33.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_1_OUTPUT_34.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_1_OUTPUT_35.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_1_OUTPUT_36.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_1_OUTPUT_37.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_1_OUTPUT_3.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_1_OUTPUT_4.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_1_OUTPUT_5.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_1_OUTPUT_6.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_1_OUTPUT_7.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_1_OUTPUT_8.dbf",
#"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_1_OUTPUT_9.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Smoke_GOES_2_OUTPUT_0.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Smoke_GOES_2_OUTPUT_1.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190807_Smoke_GOES_OUTPUT_0.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Smoke_GOES_OUTPUT_0.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190807_Smoke_GOES_OUTPUT_1.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Smoke_GOES_OUTPUT_1.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190807_Smoke_GOES_OUTPUT_2.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Smoke_GOES_OUTPUT_2.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190807_Smoke_GOES_OUTPUT_3.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Smoke_GOES_OUTPUT_3.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190807_Smoke_GOES_OUTPUT_4.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Smoke_GOES_OUTPUT_4.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190807_Smoke_GOES_OUTPUT_5.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Smoke_GOES_OUTPUT_5.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Smoke_GOES_OUTPUT_6.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Smoke_GOES_OUTPUT_7.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Smoke_GOES_OUTPUT_8.dbf"
]]
 


