
dbf: True
dbf_percentage_thresh: 0.51
dbf_list: [[
"/mnt/data/DBN_PV_MAPPING_WIDE_CLIPPED/pv_no_heir_building_clipped_wide_OUTPUT.csv",
],
[
"/mnt/data/DBN_PV_MAPPING_WIDE_CLIPPED/background_no_heir_building_clipped_wide_OUTPUT.csv",
]]




