 
dbf_percentage_thresh: 0.51
dbf: True
dbf_list: [
[
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Fire_GOES_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Fire_GOES_OUTPUT_1.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Fire_GOES_OUTPUT_10.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Fire_GOES_OUTPUT_11.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Fire_GOES_OUTPUT_12.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Fire_GOES_OUTPUT_13.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Fire_GOES_OUTPUT_14.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Fire_GOES_OUTPUT_15.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Fire_GOES_OUTPUT_16.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Fire_GOES_OUTPUT_17.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Fire_GOES_OUTPUT_18.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Fire_GOES_OUTPUT_19.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Fire_GOES_OUTPUT_2.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Fire_GOES_OUTPUT_20.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Fire_GOES_OUTPUT_21.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Fire_GOES_OUTPUT_22.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Fire_GOES_OUTPUT_23.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Fire_GOES_OUTPUT_24.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Fire_GOES_OUTPUT_25.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Fire_GOES_OUTPUT_26.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Fire_GOES_OUTPUT_27.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Fire_GOES_OUTPUT_28.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Fire_GOES_OUTPUT_29.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Fire_GOES_OUTPUT_3.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Fire_GOES_OUTPUT_30.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Fire_GOES_OUTPUT_31.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Fire_GOES_OUTPUT_32.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Fire_GOES_OUTPUT_33.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Fire_GOES_OUTPUT_34.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Fire_GOES_OUTPUT_35.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Fire_GOES_OUTPUT_36.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Fire_GOES_OUTPUT_37.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Fire_GOES_OUTPUT_4.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Fire_GOES_OUTPUT_5.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Fire_GOES_OUTPUT_6.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Fire_GOES_OUTPUT_7.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Fire_GOES_OUTPUT_8.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Fire_GOES_OUTPUT_9.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190807_Fire_OUTPUT_38.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190807_Fire_OUTPUT_39.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190807_Fire_OUTPUT_40.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190807_Fire_OUTPUT_41.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190807_Fire_OUTPUT_42.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190807_Fire_OUTPUT_43.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190808_Fire_GOES_OUTPUT_44.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190808_Fire_GOES_OUTPUT_45.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190808_Fire_GOES_OUTPUT_46.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190808_Fire_GOES_OUTPUT_47.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190808_Fire_GOES_OUTPUT_48.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190808_Fire_GOES_OUTPUT_49.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190808_Fire_GOES_OUTPUT_50.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190808_Fire_GOES_OUTPUT_51.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190808_Fire_GOES_OUTPUT_52.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190808_Fire_GOES_OUTPUT_53.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190808_Fire_GOES_OUTPUT_54.dbf",
#"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/OR_ABI-L1b-RadC-M6C01_G17_s20192201821196_e20192201823569_c20192201824006_fire_OUTPUT_46.dbf",
],

[
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Background_1_OUTPUT_0.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Background_1_OUTPUT_1.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Background_1_OUTPUT_10.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Background_1_OUTPUT_11.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Background_1_OUTPUT_12.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Background_1_OUTPUT_13.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Background_1_OUTPUT_14.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Background_1_OUTPUT_15.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Background_1_OUTPUT_16.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Background_1_OUTPUT_17.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Background_1_OUTPUT_18.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Background_1_OUTPUT_19.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Background_1_OUTPUT_2.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Background_1_OUTPUT_20.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Background_1_OUTPUT_21.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Background_1_OUTPUT_22.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Background_1_OUTPUT_23.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Background_1_OUTPUT_24.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Background_1_OUTPUT_25.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Background_1_OUTPUT_26.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Background_1_OUTPUT_27.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Background_1_OUTPUT_28.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Background_1_OUTPUT_29.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Background_1_OUTPUT_3.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Background_1_OUTPUT_30.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Background_1_OUTPUT_31.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Background_1_OUTPUT_32.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Background_1_OUTPUT_33.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Background_1_OUTPUT_34.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Background_1_OUTPUT_35.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Background_1_OUTPUT_36.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Background_1_OUTPUT_37.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Background_1_OUTPUT_4.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Background_1_OUTPUT_5.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Background_1_OUTPUT_6.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Background_1_OUTPUT_7.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Background_1_OUTPUT_8.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190806_Background_1_OUTPUT_9.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190807_Background_GOES_OUTPUT_38.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190807_Background_GOES_OUTPUT_39.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190807_Background_GOES_OUTPUT_40.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190807_Background_GOES_OUTPUT_41.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190807_Background_GOES_OUTPUT_42.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190807_Background_GOES_OUTPUT_43.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190808_Background_GOES_OUTPUT_44.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190808_Background_GOES_OUTPUT_45.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190808_Background_GOES_OUTPUT_46.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190808_Background_GOES_OUTPUT_47.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190808_Background_GOES_OUTPUT_48.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190808_Background_GOES_OUTPUT_49.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190808_Background_GOES_OUTPUT_50.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190808_Background_GOES_OUTPUT_51.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190808_Background_GOES_OUTPUT_52.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190808_Background_GOES_OUTPUT_53.dbf",
"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/20190808_Background_GOES_OUTPUT_54.dbf",
#"/data/nlahaye/SIT_FUSE_Geo/GOES_REDO/OR_ABI-L1b-RadC-M6C01_G17_s20192201821196_e20192201823569_c20192201824006_fire_background_OUTPUT_46.dbf",
]
]
 


