
dbf: True
dbf_percentage_thresh: 0.6
dbf_list: [[
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA/GOES_FIRE_OUTPUT_9.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA/GOES_FIRE_OUTPUT_8.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA/GOES_FIRE_OUTPUT_7.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA/GOES_FIRE_OUTPUT_6.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA/GOES_FIRE_OUTPUT_5.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA/GOES_FIRE_OUTPUT_4.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA/GOES_FIRE_OUTPUT_3.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA/GOES_FIRE_OUTPUT_2.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA/GOES_FIRE_OUTPUT_11.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA/GOES_FIRE_OUTPUT_10.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA/GOES_FIRE_OUTPUT_1.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA/GOES_FIRE_OUTPUT_0.csv",
],
[
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA/GOES_FIRE_BACKGROUND_OUTPUT_9.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA/GOES_FIRE_BACKGROUND_OUTPUT_8.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA/GOES_FIRE_BACKGROUND_OUTPUT_7.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA/GOES_FIRE_BACKGROUND_OUTPUT_6.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA/GOES_FIRE_BACKGROUND_OUTPUT_5.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA/GOES_FIRE_BACKGROUND_OUTPUT_4.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA/GOES_FIRE_BACKGROUND_OUTPUT_3.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA/GOES_FIRE_BACKGROUND_OUTPUT_2.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA/GOES_FIRE_BACKGROUND_OUTPUT_11.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA/GOES_FIRE_BACKGROUND_OUTPUT_10.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA/GOES_FIRE_BACKGROUND_OUTPUT_1.csv",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA/GOES_FIRE_BACKGROUND_OUTPUT_0.csv",
]]





