
gen_from_geotiffs: False

data:
 clust_reader_type: "zarr_to_numpy"
 reader_kwargs:
   no_arg: "no_arg" 
 subset_inds: [[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]]
 create_separate: False

 
 gtiff_data: [
"/data/nlahaye/remoteSensing/EMIT_WQ/EMIT_L2A_RFL_001_20230419T173941_2310912_005.tif",
"/data/nlahaye/remoteSensing/EMIT_WQ/EMIT_L2A_RFL_001_20230729T223029_2321015_001.tif",
"/data/nlahaye/remoteSensing/EMIT_WQ/EMIT_L2A_RFL_001_20240621T160541_2417311_026.tif",
"/data/nlahaye/remoteSensing/EMIT_WQ/EMIT_L2A_RFL_001_20240621T160553_2417311_027.tif",
"/data/nlahaye/remoteSensing/EMIT_WQ/EMIT_L2A_RFL_001_20240626T152144_2417810_030.tif",
"/data/nlahaye/remoteSensing/EMIT_WQ/EMIT_L2A_RFL_001_20240626T152155_2417810_031.tif"
]

 
 cluster_fnames: [
"/data/nlahaye/output/Learnergy/EMIT_WQ_REDUCED/EMIT_L2A_RFL_001_20230419T173941_2310912_005.nc.clust.data_74699clusters.zarr",
"/data/nlahaye/output/Learnergy/EMIT_WQ_REDUCED/EMIT_L2A_RFL_001_20230729T223029_2321015_001.nc.clust.data_74699clusters.zarr",
"/data/nlahaye/output/Learnergy/EMIT_WQ_REDUCED/EMIT_L2A_RFL_001_20240621T160541_2417311_026.nc.clust.data_74699clusters.zarr",
"/data/nlahaye/output/Learnergy/EMIT_WQ_REDUCED/EMIT_L2A_RFL_001_20240621T160553_2417311_027.nc.clust.data_74699clusters.zarr",
"/data/nlahaye/output/Learnergy/EMIT_WQ_REDUCED/EMIT_L2A_RFL_001_20240626T152144_2417810_030.nc.clust.data_74699clusters.zarr",
"/data/nlahaye/output/Learnergy/EMIT_WQ_REDUCED/EMIT_L2A_RFL_001_20240626T152155_2417810_031.nc.clust.data_74699clusters.zarr"
]


context: 
 apply_context: False
 clusters: [7,99,913, 572,2207,1032]  #64 #i.e. smoke clusters
 name: "smoke" #i.e. smoke
 compare_truth: False
 generate_union: False

