

data:

 out_dir: "/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/"
 label_fname: "genetics_poc_combined_wass.npy"
 filename: [
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P242_73665006707-A6_002_054_proj.tif.clust.data_73888clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P242_73665006707-A6_004_053_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P242_73665006707-C6_024_005_proj.tif.clust.data_73299clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P242_73665006707-G3_002_042_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P242_73665006707-G3_006_031_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P242_73665006707-G3_008_028_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P243_73665098237-A6_016_012_proj.tif.clust.data_73897clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P243_73665098237-A8_014_013_proj.tif.clust.data_73299clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P243_73665098237-A8_019_012_proj.tif.clust.data_73299clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P243_73665098237-C6_014_002_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P243_73665098237-C7_010_022_proj.tif.clust.data_73864clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P243_73665098237-C8_011_023_proj.tif.clust.data_73299clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P243_73665098237-C8_013_002_proj.tif.clust.data_73897clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P243_73665098237-E4_004_038_proj.tif.clust.data_73299clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P243_73665098237-G3_003_037_proj.tif.clust.data_73894clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P244_73665165741-A6_009_023_proj.tif.clust.data_73299clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P244_73665165741-A8_020_005_proj.tif.clust.data_73299clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P244_73665165741-A8_026_002_proj.tif.clust.data_73299clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P244_73665165741-C7_011_005_proj.tif.clust.data_73299clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P244_73665165741-C8_026_015_proj.tif.clust.data_73299clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P244_73665165741-G4_007_026_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P244_73665165741-G4_013_030_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P248_73665445941-C8_005_035_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P248_73665445941-G3_015_022_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P248_73665445941-G4_003_001_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P249_73665543731-A6_001_043_proj.tif.clust.data_73887clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P249_73665543731-A8_001_002_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P249_73665543731-C8_016_005_proj.tif.clust.data_73898clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P249_73665543731-G3_002_006_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P249_73665543731-G3_010_042_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P249_73665543731-G4_003_014_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P250_73665642094-A8_012_004_proj.tif.clust.data_70398clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P250_73665642094-A8_012_007_proj.tif.clust.data_73887clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P250_73665642094-C7_004_030_proj.tif.clust.data_73897clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P250_73665642094-C7_024_005_proj.tif.clust.data_73897clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P250_73665642094-C8_024_006_proj.tif.clust.data_73889clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P250_73665642094-G4_002_015_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P251_73665707362-A6_008_029_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P251_73665707362-A8_016_001_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P251_73665707362-C7_023_014_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P251_73665707362-C8_030_001_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P251_73665707362-G3_005_048_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P251_73665707362-G3_011_013_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P251_73665707362-G3_012_026_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P253_73665853037-E4_006_015_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P253_73665853037-E4_007_025_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P253_73665853037-G3_002_050_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P253_73665853037-G3_012_006_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P253_73666050044-A6_012_040_proj.tif.clust.data_23997clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P253_73666050044-A6_016_033_proj.tif.clust.data_23999clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P253_73666050044-C7_001_034_proj.tif.clust.data_23999clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P253_73666050044-C7_019_013_proj.tif.clust.data_23999clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P253_73666050044-C8_014_019_proj.tif.clust.data_23999clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P278_73668090728-C7_002_025_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P278_73668090728-C7_021_014_proj.tif.clust.data_73864clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P278_73668090728-E1_001_013_proj.tif.clust.data_73864clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P278_73668090728-E5_008_005_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P278_73668090728-E5_013_026_proj.tif.clust.data_73864clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P278_73668090728-E5_020_023_proj.tif.clust.data_73887clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P278_73668090728-E6_012_004_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P279_73668277350-A7_006_001_proj.tif.clust.data_73872clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P279_73668277350-A7_010_016_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P279_73668277350-C7_011_003_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P279_73668277350-E1_008_038_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P279_73668277350-E5_002_078_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P279_73668277350-E5_017_027_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P280_73668439105-A7_005_021_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P280_73668439105-E1_014_010_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P280_73668439105-E1_020_005_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P280_73668439105-E2_035_005_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P282_73668608120-D5_007_019_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P282_73668608120-D5_010_043_proj.tif.clust.data_73898clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P282_73668608120-D5_013_018_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P282_73668608120-E1_001_034_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P282_73668608120-E1_018_026_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P282_73668608120-E2_030_005_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P282_73668608120-E5_016_021_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P282_73668608120-E6_007_041_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P282_73668608120-E6_012_034_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P282_73668608120-F5_013_031_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P282_73668608120-F5_015_015_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P283_73668670516-C7_006_005_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P283_73668670516-D5_010_032_proj.tif.clust.data_73884clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P283_73668670516-D5_017_029_proj.tif.clust.data_73886clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P283_73668670516-E2_025_008_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P283_73668670516-E2_040_005_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P284_73668752578-C7_004_015_proj.tif.clust.data_73298clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P284_73668752578-D5_003_008_proj.tif.clust.data_73894clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P284_73668752578-D5_003_020_proj.tif.clust.data_73887clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P284_73668752578-E2_001_032_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P284_73668752578-E2_002_001_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P284_73668752578-E5_018_014_proj.tif.clust.data_64199clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P284_73668752578-E6_003_030_proj.tif.clust.data_64187clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P284_73668752578-F5_002_045_proj.tif.clust.data_73884clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P284_73668752578-F5_009_027_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P286_73668871024-C7_024_013_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P286_73668871024-E2_015_002_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P286_73668871024-E5_003_020_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P286_73668871024-E6_001_040_proj.tif.clust.data_73887clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P287_73668956345-D5_010_040_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P287_73668956345-E1_003_031_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P287_73668956345-E1_017_033_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P287_73668956345-E1_019_017_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P287_73668956345-E2_012_003_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P287_73668956345-E2_015_010_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P287_73668956345-E6_013_030_proj.tif.clust.data_73296clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P287_73668956345-F5_004_039_proj.tif.clust.data_73296clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P288_73669012104-D5_001_023_proj.tif.clust.data_73896clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P288_73669012104-D5_016_013_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P288_73669012104-E1_001_005_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P288_73669012104-E2_020_009_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P288_73669012104-E5_013_016_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P288_73669012104-E5_014_026_proj.tif.clust.data_73899clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P288_73669012104-E6_001_001_proj.tif.clust.data_73889clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P288_73669012104-E6_014_021_proj.tif.clust.data_73892clusters.zarr",
"/data/nlahaye/output/Learnergy/GENETICS_POC_COMBINED/P288_73669012104-E6_017_021_proj.tif.clust.data_73898clusters.zarr",
]


 reader_type: "zarr_to_numpy"
 reader_kwargs:
  None:
 
remove_singles: True
write_geotiff: True


