



input_files: [
[
"'/Users/nlahaye/Planet/20190806_182856_0f34_3B_AnalyticMS_clip.tif.clust.data_74590clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190806_182857_0f34_3B_AnalyticMS_clip.tif.clust.data_74590clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190806_182858_0f34_3B_AnalyticMS_clip.tif.clust.data_74590clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190806_182859_0f34_3B_AnalyticMS_clip.tif.clust.data_74590clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190806_182900_0f34_3B_AnalyticMS_clip.tif.clust.data_74590clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190806_184209_19_105e_3B_AnalyticMS_clip.tif.clust.data_74590clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190806_184211_23_105e_3B_AnalyticMS_clip.tif.clust.data_74580clusters.zarr.full_geo.tif'",
],
[
"'/Users/nlahaye/Planet/20190807_183230_33_1065_3B_AnalyticMS_clip.tif.clust.data_74580clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190807_165439_1054_3B_AnalyticMS_clip.tif.clust.data_74590clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190807_182619_1035_3B_AnalyticMS_clip.tif.clust.data_74590clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190807_182622_1035_3B_AnalyticMS_clip.tif.clust.data_74590clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190807_165441_1054_3B_AnalyticMS_clip.tif.clust.data_74590clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190807_183202_0f22_3B_AnalyticMS_clip.tif.clust.data_74590clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190807_182618_1035_3B_AnalyticMS_clip.tif.clust.data_74590clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190807_181427_0e26_3B_AnalyticMS_clip.tif.clust.data_74590clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190807_182621_1035_3B_AnalyticMS_clip.tif.clust.data_74590clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190807_182616_1035_3B_AnalyticMS_clip.tif.clust.data_74535clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190807_183228_25_1065_3B_AnalyticMS_clip.tif.clust.data_74580clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190807_183159_0f22_3B_AnalyticMS_clip.tif.clust.data_74590clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190807_165442_1054_3B_AnalyticMS_clip.tif.clust.data_74590clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190807_182620_1035_3B_AnalyticMS_clip.tif.clust.data_74580clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190807_181429_0e26_3B_AnalyticMS_clip.tif.clust.data_74590clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190807_181430_0e26_3B_AnalyticMS_clip.tif.clust.data_74590clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190807_183201_0f22_3B_AnalyticMS_clip.tif.clust.data_74590clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190807_183232_41_1065_3B_AnalyticMS_clip.tif.clust.data_74590clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190807_183158_0f22_3B_AnalyticMS_clip.tif.clust.data_74590clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190807_181431_0e26_3B_AnalyticMS_clip.tif.clust.data_74590clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190807_181428_0e26_3B_AnalyticMS_clip.tif.clust.data_74590clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190807_183200_0f22_3B_AnalyticMS_clip.tif.clust.data_74590clusters.zarr.full_geo.tif'",
],
[
"'/Users/nlahaye/Planet/20190808_182956_1001_3B_AnalyticMS_clip.tif.clust.data_74575clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190808_182605_101f_3B_AnalyticMS_clip.tif.clust.data_74590clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190808_182955_1001_3B_AnalyticMS_clip.tif.clust.data_74580clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190808_183356_19_1067_3B_AnalyticMS_clip.tif.clust.data_74590clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190808_182954_1001_3B_AnalyticMS_clip.tif.clust.data_74590clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190808_183352_07_1067_3B_AnalyticMS_clip.tif.clust.data_74580clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190808_182953_1001_3B_AnalyticMS_clip.tif.clust.data_74590clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190808_182604_101f_3B_AnalyticMS_clip.tif.clust.data_74590clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190808_182608_101f_3B_AnalyticMS_clip.tif.clust.data_74580clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190808_182957_1001_3B_AnalyticMS_clip.tif.clust.data_69173clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190808_182606_101f_3B_AnalyticMS_clip.tif.clust.data_74580clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190808_183354_13_1067_3B_AnalyticMS_clip.tif.clust.data_74580clusters.zarr.full_geo.tif'",
"'/Users/nlahaye/Planet/20190808_182607_101f_3B_AnalyticMS_clip.tif.clust.data_74580clusters.zarr.full_geo.tif'",
]
]

shp_files: [
["/Volumes/NL_WD_HD_2/Context_Assignment_Planet_PSS/emas_19910_06_fire.shp", "/Volumes/NL_WD_HD_2/Context_Assignment_Planet_PSS/emas_19910_06_burn_scar.shp", "/Volumes/NL_WD_HD_2/Context_Assignment_Planet_PSS/20190806_Smoke.shp", "/Volumes/NL_WD_HD_2/Context_Assignment_Planet_PSS/20190806_Background.shp"],
["/Volumes/NL_WD_HD_2/Context_Assignment_Planet_PSS/emas_19911_05_fire.shp", "/Volumes/NL_WD_HD_2/Context_Assignment_Planet_PSS/emas_19911_05_burn_scar.shp", "/Volumes/NL_WD_HD_2/Context_Assignment_Planet_PSS/20190807_Smoke.shp", "/Volumes/NL_WD_HD_2/Context_Assignment_Planet_PSS/20190807_Background_Planet.shp"],
["/Volumes/NL_WD_HD_2/Context_Assignment_Planet_PSS/emas_19912_07_fire.shp", "/Volumes/NL_WD_HD_2/Context_Assignment_Planet_PSS/20190808_Smoke_Planet.shp"]
]

out_file: "Planet_Batch_Full.json"

