
gen_from_geotiffs: False

data:
 clust_reader_type: "gtiff"
 reader_kwargs:
   no_arg: "no_arg" 
 subset_inds: [[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]]
 create_separate: False

 
 gtiff_data: [
"/data/nlahaye/remoteSensing/GK2A_FOG/RADI_FOG/gk2a_ami_le1b_ir087_ea020lc_202109301700.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/RADI_FOG/gk2a_ami_le1b_ir087_ea020lc_202109301730.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/RADI_FOG/gk2a_ami_le1b_ir087_ea020lc_202109301800.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/RADI_FOG/gk2a_ami_le1b_ir087_ea020lc_202109301830.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/RADI_FOG/gk2a_ami_le1b_ir087_ea020lc_202109301900.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/RADI_FOG/gk2a_ami_le1b_ir087_ea020lc_202109301930.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/RADI_FOG/gk2a_ami_le1b_ir087_ea020lc_202109302000.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/RADI_FOG/gk2a_ami_le1b_ir087_ea020lc_202109302030.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/RADI_FOG/gk2a_ami_le1b_ir087_ea020lc_202109302100.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/RADI_FOG/gk2a_ami_le1b_ir087_ea020lc_202109302130.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/RADI_FOG/gk2a_ami_le1b_ir087_ea020lc_202109302200.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/RADI_FOG/gk2a_ami_le1b_ir087_ea020lc_202109302230.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/RADI_FOG/gk2a_ami_le1b_ir087_ea020lc_202109302300.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/RADI_FOG/gk2a_ami_le1b_ir087_ea020lc_202109302330.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/RADI_FOG/gk2a_ami_le1b_ir087_ea020lc_202110010000.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/RADI_FOG/gk2a_ami_le1b_ir087_ea020lc_202110010030.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/RADI_FOG/gk2a_ami_le1b_ir087_ea020lc_202110010100.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/RADI_FOG/gk2a_ami_le1b_ir087_ea020lc_202110010130.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/RADI_FOG/gk2a_ami_le1b_ir087_ea020lc_202110010200.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/RADI_FOG/gk2a_ami_le1b_ir087_ea020lc_202110010230.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/RADI_FOG/gk2a_ami_le1b_ir087_ea020lc_202110010300.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/RADI_FOG/gk2a_ami_le1b_ir087_ea020lc_202110010330.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/ADVE_FOG/gk2a_ami_le1b_ir087_ea020lc_202203131000.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/ADVE_FOG/gk2a_ami_le1b_ir087_ea020lc_202203131030.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/ADVE_FOG/gk2a_ami_le1b_ir087_ea020lc_202203131100.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/ADVE_FOG/gk2a_ami_le1b_ir087_ea020lc_202203131130.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/ADVE_FOG/gk2a_ami_le1b_ir087_ea020lc_202203131200.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/ADVE_FOG/gk2a_ami_le1b_ir087_ea020lc_202203131230.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/ADVE_FOG/gk2a_ami_le1b_ir087_ea020lc_202203131300.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/ADVE_FOG/gk2a_ami_le1b_ir087_ea020lc_202203131330.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/ADVE_FOG/gk2a_ami_le1b_ir087_ea020lc_202203131400.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/ADVE_FOG/gk2a_ami_le1b_ir087_ea020lc_202203131430.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/ADVE_FOG/gk2a_ami_le1b_ir087_ea020lc_202203131500.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/ADVE_FOG/gk2a_ami_le1b_ir087_ea020lc_202203131530.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/ADVE_FOG/gk2a_ami_le1b_ir087_ea020lc_202203131600.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/ADVE_FOG/gk2a_ami_le1b_ir087_ea020lc_202203131630.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/ADVE_FOG/gk2a_ami_le1b_ir087_ea020lc_202203131700.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/ADVE_FOG/gk2a_ami_le1b_ir087_ea020lc_202203131730.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/ADVE_FOG/gk2a_ami_le1b_ir087_ea020lc_202203131800.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/ADVE_FOG/gk2a_ami_le1b_ir087_ea020lc_202203131830.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/ADVE_FOG/gk2a_ami_le1b_ir087_ea020lc_202203131900.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/ADVE_FOG/gk2a_ami_le1b_ir087_ea020lc_202203131930.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/ADVE_FOG/gk2a_ami_le1b_ir087_ea020lc_202203132000.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/ADVE_FOG/gk2a_ami_le1b_ir087_ea020lc_202203132030.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/ADVE_FOG/gk2a_ami_le1b_ir087_ea020lc_202203132100.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/ADVE_FOG/gk2a_ami_le1b_ir087_ea020lc_202203132130.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/ADVE_FOG/gk2a_ami_le1b_ir087_ea020lc_202203132200.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/ADVE_FOG/gk2a_ami_le1b_ir087_ea020lc_202203132230.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/ADVE_FOG/gk2a_ami_le1b_ir087_ea020lc_202203132300.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/ADVE_FOG/gk2a_ami_le1b_ir087_ea020lc_202203132330.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/ADVE_FOG/gk2a_ami_le1b_ir087_ea020lc_202203140000.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/LOW_CLD/gk2a_ami_le1b_ir087_ea020lc_202309151200.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/LOW_CLD/gk2a_ami_le1b_ir087_ea020lc_202309151230.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/LOW_CLD/gk2a_ami_le1b_ir087_ea020lc_202309151300.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/LOW_CLD/gk2a_ami_le1b_ir087_ea020lc_202309151330.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/LOW_CLD/gk2a_ami_le1b_ir087_ea020lc_202309151400.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/LOW_CLD/gk2a_ami_le1b_ir087_ea020lc_202309151430.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/LOW_CLD/gk2a_ami_le1b_ir087_ea020lc_202309151500.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/LOW_CLD/gk2a_ami_le1b_ir087_ea020lc_202309151530.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/LOW_CLD/gk2a_ami_le1b_ir087_ea020lc_202309151600.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/LOW_CLD/gk2a_ami_le1b_ir087_ea020lc_202309151630.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/TWILIGHT_FALSE/gk2a_ami_le1b_ir087_ea020lc_202405072000.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/TWILIGHT_FALSE/gk2a_ami_le1b_ir087_ea020lc_202405072030.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/TWILIGHT_FALSE/gk2a_ami_le1b_ir087_ea020lc_202405072100.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/TWILIGHT_FALSE/gk2a_ami_le1b_ir087_ea020lc_202405072130.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/TWILIGHT_FALSE/gk2a_ami_le1b_ir087_ea020lc_202405072200.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/TWILIGHT_FALSE/gk2a_ami_le1b_ir087_ea020lc_202405072230.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/TWILIGHT_FALSE/gk2a_ami_le1b_ir087_ea020lc_202405072300.tif",
"/data/nlahaye/remoteSensing/GK2A_FOG/TWILIGHT_FALSE/gk2a_ami_le1b_ir087_ea020lc_202405072330.tif"
]

 cluster_fnames: [
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202109301700.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202109301730.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202109301800.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202109301830.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202109301900.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202109301930.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202109302000.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202109302030.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202109302100.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202109302130.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202109302200.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202109302230.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202109302300.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202109302330.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202110010000.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202110010030.tif.clust.data_60195clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202110010100.tif.clust.data_60195clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202110010130.tif.clust.data_28189clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202110010200.tif.clust.data_28189clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202110010230.tif.clust.data_28189clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202110010300.tif.clust.data_28189clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202110010330.tif.clust.data_60195clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202203131000.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202203131030.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202203131100.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202203131130.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202203131200.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202203131230.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202203131300.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202203131330.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202203131400.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202203131430.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202203131500.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202203131530.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202203131600.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202203131630.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202203131700.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202203131730.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202203131800.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202203131830.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202203131900.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202203131930.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202203132000.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202203132030.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202203132100.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202203132130.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202203132200.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202203132230.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202203132300.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202203132330.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202203140000.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202309151200.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202309151230.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202309151300.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202309151330.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202309151400.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202309151430.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202309151500.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202309151530.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202405072000.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202405072030.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202405072100.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202405072130.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202405072200.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202405072230.tif.clust.data_69692clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202405072300.tif.clust.data_69688clusters.zarr",
"/data/nlahaye/output/Learnergy/GK2A_FOG_DBN/gk2a_ami_le1b_ir087_ea020lc_202405072330.tif.clust.data_60296clusters.zarr"
]


context: 
 apply_context: False
 clusters: [
#[7.248],
[60.168, 60.754, 60.776, 60.986]]
#75.002, 7.257,7.273,
 name: ["fog"] #i.e. smoke
 compare_truth: False
 generate_union: False

