
xl_fname: '/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/InSitu/W_FL_Karenia_brevis_abundance_2002-2021.04.05.updated.csv'
start_date: "2018-05-01"
end_date: "2019-08-31"
clusters: 6001
 
clusters_dir: "/data/nlahaye/output/Learnergy/MODIS_Gulf_of_Mexico/"
 
#clusters_dir: '/data/nlahaye/output/MERGED_HAB_20250225/AQUA_MODIS/'
radius_degrees: [0.01125, 0.0225, 0.045] #, 0.09]
global_max: 10000000
ranges: [0,1000,10000,100000,1000000,10000000, 100000000]
input_file_type: 'daily_no_heir'

