
#Akashiwo_sanguinea,Alexandrium_spp,Dinophysis_spp,Lingulodinium_polyedra,Prorocentrum_spp,Pseudo_nitzschia_delicatissima_group,Pseudo_nitzschia_seriata_group,Ceratium_spp,Cochlodinium_spp,Gymnodinium_spp,Other_Diatoms,Other_Dinoflagellates,Total_Phytoplankton

use_key: 'Other_Dinoflagellates'

xl_fname: '/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/InSitu/HAB_S_CA_Combined.csv'
start_date: "2018-06-01"
end_date: "2019-12-31"
clusters: 120000
  
clusters_dir: '/data/nlahaye/output/Learnergy/MODIS_ONLY_S_CA/'
radius_degrees: [0.09]  #0.0225
#0.045 degrees = 5km
global_max: 10000000
ranges: [0,1000,10000,100000,1000000,10000000, 100000000]
input_file_type: 'AQUA_MODIS'

