xl_fname: '/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/InSitu/HAB_S_CA_Combined.csv'
start_date: "2018-06-01"
end_date: "2019-12-31"
clusters: 120000
 
clusters_dir: '/data/nlahaye/output/Learnergy/S3A_S_CA/'
radius_degrees: [0.09]  #0.0225
#0.045 degrees = 5km
global_max: 10000000
ranges: [0,1000,10000,100000,1000000,10000000, 100000000]
input_file_type: 'S3A_no_heir'

use_key: 'Pseudo_nitzschia_delicatissima_group'

