
xl_fname: '/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/InSitu/W_FL_Karenia_brevis_abundance_2002-2021.04.05.updated.csv'
start_date: "2019-09-01"
end_date: "2019-12-31"
clusters: 5001
 
clusters_dir: '/data/nlahaye/output/MERGED_HAB_20240818/SNPP_VIIRS/'
radius_degrees: 0.0225
#0.045 degrees = 5km
global_max: 10000000
ranges: [0,1000,10000,100000,1000000,10000000]
input_file_type: 'daily'

