

data:

 contour_filename: [
"/data/nlahaye/output/Learnergy/DBN_eMAS/eMASL1B_19910_06_20190806_1815_1824_V02_Georeferenced_scaled.tif.npy.heir_clust2output_test.data_7989800clusters.zarr.smoke.tif.Max_Contour.tif",
"/data/nlahaye/output/Learnergy/DBN_eMAS/eMASL1B_19911_05_20190807_1817_1833_V02_georeferenced_scaled.tif.npy.heir_clust2output_test.data_7989800clusters.zarr.smoke.tif.Max_Contour.tif",
"/data/nlahaye/output/Learnergy/DBN_eMAS/eMASL1B_19912_07_20190808_1806_1821_V02_georeferenced_scaled.tif.npy.heir_clust2output_test.data_7989800clusters.zarr.smoke.tif.Max_Contour.tif",
]
 
 filename: [
"/data/nlahaye/output/Learnergy/DBN_eMAS/eMASL1B_19910_06_20190806_1815_1824_V02_Georeferenced_scaled.tif.npy.heir_clust2output_test.data_7989800clusters.zarr.smoke.FullColor.tif",
"/data/nlahaye/output/Learnergy/DBN_eMAS/eMASL1B_19911_05_20190807_1817_1833_V02_georeferenced_scaled.tif.npy.heir_clust2output_test.data_7989800clusters.zarr.smoke.FullColor.tif",
"/data/nlahaye/output/Learnergy/DBN_eMAS/eMASL1B_19912_07_20190808_1806_1821_V02_georeferenced_scaled.tif.npy.heir_clust2output_test.data_7989800clusters.zarr.smoke.FullColor.tif",
]

 mask_filename: [
"/data/nlahaye/output/Learnergy/DBN_eMAS/eMASL1B_19910_06_20190806_1815_1824_V02_Georeferenced_scaled.tif.npy.heir_clust2output_test.data_7989800clusters.zarr.smoke.tif",
"/data/nlahaye/output/Learnergy/DBN_eMAS/eMASL1B_19911_05_20190807_1817_1833_V02_georeferenced_scaled.tif.npy.heir_clust2output_test.data_7989800clusters.zarr.smoke.tif",
"/data/nlahaye/output/Learnergy/DBN_eMAS/eMASL1B_19912_07_20190808_1806_1821_V02_georeferenced_scaled.tif.npy.heir_clust2output_test.data_7989800clusters.zarr.smoke.tif",
]

##"/data/nlahaye/output/Learnergy/DBN_MASTER/MASTERL1B_1981721_05_20190809_0219_0226_V01_georeferenced.tif.npy.clustoutput_test.data_5000clusters.zarr.smoke.tif"]
 reader_type: "gtiff"
 reader_kwargs:
  None:
 
remove_singles: True
write_geotiff: True

