 
input_paths: ["/data/nlahaye/output/Learnergy/No_Data/", "/data/nlahaye/output/Learnergy/No_Data/", "/data/nlahaye/output/Learnergy/PACE_Only_Gulf_of_Mexico/"]

 
 
fname_str: "DAY.karenia_brevis_bloom.tif"
out_dir: "/data/nlahaye/output/MERGED_HAB_20250225/PACE/"
num_classes: 9
re_index: 1

gen_daily: true
gen_monthly: false

