  
input_paths: ["/data/nlahaye/output/Learnergy/MODIS_S_CA/", "/data/nlahaye/output/Learnergy//TROP_ONLY_S_CA/", "/data/nlahaye/output/Learnergy/MODIS_ONLY_S_CA/"]

 
fname_str: "karenia_brevis_bloom.tif"
out_dir: "/data/nlahaye/output/MERGED_HAB_S_CA_20240923/AQUA_MODIS/"
num_classes: 5
re_index: 1

gen_daily: true
gen_monthly: false

