
input_paths: ["/data/nlahaye/output/Learnergy/SNPP_VIIRS_S_CA/", "/data/nlahaye/output/Learnergy//TROP_ONLY_S_CA/", "/data/nlahaye/output/Learnergy/SNPP_VIIRS_ONLY_S_CA/"]
 
fname_str: "karenia_brevis_bloom.tif"
out_dir: "/data/nlahaye/output/MERGED_HAB_S_CA_20240923/SNPP_VIIRS/"
num_classes: 5
re_index: 1

gen_daily: false
gen_monthly: true


dirname: "/data/nlahaye/output/MERGED_HAB_S_CA_20240923/SNPP_VIIRS/"
max_dqi: 2
max_class: 5

