  
input_paths: ["/data/nlahaye/output/Learnergy/No_Data/", "/data/nlahaye/output/Learnergy/No_Data/", "/data/nlahaye/output/Learnergy/PACE_Only_S_CA/"]

 
fname_str: "pseudo_nitzschia_seriata_bloom"
out_dir: "/data/nlahaye/output/MERGED_HAB_20250225_S_CA/PACE/"
num_classes: 9
re_index: 3

gen_daily: false
gen_monthly: true


dirname: "/data/nlahaye/output/MERGED_HAB_20250225_S_CA/PACE/"
max_dqi: 2
max_class: 5

