 
input_paths: ["/data/nlahaye/output/Learnergy/S3A_Gulf_of_Mexico/", "/data/nlahaye/output/Learnergy//TROP_ONLY_Gulf_of_Mexico/", "/data/nlahaye/output/Learnergy/S3A_Only_Gulf_of_Mexico/"]

 
 
fname_str: "DAY.karenia_brevis_bloom.tif"
out_dir: "/data/nlahaye/output/MERGED_HAB_20250225/S3A/"
num_classes: 6
re_index: 1

gen_daily: true
gen_monthly: false

