 
input_paths: ["/data/nlahaye/output/Learnergy/S3B_S_CA/", "/data/nlahaye/output/Learnergy//TROP_ONLY_S_CA/", "/data/nlahaye/output/Learnergy/S3B_Only_S_CA/"]

 
 
fname_str: "karenia_brevis_bloom"
out_dir: "/data/nlahaye/output/MERGED_HAB_20250225_S_CA/S3B/"
num_classes: 9
re_index: 1

gen_daily: false
gen_monthly: true


dirname: "/data/nlahaye/output/MERGED_HAB_20250225_S_CA/S3B/"
max_dqi: 2
max_class: 5


