 
input_paths: ["/data/nlahaye/output/Learnergy/S3A_S_CA/", "/data/nlahaye/output/Learnergy//TROP_ONLY_S_CA/", "/data/nlahaye/output/Learnergy/S3A_Only_S_CA/"]

 
 
fname_str: "pseudo_nitzschia_seriata_bloom"
out_dir: "/data/nlahaye/output/MERGED_HAB_20250225_S_CA/S3A/"
num_classes: 9
re_index: 2

gen_daily: false
gen_monthly: true


dirname: "/data/nlahaye/output/MERGED_HAB_20250225_S_CA/S3A/"
max_dqi: 2
max_class: 5
