
input_paths: ["/data/nlahaye/output/Learnergy/SNPP_VIIRS_Gulf_of_Mexico/", "/data/nlahaye/output/Learnergy//TROP_ONLY_Gulf_of_Mexico/", "/data/nlahaye/output/Learnergy/SNPP_VIIRS_ONLY_Gulf_of_Mexico/"]
 
fname_str: "karenia_brevis_bloom"
out_dir: "/data/nlahaye/output/MERGED_HAB_20250225/SNPP_VIIRS/"
num_classes: 9
re_index: 1

gen_daily: false
gen_monthly: true


dirname: "/data/nlahaye/output/MERGED_HAB_20250225/SNPP_VIIRS/"
max_dqi: 2
max_class: 5

