 
input_paths: ["/data/nlahaye/output/Learnergy/S3B_Gulf_of_Mexico/", "/data/nlahaye/output/Learnergy//TROP_ONLY_Gulf_of_Mexico/", "/data/nlahaye/output/Learnergy/S3B_Only_Gulf_of_Mexico/"]

 
 
fname_str: "karenia_brevis_bloom.tif"
out_dir: "/data/nlahaye/output/MERGED_HAB_20240818/S3B/"
num_classes: 5
re_index: 1

gen_daily: true
gen_monthly: false

