  
input_paths: ["/data/nlahaye/output/Learnergy/MODIS_Gulf_of_Mexico/", "/data/nlahaye/output/Learnergy//TROP_ONLY_Gulf_of_Mexico/", "/data/nlahaye/output/Learnergy/MODIS_ONLY_Gulf_of_Mexico/"]

 
fname_str: "karenia_brevis_bloom.tif"
out_dir: "/data/nlahaye/output/MERGED_HAB_20240818/AQUA_MODIS/"
num_classes: 5
re_index: 1

gen_daily: true
gen_monthly: false

