 
input_paths: ["/data/nlahaye/output/Learnergy/S3A_S_CA/", "/data/nlahaye/output/Learnergy//TROP_ONLY_S_CA/", "/data/nlahaye/output/Learnergy/S3A_Only_S_CA/"]

 
 
fname_str: "DAY.karenia_brevis_bloom.tif"
out_dir: "/data/nlahaye/output/MERGED_HAB_20250225_S_CA/S3A/"
num_classes: 9
re_index: 1

gen_daily: true
gen_monthly: false

