 
input_paths: ["/data/nlahaye/output/Learnergy/No_Data/", "/data/nlahaye/output/Learnergy/No_Data/", "/data/nlahaye/output/Learnergy/PACE_Only_S_CA/"]

 
 
fname_str: "DAY.alexandrium_bloom.tif"
out_dir: "/data/nlahaye/output/MERGED_HAB_20250225_S_CA/PACE/"
num_classes: 9
re_index: 5

gen_daily: true
gen_monthly: false

