

data:
 contour_fnames: [
"/data/nlahaye/FIREX_AQ_DATA/AirMSPI_Sweep/contoured_binary_segmentation/AirMSPI_ER2_GRP_TERRAIN_20190816_213258Z_AZ-Page_SWPF_F01_V006.smoke.tif",
"/data/nlahaye/FIREX_AQ_DATA/AirMSPI_Sweep/contoured_binary_segmentation/AirMSPI_ER2_GRP_TERRAIN_20190816_214015Z_AZ-MarbleCanyon_SWPA_F01_V006.smoke.tif",
"/data/nlahaye/FIREX_AQ_DATA/AirMSPI_Sweep/contoured_binary_segmentation/AirMSPI_ER2_GRP_TERRAIN_20190816_214104Z_AZ-MarbleCanyon_SWPF_F01_V006.smoke.tif",
"/data/nlahaye/FIREX_AQ_DATA/AirMSPI_Sweep/contoured_binary_segmentation/AirMSPI_ER2_GRP_TERRAIN_20190816_220323Z_AZ-AshFork_SWPF_F01_V006.smoke.tif",
"/data/nlahaye/FIREX_AQ_DATA/AirMSPI_Sweep/contoured_binary_segmentation/AirMSPI_ER2_GRP_TERRAIN_20190816_223217Z_AZ-AshFork_SWPF_F01_V006.smoke.tif",
"/data/nlahaye/FIREX_AQ_DATA/AirMSPI_Sweep/contoured_binary_segmentation/AirMSPI_ER2_GRP_TERRAIN_20190816_224003Z_AZ-AshFork_SWPA_F01_V006.smoke.tif",
"/data/nlahaye/FIREX_AQ_DATA/AirMSPI_Sweep/contoured_binary_segmentation/AirMSPI_ER2_GRP_TERRAIN_20190816_224053Z_AZ-AshFork_SWPF_F01_V006.smoke.tif",
"/data/nlahaye/FIREX_AQ_DATA/AirMSPI_Sweep/contoured_binary_segmentation/AirMSPI_ER2_GRP_TERRAIN_20190816_230732Z_AZ-YavapaiCounty_SWPF_F01_V006.smoke.tif",
"/data/nlahaye/FIREX_AQ_DATA/AirMSPI_Sweep/contoured_binary_segmentation/AirMSPI_ER2_GRP_TERRAIN_20190816_231520Z_AZ-AshFork_SWPA_F01_V006.smoke.tif",
"/data/nlahaye/FIREX_AQ_DATA/AirMSPI_Sweep/contoured_binary_segmentation/AirMSPI_ER2_GRP_TERRAIN_20190816_231609Z_AZ-Paulden_SWPF_F01_V006.smoke.tif",
"/data/nlahaye/FIREX_AQ_DATA/AirMSPI_Sweep/contoured_binary_segmentation/AirMSPI_ER2_GRP_TERRAIN_20190816_234233Z_AZ-AshFork_SWPF_F01_V006.smoke.tif",
"/data/nlahaye/FIREX_AQ_DATA/AirMSPI_Sweep/contoured_binary_segmentation/AirMSPI_ER2_GRP_TERRAIN_20190816_235034Z_AZ-Williams_SWPA_F01_V006.smoke.tif",
"/data/nlahaye/FIREX_AQ_DATA/AirMSPI_Sweep/contoured_binary_segmentation/AirMSPI_ER2_GRP_TERRAIN_20190816_235123Z_AZ-Paulden_SWPF_F01_V006.smoke.tif",
]

 clust_fnames: [
"/data/nlahaye/FIREX_AQ_DATA/AirMSPI_Sweep/context_free_segmentation/AirMSPI_ER2_GRP_TERRAIN_20190816_213258Z_AZ-Page_SWPF_F01_V006.context_free_seg.tif",
"/data/nlahaye/FIREX_AQ_DATA/AirMSPI_Sweep/context_free_segmentation/AirMSPI_ER2_GRP_TERRAIN_20190816_214015Z_AZ-MarbleCanyon_SWPA_F01_V006.context_free_seg.tif",
"/data/nlahaye/FIREX_AQ_DATA/AirMSPI_Sweep/context_free_segmentation/AirMSPI_ER2_GRP_TERRAIN_20190816_214104Z_AZ-MarbleCanyon_SWPF_F01_V006.context_free_seg.tif",
"/data/nlahaye/FIREX_AQ_DATA/AirMSPI_Sweep/context_free_segmentation/AirMSPI_ER2_GRP_TERRAIN_20190816_220323Z_AZ-AshFork_SWPF_F01_V006.context_free_seg.tif",
"/data/nlahaye/FIREX_AQ_DATA/AirMSPI_Sweep/context_free_segmentation/AirMSPI_ER2_GRP_TERRAIN_20190816_223217Z_AZ-AshFork_SWPF_F01_V006.context_free_seg.tif",
"/data/nlahaye/FIREX_AQ_DATA/AirMSPI_Sweep/context_free_segmentation/AirMSPI_ER2_GRP_TERRAIN_20190816_224003Z_AZ-AshFork_SWPA_F01_V006.context_free_seg.tif",
"/data/nlahaye/FIREX_AQ_DATA/AirMSPI_Sweep/context_free_segmentation/AirMSPI_ER2_GRP_TERRAIN_20190816_224053Z_AZ-AshFork_SWPF_F01_V006.context_free_seg.tif",
"/data/nlahaye/FIREX_AQ_DATA/AirMSPI_Sweep/context_free_segmentation/AirMSPI_ER2_GRP_TERRAIN_20190816_230732Z_AZ-YavapaiCounty_SWPF_F01_V006.context_free_seg.tif",
"/data/nlahaye/FIREX_AQ_DATA/AirMSPI_Sweep/context_free_segmentation/AirMSPI_ER2_GRP_TERRAIN_20190816_231520Z_AZ-AshFork_SWPA_F01_V006.context_free_seg.tif",
"/data/nlahaye/FIREX_AQ_DATA/AirMSPI_Sweep/context_free_segmentation/AirMSPI_ER2_GRP_TERRAIN_20190816_231609Z_AZ-Paulden_SWPF_F01_V006.context_free_seg.tif",
"/data/nlahaye/FIREX_AQ_DATA/AirMSPI_Sweep/context_free_segmentation/AirMSPI_ER2_GRP_TERRAIN_20190816_234233Z_AZ-AshFork_SWPF_F01_V006.context_free_seg.tif",
"/data/nlahaye/FIREX_AQ_DATA/AirMSPI_Sweep/context_free_segmentation/AirMSPI_ER2_GRP_TERRAIN_20190816_235034Z_AZ-Williams_SWPA_F01_V006.context_free_seg.tif",
"/data/nlahaye/FIREX_AQ_DATA/AirMSPI_Sweep/context_free_segmentation/AirMSPI_ER2_GRP_TERRAIN_20190816_235123Z_AZ-Paulden_SWPF_F01_V006.context_free_seg.tif",
]
