clusters: 120000
clusters_dir: Z:\2026\Summer\Southern California Bight HABs\validation_testrun/PACE_OCI
end_date: '2025-04-01'
global_max: 10000000
input_file_type: daily
radius_degrees:
- 0.09
ranges:
- 0
- 1000
- 10000
- 100000
- 1000000
- 10000000
- 100000000
start_date: '2024-03-06'
use_key: Total_Phytoplankton
xl_fname: Z:\2026\Summer\Southern California Bight HABs\in_situ_nick_data\combined_full.csv
