
gen_from_geotiffs: False

data:
 clust_reader_type: "zarr_to_numpy"
 reader_kwargs:
   no_arg: "no_arg" 
 subset_inds: [[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[], [],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]]
 create_separate: False

 
 gtiff_data: [
"/mnt/data/PV_Mapping/gambia_6_band_building_clipped.tif",
]



 cluster_fnames: [
"/mnt/data/DBN_PV_MAPPING_WIDE_CLIPPED/gambia_6_band_building_clipped.tif.no_heir.clust.data_784clusters.zarr"
]

context: 
 apply_context: True
 clusters: [[0.478, 0.573]] 
 

 name: ["PV_Map"]
 compare_truth: false
 generate_union: False

