
gen_from_geotiffs: False

data:
 clust_reader_type: "gtiff"
 reader_kwargs:
   no_arg: "no_arg" 
 subset_inds: [[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[], [],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]]
 create_separate: False

 
 gtiff_data: [
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_0_s1_s2_ls8.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_10_s1_s2_ls8.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_11_s1_s2_ls8.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_12_s1_s2_ls8.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_13_s1_s2_ls8.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_14_s1_s2_ls8.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_15_s1_s2_ls8.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_1_s1_s2_ls8.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_2_s1_s2_ls8.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_3_s1_s2_ls8.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_4_s1_s2_ls8.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_5_s1_s2_ls8.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_6_s1_s2_ls8.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_7_s1_s2_ls8.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_8_s1_s2_ls8.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_9_s1_s2_ls8.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/urban_small_road_clipped_s1_s2_ls8.tif",
]



 cluster_fnames: [
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_ROAD_CLIP_S1/large_urban_gambia_clipped_0_s1_s2_ls8.tif.clust.data_78994clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_ROAD_CLIP_S1/large_urban_gambia_clipped_10_s1_s2_ls8.tif.clust.data_79799clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_ROAD_CLIP_S1/large_urban_gambia_clipped_11_s1_s2_ls8.tif.clust.data_79799clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_ROAD_CLIP_S1/large_urban_gambia_clipped_12_s1_s2_ls8.tif.clust.data_79799clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_ROAD_CLIP_S1/large_urban_gambia_clipped_13_s1_s2_ls8.tif.clust.data_79799clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_ROAD_CLIP_S1/large_urban_gambia_clipped_14_s1_s2_ls8.tif.clust.data_79799clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_ROAD_CLIP_S1/large_urban_gambia_clipped_15_s1_s2_ls8.tif.clust.data_79799clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_ROAD_CLIP_S1/large_urban_gambia_clipped_1_s1_s2_ls8.tif.clust.data_79799clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_ROAD_CLIP_S1/large_urban_gambia_clipped_2_s1_s2_ls8.tif.clust.data_79799clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_ROAD_CLIP_S1/large_urban_gambia_clipped_3_s1_s2_ls8.tif.clust.data_79799clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_ROAD_CLIP_S1/large_urban_gambia_clipped_4_s1_s2_ls8.tif.clust.data_79799clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_ROAD_CLIP_S1/large_urban_gambia_clipped_5_s1_s2_ls8.tif.clust.data_79799clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_ROAD_CLIP_S1/large_urban_gambia_clipped_6_s1_s2_ls8.tif.clust.data_79799clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_ROAD_CLIP_S1/large_urban_gambia_clipped_7_s1_s2_ls8.tif.clust.data_79799clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_ROAD_CLIP_S1/large_urban_gambia_clipped_8_s1_s2_ls8.tif.clust.data_79799clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_ROAD_CLIP_S1/large_urban_gambia_clipped_9_s1_s2_ls8.tif.clust.data_79799clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_ROAD_CLIP_S1/urban_small_road_clipped_s1_s2_ls8.tif.clust.data_78998clusters.zarr",
]

context: 
 apply_context: True
 clusters: [47.761, 30.945, 76.13, 3.688, 3.625, 3.684, 3.614, 3.616, 3.604, 3.608, 3.677, 3.63, 3.642, 68.975, 68.488, 30.958, 10.909, 10.986, 10.947, 10.962, 10.971, 10.917, 10.974, 71.441, 71.406, 71.473, 10.918, 10.961, 10.949, 10.93, 10.933, 10.97, 10.903, 10.913, 10.923, 10.99, 71.439, 71.472, 71.469, 71.492, 3.624, 3.659, 30.965, 40.435, 40.426, 40.464, 40.492, 47.719, 47.799, 47.731, 47.716, 47.739, 74.247, 35.992, 35.949, 64.305, 64.319, 68.44, 68.425, 68.493, 68.498, 68.441] 
         
         
 
 background_class: 2
 name: "PV_Map"
 compare_truth: false
 generate_union: False

