
gen_from_geotiffs: False

data:
 clust_reader_type: "gtiff"
 reader_kwargs:
   no_arg: "no_arg" 
 subset_inds: [[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[], [],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]]
 create_separate: False

 cluster_fnames: [
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_WIDE_ROAD_CLIP/large_urban_gambia_clipped_0.tif.clust.data_79199clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_WIDE_ROAD_CLIP/large_urban_gambia_clipped_10.tif.clust.data_79199clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_WIDE_ROAD_CLIP/large_urban_gambia_clipped_11.tif.clust.data_79199clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_WIDE_ROAD_CLIP/large_urban_gambia_clipped_12.tif.clust.data_79199clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_WIDE_ROAD_CLIP/large_urban_gambia_clipped_13.tif.clust.data_79199clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_WIDE_ROAD_CLIP/large_urban_gambia_clipped_14.tif.clust.data_79199clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_WIDE_ROAD_CLIP/large_urban_gambia_clipped_15.tif.clust.data_79199clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_WIDE_ROAD_CLIP/large_urban_gambia_clipped_1.tif.clust.data_79199clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_WIDE_ROAD_CLIP/large_urban_gambia_clipped_2.tif.clust.data_79199clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_WIDE_ROAD_CLIP/large_urban_gambia_clipped_3.tif.clust.data_79199clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_WIDE_ROAD_CLIP/large_urban_gambia_clipped_4.tif.clust.data_79199clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_WIDE_ROAD_CLIP/large_urban_gambia_clipped_5.tif.clust.data_79199clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_WIDE_ROAD_CLIP/large_urban_gambia_clipped_6.tif.clust.data_79199clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_WIDE_ROAD_CLIP/large_urban_gambia_clipped_7.tif.clust.data_79199clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_WIDE_ROAD_CLIP/large_urban_gambia_clipped_8.tif.clust.data_79199clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_WIDE_ROAD_CLIP/large_urban_gambia_clipped_9.tif.clust.data_79199clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_WIDE_ROAD_CLIP/urban_small_road_clipped.tif.clust.data_79199clusters.zarr",
]


 gtiff_data: [
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_0.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_10.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_11.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_12.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_13.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_14.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_15.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_1.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_2.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_3.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_4.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_5.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_6.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_7.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_8.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_9.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/urban_small_road_clipped.tif",
]

context: 
 apply_context: False
 clusters: [
]
 name: ["fire", "smoke"]
 compare_truth: False
 generate_union: False
 background_class: -1
