
gen_from_geotiffs: False

data:
 clust_reader_type: "gtiff"
 reader_kwargs:
   no_arg: "no_arg" 
 subset_inds: [[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[], [],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]]
 create_separate: False

 cluster_fnames: [
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_ROAD_CLIP_S1/large_urban_gambia_clipped_0_s1.tif.clust.data_78099clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_ROAD_CLIP_S1/large_urban_gambia_clipped_10_s1.tif.clust.data_78099clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_ROAD_CLIP_S1/large_urban_gambia_clipped_11_s1.tif.clust.data_78099clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_ROAD_CLIP_S1/large_urban_gambia_clipped_12_s1.tif.clust.data_78099clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_ROAD_CLIP_S1/large_urban_gambia_clipped_13_s1.tif.clust.data_78099clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_ROAD_CLIP_S1/large_urban_gambia_clipped_14_s1.tif.clust.data_78099clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_ROAD_CLIP_S1/large_urban_gambia_clipped_15_s1.tif.clust.data_78099clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_ROAD_CLIP_S1/large_urban_gambia_clipped_1_s1.tif.clust.data_78099clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_ROAD_CLIP_S1/large_urban_gambia_clipped_2_s1.tif.clust.data_78099clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_ROAD_CLIP_S1/large_urban_gambia_clipped_3_s1.tif.clust.data_78099clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_ROAD_CLIP_S1/large_urban_gambia_clipped_4_s1.tif.clust.data_78099clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_ROAD_CLIP_S1/large_urban_gambia_clipped_5_s1.tif.clust.data_78099clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_ROAD_CLIP_S1/large_urban_gambia_clipped_6_s1.tif.clust.data_78099clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_ROAD_CLIP_S1/large_urban_gambia_clipped_7_s1.tif.clust.data_78099clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_ROAD_CLIP_S1/large_urban_gambia_clipped_8_s1.tif.clust.data_78099clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_ROAD_CLIP_S1/large_urban_gambia_clipped_9_s1.tif.clust.data_78099clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_PV_MAPPING_ROAD_CLIP_S1/urban_small_road_clipped_s1.tif.clust.data_78099clusters.zarr",
]


 gtiff_data: [
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_0.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_10.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_11.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_12.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_13.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_14.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_15.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_1.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_2.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_3.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_4.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_5.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_6.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_7.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_8.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/large_urban_gambia_clipped_9.tif",
"/data/nlahaye/remoteSensing/PV_Mapping/urban_small_road_clipped.tif",
]

context: 
 apply_context: False
 clusters: [
]
 name: ["fire", "smoke"]
 compare_truth: False
 generate_union: False
 background_class: -1
