
truth_maps: [
#"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_06_20190806_1815_1824_V03_fire.tif",
##"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_08_20190806_1834_1846_V03_fire.tif", ##
#"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_10_20190806_1858_1910_V03_fire.tif",
##"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_14_20190806_1926_1929_V03_fire.tif", ##
##"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_16_20190806_1941_1956_V03_fire.tif", ##
##"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_17_20190806_2000_2010_V03_fire.tif", ##
##"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_18_20190806_2018_2031_V03_fire.tif", ##
##"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_19_20190806_2035_2048_V03_fire.tif", ##
#"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_20_20190806_2052_2106_V03_fire.tif",
##"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_21_20190806_2111_2125_V03_fire.tif", ##
##"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19911_05_20190807_1817_1833_V03_fire.tif", ##
##"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19911_08_20190807_1928_1942_V03_fire.tif", ##
#"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19911_09_20190807_1947_2002_V03_fire.tif",
#"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19911_10_20190807_2004_2016_V03_fire.tif",
##"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19911_11_20190807_2021_2035_V03_fire.tif", ##
##"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19911_12_20190807_2039_2051_V03_fire.tif", ##

#"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19912_07_20190808_1806_1821_V03_fire.tif",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19915_17_20190815_2122_2143_V03_fire.tif",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19915_21_20190815_2216_2225_V03_fire.tif",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19915_22_20190815_2231_2241_V03_fire.tif",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19915_23_20190815_2247_2256_V03_fire.tif",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19916_10_20190816_2201_2214_V03_fire.tif",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19916_11_20190816_2219_2234_V03_fire.tif",
##"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19916_12_20190816_2238_2252_V03_fire.tif",
##"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19916_13_20190816_2255_2310_V03_fire.tif",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19916_14_20190816_2313_2327_V03_fire.tif",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19916_15_20190816_2330_2345_V03_fire.tif",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19916_16_20190816_2349_0002_V03_fire.tif",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19916_17_20190817_0006_0020_V03_fire.tif",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19916_18_20190817_0023_0036_V03_fire.tif",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19916_19_20190817_0040_0054_V03_fire.tif",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19916_20_20190817_0057_0108_V03_fire.tif",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19919_13_20190821_2324_2339_V03_fire.tif",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19919_14_20190821_2343_2356_V03_fire.tif",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19919_17_20190822_0036_0104_V03_fire.tif",
]

sit_fuse_maps: [
#"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_06_20190806_1815_1824_V03.tif.clust.data_78199clusters.zarr.full_geo.tif.fire.tif.Contours.tif",
##"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_08_20190806_1834_1846_V03.tif.clust.data_78199clusters.zarr.full_geo.tif.fire.tif.Contours.tif", ##
#"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_10_20190806_1858_1910_V03.tif.clust.data_78993clusters.zarr.full_geo.tif.fire.tif.Contours.tif",
##"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_14_20190806_1926_1929_V03.tif.clust.data_78198clusters.zarr.full_geo.tif.fire.tif.Contours.tif", ##
##"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_16_20190806_1941_1956_V03.tif.clust.data_78999clusters.zarr.full_geo.tif.fire.tif.Contours.tif", ##
##"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_17_20190806_2000_2010_V03.tif.clust.data_78999clusters.zarr.full_geo.tif.fire.tif.Contours.tif", ##
##"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_18_20190806_2018_2031_V03.tif.clust.data_78999clusters.zarr.full_geo.tif.fire.tif.Contours.tif", ##
##"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_19_20190806_2035_2048_V03.tif.clust.data_78999clusters.zarr.full_geo.tif.fire.tif.Contours.tif", ##
#"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_20_20190806_2052_2106_V03.tif.clust.data_78999clusters.zarr.full_geo.tif.fire.tif.Contours.tif",
##"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_21_20190806_2111_2125_V03.tif.clust.data_78999clusters.zarr.full_geo.tif.fire.tif.Contours.tif", ##
##"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19911_05_20190807_1817_1833_V03.tif.clust.data_78998clusters.zarr.full_geo.tif.fire.tif.Contours.tif", ##
##"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19911_08_20190807_1928_1942_V03.tif.clust.data_78991clusters.zarr.full_geo.tif.fire.tif.Contours.tif", ##
#"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19911_09_20190807_1947_2002_V03.tif.clust.data_78999clusters.zarr.full_geo.tif.fire.tif.Contours.tif",
#"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19911_10_20190807_2004_2016_V03.tif.clust.data_78999clusters.zarr.full_geo.tif.fire.tif.Contours.tif",
##"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19911_11_20190807_2021_2035_V03.tif.clust.data_78999clusters.zarr.full_geo.tif.fire.tif.Contours.tif", ##
##"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19911_12_20190807_2039_2051_V03.tif.clust.data_78999clusters.zarr.full_geo.tif.fire.tif.Contours.tif", ##
 
#"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19912_07_20190808_1806_1821_V03.tif.clust.data_78999clusters.zarr.full_geo.tif.fire.tif.Contours.tif",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19915_17_20190815_2122_2143_V03.tif.clust.data_78999clusters.zarr.full_geo.tif.fire.tif.Contours.tif",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19915_21_20190815_2216_2225_V03.tif.clust.data_78999clusters.zarr.full_geo.tif.fire.tif.Contours.tif",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19915_22_20190815_2231_2241_V03.tif.clust.data_78999clusters.zarr.full_geo.tif.fire.tif.Contours.tif",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19915_23_20190815_2247_2256_V03.tif.clust.data_78999clusters.zarr.full_geo.tif.fire.tif.Contours.tif",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19916_10_20190816_2201_2214_V03.tif.clust.data_78999clusters.zarr.full_geo.tif.fire.tif.Contours.tif",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19916_11_20190816_2219_2234_V03.tif.clust.data_78999clusters.zarr.full_geo.tif.fire.tif.Contours.tif",
##"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19916_12_20190816_2238_2252_V03.tif.clust.data_78999clusters.zarr.full_geo.tif.fire.tif.Contours.tif",
##"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19916_13_20190816_2255_2310_V03.tif.clust.data_78999clusters.zarr.full_geo.tif.fire.tif.Contours.tif",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19916_14_20190816_2313_2327_V03.tif.clust.data_78999clusters.zarr.full_geo.tif.fire.tif.Contours.tif",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19916_15_20190816_2330_2345_V03.tif.clust.data_78995clusters.zarr.full_geo.tif.fire.tif.Contours.tif",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19916_16_20190816_2349_0002_V03.tif.clust.data_78996clusters.zarr.full_geo.tif.fire.tif.Contours.tif",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19916_17_20190817_0006_0020_V03.tif.clust.data_78995clusters.zarr.full_geo.tif.fire.tif.Contours.tif",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19916_18_20190817_0023_0036_V03.tif.clust.data_78996clusters.zarr.full_geo.tif.fire.tif.Contours.tif",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19916_19_20190817_0040_0054_V03.tif.clust.data_78917clusters.zarr.full_geo.tif.fire.tif.Contours.tif",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19916_20_20190817_0057_0108_V03.tif.clust.data_72768clusters.zarr.full_geo.tif.fire.tif.Contours.tif",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19919_13_20190821_2324_2339_V03.tif.clust.data_78999clusters.zarr.full_geo.tif.fire.tif.Contours.tif",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19919_14_20190821_2343_2356_V03.tif.clust.data_78999clusters.zarr.full_geo.tif.fire.tif.Contours.tif",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19919_17_20190822_0036_0104_V03.tif.clust.data_78999clusters.zarr.full_geo.tif.fire.tif.Contours.tif",

]
