
truth_maps: [
#"/data/nlahaye/SIT_FUSE_Geo/AVIRIS_REDO/aviris_20190806_p00r09_smoke.tif",
##"/data/nlahaye/SIT_FUSE_Geo/AVIRIS_REDO/aviris_20190806_p00r10_smoke.tif",
#"/data/nlahaye/SIT_FUSE_Geo/AVIRIS_REDO/aviris_20190806_p00r11_smoke.tif",
##"/data/nlahaye/SIT_FUSE_Geo/AVIRIS_REDO/aviris_20190806_p00r13_smoke.tif",
#"/data/nlahaye/SIT_FUSE_Geo/AVIRIS_REDO/aviris_20190806_p00r14_smoke.tif",
#"/data/nlahaye/SIT_FUSE_Geo/AVIRIS_REDO/aviris_20190806_p00r15_smoke.tif",
##"/data/nlahaye/SIT_FUSE_Geo/AVIRIS_REDO/aviris_20190806_p00r16_smoke.tif",
#"/data/nlahaye/SIT_FUSE_Geo/AVIRIS_REDO/aviris_20190806_p00r17_smoke.tif",
##"/data/nlahaye/SIT_FUSE_Geo/AVIRIS_REDO/aviris_20190806_p00r18_smoke.tif",
#"/data/nlahaye/SIT_FUSE_Geo/AVIRIS_REDO/aviris_20190807_p00r11_smoke.tif",
#"/data/nlahaye/SIT_FUSE_Geo/AVIRIS_REDO/aviris_20190807_p00r12_smoke.tif",
##"/data/nlahaye/SIT_FUSE_Geo/AVIRIS_REDO/aviris_20190807_p00r13_smoke.tif",
##"/data/nlahaye/SIT_FUSE_Geo/AVIRIS_REDO/aviris_20190807_p00r14_smoke.tif",
"/data/nlahaye/SIT_FUSE_Geo/AVIRIS_REDO/aviris_20190821_p00r23_smoke.tif",
##"/data/nlahaye/SIT_FUSE_Geo/AVIRIS_REDO/aviris_20190821_p00r24_smoke.tif",
##"/data/nlahaye/SIT_FUSE_Geo/AVIRIS_REDO/aviris_20190821_p00r25_smoke.tif",
##"/data/nlahaye/SIT_FUSE_Geo/AVIRIS_REDO/aviris_20190821_p00r26_smoke.tif",
"/data/nlahaye/SIT_FUSE_Geo/AVIRIS_REDO/aviris_20190821_p00r27_smoke.tif",
]

sit_fuse_maps: [
#"/data/nlahaye/SIT_FUSE_Geo/AVIRIS_REDO/4326/aviris_20190806_p00r09.tif.clust.data_191199clusters.zarr.full_geo.smoke.tif.Contours.tif",
##"/data/nlahaye/SIT_FUSE_Geo/AVIRIS_REDO/4326/aviris_20190806_p00r10.tif.clust.data_191198clusters.zarr.full_geo.smoke.tif.Contours.tif",
#"/data/nlahaye/SIT_FUSE_Geo/AVIRIS_REDO/4326/aviris_20190806_p00r11.tif.clust.data_191199clusters.zarr.full_geo.smoke.tif.Contours.tif",
##"/data/nlahaye/SIT_FUSE_Geo/AVIRIS_REDO/4326/aviris_20190806_p00r13.tif.clust.data_191198clusters.zarr.full_geo.smoke.tif.Contours.tif",
#"/data/nlahaye/SIT_FUSE_Geo/AVIRIS_REDO/4326/aviris_20190806_p00r14.tif.clust.data_191199clusters.zarr.full_geo.smoke.tif.Contours.tif",
#"/data/nlahaye/SIT_FUSE_Geo/AVIRIS_REDO/4326/aviris_20190806_p00r15.tif.clust.data_191199clusters.zarr.full_geo.smoke.tif.Contours.tif",
##"/data/nlahaye/SIT_FUSE_Geo/AVIRIS_REDO/4326/aviris_20190806_p00r16.tif.clust.data_191199clusters.zarr.full_geo.smoke.tif.Contours.tif",
#"/data/nlahaye/SIT_FUSE_Geo/AVIRIS_REDO/4326/aviris_20190806_p00r17.tif.clust.data_191199clusters.zarr.full_geo.smoke.tif.Contours.tif",
#"/data/nlahaye/SIT_FUSE_Geo/AVIRIS_REDO/4326/aviris_20190806_p00r18.tif.clust.data_191199clusters.zarr.full_geo.fire.tif.Contours.tif",
#"/data/nlahaye/SIT_FUSE_Geo/AVIRIS_REDO/4326/aviris_20190807_p00r11.tif.clust.data_191199clusters.zarr.full_geo.smoke.tif.Contours.tif",
#"/data/nlahaye/SIT_FUSE_Geo/AVIRIS_REDO/4326/aviris_20190807_p00r12.tif.clust.data_191199clusters.zarr.full_geo.smoke.tif.Contours.tif",
##"/data/nlahaye/SIT_FUSE_Geo/AVIRIS_REDO/4326/aviris_20190807_p00r13.tif.clust.data_191199clusters.zarr.full_geo.smoke.tif.Contours.tif",
##"/data/nlahaye/SIT_FUSE_Geo/AVIRIS_REDO/4326/aviris_20190807_p00r14.tif.clust.data_191199clusters.zarr.full_geo.smoke.tif.Contours.tif",
"/data/nlahaye/SIT_FUSE_Geo/AVIRIS_REDO/4326/aviris_20190821_p00r23.tif.clust.data_191191clusters.zarr.full_geo.smoke.tif.Contours.tif",
##"/data/nlahaye/SIT_FUSE_Geo/AVIRIS_REDO/4326/aviris_20190821_p00r24.tif.clust.data_191190clusters.zarr.full_geo.smoke.tif.Contours.tif",
##"/data/nlahaye/SIT_FUSE_Geo/AVIRIS_REDO/4326/aviris_20190821_p00r25.tif.clust.data_191181clusters.zarr.full_geo.smoke.tif.Contours.tif",
##"/data/nlahaye/SIT_FUSE_Geo/AVIRIS_REDO/4326/aviris_20190821_p00r26.tif.clust.data_181920clusters.zarr.full_geo.smoke.tif.Contours.tif",
"/data/nlahaye/SIT_FUSE_Geo/AVIRIS_REDO/4326/aviris_20190821_p00r27.tif.clust.data_191186clusters.zarr.full_geo.smoke.tif.Contours.tif",

]
