
truth_maps: [
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_06_20190806_1815_1824_V03_smoke.tif",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_21_20190806_2111_2125_V03_smoke.tif",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_17_20190806_2000_2010_V03_smoke.tif",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19910_21_20190806_2111_2125_V03_smoke.tif",

"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19911_12_20190807_2039_2051_V03_smoke.tif", ##

"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19912_07_20190808_1806_1821_V03_smoke.tif",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19912_07_20190808_1806_1821_V03_smoke.tif",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19912_07_20190808_1806_1821_V03_smoke.tif",
"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19912_07_20190808_1806_1821_V03_smoke.tif",

#"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19915_17_20190815_2122_2143_V03_smoke.tif",
#"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19915_21_20190815_2216_2225_V03_smoke.tif",
#"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19915_22_20190815_2231_2241_V03_smoke.tif",
#"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19915_23_20190815_2247_2256_V03_smoke.tif",
#"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19916_10_20190816_2201_2214_V03_smoke.tif",
#"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19916_11_20190816_2219_2234_V03_smoke.tif",
#"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19916_12_20190816_2238_2252_V03_smoke.tif",
#"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19916_13_20190816_2255_2310_V03_smoke.tif",
#"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19916_14_20190816_2313_2327_V03_smoke.tif",
#"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19916_15_20190816_2330_2345_V03_smoke.tif",
#"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19916_16_20190816_2349_0002_V03_smoke.tif",
#"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19916_17_20190817_0006_0020_V03_smoke.tif",
#"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19916_18_20190817_0023_0036_V03_smoke.tif",
#"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19916_19_20190817_0040_0054_V03_smoke.tif",
#"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19916_20_20190817_0057_0108_V03_smoke.tif",
#"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19919_13_20190821_2324_2339_V03_smoke.tif",
#"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19919_14_20190821_2343_2356_V03_smoke.tif",
#"/data/nlahaye/SIT_FUSE_Geo/eMAS_REDO/eMASL1B_19919_17_20190822_0036_0104_V03_smoke.tif",

]

sit_fuse_maps: [
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/noaa20_viirs_i01_20190806_191800_wgs84_fit.tif.clust.data_79769clusters.zarr.full_geo.smoke.tif.Contours.tif",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/noaa20_viirs_i01_20190806_210000_wgs84_fit.tif.clust.data_79799clusters.zarr.full_geo.smoke.tif.Contours.tif",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/npp_viirs_i01_20190806_200600_wgs84_fit.tif.clust.data_79788clusters.zarr.full_geo.smoke.tif.Contours.tif",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/npp_viirs_i01_20190806_214800_wgs84_fit.tif.clust.data_79799clusters.zarr.full_geo.smoke.tif.Contours.tif",

"/data/nlahaye/SIT_FUSE_Geo/VIIRS/npp_viirs_i01_20190807_213000_wgs84_fit.tif.clust.data_79797clusters.zarr.full_geo.smoke.tif.Contours.tif",

"/data/nlahaye/SIT_FUSE_Geo/VIIRS/npp_viirs_i01_20190808_193000_wgs84_fit.tif.clust.data_79799clusters.zarr.full_geo.smoke.tif.Contours.tif",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/npp_viirs_i01_20190808_211200_wgs84_fit.tif.clust.data_79799clusters.zarr.full_geo.smoke.tif.Contours.tif",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/noaa20_viirs_i01_20190808_201800_wgs84_fit.tif.clust.data_79799clusters.zarr.full_geo.smoke.tif.Contours.tif",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/noaa20_viirs_i01_20190808_220000_wgs84_fit.tif.clust.data_79799clusters.zarr.full_geo.smoke.tif.Contours.tif",


]
