
gen_from_geotiffs: True

data:
 clust_reader_type: "gtiff"
 reader_kwargs:
   no_arg: "no_arg" 
 subset_inds: [[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[], [],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]]
 create_separate: False

 
 gtiff_data: [
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250106T174347Z_S007G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250106T184347Z_S008G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250106T194347Z_S009G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250106T204347Z_S010G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250106T214347Z_S011G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250106T222355Z_S012G06.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250106T230403Z_S013G06.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250106T234411Z_S014G06.tif.clust.data_146188clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250107T174414Z_S007G09.tif.clust.data_146183clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250107T184414Z_S008G09.tif.clust.data_146190clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250107T194414Z_S009G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250107T204414Z_S010G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250107T214414Z_S011G09.tif.clust.data_146184clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250107T222252Z_S012G06.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250108T174439Z_S007G09.tif.clust.data_146188clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250108T184439Z_S008G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250108T194439Z_S009G09.tif.clust.data_146197clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250108T204439Z_S010G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250108T214439Z_S011G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250108T222447Z_S012G06.tif.clust.data_146199clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250108T230455Z_S013G06.tif.clust.data_146189clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250108T234503Z_S014G06.tif.clust.data_146195clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250109T174504Z_S007G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250109T184504Z_S008G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250109T194504Z_S009G09.tif.clust.data_146197clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250109T204504Z_S010G09.tif.clust.data_146197clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250109T214504Z_S011G09.tif.clust.data_146199clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250109T222512Z_S012G06.tif.clust.data_146189clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250109T230520Z_S013G06.tif.clust.data_146199clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250109T234528Z_S014G06.tif.clust.data_146199clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250110T174529Z_S007G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250110T184529Z_S008G09.tif.clust.data_146195clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250110T194529Z_S009G09.tif.clust.data_146195clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250110T204529Z_S010G09.tif.clust.data_146195clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250110T214529Z_S011G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250110T222537Z_S012G06.tif.clust.data_146193clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250110T230545Z_S013G06.tif.clust.data_146194clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250110T234553Z_S014G06.tif.clust.data_146177clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250111T174553Z_S007G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250111T184553Z_S008G09.tif.clust.data_146199clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250111T194553Z_S009G09.tif.clust.data_146195clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250111T204553Z_S010G09.tif.clust.data_146195clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250111T214553Z_S011G09.tif.clust.data_146194clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250111T222601Z_S012G06.tif.clust.data_146194clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250111T230609Z_S013G06.tif.clust.data_146197clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250111T234617Z_S014G06.tif.clust.data_146195clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250112T174616Z_S007G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250112T184616Z_S008G09.tif.clust.data_146196clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250112T194616Z_S009G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250112T204616Z_S010G09.tif.clust.data_146194clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250112T214616Z_S011G09.tif.clust.data_146197clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250112T222624Z_S012G06.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250112T230632Z_S013G06.tif.clust.data_146197clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250112T234640Z_S014G06.tif.clust.data_146195clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250113T174639Z_S007G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250113T184639Z_S008G09.tif.clust.data_146196clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250113T194639Z_S009G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250113T204639Z_S010G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250113T214639Z_S011G09.tif.clust.data_146197clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250113T222647Z_S012G06.tif.clust.data_146180clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250113T230655Z_S013G06.tif.clust.data_146195clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250113T234703Z_S014G06.tif.clust.data_146195clusters.zarr.full_geo.tif",
]



 cluster_fnames: [
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250106T174347Z_S007G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250106T184347Z_S008G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250106T194347Z_S009G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250106T204347Z_S010G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250106T214347Z_S011G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250106T222355Z_S012G06.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250106T230403Z_S013G06.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250106T234411Z_S014G06.tif.clust.data_146188clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250107T174414Z_S007G09.tif.clust.data_146183clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250107T184414Z_S008G09.tif.clust.data_146190clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250107T194414Z_S009G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250107T204414Z_S010G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250107T214414Z_S011G09.tif.clust.data_146184clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250107T222252Z_S012G06.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250108T174439Z_S007G09.tif.clust.data_146188clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250108T184439Z_S008G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250108T194439Z_S009G09.tif.clust.data_146197clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250108T204439Z_S010G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250108T214439Z_S011G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250108T222447Z_S012G06.tif.clust.data_146199clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250108T230455Z_S013G06.tif.clust.data_146189clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250108T234503Z_S014G06.tif.clust.data_146195clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250109T174504Z_S007G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250109T184504Z_S008G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250109T194504Z_S009G09.tif.clust.data_146197clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250109T204504Z_S010G09.tif.clust.data_146197clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250109T214504Z_S011G09.tif.clust.data_146199clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250109T222512Z_S012G06.tif.clust.data_146189clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250109T230520Z_S013G06.tif.clust.data_146199clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250109T234528Z_S014G06.tif.clust.data_146199clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250110T174529Z_S007G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250110T184529Z_S008G09.tif.clust.data_146195clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250110T194529Z_S009G09.tif.clust.data_146195clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250110T204529Z_S010G09.tif.clust.data_146195clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250110T214529Z_S011G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250110T222537Z_S012G06.tif.clust.data_146193clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250110T230545Z_S013G06.tif.clust.data_146194clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250110T234553Z_S014G06.tif.clust.data_146177clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250111T174553Z_S007G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250111T184553Z_S008G09.tif.clust.data_146199clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250111T194553Z_S009G09.tif.clust.data_146195clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250111T204553Z_S010G09.tif.clust.data_146195clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250111T214553Z_S011G09.tif.clust.data_146194clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250111T222601Z_S012G06.tif.clust.data_146194clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250111T230609Z_S013G06.tif.clust.data_146197clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250111T234617Z_S014G06.tif.clust.data_146195clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250112T174616Z_S007G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250112T184616Z_S008G09.tif.clust.data_146196clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250112T194616Z_S009G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250112T204616Z_S010G09.tif.clust.data_146194clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250112T214616Z_S011G09.tif.clust.data_146197clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250112T222624Z_S012G06.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250112T230632Z_S013G06.tif.clust.data_146197clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250112T234640Z_S014G06.tif.clust.data_146195clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250113T174639Z_S007G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250113T184639Z_S008G09.tif.clust.data_146196clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250113T194639Z_S009G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250113T204639Z_S010G09.tif.clust.data_146198clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250113T214639Z_S011G09.tif.clust.data_146197clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250113T222647Z_S012G06.tif.clust.data_146180clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250113T230655Z_S013G06.tif.clust.data_146195clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/TEMPO_LA_FIRE/TEMPO_RAD_L1_V03_20250113T234703Z_S014G06.tif.clust.data_146195clusters.zarr.full_geo.tif",
]

context: 
 apply_context: True
 clusters: [
[90.31, 146.008, 146.02, 90.249, 146.003, 90.32, 146.038, 146.155, 64.766, 146.028, 146.142, 146.104, 146.084, 64.612, 146.096, 146.113, 146.149, 146.077, 146.147, 64.611, 146.06, 146.19]

]
 name: ["fire"]
 compare_truth: False
 generate_union: False
 background_class: 0

