
gen_from_geotiffs: False

data:
 clust_reader_type: "zarr_to_numpy"
 reader_kwargs:
  no_arg: ''
 subset_inds: [[], [],[],[],[],[],[],[],[],[],[],[],[],[],[],[]]
 create_separate: False
  
 gtiff_data: [
"/data/nlahaye/remoteSensing/Burn_Severity/Bridge_Fire_Stack.tif",
"/data/nlahaye/remoteSensing/Burn_Severity/Bridge_Fire_Stack.tif",
"/data/nlahaye/remoteSensing/Burn_Severity/Bridge_Fire_Stack.tif",
"/data/nlahaye/remoteSensing/Burn_Severity/Bridge_Fire_Stack.tif",
"/data/nlahaye/remoteSensing/Burn_Severity/Line_Fire_Stack.tif",
"/data/nlahaye/remoteSensing/Burn_Severity/Line_Fire_Stack.tif",
"/data/nlahaye/remoteSensing/Burn_Severity/Line_Fire_Stack.tif",
"/data/nlahaye/remoteSensing/Burn_Severity/Line_Fire_Stack.tif"
] 

 
 cluster_fnames: [
"/data/nlahaye/output/Learnergy/DBN_UAVSAR_BURN_SEVERITY/Bridge_Fire_Stack.tif.clust.data_73399clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_UAVSAR_BURN_SEVERITY/Bridge_Fire_Stack.tif.no_heir.clust.data_733clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_UAVSAR_BURN_SEVERITY_BURN_ONLY/Bridge_Fire_Stack.tif.clust.data_69399clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_UAVSAR_BURN_SEVERITY_BURN_ONLY/Bridge_Fire_Stack.tif.no_heir.clust.data_693clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_UAVSAR_BURN_SEVERITY_BURN_ONLY/Line_Fire_Stack.tif.clust.data_69399clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_UAVSAR_BURN_SEVERITY_BURN_ONLY/Line_Fire_Stack.tif.no_heir.clust.data_693clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_UAVSAR_BURN_SEVERITY/Line_Fire_Stack.tif.clust.data_73399clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_UAVSAR_BURN_SEVERITY/Line_Fire_Stack.tif.no_heir.clust.data_733clusters.zarr",
]


context:
 apply_context: False
 clusters: []  #64 #i.e. smoke clusters
 name: "" #i.e. smoke
 compare_truth: false
 generate_union: false

