

data:
 filename: [
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/noaa20_viirs_i01_20190806_191800_wgs84_fit.tif.clust.data_79769clusters.zarr.full_geo.smoke.tif",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/noaa20_viirs_i01_20190806_210000_wgs84_fit.tif.clust.data_79799clusters.zarr.full_geo.smoke.tif",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/noaa20_viirs_i01_20190808_201800_wgs84_fit.tif.clust.data_79799clusters.zarr.full_geo.smoke.tif",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/noaa20_viirs_i01_20190808_220000_wgs84_fit.tif.clust.data_79799clusters.zarr.full_geo.smoke.tif",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/noaa20_viirs_i01_20190809_200000_wgs84_fit.tif.clust.data_79799clusters.zarr.full_geo.smoke.tif",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/noaa20_viirs_i01_20190809_214200_wgs84_fit.tif.clust.data_79799clusters.zarr.full_geo.smoke.tif",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/noaa20_viirs_i01_20190810_194200_wgs84_fit.tif.clust.data_79799clusters.zarr.full_geo.smoke.tif",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/noaa20_viirs_i01_20190810_212400_wgs84_fit.tif.clust.data_79799clusters.zarr.full_geo.smoke.tif",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/noaa20_viirs_i01_20190811_192400_wgs84_fit.tif.clust.data_79799clusters.zarr.full_geo.smoke.tif",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/noaa20_viirs_i01_20190811_210600_wgs84_fit.tif.clust.data_79799clusters.zarr.full_geo.smoke.tif",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/noaa20_viirs_i01_20190812_204800_wgs84_fit.tif.clust.data_79799clusters.zarr.full_geo.smoke.tif",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/npp_viirs_i01_20190806_200600_wgs84_fit.tif.clust.data_79788clusters.zarr.full_geo.smoke.tif",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/npp_viirs_i01_20190806_214800_wgs84_fit.tif.clust.data_79799clusters.zarr.full_geo.smoke.tif",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/npp_viirs_i01_20190807_213000_wgs84_fit.tif.clust.data_79797clusters.zarr.full_geo.smoke.tif",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/npp_viirs_i01_20190808_193000_wgs84_fit.tif.clust.data_79799clusters.zarr.full_geo.smoke.tif",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/npp_viirs_i01_20190808_211200_wgs84_fit.tif.clust.data_79799clusters.zarr.full_geo.smoke.tif",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/npp_viirs_i01_20190809_191200_wgs84_fit.tif.clust.data_79799clusters.zarr.full_geo.smoke.tif",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/npp_viirs_i01_20190809_205400_wgs84_fit.tif.clust.data_79799clusters.zarr.full_geo.smoke.tif",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/npp_viirs_i01_20190810_203600_wgs84_fit.tif.clust.data_79799clusters.zarr.full_geo.smoke.tif",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/npp_viirs_i01_20190811_201200_wgs84_fit.tif.clust.data_79799clusters.zarr.full_geo.smoke.tif",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/npp_viirs_i01_20190811_215400_wgs84_fit.tif.clust.data_79799clusters.zarr.full_geo.smoke.tif",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/npp_viirs_i01_20190812_195400_wgs84_fit.tif.clust.data_79799clusters.zarr.full_geo.smoke.tif",
"/data/nlahaye/SIT_FUSE_Geo/VIIRS/npp_viirs_i01_20190812_213600_wgs84_fit.tif.clust.data_79799clusters.zarr.full_geo.smoke.tif",
]
 reader_type: "gtiff"
 reader_kwargs:
  None:

remove_singles: True
remove_singles_2: True
write_geotiff: True
contour_min_size: 10

dilations: 0
erosions: 0

