
output:
 out_dir: '/data/nlahaye/output/Learnergy/DBN_OIL_PALM_MULTI_LAYER_WIDE_NEW/'
 class_name: ['BACKGROUND', 'OIL_PALM']

data:
 min_thresh: 0
 label_gtiffs: [
[
'/data/nlahaye/remoteSensing/Palm_Oil/Dataset_Ucayali_Palm_V2.tif'
],
[
'/data/nlahaye/remoteSensing/Palm_Oil/Dataset_Ucayali_Palm_V2.tif'
],
]

 clust_gtiffs: [
"/data/nlahaye/output/Learnergy/DBN_OIL_PALM_MULTI_LAYER_WIDE_NEW/ucayali_stacks_2020_h1v1.tif.clust.data_79299clusters.zarr.full_geo.tif"
]

regrid: True

