
output:
 out_dir: '/data/nlahaye/output/GOES_TEMPO/'
 class_name: ['fire']

output:
 out_dir: '/data/nlahaye/output/Learnergy/SF_TEMPO_PARK'
 class_name: ['FIRE']

data:
 regrid: True
 multiclass: True
 zone_min: 0
 zone_max: 1
 min_thresh: 0
 min_thresh: 0.1
 label_gtiffs: [

[
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",

"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",

"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_TEMPO_DATA/GOES_TEMPO_FIRE_BACKGROUND.tif",
],


[

"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242081401177_e20242081403550_c20242081403597.fire.tif",
"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242081401177_e20242081403550_c20242081403597.fire.tif",
"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242081401177_e20242081403550_c20242081403597.fire.tif",
"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242081401177_e20242081403550_c20242081403597.fire.tif",

"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242081501177_e20242081503550_c20242081503592.fire.tif",
"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242081501177_e20242081503550_c20242081503592.fire.tif",
"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242081501177_e20242081503550_c20242081503592.fire.tif",
"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242081501177_e20242081503550_c20242081503592.fire.tif",

"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242081601177_e20242081603550_c20242081603591.fire.tif",
"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242081601177_e20242081603550_c20242081603591.fire.tif",
"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242081601177_e20242081603550_c20242081603591.fire.tif",
"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242081601177_e20242081603550_c20242081603591.fire.tif",

"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242081701177_e20242081703550_c20242081703592.fire.tif",
"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242081701177_e20242081703550_c20242081703592.fire.tif",
"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242081701177_e20242081703550_c20242081703592.fire.tif",
"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242081701177_e20242081703550_c20242081703592.fire.tif",

"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242081801177_e20242081803550_c20242081803594.fire.tif",
"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242081801177_e20242081803550_c20242081803594.fire.tif",
"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242081801177_e20242081803550_c20242081803594.fire.tif",
"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242081801177_e20242081803550_c20242081803594.fire.tif",

"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242081901177_e20242081903550_c20242081904000.fire.tif",
"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242081901177_e20242081903550_c20242081904000.fire.tif",
"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242081901177_e20242081903550_c20242081904000.fire.tif",
"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242081901177_e20242081903550_c20242081904000.fire.tif",

"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242082001177_e20242082003550_c20242082003591.fire.tif",
"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242082001177_e20242082003550_c20242082003591.fire.tif",
"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242082001177_e20242082003550_c20242082003591.fire.tif",
"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242082001177_e20242082003550_c20242082003591.fire.tif",

"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242082101177_e20242082103550_c20242082103590.fire.tif",
"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242082101177_e20242082103550_c20242082103590.fire.tif",
"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242082101177_e20242082103550_c20242082103590.fire.tif",
"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242082101177_e20242082103550_c20242082103590.fire.tif",

"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242082201177_e20242082203550_c20242082204028.fire.tif",
"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242082201177_e20242082203550_c20242082204028.fire.tif",
"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242082201177_e20242082203550_c20242082204028.fire.tif",
"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242082201177_e20242082203550_c20242082204028.fire.tif",

"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242082301177_e20242082303550_c20242082303596.fire.tif",
"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242082301177_e20242082303550_c20242082303596.fire.tif",
"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242082301177_e20242082303550_c20242082303596.fire.tif",
"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242082301177_e20242082303550_c20242082303596.fire.tif",
"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242082301177_e20242082303550_c20242082303596.fire.tif",
"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242082301177_e20242082303550_c20242082303596.fire.tif",
"/home/nlahaye/SIT_FUSE/src/sit_fuse/pipelines/context_assign/OR_ABI-L1b-RadC-M6C01_G18_s20242082301177_e20242082303550_c20242082303596.fire.tif",


]]

 clust_gtiffs: [

"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T142444Z_S006G06.tif.clust.data_186199clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T143122Z_S006G07.tif.clust.data_186199clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T143759Z_S006G08.tif.clust.data_186180clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T144436Z_S006G09.tif.clust.data_148470clusters.zarr.full_geo.tif",

"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T152444Z_S007G06.tif.clust.data_186199clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T153122Z_S007G07.tif.clust.data_186199clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T153759Z_S007G08.tif.clust.data_186199clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T154436Z_S007G09.tif.clust.data_186189clusters.zarr.full_geo.tif",

"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T162444Z_S008G06.tif.clust.data_186199clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T163122Z_S008G07.tif.clust.data_186199clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T163759Z_S008G08.tif.clust.data_186199clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T164436Z_S008G09.tif.clust.data_186193clusters.zarr.full_geo.tif",

"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T172444Z_S009G06.tif.clust.data_186199clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T173122Z_S009G07.tif.clust.data_186199clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T173759Z_S009G08.tif.clust.data_186199clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T174436Z_S009G09.tif.clust.data_186188clusters.zarr.full_geo.tif",

"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T182444Z_S010G06.tif.clust.data_186199clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T183122Z_S010G07.tif.clust.data_186199clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T183759Z_S010G08.tif.clust.data_186199clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T184436Z_S010G09.tif.clust.data_186197clusters.zarr.full_geo.tif",

"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T192444Z_S011G06.tif.clust.data_186199clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T193122Z_S011G07.tif.clust.data_186199clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T193759Z_S011G08.tif.clust.data_186199clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T194436Z_S011G09.tif.clust.data_186193clusters.zarr.full_geo.tif",

"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T202444Z_S012G06.tif.clust.data_186199clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T203122Z_S012G07.tif.clust.data_186199clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T203759Z_S012G08.tif.clust.data_186199clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T204436Z_S012G09.tif.clust.data_186193clusters.zarr.full_geo.tif",

"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T212444Z_S013G06.tif.clust.data_186199clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T213122Z_S013G07.tif.clust.data_186199clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T213759Z_S013G08.tif.clust.data_186199clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T214436Z_S013G09.tif.clust.data_186198clusters.zarr.full_geo.tif",

"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T222444Z_S014G06.tif.clust.data_186199clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T223122Z_S014G07.tif.clust.data_186199clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T223759Z_S014G08.tif.clust.data_186199clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T224436Z_S014G09.tif.clust.data_186198clusters.zarr.full_geo.tif",

"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T230449Z_S015G03.tif.clust.data_186199clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T231127Z_S015G04.tif.clust.data_186199clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T231804Z_S015G05.tif.clust.data_186199clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T232441Z_S015G06.tif.clust.data_186198clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T234454Z_S016G03.tif.clust.data_186197clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T235132Z_S016G04.tif.clust.data_186197clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/SF_TEMPO_PARK/TEMPO_RAD_L1_V03_20240726T235809Z_S016G05.tif.clust.data_186199clusters.zarr.full_geo.tif",

]


