 
 

dbf: True
dbf_list: [
["/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Background_Output_18.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Background_Output_19.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Background_Output_20.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Background_Output_21.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Background_Output_22.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Background_Planet_Output_10.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Background_Planet_Output_11.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Background_Planet_Output_12.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Background_Planet_Output_13.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Background_Planet_Output_14.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Background_Planet_Output_15.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Background_Planet_Output_16.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Background_Planet_Output_17.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190806_Background_Planet_Output_1.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Background_Planet_Output_1.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190806_Background_Planet_Output_2.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Background_Planet_Output_2.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190806_Background_Planet_Output_3.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Background_Planet_Output_3.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190806_Background_Planet_Output_4.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Background_Planet_Output_4.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190806_Background_Planet_Output_5.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Background_Planet_Output_5.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190806_Background_Planet_Output_6.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Background_Planet_Output_6.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190806_Background_Planet_Output_7.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Background_Planet_Output_7.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Background_Planet_Output_8.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Background_Planet_Output_9.dbf"],
["/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190808_Fire_Output_10.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190808_Fire_Output_11.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190808_Fire_Output_12.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190808_Fire_Output_13.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Fire_Output_18.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Fire_Output_19.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190808_Fire_Output_1.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Fire_Output_20.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190808_Fire_Output_2.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190808_Fire_Output_3.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190808_Fire_Output_4.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190808_Fire_Output_5.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190808_Fire_Output_6.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190808_Fire_Output_7.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190808_Fire_Output_8.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190808_Fire_Output_9.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Fire_Planet_Output_10.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Fire_Planet_Output_11.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Fire_Planet_Output_12.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Fire_Planet_Output_13.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Fire_Planet_Output_14.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Fire_Planet_Output_15.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Fire_Planet_Output_16.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Fire_Planet_Output_17.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Fire_Planet_Output_1.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Fire_Planet_Output_2.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Fire_Planet_Output_3.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Fire_Planet_Output_4.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Fire_Planet_Output_5.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Fire_Planet_Output_6.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Fire_Planet_Output_7.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Fire_Planet_Output_8.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Fire_Planet_Output_9.dbf"],
["/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190808_Smoke_Output_10.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190808_Smoke_Output_11.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190808_Smoke_Output_12.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190808_Smoke_Output_13.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Smoke_Output_18.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Smoke_Output_19.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190808_Smoke_Output_1.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Smoke_Output_20.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Smoke_Output_21.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Smoke_Output_22.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190808_Smoke_Output_2.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190808_Smoke_Output_3.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190808_Smoke_Output_4.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190808_Smoke_Output_5.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190808_Smoke_Output_6.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190808_Smoke_Output_7.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190808_Smoke_Output_8.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190808_Smoke_Output_9.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Smoke_Planet_Output_10.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Smoke_Planet_Output_11.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Smoke_Planet_Output_12.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Smoke_Planet_Output_13.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Smoke_Planet_Output_14.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Smoke_Planet_Output_15.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Smoke_Planet_Output_16.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Smoke_Planet_Output_17.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190806_Smoke_Planet_Output_1.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Smoke_Planet_Output_1.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190806_Smoke_Planet_Output_2.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Smoke_Planet_Output_2.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190806_Smoke_Planet_Output_3.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Smoke_Planet_Output_3.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190806_Smoke_Planet_Output_4.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Smoke_Planet_Output_4.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190806_Smoke_Planet_Output_5.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Smoke_Planet_Output_5.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190806_Smoke_Planet_Output_6.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Smoke_Planet_Output_6.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190806_Smoke_Planet_Output_7.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Smoke_Planet_Output_7.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Smoke_Planet_Output_8.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Smoke_Planet_Output_9.dbf"],
["/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Burn_Scar_Output_18.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Burn_Scar_Output_19.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Burn_Scar_Output_20.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Burn_Scar_Planet_Output_10.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Burn_Scar_Planet_Output_11.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Burn_Scar_Planet_Output_12.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Burn_Scar_Planet_Output_13.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Burn_Scar_Planet_Output_14.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Burn_Scar_Planet_Output_15.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Burn_Scar_Planet_Output_16.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Burn_Scar_Planet_Output_17.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Burn_Scar_Planet_Output_1.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Burn_Scar_Planet_Output_2.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Burn_Scar_Planet_Output_3.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Burn_Scar_Planet_Output_4.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Burn_Scar_Planet_Output_5.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Burn_Scar_Planet_Output_6.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Burn_Scar_Planet_Output_7.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Burn_Scar_Planet_Output_8.dbf",
"/data/nlahaye/output/Context_Assignment_Planet_PSS/output_DBFs/20190807_Burn_Scar_Planet_Output_9.dbf"]
]
 


