 
 

dbf: True
dbf_list: [
#["/data/nlahaye/output/Context_Assignment_S2/output_DBFs/20190813_Background_Output_1.dbf",
#"/data/nlahaye/output/Context_Assignment_S2/output_DBFs/20190813_Background_Output_2.dbf",
#"/data/nlahaye/output/Context_Assignment_S2/output_DBFs/20190813_Background_Output_3.dbf",
#"/data/nlahaye/output/Context_Assignment_S2/output_DBFs/20190813_Background_Output_4.dbf"],
["/data/nlahaye/output/Context_Assignment_S2/output_DBFs/20190808_Fire_Output_4.dbf"],
["/data/nlahaye/output/Context_Assignment_S2/output_DBFs/20190808_Smoke_Output_1.dbf",
"/data/nlahaye/output/Context_Assignment_S2/output_DBFs/20190808_Smoke_Output_2.dbf",
"/data/nlahaye/output/Context_Assignment_S2/output_DBFs/20190808_Smoke_Output_3.dbf",
"/data/nlahaye/output/Context_Assignment_S2/output_DBFs/20190808_Smoke_Output_4.dbf",
"/data/nlahaye/output/Context_Assignment_S2/output_DBFs/20190808_Smoke_Output_5.dbf"]
]

