dbf: True
dbf_list: [
[
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190807_Background_output_12.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190807_Background_output_13.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190807_Background_output_14.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190807_Background_output_17.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190807_Background_output_1.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190807_Background_output_6.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190807_Background_output_7.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190807_Background_output_8.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Background_output_10.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Background_output_11.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Background_output_14.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Background_output_15.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Background_output_16.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Background_output_17.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Background_output_1.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Background_output_20.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Background_output_21.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Background_output_22.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Background_output_26.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Background_output_2.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Background_output_31.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Background_output_32.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Background_output_35.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Background_output_36.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Background_output_37.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Background_output_3.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Background_output_7.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Background_output_8.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Background_output_9.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190808_Background_output_18.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190808_Background_output_19.dbf"
],
[
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190808_Fire_output_19.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190807_Fire_output_14.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190807_Fire_output_16.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190807_Fire_output_17.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190807_Fire_output_1.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190807_Fire_output_8.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Fire_output_12.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Fire_output_19.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Fire_output_1.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Fire_output_23.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Fire_output_25.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Fire_output_2.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Fire_output_30.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Fire_output_33.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Fire_output_34.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Fire_output_35.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Fire_output_36.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Fire_output_3.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Fire_output_4.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Fire_output_5.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Fire_output_6.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Fire_output_7.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Fire_output_8.dbf"
],
[
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Smoke_output_12.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Smoke_output_13.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Smoke_output_14.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Smoke_output_18.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Smoke_output_19.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Smoke_output_1.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Smoke_output_23.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Smoke_output_24.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Smoke_output_25.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Smoke_output_2.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Smoke_output_30.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Smoke_output_33.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Smoke_output_35.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Smoke_output_36.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190806_Smoke_output_3.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190807_Smoke_output_10.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190807_Smoke_output_11.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190807_Smoke_output_15.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190807_Smoke_output_16.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190807_Smoke_output_2.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190807_Smoke_output_3.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190807_Smoke_output_5.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190807_Smoke_output_9.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190808_Smoke_output_19.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190808_Smoke_output_20.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190808_Smoke_output_21.dbf",
"/data/nlahaye/output/Context_Assignment_AirMSPI/output_dbfs/MSPI_20190808_Smoke_output_22.dbf"
]]
 


