 
 

dbf: True
dbf_list: [
["/data/nlahaye/output/Context_Assignment_LS8/output_DBFs/20190807_Background_Output_1.dbf",
"/data/nlahaye/output/Context_Assignment_LS8/output_DBFs/20190814_Background_Output_1.dbf",
"/data/nlahaye/output/Context_Assignment_LS8/output_DBFs/20190807_Background_Output_2.dbf",
"/data/nlahaye/output/Context_Assignment_LS8/output_DBFs/20190814_Background_Output_2.dbf"],
["/data/nlahaye/output/Context_Assignment_LS8/output_DBFs/20190807_Fire_Output_1.dbf",
"/data/nlahaye/output/Context_Assignment_LS8/output_DBFs/20190807_Fire_Output_2.dbf"],
["/data/nlahaye/output/Context_Assignment_LS8/output_DBFs/20190807_Smoke_Output_1.dbf",
"/data/nlahaye/output/Context_Assignment_LS8/output_DBFs/20190807_Smoke_Output_2.dbf"]
]

