 


dbf: True
dbf_list: [
["/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_Output_10.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Fire_GOES_Output_10.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_Output_11.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Fire_GOES_Output_11.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_Output_12.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_Output_13.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_Output_14.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_Output_15.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_Output_16.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_FIre_GOES_Output_17.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_Output_18.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_Output_19.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_Output_1.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190807_Fire_GOES_Output_1.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Fire_GOES_Output_1.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_Output_20.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_Output_21.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_Output_22.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_Output_23.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_Output_24.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_Output_25.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_Output_26.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_Output_27.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_Output_28.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_Output_29.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_Output_2.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190807_Fire_GOES_Output_2.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Fire_GOES_Output_2.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_Output_30.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_Output_31.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_Output_32.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_Output_33.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_Output_34.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_Output_35.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_Output_36.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_Output_37.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_Output_3.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190807_Fire_GOES_Output_3.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_FIre_GOES_Output_3.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_Output_4.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190807_Fire_GOES_Output_4.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Fire_GOES_Output_4.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_Output_5.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190807_Fire_GOES_Output_5.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Fire_GOES_Output_5.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_Output_6.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190807_Fire_GOES_Output_6.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Fire_GOES_Output_6.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_Output_7.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Fire_GOES_Output_7.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_Output_8.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Fire_GOES_Output_8.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Fire_GOES_Output_9.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Fire_GOES_Output_9.dbf"],
["/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_GOES_Output_10.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Smoke_GOES_Output_10.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_GOES_Output_11.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Smoke_GOES_Output_11.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_GOES_Output_12.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_GOES_Output_13.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_GOES_Output_14.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_GOES_Output_15.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_GOES_Output_16.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_GOES_Output_17.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_GOES_Output_18.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_GOES_Output_19.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_GOES_Output_1.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190807_Smoke_GOES_Output_1.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Smoke_GOES_Output_1.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_GOES_Output_20.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_GOES_Output_21.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_GOES_Output_22.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_GOES_Output_23.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_GOES_Output_24.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_GOES_Output_25.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_GOES_Output_26.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_GOES_Output_27.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_GOES_Output_28.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_GOES_Output_29.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_GOES_Output_2.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190807_Smoke_GOES_Output_2.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Smoke_GOES_Output_2.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_GOES_Output_30.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_GOES_Output_31.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_GOES_Output_32.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_GOES_Output_33.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_GOES_Output_34.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_GOES_Output_35.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_GOES_Output_36.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_GOES_Output_37.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_GOES_Output_3.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190807_Smoke_GOES_Output_3.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Smoke_GOES_Output_3.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_GOES_Output_4.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190807_Smoke_GOES_Output_4.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Smoke_GOES_Output_4.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_GOES_Output_5.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190807_Smoke_GOES_Output_5.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Smoke_GOES_Output_5.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_GOES_Output_6.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190807_Smoke_GOES_Output_6.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Smoke_GOES_Output_6.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_GOES_Output_7.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Smoke_GOES_Output_7.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_GOES_Output_8.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Smoke_GOES_Output_8.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190806_Smoke_GOES_Output_9.dbf",
"/data/nlahaye/output/Context_Assignment_GOES/output_DBFs/20190808_Smoke_GOES_Output_9.dbf"]
]
 


