
gen_from_geotiffs: false

data:
 clust_reader_type: "zarr_to_numpy"
 reader_kwargs:
   no_arg: "no_arg" 
 subset_inds: [[],[],[],[],[],[],[],[]]
 create_separate: false
   
 gtiff_data: [
"/data/nlahaye/remoteSensing/LS8_GARRONE/HLS.L30.T30TYQ.2022105T104152.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LS8_GARRONE/HLS.L30.T30TYQ.2022105T104152.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LS8_GARRONE/HLS.L30.T30TYQ.2022105T104152.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LS8_GARRONE/HLS.L30.T30TYQ.2022105T104152.v2.0.B01.tif"] 



 cluster_fnames: ["/data/nlahaye/output/Learnergy/DBN_HSL_S2_GARONNE/file0_output.data.clustering_500clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_HSL_S2_GARONNE/file0_output_test.data.clustering_500clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_HSL_S2_GARONNE/file1_output_test.data.clustering_500clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_HSL_S2_GARONNE/file2_output_test.data.clustering_500clusters.zarr"]


 
context:
 apply_context: true
 clusters: [4, 21, 71, 127, 172, 179, 180, 275, 231, 284, 291, 298, 319, 325, 366, 408, 427, 418, 483]
 name: "Water" #i.e. smoke
 compare_truth: false
 generate_union: true


