
gen_from_geotiffs: false

data:
 clust_reader_type: "zarr_to_numpy"
 reader_kwargs:
   no_arg: "no_arg" 
 subset_inds: [[],[],[],[],[],[],[],[]]
 create_separate: false
   

 gtiff_data: [
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/HLS.L30.T11ULP.2019219T184259.v2.0.B01.tif"
]

  
 cluster_fnames: [
"/data/nlahaye/output/Learnergy/DBN_LS8_FIREX/HLS.L30.T11ULP.2019219T184259.v2.0.B01.tif.clust.output_test.data_5000clusters.zarr"
]


context:
 apply_context: True
 clusters: [2987, 1641, 3683, 1858, 942, 3011] #i.e. smoke clusters
 name: "smoke" #i.e. smoke
 compare_truth: false
 generate_union: false
 cluster_dependencies: 
  -1: [-1]
  #129: [42,346]
  #289: [42,346]
  #354: [42,346]
  #181: [42,346]



