
gen_from_geotiffs: false

data:
 clust_reader_type: "zarr_to_numpy"
 reader_kwargs:
   no_arg: "no_arg" 
 subset_inds: [[],[],[],[],[],[],[],[]]
 create_separate: True
   
 gtiff_data: [
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TNN.2022253T183110.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TPM.2022246T182458.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TNM.2022253T183110.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TNN.2022244T183720.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TQM.2022246T182458.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TPL.2022247T181930.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TPL.2022245T183151.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TNM.2022246T182458.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TPK.2022245T183151.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TPN.2022246T182458.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TQL.2022247T181930.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TQL.2022246T182522.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TNK.2022253T183158.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TNL.2022245T183151.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TPK.2022253T183134.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TNN.2022245T183127.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TNN.2022246T182458.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TPL.2022246T182522.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TPM.2022245T183127.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TNN.2022252T183742.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TPL.2022253T183134.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TNK.2022246T182546.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TPM.2022247T181930.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TPM.2022253T183110.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TNL.2022253T183134.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TPK.2022247T181954.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TPK.2022246T182546.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TQM.2022247T181907.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TPN.2022253T183110.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TQK.2022246T182546.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TQK.2022247T181954.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TPN.2022245T183127.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TNL.2022246T182522.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TNM.2022245T183127.v2.0.B01.tif"]
 
 
 cluster_fnames: [
"/data/nlahaye/output/Learnergy/DBN_LS8_BENCHMARK/HLS.L30.T11TNN.2022253T183110.v2.0.B01.tif.clust.output_test.data_5000clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LS8_BENCHMARK/HLS.L30.T11TPM.2022246T182458.v2.0.B01.tif.clust.output_test.data_5000clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LS8_BENCHMARK/HLS.L30.T11TNM.2022253T183110.v2.0.B01.tif.clust.output_test.data_5000clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LS8_BENCHMARK/HLS.L30.T11TNN.2022244T183720.v2.0.B01.tif.clust.output_test.data_5000clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LS8_BENCHMARK/HLS.L30.T11TQM.2022246T182458.v2.0.B01.tif.clust.output_test.data_5000clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LS8_BENCHMARK/HLS.L30.T11TPL.2022247T181930.v2.0.B01.tif.clust.output_test.data_5000clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LS8_BENCHMARK/HLS.L30.T11TPL.2022245T183151.v2.0.B01.tif.clust.output_test.data_5000clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LS8_BENCHMARK/HLS.L30.T11TNM.2022246T182458.v2.0.B01.tif.clust.output_test.data_5000clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LS8_BENCHMARK/HLS.L30.T11TPK.2022245T183151.v2.0.B01.tif.clust.output_test.data_5000clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LS8_BENCHMARK/HLS.L30.T11TPN.2022246T182458.v2.0.B01.tif.clust.output_test.data_5000clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LS8_BENCHMARK/HLS.L30.T11TQL.2022247T181930.v2.0.B01.tif.clust.output_test.data_5000clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LS8_BENCHMARK/HLS.L30.T11TQL.2022246T182522.v2.0.B01.tif.clust.output_test.data_5000clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LS8_BENCHMARK/HLS.L30.T11TNK.2022253T183158.v2.0.B01.tif.clust.output_test.data_5000clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LS8_BENCHMARK/HLS.L30.T11TNL.2022245T183151.v2.0.B01.tif.clust.output_test.data_5000clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LS8_BENCHMARK/HLS.L30.T11TPK.2022253T183134.v2.0.B01.tif.clust.output_test.data_5000clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LS8_BENCHMARK/HLS.L30.T11TNN.2022245T183127.v2.0.B01.tif.clust.output_test.data_5000clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LS8_BENCHMARK/HLS.L30.T11TNN.2022246T182458.v2.0.B01.tif.clust.output_test.data_5000clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LS8_BENCHMARK/HLS.L30.T11TPL.2022246T182522.v2.0.B01.tif.clust.output_test.data_5000clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LS8_BENCHMARK/HLS.L30.T11TPM.2022245T183127.v2.0.B01.tif.clust.output_test.data_5000clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LS8_BENCHMARK/HLS.L30.T11TNN.2022252T183742.v2.0.B01.tif.clust.output_test.data_5000clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LS8_BENCHMARK/HLS.L30.T11TPL.2022253T183134.v2.0.B01.tif.clust.output_test.data_5000clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LS8_BENCHMARK/HLS.L30.T11TNK.2022246T182546.v2.0.B01.tif.clust.output_test.data_5000clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LS8_BENCHMARK/HLS.L30.T11TPM.2022247T181930.v2.0.B01.tif.clust.output_test.data_5000clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LS8_BENCHMARK/HLS.L30.T11TPM.2022253T183110.v2.0.B01.tif.clust.output_test.data_5000clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LS8_BENCHMARK/HLS.L30.T11TNL.2022253T183134.v2.0.B01.tif.clust.output_test.data_5000clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LS8_BENCHMARK/HLS.L30.T11TPK.2022247T181954.v2.0.B01.tif.clust.output_test.data_5000clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LS8_BENCHMARK/HLS.L30.T11TPK.2022246T182546.v2.0.B01.tif.clust.output_test.data_5000clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LS8_BENCHMARK/HLS.L30.T11TQM.2022247T181907.v2.0.B01.tif.clust.output_test.data_5000clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LS8_BENCHMARK/HLS.L30.T11TPN.2022253T183110.v2.0.B01.tif.clust.output_test.data_5000clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LS8_BENCHMARK/HLS.L30.T11TQK.2022246T182546.v2.0.B01.tif.clust.output_test.data_5000clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LS8_BENCHMARK/HLS.L30.T11TQK.2022247T181954.v2.0.B01.tif.clust.output_test.data_5000clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LS8_BENCHMARK/HLS.L30.T11TPN.2022245T183127.v2.0.B01.tif.clust.output_test.data_5000clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LS8_BENCHMARK/HLS.L30.T11TNL.2022246T182522.v2.0.B01.tif.clust.output_test.data_5000clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LS8_BENCHMARK/HLS.L30.T11TNM.2022245T183127.v2.0.B01.tif.clust.output_test.data_5000clusters.zarr"]


context:
 apply_context: true
 clusters: [354] #i.e. smoke clusters
 name: "fire" #i.e. smoke
 compare_truth: false
 generate_union: false

