

data:

 contour_filename: [
"/data/nlahaye/output/Learnergy/DBN_MASTER/MASTERL1B_1981719_06_20190806_2153_2156_V01_georeferenced.tif.npy.heir_clust2output_test.data_7868200clusters.zarr.smoke.tif.Max_Contour.tif",
"/data/nlahaye/output/Learnergy/DBN_MASTER/MASTERL1B_1981719_07_20190806_2226_2231_V01_georeferenced.tif.npy.heir_clust2output_test.data_7869900clusters.zarr.smoke.tif.Max_Contour.tif",
"/data/nlahaye/output/Learnergy/DBN_MASTER/MASTERL1B_1981720_07_20190808_0055_0103_V01_georeferenced.tif.npy.heir_clust2output_test.data_7869900clusters.zarr.smoke.tif.Max_Contour.tif",
"/data/nlahaye/output/Learnergy/DBN_MASTER/MASTERL1B_1981721_01_20190809_0113_0117_V01_georeferenced.tif.npy.heir_clust2output_test.data_7869900clusters.zarr.smoke.tif.Max_Contour.tif"
]


 filename: [
"/data/nlahaye/output/Learnergy/DBN_MASTER/MASTERL1B_1981719_06_20190806_2153_2156_V01_georeferenced.tif.npy.heir_clust2output_test.data_7868200clusters.zarr.smoke.FullColor.tif",
"/data/nlahaye/output/Learnergy/DBN_MASTER/MASTERL1B_1981719_07_20190806_2226_2231_V01_georeferenced.tif.npy.heir_clust2output_test.data_7869900clusters.zarr.smoke.FullColor.tif",
"/data/nlahaye/output/Learnergy/DBN_MASTER/MASTERL1B_1981720_07_20190808_0055_0103_V01_georeferenced.tif.npy.heir_clust2output_test.data_7869900clusters.zarr.smoke.FullColor.tif",
"/data/nlahaye/output/Learnergy/DBN_MASTER/MASTERL1B_1981721_01_20190809_0113_0117_V01_georeferenced.tif.npy.heir_clust2output_test.data_7869900clusters.zarr.smoke.FullColor.tif"
]

 mask_filename: [
"/data/nlahaye/output/Learnergy/DBN_MASTER/MASTERL1B_1981719_06_20190806_2153_2156_V01_georeferenced.tif.npy.heir_clust2output_test.data_7868200clusters.zarr.smoke.tif",
"/data/nlahaye/output/Learnergy/DBN_MASTER/MASTERL1B_1981719_07_20190806_2226_2231_V01_georeferenced.tif.npy.heir_clust2output_test.data_7869900clusters.zarr.smoke.tif",
"/data/nlahaye/output/Learnergy/DBN_MASTER/MASTERL1B_1981720_07_20190808_0055_0103_V01_georeferenced.tif.npy.heir_clust2output_test.data_7869900clusters.zarr.smoke.tif",
"/data/nlahaye/output/Learnergy/DBN_MASTER/MASTERL1B_1981721_01_20190809_0113_0117_V01_georeferenced.tif.npy.heir_clust2output_test.data_7869900clusters.zarr.smoke.tif"
]

 reader_type: "gtiff"
 reader_kwargs:
  None:

remove_singles: True
write_geotiff: True

