
gen_from_geotiffs: false

data:
 clust_reader_type: "zarr_to_numpy"
 reader_kwargs:
   no_arg: "no_arg" 
 subset_inds: [[],[],[],[],[],[]]
 create_separate: true
 

 gtiff_data: ["/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/MOD021KM.A2010105.1315.061.2017251212752.EV_1KM_RefSB_1-EV_1KM_RefSB.tif",
"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/MOD021KM.A2010123.1300.061.2017253123623.pssgrp_000501840459.EV_1KM_RefSB_1-EV_1KM_RefSB.tif",
"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/MOD021KM.A2010125.1250.061.2017254220019.pssgrp_000501840459.EV_1KM_RefSB_1-EV_1KM_RefSB.tif",
"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/MOD021KM.A2010127.1235.061.2017255001328.pssgrp_000501840459.EV_1KM_RefSB_1-EV_1KM_RefSB.tif",
"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/MOD021KM.A2010132.1255.061.2017253164459.pssgrp_000501840459.EV_1KM_RefSB_1-EV_1KM_RefSB.tif",
"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/MOD021KM.A2010136.1230.061.2017255014157.pssgrp_000501840459.EV_1KM_RefSB_1-EV_1KM_RefSB.tif"]
#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/MOD021KM.A2010111.1235.061.2017255003423.EV_1KM_RefSB_1-EV_1KM_RefSB.tif"]#,
#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/MOD021KM.A2010105.1135.061.2017251212802.EV_1KM_RefSB_1-EV_1KM_RefSB.tif",
#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/MOD021KM.A2010105.1315.061.2017251212752.EV_1KM_RefSB_1-EV_1KM_RefSB.tif"]
   
 cluster_fnames: ["/data/nlahaye/output/Learnergy/DBN_MODIS_VOLC_ACTUAL/file0_output_test.data.clustering_500clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_MODIS_VOLC_ACTUAL/file1_output_test.data.clustering_500clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_MODIS_VOLC_ACTUAL/file2_output_test.data.clustering_500clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_MODIS_VOLC_ACTUAL/file3_output_test.data.clustering_500clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_MODIS_VOLC_ACTUAL/file4_output_test.data.clustering_500clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_MODIS_VOLC_ACTUAL/file5_output_test.data.clustering_500clusters.zarr"]
#"/data/nlahaye/output/Learnergy/DBN_MODIS_VOLC/file0_output_test.data.clustering_500clusters.zarr",
#"/data/nlahaye/output/Learnergy/DBN_MODIS_VOLC/file1_output_test.data.clustering_500clusters.zarr"]
 
context:
 apply_context: True
#40, 64, 69
 clusters: [2, 23, 28, 30, 31, 64, 69, 87, 92, 138, 153, 242, 251, 265, 274, 280, 329, 361, 367, 386, 407,  441, 478,38, 89, 277, 285, 336, 167, 444, 289, 489]  #[84, 175, 244, 274, 395, 460, 173, 222] #i.e. smoke clusters
 name: "volc_ash_v3" #i.e. smoke
 compare_truth: false
 generate_union: False

#Removed 439, 440, 172, 320, 340, 371

