
gen_from_geotiffs: true

data:
 clust_reader_type: "zarr_to_numpy"
 reader_kwargs:
   no_arg: "no_arg" 
 subset_inds: [[],[],[]]
 create_separate: true
 gtiff_data: ["/data/nlahaye/output/Learnergy/DBN_S3_GERD_INPUT/file0_output.data.input.clustering.zarr.tif",
"/data/nlahaye/output/Learnergy/DBN_S3_GERD_INPUT/file0_output_test.data.input.clustering.zarr.tif",
"/data/nlahaye/output/Learnergy/DBN_S3_GERD_INPUT/file1_output.data.input.clustering.zarr.tif",
"/data/nlahaye/output/Learnergy/DBN_S3_GERD_INPUT/file1_output_test.data.input.clustering.zarr.tif",
"/data/nlahaye/output/Learnergy/DBN_S3_GERD_INPUT/file2_output_test.data.input.clustering.zarr.tif"]
 cluster_fnames: []
 
context:
 apply_context: false
 clusters: [] #i.e. smoke clusters
 name: "" #i.e. smoke
 compare_truth: false


