 
input_paths: ["/data/nlahaye/output/Learnergy/No_Data/",
              "/data/nlahaye/output/Learnergy/No_Data/",
              "/mnt/data/HAB_MODEL_WEIGHTS/OC_SIF_HABs_2025/JPSS1_VIIRS_S_CA/"]

 
 
fname_str: "DAY.pseudo_nitzschia_seriata_bloom.tif"
out_dir: "/mnt/data/HAB_MODEL_WEIGHTS/OC_SIF_HABs_2025/MERGED_HAB/JPSS1_VIIRS/"
num_classes: 9
re_index: 3

gen_daily: true
gen_monthly: false

