

train_min_date: "20250110"
train_max_date: "20250220"

output: "/mnt/data/HAB_MODEL_WEIGHTS/OC_SIF_HABs_2025/GOES_18/"

start_lon: -124.00
end_lon: -114.00
start_lat: 28.00
end_lat: 38.00

config_dir: "/home/nlahaye/SIT_FUSE/src/sit_fuse/config/"


input_dir: "/mnt/data/GOES_18_LA_FIRE_RADIANCES/"
 

