

start_lon: -128.00
end_lon: -116.00
start_lat: 30.00
end_lat: 38.94

train_min_date: "20250110"
train_max_date: "20250220"

output: "/mnt/data/HAB_MODEL_WEIGHTS/OC_SIF_HABs_2025/GOES_18/"

config_dir: "/home/nlahaye/SIT_FUSE/src/sit_fuse/config/"





