
data:
 filenames: [
#"/data/nlahaye/output/Learnergy/DBN_UAVSAR_LT_3/SanAnd_26526_17122_004_171102_L090HHHH_CX_01.grd.heir_clust2output_test.data"
#"/data/nlahaye/output/Learnergy/DBN_UAVSAR_LT_3/SanAnd_26526_17122_004_171102_L090HHHH_CX_01.grd.clustoutput_test.data"
"/data/nlahaye/output/Learnergy/DBN_UAVSAR_LT_3/SanAnd_26526_17122_004_171102_L090HHHH_CX_01.grd.heir_clust1output_test.data"
]



