

data:
  filenames: [
"/data/nlahaye/output/Learnergy/DBN_GK2A/gk2a_ami_le1b_ir087_ea020lc_202203060100.nc.heir_clust2output_test.data",
"/data/nlahaye/output/Learnergy/DBN_GK2A/gk2a_ami_le1b_ir087_ea020lc_202203070020.nc.heir_clust2output_test.data",
"/data/nlahaye/output/Learnergy/DBN_GK2A/gk2a_ami_le1b_ir087_ea020lc_202203070030.nc.heir_clust2output_test.data",
"/data/nlahaye/output/Learnergy/DBN_GK2A/gk2a_ami_le1b_ir087_ea020lc_202203070050.nc.heir_clust2output_test.data",
"/data/nlahaye/output/Learnergy/DBN_GK2A/gk2a_ami_le1b_ir087_ea020lc_202203070100.nc.heir_clust2output_test.data",
"/data/nlahaye/output/Learnergy/DBN_GK2A/gk2a_ami_le1b_ir087_ea020lc_202203070110.nc.heir_clust2output_test.data"
]



