

data:
 filenames: [
"/data/nlahaye/output/Learnergy/DBN_EMIT/EMIT_L1B_RAD_001_20230419T065236_2310905_033.nc.clustoutput_test.data",
"/data/nlahaye/output/Learnergy/DBN_EMIT/EMIT_L1B_RAD_001_20230419T065224_2310905_032.nc.clustoutput_test.data",
"/data/nlahaye/output/Learnergy/DBN_EMIT/EMIT_L1B_RAD_001_20230419T051739_2310904_018.nc.clustoutput_test.data",
"/data/nlahaye/output/Learnergy/DBN_EMIT/EMIT_L1B_RAD_001_20230419T051750_2310904_019.nc.clustoutput.data",
"/data/nlahaye/output/Learnergy/DBN_EMIT/EMIT_L1B_RAD_001_20230419T065137_2310905_028.nc.clustoutput.data",
"/data/nlahaye/output/Learnergy/DBN_EMIT/EMIT_L1B_RAD_001_20230419T065212_2310905_031.nc.clustoutput.data"
]






