

data:
 filenames: [
"/data/nlahaye/output/Learnergy/DBN_MSPI_STEP_AND_STARE_PAD_MULTI_LAYER/AirMSPI_ER2_GRP_ELLIPSOID_20190807_200717Z_WA-Lincoln_STEP_AND_STARE_FUSE.npy.heir_clust1output.data",
"/data/nlahaye/output/Learnergy/DBN_MSPI_STEP_AND_STARE_PAD_MULTI_LAYER/AirMSPI_ER2_GRP_ELLIPSOID_20190808_181835Z_WA-Inchelium_STEP_AND_STARE_FUSE.npy.heir_clust1output_test.data",
"/data/nlahaye/output/Learnergy/DBN_MSPI_STEP_AND_STARE_PAD_MULTI_LAYER/AirMSPI_ER2_GRP_ELLIPSOID_20190806_200308Z_WA-Keller_STEP_AND_STARE_FUSE.npy.heir_clust1output.data",
"/data/nlahaye/output/Learnergy/DBN_MSPI_STEP_AND_STARE_PAD_MULTI_LAYER/AirMSPI_ER2_GRP_ELLIPSOID_20190806_205617Z_WA-Wilbur_STEP_AND_STARE_FUSE.npy.heir_clust1output_test.data",
"/data/nlahaye/output/Learnergy/DBN_MSPI_STEP_AND_STARE_PAD_MULTI_LAYER/AirMSPI_ER2_GRP_ELLIPSOID_20190806_184317Z_WA-Keller_STEP_AND_STARE_FUSE.npy.heir_clust1output_test.data",
"/data/nlahaye/output/Learnergy/DBN_MSPI_STEP_AND_STARE_PAD_MULTI_LAYER/AirMSPI_ER2_GRP_ELLIPSOID_20190806_211454Z_WA-Wilbur_STEP_AND_STARE_FUSE.npy.heir_clust1output.data",
"/data/nlahaye/output/Learnergy/DBN_MSPI_STEP_AND_STARE_PAD_MULTI_LAYER/AirMSPI_ER2_GRP_ELLIPSOID_20190807_204916Z_WA-Inchelium_STEP_AND_STARE_FUSE.npy.heir_clust1output.data",
"/data/nlahaye/output/Learnergy/DBN_MSPI_STEP_AND_STARE_PAD_MULTI_LAYER/AirMSPI_ER2_GRP_ELLIPSOID_20190807_202502Z_WA-Inchelium_STEP_AND_STARE_FUSE.npy.heir_clust1output_test.data",
"/data/nlahaye/output/Learnergy/DBN_MSPI_STEP_AND_STARE_PAD_MULTI_LAYER/AirMSPI_ER2_GRP_ELLIPSOID_20190807_182404Z_WA-Inchelium_STEP_AND_STARE_FUSE.npy.heir_clust1output_test.data",
"/data/nlahaye/output/Learnergy/DBN_MSPI_STEP_AND_STARE_PAD_MULTI_LAYER/AirMSPI_ER2_GRP_ELLIPSOID_20190806_190738Z_WA-Keller_STEP_AND_STARE_FUSE.npy.heir_clust1output_test.data",
"/data/nlahaye/output/Learnergy/DBN_MSPI_STEP_AND_STARE_PAD_MULTI_LAYER/AirMSPI_ER2_GRP_ELLIPSOID_20190807_195226Z_WA-Inchelium_STEP_AND_STARE_FUSE.npy.heir_clust1output.data",
"/data/nlahaye/output/Learnergy/DBN_MSPI_STEP_AND_STARE_PAD_MULTI_LAYER/AirMSPI_ER2_GRP_ELLIPSOID_20190806_195205Z_WA-Keller_STEP_AND_STARE_FUSE.npy.heir_clust1output.data",
"/data/nlahaye/output/Learnergy/DBN_MSPI_STEP_AND_STARE_PAD_MULTI_LAYER/AirMSPI_ER2_GRP_ELLIPSOID_20190806_203821Z_WA-Keller_STEP_AND_STARE_FUSE.npy.heir_clust1output.data",
"/data/nlahaye/output/Learnergy/DBN_MSPI_STEP_AND_STARE_PAD_MULTI_LAYER/AirMSPI_ER2_GRP_ELLIPSOID_20190807_193859Z_WA-Inchelium_STEP_AND_STARE_FUSE.npy.heir_clust1output_test.data",
"/data/nlahaye/output/Learnergy/DBN_MSPI_STEP_AND_STARE_PAD_MULTI_LAYER/AirMSPI_ER2_GRP_ELLIPSOID_20190806_202139Z_WA-Creston_STEP_AND_STARE_FUSE.npy.heir_clust1output.data"
]



