 
data: 
 filenames: [
"/data/nlahaye/output/Learnergy/DBN_TROP_RED_SIF_AUTO_CLUST/TROPO_redSIF_2018-09-05_ungridded.nc.clustoutput.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_RED_SIF_AUTO_CLUST/TROPO_redSIF_2018-09-29_ungridded.nc.clustoutput.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_RED_SIF_AUTO_CLUST/TROPO_redSIF_2018-09-06_ungridded.nc.clustoutput.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_RED_SIF_AUTO_CLUST/TROPO_redSIF_2018-09-21_ungridded.nc.clustoutput.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_RED_SIF_AUTO_CLUST/TROPO_redSIF_2018-09-19_ungridded.nc.clustoutput.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_RED_SIF_AUTO_CLUST/TROPO_redSIF_2018-09-17_ungridded.nc.clustoutput.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_RED_SIF_AUTO_CLUST/TROPO_redSIF_2018-09-16_ungridded.nc.clustoutput.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_RED_SIF_AUTO_CLUST/TROPO_redSIF_2018-09-13_ungridded.nc.clustoutput.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_RED_SIF_AUTO_CLUST/TROPO_redSIF_2018-09-10_ungridded.nc.clustoutput.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_RED_SIF_AUTO_CLUST/TROPO_redSIF_2018-09-26_ungridded.nc.clustoutput.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_RED_SIF_AUTO_CLUST/TROPO_redSIF_2018-09-15_ungridded.nc.clustoutput.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_RED_SIF_AUTO_CLUST/TROPO_redSIF_2018-09-24_ungridded.nc.clustoutput.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_RED_SIF_AUTO_CLUST/TROPO_redSIF_2018-09-30_ungridded.nc.clustoutput.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_RED_SIF_AUTO_CLUST/TROPO_redSIF_2018-09-20_ungridded.nc.clustoutput.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_RED_SIF_AUTO_CLUST/TROPO_redSIF_2018-09-03_ungridded.nc.clustoutput.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_RED_SIF_AUTO_CLUST/TROPO_redSIF_2018-09-08_ungridded.nc.clustoutput.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_RED_SIF_AUTO_CLUST/TROPO_redSIF_2018-09-07_ungridded.nc.clustoutput.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_RED_SIF_AUTO_CLUST/TROPO_redSIF_2018-09-27_ungridded.nc.clustoutput.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_RED_SIF_AUTO_CLUST/TROPO_redSIF_2018-09-14_ungridded.nc.clustoutput.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_RED_SIF_AUTO_CLUST/TROPO_redSIF_2018-09-25_ungridded.nc.clustoutput.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_RED_SIF_AUTO_CLUST/TROPO_redSIF_2018-09-22_ungridded.nc.clustoutput.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_RED_SIF_AUTO_CLUST/TROPO_redSIF_2018-09-23_ungridded.nc.clustoutput.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_RED_SIF_AUTO_CLUST/TROPO_redSIF_2018-09-18_ungridded.nc.clustoutput.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_RED_SIF_AUTO_CLUST/TROPO_redSIF_2018-09-04_ungridded.nc.clustoutput.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_RED_SIF_AUTO_CLUST/TROPO_redSIF_2018-09-28_ungridded.nc.clustoutput.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_RED_SIF_AUTO_CLUST/TROPO_redSIF_2018-09-12_ungridded.nc.clustoutput.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_RED_SIF_AUTO_CLUST/TROPO_redSIF_2018-09-11_ungridded.nc.clustoutput.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_RED_SIF_AUTO_CLUST/TROPO_redSIF_2018-09-09_ungridded.nc.clustoutput.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_RED_SIF_AUTO_CLUST/TROPO_redSIF_2018-09-01_ungridded.nc.clustoutput_test.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_RED_SIF_AUTO_CLUST/TROPO_redSIF_2018-09-02_ungridded.nc.clustoutput_test.data"
]
