files_train: ["/data/nlahaye/output/Learnergy/DBN_eMAS/file0_output.data",
"/data/nlahaye/output/Learnergy/DBN_eMAS/file1_output.data",
"/data/nlahaye/output/Learnergy/DBN_eMAS/file2_output.data"]
files_test: ["/data/nlahaye/output/Learnergy/DBN_eMAS/file0_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_eMAS/file1_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_eMAS/file2_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_eMAS/file3_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_eMAS/file4_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_eMAS/file5_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_eMAS/file6_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_eMAS/file7_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_eMAS/file8_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_eMAS/file9_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_eMAS/file10_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_eMAS/file11_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_eMAS/file12_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_eMAS/file13_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_eMAS/file14_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_eMAS/file15_output_test.data"
]
 

output:
 out_dir: "/data/nlahaye/output/Learnergy/DBN_eMAS/"


clustering:
        n_clusters: 500
        branch: 5
        thresh: 1e-5
        pixel_padding: 1
        train_sample_size: 1500000
        clustering:
        train: True
        reset_n_clusters: True
        model:  


scaler:
 name: "standard_dask"
 scale: True
