output:
 out_dir: "/data/nlahaye/output/Learnergy/DBN_GENETICS/"


clustering:
        n_clusters: 75
        branch: 5
        thresh: 1e-5
        pixel_padding: 1
        train_sample_size: 150000 #000
        clustering:
        train: True
        reset_n_clusters: True
        model:

scaler:
 name: "standard_dask"
 scale: True


files_train: ["/data/nlahaye/output/Learnergy/DBN_GENETICS/file0_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file10_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file11_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file12_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file13_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file14_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file15_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file16_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file17_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file18_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file19_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file1_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file20_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file21_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file22_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file23_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file24_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file25_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file26_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file27_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file28_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file29_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file2_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file30_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file31_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file32_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file33_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file34_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file35_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file36_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file37_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file38_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file39_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file3_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file40_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file41_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file42_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file43_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file44_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file45_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file46_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file47_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file48_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file49_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file4_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file50_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file51_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file52_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file53_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file54_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file55_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file56_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file57_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file58_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file59_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file5_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file60_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file61_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file62_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file63_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file64_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file65_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file66_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file67_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file68_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file69_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file6_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file70_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file71_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file72_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file73_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file74_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file75_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file76_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file77_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file78_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file79_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file7_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file80_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file81_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file82_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file83_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file84_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file85_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file86_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file87_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file88_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file89_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file8_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file90_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file91_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file92_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file93_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file94_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file95_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file96_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file97_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file98_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file99_output.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file9_output.data"]


files_test: ["/data/nlahaye/output/Learnergy/DBN_GENETICS/file0_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file10_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file11_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file12_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file13_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file14_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file15_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file1_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file2_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file3_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file4_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file5_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file6_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file7_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file8_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_GENETICS/file9_output_test.data"]

