
files_train: ["/data/nlahaye/output/Learnergy/DBN_HSL_S2_GARONNE/file0_output.data"]

files_test: [
"/data/nlahaye/output/Learnergy/DBN_HSL_S2_GARONNE/file0_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_HSL_S2_GARONNE/file1_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_HSL_S2_GARONNE/file2_output_test.data"]

#"/data/nlahaye/output/Learnergy/DBN_HSL_S2_GARONNE/file3_output_test.data"]
#"/data/nlahaye/output/Learnergy/DBN_HSL_S2_GARONNE/file4_output_test.data",
#"/data/nlahaye/output/Learnergy/DBN_HSL_S2_GARONNE/file5_output_test.data"] #,
#"/data/nlahaye/output/Learnergy/DBN_HSL_S2_GARONNE/file6_output_test.data"] #,
#"/data/nlahaye/output/Learnergy/DBN_HSL_S2_GARONNE/file7_output_test.data"] #,
#"/data/nlahaye/output/Learnergy/DBN_HSL_S2_GARONNE/file8_output_test.data", "/data/nlahaye/output/Learnergy/DBN_HSL_S2_GARONNE/file9_output_test.data"]
 
output:
 out_dir: "/data/nlahaye/output/Learnergy/DBN_HSL_S2_GARONNE/"


clustering:
        n_clusters: 500
        branch: 5
        thresh: 1e-5
        pixel_padding: 1
        train_sample_size: 150000 #000
        clustering:
        train: True
        reset_n_clusters: True
        model:  

scaler:
 name: "standard_dask"
 scale: True


