files_train: ["/data/nlahaye/output/Learnergy/DBN_MISR_MODIS_1/file0_output.data",
"/data/nlahaye/output/Learnergy/DBN_MISR_MODIS_1/file1_output.data",
"/data/nlahaye/output/Learnergy/DBN_MISR_MODIS_1/file2_output.data"]
files_test: ["/data/nlahaye/output/Learnergy/DBN_MISR_MODIS_1/file0_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_MISR_MODIS_1/file1_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_MISR_MODIS_1/file2_output_test.data"]
 

output:
 out_dir: "/data/nlahaye/output/Learnergy/DBN_MISR_MODIS_1/"


clustering:
        n_clusters: 500
        branch: 5
        thresh: 1e-5
        pixel_padding: 1
        train_sample_size: 1500000
        clustering:
        train: True
        reset_n_clusters: True
        model:  


scaler:
 name: "standard_dask"
 scale: True
