output:
 out_dir: "/data/nlahaye/output/Learnergy/DBN_MISR_SIMULATED/"


clustering:
        n_clusters: 20
        branch: 5
        thresh: 1e-15
        pixel_padding: 1
        train_sample_size: 150000 #000
        clustering:
        train: True
        reset_n_clusters: True
        model:

scaler:
 name: "standard_dask"
 scale: True

files_train: ["/data/nlahaye/output/Learnergy/DBN_MISR_SIMULATED/file0_output.data",
"/data/nlahaye/output/Learnergy/DBN_MISR_SIMULATED/file1_output.data",
"/data/nlahaye/output/Learnergy/DBN_MISR_SIMULATED/file2_output.data",
"/data/nlahaye/output/Learnergy/DBN_MISR_SIMULATED/file3_output.data",
"/data/nlahaye/output/Learnergy/DBN_MISR_SIMULATED/file4_output.data",
"/data/nlahaye/output/Learnergy/DBN_MISR_SIMULATED/file5_output.data",
"/data/nlahaye/output/Learnergy/DBN_MISR_SIMULATED/file6_output.data",
"/data/nlahaye/output/Learnergy/DBN_MISR_SIMULATED/file7_output.data",
"/data/nlahaye/output/Learnergy/DBN_MISR_SIMULATED/file8_output.data"]

files_test: ["/data/nlahaye/output/Learnergy/DBN_MISR_SIMULATED/file0_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_MISR_SIMULATED/file1_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_MISR_SIMULATED/file2_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_MISR_SIMULATED/file3_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_MISR_SIMULATED/file4_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_MISR_SIMULATED/file5_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_MISR_SIMULATED/file6_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_MISR_SIMULATED/file7_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_MISR_SIMULATED/file8_output_test.data"]

