output:
 out_dir: "/content/drive/MyDrive/oil_palm_data_science/ML_Test/"


clustering:
        n_clusters: 100
        branch: 5
        thresh: 1e-5
        pixel_padding: 1
        train_sample_size: 150000 #000
        clustering: "/content/drive/MyDrive/oil_palm_data_science/ML_Test/clustering_centroids.pkl"
        train: False
        reset_n_clusters: False
        model: "/content/drive/MyDrive/oil_palm_data_science/ML_Test/clustering_centroids.pkl"

scaler:
 name: "standard_dask"
 scale: True


files_train: ["/content/drive/MyDrive/oil_palm_data_science/ML_Test/file0_output.data"]

files_test: ["/content/drive/MyDrive/oil_palm_data_science/ML_Test/file0_output.data"]

