 
files_train: ["/data/nlahaye/output/Learnergy/DBN_TROP_L1B/file0_output.data", "/data/nlahaye/output/Learnergy/DBN_TROP_L1B/file1_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_L1B/file2_output.data", "/data/nlahaye/output/Learnergy/DBN_TROP_L1B/file3_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_L1B/file4_output.data"]

files_test: ["/data/nlahaye/output/Learnergy/DBN_TROP_L1B/file0_output_test.data"]

output:
 out_dir: "/data/nlahaye/output/Learnergy/DBN_TROP_L1B/"

clustering:
        n_clusters: 500
        branch: 5
        thresh: 1e-5
        pixel_padding: 1
        train_sample_size: 150000 #000
        clustering:
        train: True
        chunks: 2000
        reset_n_clusters: True
        model:  

scaler:
 name: "standard"
 scale: True


