dbf: True
dbf_percentage_thresh: 0.51
dbf_list:
  [

    [ "/home/stasya/DBF_final/MASTER/Sheridan/20190816/shapes/labels/fire/MASTERL1B_1981724_02_20190816_0033_0033_V01_fire_OUTPUT_0.dbf",
      "/home/stasya/DBF_final/MASTER/Sheridan/20190816/shapes/labels/fire/MASTERL1B_1981724_04_20190816_0106_0107_V01_fire_OUTPUT_0.dbf",
      "/home/stasya/DBF_final/MASTER/Sheridan/20190816/shapes/labels/fire/MASTERL1B_1981724_05_20190816_0124_0125_V01_fire_OUTPUT_0.dbf",
      "/home/stasya/DBF_final/MASTER/Sheridan/20190816/shapes/labels/fire/MASTERL1B_1981724_06_20190816_0139_0140_V01_fire_OUTPUT_0.dbf",

      "/home/stasya/DBF_final/MASTER/Sheridan/20190817/shapes/labels/fire/MASTERL1B_1981725_01_20190817_0004_0007_V01_fire_OUTPUT_0.dbf",
      "/home/stasya/DBF_final/MASTER/Sheridan/20190817/shapes/labels/fire/MASTERL1B_1981725_02_20190817_0025_0026_V01_fire_OUTPUT_0.dbf" ],

    [ "/home/stasya/DBF_final/MASTER/Sheridan/20190816/shapes/background/fire_background/MASTERL1B_1981724_02_20190816_0033_0033_V01_fire_background_OUTPUT_0.dbf",
      "/home/stasya/DBF_final/MASTER/Sheridan/20190816/shapes/background/fire_background/MASTERL1B_1981724_04_20190816_0106_0107_V01_fire_background_OUTPUT_0.dbf",
      "/home/stasya/DBF_final/MASTER/Sheridan/20190816/shapes/background/fire_background/MASTERL1B_1981724_05_20190816_0124_0125_V01_fire_background_OUTPUT_0.dbf",
      "/home/stasya/DBF_final/MASTER/Sheridan/20190816/shapes/background/fire_background/MASTERL1B_1981724_06_20190816_0139_0140_V01_fire_background_OUTPUT_0.dbf",

      "/home/stasya/DBF_final/MASTER/Sheridan/20190817/shapes/background/fire_background/MASTERL1B_1981725_01_20190817_0004_0007_V01_fire_background_OUTPUT_0.dbf",
      "/home/stasya/DBF_final/MASTER/Sheridan/20190817/shapes/background/fire_background/MASTERL1B_1981725_02_20190817_0025_0026_V01_fire_background_OUTPUT_0.dbf" ]

  ]