dbf: True
dbf_percentage_thresh: 0.51

dbf_list: [
  ["/mnt/data/GOES/DBF/goes_cloud_mask_OUTPUT_0.dbf",
   "/mnt/data/GOES/DBF/goes_cloud_mask_2_OUTPUT_0.dbf",
   "/mnt/data/GOES/DBF/goes_cloud_mask_3_OUTPUT_0.dbf",
   "/mnt/data/GOES/DBF/goes_cloud_mask_4_OUTPUT_0.dbf",
   "/mnt/data/GOES/DBF/goes_cloud_mask_5_OUTPUT_0.dbf",
   "/mnt/data/GOES/DBF/goes_cloud_mask_6_OUTPUT_0.dbf"]
]



