




dbf_list: [[
        #'/mnt/data/HAB_MODEL_WEIGHTS/OC_SIF_HABs_2025/JPSS2_VIIRS/tiered_hab_hist_dict.pkl'
'/mnt/data/HAB_MODEL_WEIGHTS/OC_SIF_HABs_2025/JPSS2_VIIRS/S_CA/tiered_hab_hist_dict.pkl'
]]
dbf: True
dbf_percentage_thresh: 0.51



