dbf: True
dbf_percentage_thresh: 0.51

dbf_list: [
  ["/mnt/data/OUTPUTDBF/goes_background_2025006_OUTPUT_0.dbf",
"/mnt/data/OUTPUTDBF/goes_background_2025007_OUTPUT_0.dbf",
"/mnt/data/OUTPUTDBF/goes_background_2025008_OUTPUT_0.dbf",
"/mnt/data/OUTPUTDBF/goes_background_2025009_OUTPUT_0.dbf",
"/mnt/data/OUTPUTDBF/goes_background_2025010_OUTPUT_0.dbf",
"/mnt/data/OUTPUTDBF/goes_background_2025011_OUTPUT_0.dbf",
"/mnt/data/OUTPUTDBF/goes_background_2025012_OUTPUT_0.dbf",
"/mnt/data/OUTPUTDBF/goes_background_2025013_OUTPUT_0.dbf"],

 ["/mnt/data/OUTPUTDBF/goes_cloud_2025006_OUTPUT_0.dbf",
"/mnt/data/OUTPUTDBF/goes_cloud_2025007_OUTPUT_0.dbf",
"/mnt/data/OUTPUTDBF/goes_cloud_2025008_OUTPUT_0.dbf",
"/mnt/data/OUTPUTDBF/goes_cloud_2025009_OUTPUT_0.dbf",
"/mnt/data/OUTPUTDBF/goes_cloud_2025010_OUTPUT_0.dbf",
"/mnt/data/OUTPUTDBF/goes_cloud_2025011_OUTPUT_0.dbf",
"/mnt/data/OUTPUTDBF/goes_cloud_2025012_OUTPUT_0.dbf",
"/mnt/data/OUTPUTDBF/goes_cloud_2025013_OUTPUT_0.dbf"]
]



