  
input_paths: ["/data/nlahaye/output/Learnergy/No_Data/",
              "/data/nlahaye/output/Learnergy/No_Data/",
              "/mnt/data/HAB_MODEL_WEIGHTS/OC_SIF_HABs_2025/S3A_OLCI_S_CA/"]

 
fname_str: "alexandrium_bloom"
out_dir: "/mnt/data/HAB_MODEL_WEIGHTS/OC_SIF_HABs_2025/MERGED_HAB/S3A_OLCI/"
num_classes: 9
re_index: 5

gen_daily: false
gen_monthly: true


dirname: "/mnt/data/HAB_MODEL_WEIGHTS/OC_SIF_HABs_2025/MERGED_HAB/S3A_OLCI/"
max_dqi: 2
max_class: 5

