
data:
 val_percent: 0.1
 num_loader_workers: 10
 scale_data: True
 pixel_padding: 1
 number_channels: 34
 fill_value: -9999.0
 valid_min:  -900.0
 valid_max: 100000000
 subset_count: 1
 output_subset_count: 10
 reader_type: "numpy"
 reader_kwargs:
  no_arg: "no_arg"
 chan_dim: 0
 delete_chans: [25,26,36,37]
 transform_default:
  chans: []
  transform: []


 files_train: [
'/data/nlahaye/remoteSensing/eMAS/rad/eMASL1B_19910_10_20190806_1858_1910_V02_Georeferenced_scaled.tif.npy',
'/data/nlahaye/remoteSensing/eMAS/rad/eMASL1B_19911_10_20190807_2004_2016_V02_georeferenced_scaled.tif.npy',
'/data/nlahaye/remoteSensing/eMAS/rad/eMASL1B_19911_09_20190807_1947_2002_V02_georeferenced_scaled.tif.npy',
'/data/nlahaye/remoteSensing/eMAS/rad/eMASL1B_19912_07_20190808_1806_1821_V02_georeferenced_scaled.tif.npy',
]

 files_test: [
'/data/nlahaye/remoteSensing/eMAS/rad/eMASL1B_19911_05_20190807_1817_1833_V02_georeferenced_scaled.tif.npy',
'/data/nlahaye/remoteSensing/eMAS/rad/eMASL1B_19910_06_20190806_1815_1824_V02_Georeferenced_scaled.tif.npy',
'/data/nlahaye/remoteSensing/eMAS/rad/eMASL1B_19912_07_20190808_1806_1821_V02_georeferenced_scaled.tif.npy',
'/data/nlahaye/remoteSensing/eMAS/rad/eMASL1B_19910_21_20190806_2111_2125_V02_Georeferenced_scaled.tif.npy',
'/data/nlahaye/remoteSensing/eMAS/rad/eMASL1B_19910_19_20190806_2035_2048_V02_Georeferenced_scaled.tif.npy',
'/data/nlahaye/remoteSensing/eMAS/rad/eMASL1B_19911_08_20190807_1928_1942_V02_georeferenced_scaled.tif.npy',
'/data/nlahaye/remoteSensing/eMAS/rad/eMASL1B_19911_12_20190807_2039_2051_V02_georeferenced_scaled.tif.npy',
'/data/nlahaye/remoteSensing/eMAS/rad/eMASL1B_19911_11_20190807_2021_2035_V02_georeferenced_scaled.tif.npy',
'/data/nlahaye/remoteSensing/eMAS/rad/eMASL1B_19910_17_20190806_2000_2010_V02_Georeferenced_scaled.tif.npy',
'/data/nlahaye/remoteSensing/eMAS/rad/eMASL1B_19910_16_20190806_1941_1956_V02_Georeferenced_scaled.tif.npy',
'/data/nlahaye/remoteSensing/eMAS/rad/eMASL1B_19910_13_20190806_1923_1925_V02_Georeferenced_scaled.tif.npy',
'/data/nlahaye/remoteSensing/eMAS/rad/eMASL1B_19910_20_20190806_2052_2106_V02_Georeferenced_scaled.tif.npy',
'/data/nlahaye/remoteSensing/eMAS/rad/eMASL1B_19910_06_20190806_1815_1824_V02_Georeferenced_scaled.tif.npy',
'/data/nlahaye/remoteSensing/eMAS/rad/eMASL1B_19910_08_20190806_1834_1846_V02_Georeferenced_scaled.tif.npy',
'/data/nlahaye/remoteSensing/eMAS/rad/eMASL1B_19910_18_20190806_2018_2031_V02_Georeferenced_scaled.tif.npy',
'/data/nlahaye/remoteSensing/eMAS/rad/eMASL1B_19910_15_20190806_1931_1938_V02_Georeferenced_scaled.tif.npy',
'/data/nlahaye/remoteSensing/eMAS/rad/eMASL1B_19910_14_20190806_1926_1929_V02_Georeferenced_scaled.tif.npy',
'/data/nlahaye/remoteSensing/eMAS/rad/eMASL1B_19910_10_20190806_1858_1910_V02_Georeferenced_scaled.tif.npy',
'/data/nlahaye/remoteSensing/eMAS/rad/eMASL1B_19911_10_20190807_2004_2016_V02_georeferenced_scaled.tif.npy',
'/data/nlahaye/remoteSensing/eMAS/rad/eMASL1B_19911_09_20190807_1947_2002_V02_georeferenced_scaled.tif.npy']

scaler:
 name: "standard" 

output:
 out_dir: "/data/nlahaye/output/Learnergy/DBN_eMAS_FULL_STRAT_MULTI_LAYER_PL/"
 generate_train_output: False
 generate_output: False


dbn:
 conv: False
 subset_training: 2000000
 deep_cluster: 800
 heir_tiers: 1
 overwrite_model: False
 tune_clust: False
 tune_dbn: False
 tune_scaler: False
 model_type: ["gaussian_selu", "gaussian_selu"]
 dbn_arch: [2000, 1000] #[250, 500, 2000] #, 2000]
 gibbs_steps: [1,1] #, 7, 7] #, 10] #, 25]
 temp: [1.0, 1.0] #, 1.0, 1.0] ##[0.9, 0.75, 0.5] #, 1.0] #, 0.5] #, 0.5] 
 normalize_learnergy: [False, True]
 batch_normalize: [False, False]

encoder_type: "dbn"
encoder:
 tiled: False
 tune_scaler: False
 subset_training: -1
 overwrite_model: False
 training:
  learning_rate: [0.00001, 0.00001]
  momentum: [0.95,0.95]
  weight_decay: [0.0001, 0.0001]
  nesterov_accel: [True, True]
  batch_size: 128
  epochs: 30
  accelerator: "gpu"
  devices: 1
  gradient_clip_val: 0.1
  precision: "16-mixed"
  stratify_data:
   kmeans: True


logger:
 use_wandb: True
 log_model: True
 log_out_dir: "wandb_dbn"
 project: "SIT-FUSE"

cluster:
 training:
  batch_size: 1000
  cluster_batch_size: 1000
  cluster_epochs: 30 #[10]#[8] #, 1, 1] #, 5] #, 10]
  cluster_gauss_noise_stdev:  [0.01]
  cluster_lambda: 1.0

  heir_cluster_min_samples: 1000
  heir_cluster_gauss_noise_stdev: [0.01] #[0.001, 0.0001, 0.00001, 0.000001, 0.0]
  heir_epochs: 30
  heir_tune_subtrees: False
  heir_tune_subtree_list: []
  heir_deep_cluster: 100

