
data:
 tile: False
 val_percent: 0.1
 num_loader_workers: 10
 scale_data: True
 pixel_padding: 1
 number_channels: 6
 fill_value: -9999.0
 valid_min:  -900.0
 valid_max: 100000000
 reader_type: "gtiff"
 reader_kwargs:
  no_arg: "no_arg"
 chan_dim: 0
 delete_chans: []
 transform_default:
  chans: []
  transform: []


 files_train: [
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_211401Z_WA-Hunters_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_205524Z_WA-ElectricCity_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_192738Z_WA-Davenport_SWPA_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190808_181058Z_WA-GrandCoulee_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190808_182451Z_ID-Athol_SWPF_F01_V006.hdf.tif"
]


 files_test: [
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190807_183615Z_ID-TwinLakes_SWPA_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_192233Z_WA-DeerPark_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190807_192648Z_WA-Mead_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190807_193951Z_WA-Mansfield_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_181938Z_WA-Keller_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190807_195042Z_WA-Mansfield_SWPA_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190807_193031Z_WA-NineMileFalls_SWPA_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_212231Z_WA-CouleeCity_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_192839Z_WA-Fruitland_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_205433Z_WA-CouleeCity_SWPA_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_185910Z_WA-Lamona_SWPA_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_200125Z_WA-Valley_SWPA_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190807_202410Z_WA-Hartline_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190807_195133Z_WA-GrandCoulee_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_195257Z_WA-Springdale_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_192536Z_WA-Reardan_SWPA_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190807_204139Z_WA-Springdale_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_194337Z_WA-Mansfield_SWPA_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_200215Z_WA-Valley_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_181433Z_WA-Harrington_SWPA_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_201956Z_WA-CouleeCity_SWPA_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_181837Z_WA-Keller_SWPA_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190807_183140Z_WA-Springdale_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_193440Z_WA-ElectricCity_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_202916Z_WA-Tumtum_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_204558Z_WA-Mansfield_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_184409Z_WA-Ford_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_202047Z_WA-Hartline_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190807_200625Z_WA-Ford_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190807_182220Z_WA-Mansfield_SWPA_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_181736Z_WA-Wilbur_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_193041Z_WA-Keller_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_183449Z_WA-Mansfield_SWPA_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_192637Z_WA-Reardan_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190808_181927Z_WA-Clayton_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190808_182400Z_ID-Rathdrum_SWPA_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_192334Z_WA-DeerPark_SWPA_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190807_200534Z_WA-NineMileFalls_SWPA_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_190001Z_WA-Harrington_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_194428Z_WA-Mansfield_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190807_203239Z_WA-Chewelah_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_181635Z_WA-Creston_SWPA_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_201045Z_WA-Okanogan_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_203728Z_WA-Springdale_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190807_204048Z_WA-LoonLake_SWPA_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_192435Z_WA-Tumtum_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_182241Z_WA-Keller_SWPA_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_182140Z_WA-Keller_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190807_193122Z_WA-Ford_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190808_181007Z_WA-Mansfield_SWPA_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190807_205008Z_WA-Mansfield_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190807_201454Z_WA-Mansfield_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_192940Z_WA-Inchelium_SWPA_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_183540Z_WA-Mansfield_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_211311Z_WA-Chewelah_SWPA_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_190830Z_WA-Republic_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_181534Z_WA-Creston_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190807_200002Z_WA-Springdale_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_193340Z_WA-Almira_SWPA_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_182039Z_WA-Keller_SWPA_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_210353Z_WA-Ford_SWPF_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_193517Z_WA-Waterville_SWPA_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190807_202319Z_WA-Hartline_SWPA_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_192132Z_WA-LoonLake_SWPA_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190806_203638Z_WA-Valley_SWPA_F01_V006.hdf.tif",
"/data/nlahaye/remoteSensing/MSPI/sweep/AirMSPI_ER2_GRP_TERRAIN_20190807_182311Z_WA-GrandCoulee_SWPF_F01_V006.hdf.tif"
]

scaler:
 name: "standard" 

output:
 out_dir: "/data/nlahaye/output/Learnergy/DBN_MSPI_SWEEP_MULTI_LAYER_PL/"
 generate_intermediate_output: True


dbn:
 model_type: ["gaussian_selu", "gaussian_selu"]
 dbn_arch: [2000, 1000] #[250, 500, 2000] #, 2000]
 gibbs_steps: [1,1] #, 7, 7] #, 10] #, 25]
 temp: [1.0, 1.0] #, 1.0, 1.0] ##[0.9, 0.75, 0.5] #, 1.0] #, 0.5] #, 0.5] 
 normalize_learnergy: [False, True]
 batch_normalize: [False, False]

encoder_type: "dbn"
encoder:
 tiled: False
 tune_scaler: False
 subset_training: 2000000
 overwrite_model: False
 training:
  learning_rate: [0.00001, 0.00001]
  momentum: [0.95,0.95]
  weight_decay: [0.0001, 0.0001]
  nesterov_accel: [True, True]
  batch_size: 128
  epochs: 30
  accelerator: "gpu"
  devices: 1
  gradient_clip_val: 0.1
  precision: "16-mixed"
  save_dir: "wandb_encoder"
  stratify_data:
   kmeans: True


logger:
 use_wandb: True
 log_model: True
 log_out_dir: "wandb_dbn"
 project: "SIT-FUSE"

cluster:
 gauss_noise_stdev:  [0.01]
 lambda: 1.0
 num_classes: 800
 training:
  learning_rate: 0.0001
  batch_size: 1000
  epochs: 30
  accelerator: "gpu"
  devices: 1
  gradient_clip_val: 0.1
  precision: "16-mixed"
  save_dir: "wandb_full_model"

 heir:
  tiers: 1
  gauss_noise_stdev:  [0.01]
  lambda: 1.0
  num_classes: 100
  training:
   accelerator: "gpu"
   devices: 1
   gradient_clip_val: 0.1
   precision: "16-mixed"
   save_dir: "wandb_dbn_full_model_heir"
   batch_size: 100
   min_samples: 1000
   learning_rate: 0.0001
   batch_size: 1000
   epochs: 30



