
scaler:
 name: "standard"

data:
 tile: false
 val_percent: 0.1
 num_loader_workers: 10
 scale_data: True
 pixel_padding: 1
 number_channels: 13
 fill_value: -9999.0
 valid_min: -9000.0
 valid_max: 1000000
 reader_type: "gtiff_multifile"
 reader_kwargs:
  no_arg: ''
 chan_dim: 0
 delete_chans: []
 transform_default:
  chans: []
  transform: []
 files_train: [
["/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190808T184921_B01_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190808T184921_B02_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190808T184921_B03_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190808T184921_B04_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190808T184921_B05_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190808T184921_B06_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190808T184921_B07_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190808T184921_B08_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190808T184921_B09_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190808T184921_B10_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190808T184921_B11_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190808T184921_B12_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190808T184921_B8A_clip.tif"],
["/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190813T184929_B01_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190813T184929_B02_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190813T184929_B03_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190813T184929_B04_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190813T184929_B05_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190813T184929_B06_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190813T184929_B07_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190813T184929_B08_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190813T184929_B09_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190813T184929_B10_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190813T184929_B11_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190813T184929_B12_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190813T184929_B8A_clip.tif"],
["/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11UMP_20190813T184929_B01_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11UMP_20190813T184929_B02_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11UMP_20190813T184929_B03_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11UMP_20190813T184929_B04_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11UMP_20190813T184929_B05_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11UMP_20190813T184929_B06_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11UMP_20190813T184929_B07_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11UMP_20190813T184929_B08_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11UMP_20190813T184929_B09_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11UMP_20190813T184929_B10_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11UMP_20190813T184929_B11_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11UMP_20190813T184929_B12_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11UMP_20190813T184929_B8A_clip.tif"],
["/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11UMP_20190808T184921_B01_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11UMP_20190808T184921_B02_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11UMP_20190808T184921_B03_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11UMP_20190808T184921_B04_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11UMP_20190808T184921_B05_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11UMP_20190808T184921_B06_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11UMP_20190808T184921_B07_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11UMP_20190808T184921_B08_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11UMP_20190808T184921_B09_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11UMP_20190808T184921_B10_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11UMP_20190808T184921_B11_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11UMP_20190808T184921_B12_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11UMP_20190808T184921_B8A_clip.tif"]
]

 files_test: [
["/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190806T185929_B01_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190806T185929_B02_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190806T185929_B03_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190806T185929_B04_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190806T185929_B05_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190806T185929_B06_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190806T185929_B07_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190806T185929_B08_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190806T185929_B09_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190806T185929_B10_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190806T185929_B11_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190806T185929_B12_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190806T185929_B8A_clip.tif"],
["/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TLN_20190808T184921_B01_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TLN_20190808T184921_B02_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TLN_20190808T184921_B03_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TLN_20190808T184921_B04_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TLN_20190808T184921_B05_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TLN_20190808T184921_B06_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TLN_20190808T184921_B07_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TLN_20190808T184921_B08_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TLN_20190808T184921_B09_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TLN_20190808T184921_B10_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TLN_20190808T184921_B11_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TLN_20190808T184921_B12_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TLN_20190808T184921_B8A_clip.tif"],
["/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TMN_20190808T184921_B01_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TMN_20190808T184921_B02_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TMN_20190808T184921_B03_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TMN_20190808T184921_B04_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TMN_20190808T184921_B05_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TMN_20190808T184921_B06_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TMN_20190808T184921_B07_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TMN_20190808T184921_B08_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TMN_20190808T184921_B09_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TMN_20190808T184921_B10_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TMN_20190808T184921_B11_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TMN_20190808T184921_B12_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TMN_20190808T184921_B8A_clip.tif"],
["/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190811T185921_B01_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190811T185921_B02_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190811T185921_B03_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190811T185921_B04_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190811T185921_B05_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190811T185921_B06_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190811T185921_B07_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190811T185921_B08_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190811T185921_B09_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190811T185921_B10_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190811T185921_B11_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190811T185921_B12_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11ULP_20190811T185921_B8A_clip.tif"],
["/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TLN_20190813T184929_B01_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TLN_20190813T184929_B02_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TLN_20190813T184929_B03_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TLN_20190813T184929_B04_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TLN_20190813T184929_B05_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TLN_20190813T184929_B06_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TLN_20190813T184929_B07_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TLN_20190813T184929_B08_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TLN_20190813T184929_B09_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TLN_20190813T184929_B10_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TLN_20190813T184929_B11_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TLN_20190813T184929_B12_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TLN_20190813T184929_B8A_clip.tif"],
["/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TMN_20190813T184929_B01_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TMN_20190813T184929_B02_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TMN_20190813T184929_B03_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TMN_20190813T184929_B04_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TMN_20190813T184929_B05_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TMN_20190813T184929_B06_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TMN_20190813T184929_B07_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TMN_20190813T184929_B08_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TMN_20190813T184929_B09_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TMN_20190813T184929_B10_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TMN_20190813T184929_B11_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TMN_20190813T184929_B12_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Sentinel2L1C/T11TMN_20190813T184929_B8A_clip.tif"]
]


output:
 out_dir: "/data/nlahaye/output/Learnergy/DBN_S2_FIREX/"
 generate_train_output: True
 generate_intermediate_output: True


dbn:
 model_type: ["gaussian_selu", "gaussian_selu"]
 dbn_arch: [2000, 1000] #[250, 500, 2000] #, 2000]
 gibbs_steps: [1,1] #, 7, 7] #, 10] #, 25]
 temp: [1.0, 1.0] #, 1.0, 1.0] ##[0.9, 0.75, 0.5] #, 1.0] #, 0.5] #, 0.5] 
 normalize_learnergy: [False, True]
 batch_normalize: [False, False]

encoder_type: "dbn"
encoder:
 tiled: False
 tune_scaler: False
 subset_training: 2500000
 overwrite_model: False
 training:
  learning_rate: [0.00001, 0.00001]
  momentum: [0.95,0.95]
  weight_decay: [0.0001, 0.0001]
  nesterov_accel: [True, True]
  batch_size: 128
  epochs: 30
  accelerator: "gpu"
  devices: 1
  gradient_clip_val: 0.1
  precision: "16-mixed"
  save_dir: "wandb_encoder"
  stratify_data:
   kmeans: True


logger:
 use_wandb: True
 log_model: True
 log_out_dir: "wandb_dbn"
 project: "SIT-FUSE"

cluster:
 gauss_noise_stdev:  [0.01]
 lambda: 1.0
 num_classes: 800
 training:
  learning_rate: 0.0001
  batch_size: 1000
  epochs: 30
  accelerator: "gpu"
  devices: 1
  gradient_clip_val: 0.1
  precision: "16-mixed"
  save_dir: "wandb_full_model"

 heir:
  tiers: 1
  gauss_noise_stdev:  [0.01]
  lambda: 1.0
  num_classes: 100
  training:
   accelerator: "gpu"
   devices: 1
   gradient_clip_val: 0.1
   precision: "16-mixed"
   save_dir: "wandb_dbn_full_model_heir"
   batch_size: 100
   min_samples: 1000
   learning_rate: 0.0001
   batch_size: 1000
   epochs: 30



