data:
 num_loader_workers: 10
 scale_data: True
 pixel_padding: 1
 number_channels: 72
 fill_value: -9999.0
 valid_min: -900.0 #0.0000001
 valid_max: 100000000
 subset_count: 1
 output_subset_count: 10
 reader_type: "numpy"
 reader_kwargs:
  no_arg: "no_arg"
 chan_dim: 2
 delete_chans: []
 transform_default:
  chans: []
  transform: []
   
 files_train: ["/data/nlahaye/remoteSensing/MSPI/2019-08-06/194843Z_WA-Keller/AirMSPI_ER2_GRP_ELLIPSOID_20190806_195205Z_WA-Keller_STEP_AND_STARE_FUSE.npy",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/200630Z_WA-Keller/AirMSPI_ER2_GRP_ELLIPSOID_20190806_200308Z_WA-Keller_STEP_AND_STARE_FUSE.npy",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/211816Z_WA-Wilbur/AirMSPI_ER2_GRP_ELLIPSOID_20190806_211454Z_WA-Wilbur_STEP_AND_STARE_FUSE.npy",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/202501Z_WA-Creston/AirMSPI_ER2_GRP_ELLIPSOID_20190806_202139Z_WA-Creston_STEP_AND_STARE_FUSE.npy",
"/data/nlahaye/remoteSensing/MSPI/2019-08-07/201039Z_WA-Lincoln/AirMSPI_ER2_GRP_ELLIPSOID_20190807_200717Z_WA-Lincoln_STEP_AND_STARE_FUSE.npy",
"/data/nlahaye/remoteSensing/MSPI/2019-08-07/195548Z_WA-Inchelium/AirMSPI_ER2_GRP_ELLIPSOID_20190807_195226Z_WA-Inchelium_STEP_AND_STARE_FUSE.npy",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/204143Z_WA-Keller/AirMSPI_ER2_GRP_ELLIPSOID_20190806_203821Z_WA-Keller_STEP_AND_STARE_FUSE.npy",
"/data/nlahaye/remoteSensing/MSPI/2019-08-07/204554Z_WA-Inchelium/AirMSPI_ER2_GRP_ELLIPSOID_20190807_204916Z_WA-Inchelium_STEP_AND_STARE_FUSE.npy"]


 files_test: ["/data/nlahaye/remoteSensing/MSPI/2019-08-07/202824Z_WA-Inchelium/AirMSPI_ER2_GRP_ELLIPSOID_20190807_202502Z_WA-Inchelium_STEP_AND_STARE_FUSE.npy",
 "/data/nlahaye/remoteSensing/MSPI/2019-08-07/182726Z_WA-Inchelium/AirMSPI_ER2_GRP_ELLIPSOID_20190807_182404Z_WA-Inchelium_STEP_AND_STARE_FUSE.npy",
 "/data/nlahaye/remoteSensing/MSPI/2019-08-06/190416Z_WA-Keller/AirMSPI_ER2_GRP_ELLIPSOID_20190806_190738Z_WA-Keller_STEP_AND_STARE_FUSE.npy",
 "/data/nlahaye/remoteSensing/MSPI/2019-08-08/181513Z_WA-Inchelium/AirMSPI_ER2_GRP_ELLIPSOID_20190808_181835Z_WA-Inchelium_STEP_AND_STARE_FUSE.npy",
 "/data/nlahaye/remoteSensing/MSPI/2019-08-07/193536Z_WA-Inchelium/AirMSPI_ER2_GRP_ELLIPSOID_20190807_193859Z_WA-Inchelium_STEP_AND_STARE_FUSE.npy",
 "/data/nlahaye/remoteSensing/MSPI/2019-08-06/205939Z_WA-Wilbur/AirMSPI_ER2_GRP_ELLIPSOID_20190806_205617Z_WA-Wilbur_STEP_AND_STARE_FUSE.npy",
 "/data/nlahaye/remoteSensing/MSPI/2019-08-06/183954Z_WA-Keller/AirMSPI_ER2_GRP_ELLIPSOID_20190806_184317Z_WA-Keller_STEP_AND_STARE_FUSE.npy"]

scaler:
 name: "standard" 

output:
 out_dir: "/data/nlahaye/output/Learnergy/DBN_MSPI_STEP_AND_STARE_PAD_MULTI_LAYER/"
 training_output: "output.data"
 training_mse: "rec_mse.data"
 testing_output: "output_test.data"
 testing_mse: "rec_mse_test.data"
 generate_train_output: True
 generate_output: True
 model: "dbn"

dbn:
 conv: False
 subset_training: 2000000
 deep_cluster: 800
 heir_tiers: 1
 overwrite_model: False
 tune_clust: False
 tune_dbn: False
 tune_scaler: False
 params:
  model_type: ["gaussian_selu", "gaussian_selu"] 
  dbn_arch: [2000, 1000] #[250, 500, 2000] #, 2000]
  gibbs_steps: [1,1] #, 7, 7] #, 10] #, 25]
  learning_rate: [0.00001, 0.00001] #, 0.0001, 0.0001] #, 0.01] #, 0.01]
  momentum: [0.95, 0.95] #, 0.95, 0.95] #, 0.95] #, 0.95]
  decay: [0.0001, 0.0001] #, 0.0001, 0.0001] #, 0.0001] #, 0.0001]
  temp: [1.0, 1.0] #, 1.0, 1.0] ##[0.9, 0.75, 0.5] #, 1.0] #, 0.5] #, 0.5] 
  nesterov_accel: [True, True]
  normalize_learnergy: [False, True]
  batch_normalize: [False, False]

 training:
  use_gpu_preprocessing: False
  use_gpu: True
  world_size: 1
  rank: 0
  device_ids: ["5"]
  batch_size: 1000
  epochs: [10,10] 
  cluster_batch_size: 1000
  cluster_epochs: 30
  cluster_gauss_noise_stdev: [0.01]
  cluster_lambda: 1.0

  heir_cluster_min_samples: 1000
  heir_cluster_gauss_noise_stdev: [0.01] #[0.001, 0.0001, 0.00001, 0.000001, 0.0]
  heir_epochs: 30
  heir_tune_subtrees: False
  heir_tune_subtree_list: []
  heir_deep_cluster: 100
  stratify_data:
   kmeans: True

