data:
 num_loader_workers: 10
 scale_data: True
 pixel_padding: 1
 number_channels: 6
 fill_value: -9999.0
 valid_min: -900.0 #0.0000001
 valid_max: 100000000
 subset_count: 1
 output_subset_count: 10
 reader_type: "mspi"
 reader_kwargs:
  no_arg: "no_arg"
 chan_dim: 0
 delete_chans: []
 transform_default:
  chans: []
  transform: []
  
 files_train: ["/data/nlahaye/remoteSensing/MSPI/2019-08-06/181938Z_WA-Keller/AirMSPI_ER2_GRP_ELLIPSOID_20190806_181938Z_WA-Keller_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/200215Z_WA-Valley/AirMSPI_ER2_GRP_ELLIPSOID_20190806_200215Z_WA-Valley_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-07/205008Z_WA-Mansfield/AirMSPI_ER2_GRP_ELLIPSOID_20190807_205008Z_WA-Mansfield_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/200125Z_WA-Valley/AirMSPI_ER2_GRP_ELLIPSOID_20190806_200125Z_WA-Valley_SWPA_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/205524Z_WA-ElectricCity/AirMSPI_ER2_GRP_ELLIPSOID_20190806_205524Z_WA-ElectricCity_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-07/193122Z_WA-Ford/AirMSPI_ER2_GRP_ELLIPSOID_20190807_193122Z_WA-Ford_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-07/193951Z_WA-Mansfield/AirMSPI_ER2_GRP_ELLIPSOID_20190807_193951Z_WA-Mansfield_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-07/200625Z_WA-Ford/AirMSPI_ER2_GRP_ELLIPSOID_20190807_200625Z_WA-Ford_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-08/182451Z_ID-Athol/AirMSPI_ER2_GRP_ELLIPSOID_20190808_182451Z_ID-Athol_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/212231Z_WA-CouleeCity/AirMSPI_ER2_GRP_ELLIPSOID_20190806_212231Z_WA-CouleeCity_SWPF_F01_V006.hdf"]
 



 
 files_test: [
"/data/nlahaye/remoteSensing/MSPI/2019-08-07/193122Z_WA-Ford/AirMSPI_ER2_GRP_ELLIPSOID_20190807_193122Z_WA-Ford_SWPF_F01_V006.hdf",
#"/data/nlahaye/remoteSensing/MSPI/2019-08-07/193951Z_WA-Mansfield/AirMSPI_ER2_GRP_ELLIPSOID_20190807_193951Z_WA-Mansfield_SWPF_F01_V006.hdf",
#"/data/nlahaye/remoteSensing/MSPI/2019-08-07/200625Z_WA-Ford/AirMSPI_ER2_GRP_ELLIPSOID_20190807_200625Z_WA-Ford_SWPF_F01_V006.hdf",
#"/data/nlahaye/remoteSensing/MSPI/2019-08-08/182451Z_ID-Athol/AirMSPI_ER2_GRP_ELLIPSOID_20190808_182451Z_ID-Athol_SWPF_F01_V006.hdf",
#"/data/nlahaye/remoteSensing/MSPI/2019-08-06/212231Z_WA-CouleeCity/AirMSPI_ER2_GRP_ELLIPSOID_20190806_212231Z_WA-CouleeCity_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/190830Z_WA-Republic/AirMSPI_ER2_GRP_ELLIPSOID_20190806_190830Z_WA-Republic_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-08/182400Z_ID-Rathdrum/AirMSPI_ER2_GRP_ELLIPSOID_20190808_182400Z_ID-Rathdrum_SWPA_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/203638Z_WA-Valley/AirMSPI_ER2_GRP_ELLIPSOID_20190806_203638Z_WA-Valley_SWPA_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/193440Z_WA-ElectricCity/AirMSPI_ER2_GRP_ELLIPSOID_20190806_193440Z_WA-ElectricCity_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/205433Z_WA-CouleeCity/AirMSPI_ER2_GRP_ELLIPSOID_20190806_205433Z_WA-CouleeCity_SWPA_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/182241Z_WA-Keller/AirMSPI_ER2_GRP_ELLIPSOID_20190806_182241Z_WA-Keller_SWPA_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/192738Z_WA-Davenport/AirMSPI_ER2_GRP_ELLIPSOID_20190806_192738Z_WA-Davenport_SWPA_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-07/182311Z_WA-GrandCoulee/AirMSPI_ER2_GRP_ELLIPSOID_20190807_182311Z_WA-GrandCoulee_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/181534Z_WA-Creston/AirMSPI_ER2_GRP_ELLIPSOID_20190806_181534Z_WA-Creston_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/181433Z_WA-Harrington/AirMSPI_ER2_GRP_ELLIPSOID_20190806_181433Z_WA-Harrington_SWPA_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/185910Z_WA-Lamona/AirMSPI_ER2_GRP_ELLIPSOID_20190806_185910Z_WA-Lamona_SWPA_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/192940Z_WA-Inchelium/AirMSPI_ER2_GRP_ELLIPSOID_20190806_192940Z_WA-Inchelium_SWPA_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/182039Z_WA-Keller/AirMSPI_ER2_GRP_ELLIPSOID_20190806_182039Z_WA-Keller_SWPA_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-08/181058Z_WA-GrandCoulee/AirMSPI_ER2_GRP_ELLIPSOID_20190808_181058Z_WA-GrandCoulee_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/203728Z_WA-Springdale/AirMSPI_ER2_GRP_ELLIPSOID_20190806_203728Z_WA-Springdale_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/192637Z_WA-Reardan/AirMSPI_ER2_GRP_ELLIPSOID_20190806_192637Z_WA-Reardan_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/190001Z_WA-Harrington/AirMSPI_ER2_GRP_ELLIPSOID_20190806_190001Z_WA-Harrington_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/192536Z_WA-Reardan/AirMSPI_ER2_GRP_ELLIPSOID_20190806_192536Z_WA-Reardan_SWPA_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/193041Z_WA-Keller/AirMSPI_ER2_GRP_ELLIPSOID_20190806_193041Z_WA-Keller_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-07/182220Z_WA-Mansfield/AirMSPI_ER2_GRP_ELLIPSOID_20190807_182220Z_WA-Mansfield_SWPA_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-07/200002Z_WA-Springdale/AirMSPI_ER2_GRP_ELLIPSOID_20190807_200002Z_WA-Springdale_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/181635Z_WA-Creston/AirMSPI_ER2_GRP_ELLIPSOID_20190806_181635Z_WA-Creston_SWPA_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-07/202410Z_WA-Hartline/AirMSPI_ER2_GRP_ELLIPSOID_20190807_202410Z_WA-Hartline_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-07/183615Z_ID-TwinLakes/AirMSPI_ER2_GRP_ELLIPSOID_20190807_183615Z_ID-TwinLakes_SWPA_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-07/195133Z_WA-GrandCoulee/AirMSPI_ER2_GRP_ELLIPSOID_20190807_195133Z_WA-GrandCoulee_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-07/203239Z_WA-Chewelah/AirMSPI_ER2_GRP_ELLIPSOID_20190807_203239Z_WA-Chewelah_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-07/183140Z_WA-Springdale/AirMSPI_ER2_GRP_ELLIPSOID_20190807_183140Z_WA-Springdale_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/211401Z_WA-Hunters/AirMSPI_ER2_GRP_ELLIPSOID_20190806_211401Z_WA-Hunters_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/202916Z_WA-Tumtum/AirMSPI_ER2_GRP_ELLIPSOID_20190806_202916Z_WA-Tumtum_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-07/192648Z_WA-Mead/AirMSPI_ER2_GRP_ELLIPSOID_20190807_192648Z_WA-Mead_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/193340Z_WA-Almira/AirMSPI_ER2_GRP_ELLIPSOID_20190806_193340Z_WA-Almira_SWPA_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/202047Z_WA-Hartline/AirMSPI_ER2_GRP_ELLIPSOID_20190806_202047Z_WA-Hartline_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/181736Z_WA-Wilbur/AirMSPI_ER2_GRP_ELLIPSOID_20190806_181736Z_WA-Wilbur_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/201956Z_WA-CouleeCity/AirMSPI_ER2_GRP_ELLIPSOID_20190806_201956Z_WA-CouleeCity_SWPA_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/194337Z_WA-Mansfield/AirMSPI_ER2_GRP_ELLIPSOID_20190806_194337Z_WA-Mansfield_SWPA_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/192233Z_WA-DeerPark/AirMSPI_ER2_GRP_ELLIPSOID_20190806_192233Z_WA-DeerPark_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/184409Z_WA-Ford/AirMSPI_ER2_GRP_ELLIPSOID_20190806_184409Z_WA-Ford_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-07/200534Z_WA-NineMileFalls/AirMSPI_ER2_GRP_ELLIPSOID_20190807_200534Z_WA-NineMileFalls_SWPA_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/183449Z_WA-Mansfield/AirMSPI_ER2_GRP_ELLIPSOID_20190806_183449Z_WA-Mansfield_SWPA_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-07/195042Z_WA-Mansfield/AirMSPI_ER2_GRP_ELLIPSOID_20190807_195042Z_WA-Mansfield_SWPA_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-07/204139Z_WA-Springdale/AirMSPI_ER2_GRP_ELLIPSOID_20190807_204139Z_WA-Springdale_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/182140Z_WA-Keller/AirMSPI_ER2_GRP_ELLIPSOID_20190806_182140Z_WA-Keller_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/192132Z_WA-LoonLake/AirMSPI_ER2_GRP_ELLIPSOID_20190806_192132Z_WA-LoonLake_SWPA_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/210353Z_WA-Ford/AirMSPI_ER2_GRP_ELLIPSOID_20190806_210353Z_WA-Ford_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-07/202319Z_WA-Hartline/AirMSPI_ER2_GRP_ELLIPSOID_20190807_202319Z_WA-Hartline_SWPA_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-07/201454Z_WA-Mansfield/AirMSPI_ER2_GRP_ELLIPSOID_20190807_201454Z_WA-Mansfield_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/204558Z_WA-Mansfield/AirMSPI_ER2_GRP_ELLIPSOID_20190806_204558Z_WA-Mansfield_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/181837Z_WA-Keller/AirMSPI_ER2_GRP_ELLIPSOID_20190806_181837Z_WA-Keller_SWPA_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/195257Z_WA-Springdale/AirMSPI_ER2_GRP_ELLIPSOID_20190806_195257Z_WA-Springdale_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/211311Z_WA-Chewelah/AirMSPI_ER2_GRP_ELLIPSOID_20190806_211311Z_WA-Chewelah_SWPA_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/192839Z_WA-Fruitland/AirMSPI_ER2_GRP_ELLIPSOID_20190806_192839Z_WA-Fruitland_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-08/181927Z_WA-Clayton/AirMSPI_ER2_GRP_ELLIPSOID_20190808_181927Z_WA-Clayton_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/201045Z_WA-Okanogan/AirMSPI_ER2_GRP_ELLIPSOID_20190806_201045Z_WA-Okanogan_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/193517Z_WA-Waterville/AirMSPI_ER2_GRP_ELLIPSOID_20190806_193517Z_WA-Waterville_SWPA_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-08/181007Z_WA-Mansfield/AirMSPI_ER2_GRP_ELLIPSOID_20190808_181007Z_WA-Mansfield_SWPA_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/192334Z_WA-DeerPark/AirMSPI_ER2_GRP_ELLIPSOID_20190806_192334Z_WA-DeerPark_SWPA_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/192435Z_WA-Tumtum/AirMSPI_ER2_GRP_ELLIPSOID_20190806_192435Z_WA-Tumtum_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-07/204048Z_WA-LoonLake/AirMSPI_ER2_GRP_ELLIPSOID_20190807_204048Z_WA-LoonLake_SWPA_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-07/193031Z_WA-NineMileFalls/AirMSPI_ER2_GRP_ELLIPSOID_20190807_193031Z_WA-NineMileFalls_SWPA_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/183540Z_WA-Mansfield/AirMSPI_ER2_GRP_ELLIPSOID_20190806_183540Z_WA-Mansfield_SWPF_F01_V006.hdf",
"/data/nlahaye/remoteSensing/MSPI/2019-08-06/194428Z_WA-Mansfield/AirMSPI_ER2_GRP_ELLIPSOID_20190806_194428Z_WA-Mansfield_SWPF_F01_V006.hdf"]



scaler:
 name: "standard" 

output:
 out_dir: "/data/nlahaye/output/Learnergy/DBN_MSPI_SWEEP_PAD_MULTI_LAYER/"
 training_output: "output.data"
 training_mse: "rec_mse.data"
 testing_output: "output_test.data"
 testing_mse: "rec_mse_test.data"
 generate_train_output: False
 generate_output: False
 model: "dbn"

dbn:
 conv: False
 subset_training: 2000000
 deep_cluster: 800
 heir_tiers: 1
 overwrite_model: False
 tune_clust: False
 tune_dbn: False
 tune_scaler: False
 params:
  model_type: ["gaussian_selu", "gaussian_selu"] 
  dbn_arch: [2000, 1000] #[250, 500, 2000] #, 2000]
  gibbs_steps: [1,1] #, 7, 7] #, 10] #, 25]
  learning_rate: [0.00001, 0.00001] #, 0.0001, 0.0001] #, 0.01] #, 0.01]
  momentum: [0.95, 0.95] #, 0.95, 0.95] #, 0.95] #, 0.95]
  decay: [0.0001, 0.0001] #, 0.0001, 0.0001] #, 0.0001] #, 0.0001]
  temp: [1.0, 1.0] #, 1.0, 1.0] ##[0.9, 0.75, 0.5] #, 1.0] #, 0.5] #, 0.5] 
  nesterov_accel: [True, True]
  normalize_learnergy: [False, True]
  batch_normalize: [False, False]

 training:
  use_gpu_preprocessing: False
  use_gpu: True
  world_size: 1
  rank: 0
  device_ids: ["0"]
  batch_size: 1000
  epochs: [10,10] 
  cluster_batch_size: 1000
  cluster_epochs: 30
  cluster_gauss_noise_stdev: [0.01]
  cluster_lambda: 1.0

  heir_cluster_min_samples: 1000
  heir_cluster_gauss_noise_stdev: [0.01] #[0.001, 0.0001, 0.00001, 0.000001, 0.0]
  heir_epochs: 30
  heir_tune_subtrees: False
  heir_tune_subtree_list: []
  heir_deep_cluster: 100
  stratify_data:
   kmeans: True

