
output:
 out_dir: "/data/nlahaye/output/Learnergy/DBN_PALM_OIL_AUTO_CLUST_ITER2/"
 training_output: "output.data"
 training_mse: "rec_mse.data"
 testing_output: "output_test.data"
 testing_mse: "rec_mse_test.data"
 model: "dbn"

dbn:
 subset_training: 1000000
 deep_cluster: 500
 overwrite_model: True
 params:
  model_type: ["gaussian_selu"] #, 'gaussian_relu_dropout', 'gaussian_relu_dropout'] #'variance_gaussian_dropout' "gaussian_dropout"
  dbn_arch: [5000] #[2000] [250, 500, 2000] #, 2000]
  gibbs_steps: [10] #, 7, 7] #, 10] #, 25]
  learning_rate: [0.0001] #, 0.0001, 0.0001] #, 0.01] #, 0.01]
  momentum: [0.5] #, 0.95, 0.95] #, 0.95] #, 0.95]
  decay: [0.0001] #, 0.0001, 0.0001] #, 0.0001] #, 0.0001]
  temp: [1.0] #, 1.0, 1.0] [0.9, 0.75, 0.5] #, 1.0] #, 0.5] #, 0.5] 
  nesterov_accel: [True]
  normalize_learnergy: [False]
  batch_normalize: [False]

 training:
  use_gpu: True
  use_gpu_preprocessing: False
  world_size: 1
  rank: 0
  device_ids: ["0","1"] #["4","5","6","7"]
  batch_size: 128
  epochs: [50] #[8] #, 1, 1] #, 5] #, 10]
  stratify_data: 
   reader: "gtiff"
   filename: ["/data/nlahaye/output/Learnergy/DBN_PALM_OIL_AUTO_CLUST/file_clust0_output_test.data_800clusters.zarr.palm_oil.tif"]
   reader_kwargs:
    None:
 

scaler:
 name: "standard"

data:
 num_loader_workers: 10
 scale_data: True
 pixel_padding: 2
 number_channels: 4
 fill_value: -9999.0
 valid_min: -10000.0
 valid_max: 100000000
 subset_count: 1
 output_subset_count: 5
 reader_type: "gtiff"
 reader_kwargs:
  no_arg: ''
 chan_dim: 0
 delete_chans: []
 transform_default:
  chans: []
  transform: []
 
 files_train: [
"/data/nlahaye/remoteSensing/Palm_Oil/ucayali_condensed_stacks_2020_h1v1.tiff"]


 files_test: [
"/data/nlahaye/remoteSensing/Palm_Oil/ucayali_condensed_stacks_2020_h1v1.tiff"]

