
output:
 out_dir: "/data/nlahaye/output/Learnergy/DBN_UAVSAR_LT_2_NORM/"
 training_output: "output.data"
 training_mse: "rec_mse.data"
 testing_output: "output_test.data"
 testing_mse: "rec_mse_test.data"
 model: "dbn"
 generate_train_output: False
 generate_output: False

dbn:
 conv: True
 subset_training: 2000000 #10000000
 deep_cluster: -1
 heir_tiers: 1
 overwrite_model: False
 tune_clust: False # True
 tune_dbn: False
 tune_scaler: False
 params:
  model_type: ["gaussian"] #["gaussian_selu"] #, 'gaussian_relu_dropout', 'gaussian_relu_dropout'] #'variance_gaussian_dropout' "gaussian_dropout"
  dbn_arch: [[3000],[[4,4]]] #[2000] [250, 500, 2000] #, 2000]
  gibbs_steps: [15] #, 7, 7] #, 10] #, 25]
  learning_rate: [0.000001] #, 0.0001, 0.0001] #, 0.01] #, 0.01]
  momentum: [0.95] #, 0.95, 0.95] #, 0.95] #, 0.95]
  decay: [0.0001] #, 0.0001, 0.0001] #, 0.0001] #, 0.0001]
  temp: [1.0] #, 1.0, 1.0] [0.9, 0.75, 0.5] #, 1.0] #, 0.5] #, 0.5] 
  nesterov_accel: [True]
  normalize_learnergy: [False]
  batch_normalize: [True]
  stride: [1]
  padding: [1]


 training:
  use_gpu: True
  use_gpu_preprocessing: False
  world_size: 1
  rank: 0
  device_ids: ["7"] #["3", "4"]
  batch_size: 128
  epochs: [50] #[8] #, 1, 1] #, 5] #, 10]
  cluster_batch_size: 900
  cluster_epochs: 100
  cluster_gauss_noise_stdev:  [0.01]
  cluster_lambda: 1.0

  heir_cluster_min_samples: 1000
  heir_cluster_gauss_noise_stdev: [0.01] #[0.001, 0.0001, 0.00001, 0.000001, 0.0]
  heir_epochs: 18
  heir_tune_subtrees: False
  heir_tune_subtree_list: []
  heir_deep_cluster: 100



scaler:
 name: "standard"


data:
 tile: True
 tile_size: [16,16,3]
 tile_step: [1,1,3]
 num_loader_workers: 10
 scale_data: True
 pixel_padding: 0
 number_channels: 3
 fill_value: -9999.0
 valid_min: 0
 valid_max: 100000000
 subset_count: 1
 output_subset_count: 1
 reader_type: "uavsar"
 reader_kwargs:
    ann_fps: ["/data/nlahaye/remoteSensing/UAVSAR/fire-scenes/L-band/SanAnd_26526_17122_004_171102_L090_CX_01/uavsar.asf.alaska.edu_UA_SanAnd_26526_17122_004_171102_L090_CX_01_SanAnd_26526_17122_004_171102_L090_CX_01.ann"
  ]
    pol_modes: ['HHHH','HVHV','VVVV']
    # row
    start_line: 5800
    end_line: 6350
    # col
    start_sample: 10800
    end_sample: 19400
    clip: True
 chan_dim: 0
 delete_chans: []
 transform_default:
  chans: []
  transform: []
 files_train: [["/data/nlahaye/remoteSensing/UAVSAR/fire-scenes/L-band/SanAnd_26526_17122_004_171102_L090_CX_01/SanAnd_26526_17122_004_171102_L090HHHH_CX_01.grd",
"/data/nlahaye/remoteSensing/UAVSAR/fire-scenes/L-band/SanAnd_26526_17122_004_171102_L090_CX_01/SanAnd_26526_17122_004_171102_L090HVHV_CX_01.grd",
"/data/nlahaye/remoteSensing/UAVSAR/fire-scenes/L-band/SanAnd_26526_17122_004_171102_L090_CX_01/SanAnd_26526_17122_004_171102_L090VVVV_CX_01.grd"
]]
 files_test: [["/data/nlahaye/remoteSensing/UAVSAR/fire-scenes/L-band/SanAnd_26526_17122_004_171102_L090_CX_01/SanAnd_26526_17122_004_171102_L090HHHH_CX_01.grd",
"/data/nlahaye/remoteSensing/UAVSAR/fire-scenes/L-band/SanAnd_26526_17122_004_171102_L090_CX_01/SanAnd_26526_17122_004_171102_L090HVHV_CX_01.grd",
"/data/nlahaye/remoteSensing/UAVSAR/fire-scenes/L-band/SanAnd_26526_17122_004_171102_L090_CX_01/SanAnd_26526_17122_004_171102_L090VVVV_CX_01.grd"
]] 

# ["/data/nlahaye/remoteSensing/UAVSAR/fire-scenes/P-band/safire_14036_15102_007_150705_PL09043020_XX_01/safire_14036_15102_007_150705_PL09043020_05HVHV_XX_01.grd",
# "/data/nlahaye/remoteSensing/UAVSAR/fire-scenes/P-band/safire_14036_15102_007_150705_PL09043020_XX_01/safire_14036_15102_007_150705_PL09043020_05VVVV_XX_01.grd",
# "/data/nlahaye/remoteSensing/UAVSAR/fire-scenes/P-band/safire_14036_15102_007_150705_PL09043020_XX_01/safire_14036_15102_007_150705_PL09043020_05HHHH_XX_01.grd",]
