
output:
 out_dir: "/data/nlahaye/output/Learnergy//DBN_S3B_OC_TROP_ONLY_AUTO_CLUST_PAD/"
 training_output: "output.data"
 training_mse: "rec_mse.data"
 testing_output: "output_test.data"
 testing_mse: "rec_mse_test.data"
 model: "dbn"
 generate_train_output: False
 generate_output: True

dbn:
 conv: False
 subset_training: -1 #2000000
 deep_cluster: 800
 heir_tiers: 1
 overwrite_model: False
 tune_clust: False
 tune_dbn: False
 tune_scaler: False
 params:
  model_type: ["gaussian_selu"] #, 'gaussian_relu_dropout', 'gaussian_relu_dropout'] #'variance_gaussian_dropout' "gaussian_dropout"
  dbn_arch: [2000] #[2000] [250, 500, 2000] #, 2000]
  gibbs_steps: [1] #, 7, 7] #, 10] #, 25]
  learning_rate: [0.00001] #, 0.0001, 0.0001] #, 0.01] #, 0.01]
  momentum: [0.95] #, 0.95, 0.95] #, 0.95] #, 0.95]
  decay: [0.0001] #, 0.0001, 0.0001] #, 0.0001] #, 0.0001]
  temp: [1.0] #, 1.0, 1.0] [0.9, 0.75, 0.5] #, 1.0] #, 0.5] #, 0.5] 
  nesterov_accel: [True]
  normalize_learnergy: [False]
  batch_normalize: [False]

 training:
  use_gpu: True
  use_gpu_preprocessing: False
  world_size: 1
  rank: 0
  device_ids: ["2"]
  batch_size: 1000
  epochs: [10] #[40] #[8] #, 1, 1] #, 5] #, 10]
  cluster_batch_size: 1000
  cluster_epochs: 30
  cluster_gauss_noise_stdev: [0.01] #[0.001, 0.0001, 0.00001, 0.000001, 0.0]
  cluster_lambda: 1.0

  heir_cluster_min_samples: 1000
  heir_cluster_gauss_noise_stdev: [0.01] #[0.001, 0.0001, 0.00001, 0.000001, 0.0]
  heir_epochs: 30
  heir_tune_subtrees: False
  heir_tune_subtree_list: []
  heir_deep_cluster: 100
  #stratify_data:
  # kmeans: True

scaler:
 name: "standard"

data:
 tile: True
 tile_size: [3,3,32]
 tile_step: [1,1,32]
 num_loader_workers: 10
 scale_data: True
 pixel_padding: 1
 number_channels: 1
 fill_value: -999999.0
 valid_min: -10000.0
 valid_max: 6400000
 subset_count: 1
 output_subset_count: 1
 reader_type: "oc_and_trop"
 reader_kwargs: 
  start_lon: -83.491547
  end_lon: -81.637247
  start_lat: 25.905156
  end_lat: 28.314978
  #mask_shp: "/data/nlahaye/remoteSensing/Lakes/glwd_1.shp"
  mask_oceans: True
 chan_dim: 0
 delete_chans: [0,1,2,3,4,5,6]
 transform_default:
  chans: []
  transform: []

 files_test: [
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180930.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-09-30_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181001.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-01_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181002.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-02_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181003.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-03_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181004.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-04_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181005.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-05_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181006.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-06_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181007.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-07_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181008.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-08_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181009.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-09_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181010.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-10_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181011.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-11_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181012.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-12_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181013.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-13_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181014.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-14_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181015.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-15_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181016.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-16_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181017.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-17_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181018.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-18_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181019.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-19_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181020.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-20_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181021.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-21_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181022.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-22_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181023.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-23_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181024.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-24_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181025.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-25_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181026.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-26_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181027.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-27_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181028.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-28_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181029.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-29_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181030.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-30_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181031.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-31_ungridded.nc"]]


 files_train: [
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20180930.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-09-30_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181001.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-01_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181002.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-02_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181003.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-03_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181004.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-04_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181005.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-05_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181006.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-06_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181007.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-07_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181008.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-08_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181009.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-09_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181010.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-10_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181011.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-11_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181012.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-12_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181013.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-13_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181014.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-14_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181015.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-15_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181016.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-16_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181017.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-17_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181018.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-18_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181019.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-19_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181020.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-20_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181021.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-21_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181022.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-22_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181023.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-23_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181024.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-24_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181025.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-25_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181026.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-26_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181027.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-27_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181028.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-28_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181029.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-29_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181030.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-30_ungridded.nc"],
["/data/nlahaye/remoteSensing/Multi_Year_WQ/SNPP_VIIRS.20181031.L3m.DAY.", "/data/nlahaye/remoteSensing/TROPOMI_MODIS_HAB/TROPO_SIF_2018-10-31_ungridded.nc"]]





