
output:
 out_dir: "/data/nlahaye/output/Learnergy/DBN_VIIRS_CANADA_PAD/"
 training_output: "output.data"
 training_mse: "rec_mse.data"
 testing_output: "output_test.data"
 testing_mse: "rec_mse_test.data"
 model: "dbn"
 generate_train_output: True
 generate_output: True

dbn:
 conv: False
 subset_training: 2000000
 deep_cluster: 800
 heir_tiers: 1
 overwrite_model: False
 tune_clust: False
 tune_dbn: False
 tune_scaler: False
 params:
  model_type: ["gaussian_selu"] #, 'gaussian_relu_dropout', 'gaussian_relu_dropout'] #'variance_gaussian_dropout' "gaussian_dropout"
  dbn_arch: [2000] #[2000] [250, 500, 2000] #, 2000]
  gibbs_steps: [1] #, 7, 7] #, 10] #, 25]
  learning_rate: [0.00001] #, 0.0001, 0.0001] #, 0.01] #, 0.01]
  momentum: [0.95] #, 0.95, 0.95] #, 0.95] #, 0.95]
  decay: [0.0001] #, 0.0001, 0.0001] #, 0.0001] #, 0.0001]
  temp: [1.0] #, 1.0, 1.0] [0.9, 0.75, 0.5] #, 1.0] #, 0.5] #, 0.5] 
  nesterov_accel: [True]
  normalize_learnergy: [False]
  batch_normalize: [False]

 training:
  use_gpu: True
  use_gpu_preprocessing: False
  world_size: 1
  rank: 0
  device_ids: ["0"]
  batch_size: 1000
  epochs: [10] #[40] #[8] #, 1, 1] #, 5] #, 10]
  cluster_batch_size: 1000
  cluster_epochs: 30
  cluster_gauss_noise_stdev: [0.01] #[0.001, 0.0001, 0.00001, 0.000001, 0.0]
  cluster_lambda: 1.0

  heir_cluster_min_samples: 1000
  heir_cluster_gauss_noise_stdev: [0.01] #[0.001, 0.0001, 0.00001, 0.000001, 0.0]
  heir_epochs: 30
  heir_tune_subtrees: False
  heir_tune_subtree_list: []
  heir_deep_cluster: 100
  stratify_data:
   kmeans: True

scaler:
 name: "standard"

data:
 tile: True
 tile_size: [3,3,32]
 tile_step: [1,1,32]
 num_loader_workers: 10
 scale_data: True
 pixel_padding: 1
 number_channels: 22
 fill_value: -999999.0
 valid_min: -100.0
 valid_max: 64000
 subset_count: 1
 output_subset_count: 1
 reader_type: "zarr_to_numpy"
 reader_kwargs:
  no_arg: "no_arg"
 chan_dim: 0
 delete_chans: [15]
 transform_default:
  chans: []
  transform: []

 files_train: [
"/data/nlahaye/remoteSensing/CSDSA/MODIS_VIIRS_Canada/noaa20_viirs_m01_20230622_164800_wgs84_fit.tif.zarr"
#"/data/nlahaye/remoteSensing/CSDSA/MODIS_VIIRS_Canada/npp_viirs_m01_20230622_060600_wgs84_fit.tif.zarr"
#"/data/nlahaye/remoteSensing/CSDSA/MODIS_VIIRS_Canada/noaa20_viirs_m01_20230623_081800_wgs84_fit.tif.zarr"
#"/data/nlahaye/remoteSensing/CSDSA/MODIS_VIIRS_Canada/npp_viirs_m01_20230623_171800_wgs84_fit.tif.zarr"
] 

 files_test: [
#"/data/nlahaye/remoteSensing/CSDSA/MODIS_VIIRS_Canada/noaa20_viirs_m01_20230623_081800_wgs84_fit.tif.zarr",
#"/data/nlahaye/remoteSensing/CSDSA/MODIS_VIIRS_Canada/npp_viirs_m01_20230623_171800_wgs84_fit.tif.zarr",
"/data/nlahaye/remoteSensing/CSDSA/MODIS_VIIRS_Canada/npp_viirs_m01_20230623_171800_wgs84_fit.tif.zarr",
"/data/nlahaye/remoteSensing/CSDSA/MODIS_VIIRS_Canada/npp_viirs_m01_20230624_170000_wgs84_fit.tif.zarr",
"/data/nlahaye/remoteSensing/CSDSA/MODIS_VIIRS_Canada/noaa20_viirs_m01_20230622_182400_wgs84_fit.tif.zarr",
"/data/nlahaye/remoteSensing/CSDSA/MODIS_VIIRS_Canada/npp_viirs_m01_20230623_190000_wgs84_fit.tif.zarr",
"/data/nlahaye/remoteSensing/CSDSA/MODIS_VIIRS_Canada/noaa20_viirs_m01_20230622_083600_wgs84_fit.tif.zarr",
"/data/nlahaye/remoteSensing/CSDSA/MODIS_VIIRS_Canada/noaa20_viirs_m01_20230622_183000_wgs84_fit.tif.zarr",
"/data/nlahaye/remoteSensing/CSDSA/MODIS_VIIRS_Canada/noaa20_viirs_m01_20230623_163000_wgs84_fit.tif.zarr",
"/data/nlahaye/remoteSensing/CSDSA/MODIS_VIIRS_Canada/npp_viirs_m01_20230623_073000_wgs84_fit.tif.zarr",
"/data/nlahaye/remoteSensing/CSDSA/MODIS_VIIRS_Canada/noaa20_viirs_m01_20230623_180600_wgs84_fit.tif.zarr",
"/data/nlahaye/remoteSensing/CSDSA/MODIS_VIIRS_Canada/noaa20_viirs_m01_20230624_161200_wgs84_fit.tif.zarr",
"/data/nlahaye/remoteSensing/CSDSA/MODIS_VIIRS_Canada/npp_viirs_m01_20230624_184200_wgs84_fit.tif.zarr",
"/data/nlahaye/remoteSensing/CSDSA/MODIS_VIIRS_Canada/noaa20_viirs_m01_20230624_174800_wgs84_fit.tif.zarr",
"/data/nlahaye/remoteSensing/CSDSA/MODIS_VIIRS_Canada/noaa20_viirs_m01_20230624_080000_wgs84_fit.tif.zarr",
"/data/nlahaye/remoteSensing/CSDSA/MODIS_VIIRS_Canada/npp_viirs_m01_20230622_074800_wgs84_fit.tif.zarr",
"/data/nlahaye/remoteSensing/CSDSA/MODIS_VIIRS_Canada/npp_viirs_m01_20230622_173600_wgs84_fit.tif.zarr",
"/data/nlahaye/remoteSensing/CSDSA/MODIS_VIIRS_Canada/npp_viirs_m01_20230623_054800_wgs84_fit.tif.zarr"
]
