
dbf: True
dbf_list: [["/data/nlahaye/output/DBFs/Background_DBFs/Background_19910_06_Output.dbf",
"/data/nlahaye/output/DBFs/Background_DBFs/Background_19910_08_Output.dbf",
"/data/nlahaye/output/DBFs/Background_DBFs/Background_19910_10_Output.dbf",
"/data/nlahaye/output/DBFs/Background_DBFs/Background_19910_13_Output.dbf",
"/data/nlahaye/output/DBFs/Background_DBFs/Background_19910_14_Output.dbf",
"/data/nlahaye/output/DBFs/Background_DBFs/Background_19910_15_Output.dbf",
"/data/nlahaye/output/DBFs/Background_DBFs/Background_19910_16_Output.dbf",
"/data/nlahaye/output/DBFs/Background_DBFs/Background_19910_17_Output.dbf",
"/data/nlahaye/output/DBFs/Background_DBFs/Background_19910_18_Output.dbf",
"/data/nlahaye/output/DBFs/Background_DBFs/Background_19910_19_Output.dbf",
"/data/nlahaye/output/DBFs/Background_DBFs/Background_19910_20_Output.dbf",
"/data/nlahaye/output/DBFs/Background_DBFs/Background_19910_21_Output.dbf",
"/data/nlahaye/output/DBFs/Background_DBFs/Background_19911_05_Output.dbf",
"/data/nlahaye/output/DBFs/Background_DBFs/Background_19911_08_Output.dbf",
"/data/nlahaye/output/DBFs/Background_DBFs/Background_19911_09_Output.dbf",
"/data/nlahaye/output/DBFs/Background_DBFs/Background_19911_10_Output.dbf",
"/data/nlahaye/output/DBFs/Background_DBFs/Background_19911_11_Output.dbf",
"/data/nlahaye/output/DBFs/Background_DBFs/Background_19911_12_Output.dbf",
"/data/nlahaye/output/DBFs/Background_DBFs/Background_19912_07_Output.dbf"],
["/data/nlahaye/output/DBFs/Fire_DBFs/Fire_19910_06_Output.dbf",
"/data/nlahaye/output/DBFs/Fire_DBFs/Fire_19910_08_Output.dbf",
"/data/nlahaye/output/DBFs/Fire_DBFs/Fire_19910_10_Output.dbf",
"",
"/data/nlahaye/output/DBFs/Fire_DBFs/Fire_19910_14_Output.dbf",
"/data/nlahaye/output/DBFs/Fire_DBFs/Fire_19910_15_Output.dbf",
"/data/nlahaye/output/DBFs/Fire_DBFs/Fire_19910_16_Output.dbf",
"/data/nlahaye/output/DBFs/Fire_DBFs/Fire_19910_17_Output.dbf",
"/data/nlahaye/output/DBFs/Fire_DBFs/Fire_19910_18_Output.dbf",
"/data/nlahaye/output/DBFs/Fire_DBFs/Fire_19910_19_Output.dbf",
"/data/nlahaye/output/DBFs/Fire_DBFs/Fire_19910_20_Output.dbf",
"/data/nlahaye/output/DBFs/Fire_DBFs/Fire_19910_21_Output.dbf",
"/data/nlahaye/output/DBFs/Fire_DBFs/Fire_19911_05_Output.dbf",
"/data/nlahaye/output/DBFs/Fire_DBFs/Fire_19911_08_Output.dbf",
"/data/nlahaye/output/DBFs/Fire_DBFs/Fire_19911_09_Output.dbf",
"/data/nlahaye/output/DBFs/Fire_DBFs/Fire_19911_10_Output.dbf",
"/data/nlahaye/output/DBFs/Fire_DBFs/Fire_19911_11_Output.dbf",
"/data/nlahaye/output/DBFs/Fire_DBFs/Fire_19911_12_Output.dbf",
"/data/nlahaye/output/DBFs/Fire_DBFs/Fire_19912_07_Output.dbf"],
#["/data/nlahaye/output/DBFs/Burn_Scar_DBFs/Burn_Scar_19910_06_Output.dbf",
#"/data/nlahaye/output/DBFs/Burn_Scar_DBFs/Burn_Scar_19910_08_Output.dbf",
#"/data/nlahaye/output/DBFs/Burn_Scar_DBFs/Burn_Scar_19910_10_Output.dbf",
#"",
#"/data/nlahaye/output/DBFs/Burn_Scar_DBFs/Burn_Scar_19910_14_Output.dbf",
#"/data/nlahaye/output/DBFs/Burn_Scar_DBFs/Burn_Scar_19910_15_Output.dbf",
#"/data/nlahaye/output/DBFs/Burn_Scar_DBFs/Burn_Scar_19910_16_Output.dbf",
#"/data/nlahaye/output/DBFs/Burn_Scar_DBFs/Burn_Scar_19910_17_Output.dbf",
#"/data/nlahaye/output/DBFs/Burn_Scar_DBFs/Burn_Scar_19910_18_Output.dbf",
#"/data/nlahaye/output/DBFs/Burn_Scar_DBFs/Burn_Scar_19910_19_Output.dbf",
#"/data/nlahaye/output/DBFs/Burn_Scar_DBFs/Burn_Scar_19910_20_Output.dbf",
#"/data/nlahaye/output/DBFs/Burn_Scar_DBFs/Burn_Scar_19910_21_Output.dbf",
#"/data/nlahaye/output/DBFs/Burn_Scar_DBFs/Burn_Scar_19911_05_Output.dbf",
#"/data/nlahaye/output/DBFs/Burn_Scar_DBFs/Burn_Scar_19911_08_Output.dbf",
#"/data/nlahaye/output/DBFs/Burn_Scar_DBFs/Burn_Scar_19911_09_Output.dbf",
#"/data/nlahaye/output/DBFs/Burn_Scar_DBFs/Burn_Scar_19911_10_Output.dbf",
#"/data/nlahaye/output/DBFs/Burn_Scar_DBFs/Burn_Scar_19911_11_Output.dbf",
#"/data/nlahaye/output/DBFs/Burn_Scar_DBFs/Burn_Scar_19911_12_Output.dbf",
#""],
["/data/nlahaye/output/DBFs/Smoke_DBFs/Smoke_19910_06_Output.dbf",
"/data/nlahaye/output/DBFs/Smoke_DBFs/Smoke_19910_08_Output.dbf",
"/data/nlahaye/output/DBFs/Smoke_DBFs/Smoke_19910_10_Output.dbf",
"/data/nlahaye/output/DBFs/Smoke_DBFs/Smoke_19910_13_Output.dbf",
"/data/nlahaye/output/DBFs/Smoke_DBFs/Smoke_19910_14_Output.dbf",
"",
"/data/nlahaye/output/DBFs/Smoke_DBFs/Smoke_19910_16_Output.dbf",
"/data/nlahaye/output/DBFs/Smoke_DBFs/Smoke_19910_17_Output.dbf",
"/data/nlahaye/output/DBFs/Smoke_DBFs/Smoke_19910_18_Output.dbf",
"/data/nlahaye/output/DBFs/Smoke_DBFs/Smoke_19910_19_Output.dbf",
"/data/nlahaye/output/DBFs/Smoke_DBFs/Smoke_19910_20_Output.dbf",
"/data/nlahaye/output/DBFs/Smoke_DBFs/Smoke_19910_21_Output.dbf",
"/data/nlahaye/output/DBFs/Smoke_DBFs/Smoke_19911_05_Output.dbf",
"/data/nlahaye/output/DBFs/Smoke_DBFs/Smoke_19911_08_Output.dbf",
"/data/nlahaye/output/DBFs/Smoke_DBFs/Smoke_19911_09_Output.dbf",
"/data/nlahaye/output/DBFs/Smoke_DBFs/Smoke_19911_10_Output.dbf",
"/data/nlahaye/output/DBFs/Smoke_DBFs/Smoke_19911_11_Output.dbf",
"/data/nlahaye/output/DBFs/Smoke_DBFs/Smoke_19911_12_Output.dbf",
"/data/nlahaye/output/DBFs/Smoke_DBFs/Smoke_19912_07_Output.dbf"]]
 


