
gen_from_geotiffs: false

data:
 clust_reader_type: "zarr_to_numpy"
 reader_kwargs:
   no_arg: "no_arg" 
 subset_inds: [[],[],[],[],[],[],[],[]]
 create_separate: true
   
 gtiff_data: [
"/data/nlahaye/remoteSensing/CSDSA/Korea/Sentinel2L1C/T52SDF_20220305T020701_B01_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Korea/Sentinel2L1C/T52SDG_20220305T020701_B01_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Korea/Sentinel2L1C/T52SEF_20220305T020701_B01_clip.tif",
"/data/nlahaye/remoteSensing/CSDSA/Korea/Sentinel2L1C/T52SEG_20220305T020701_B01_clip.tif"
]


 cluster_fnames: [
"data/nlahaye/output/Learnergy/S2_KOREA_2/T52SDF_20220305T020701_B01_clip.tif.heir_clust2output_test.data_7930000clusters.zarr",
"/data/nlahaye/output/Learnergy/S2_KOREA_2/T52SDG_20220305T020701_B01_clip.tif.heir_clust2output_test.data_7930000clusters.zarr",
"/data/nlahaye/output/Learnergy/S2_KOREA_2/T52SEF_20220305T020701_B01_clip.tif.heir_clust2output_test.data_7930000clusters.zarr",
"/data/nlahaye/output/Learnergy/S2_KOREA_2/T52SEG_20220305T020701_B01_clip.tif.heir_clust2output.data_7930000clusters.zarr"
]

context:
 apply_context: false
 clusters: [] #i.e. smoke clusters
 name: "" #i.e. smoke
 compare_truth: false
 generate_union: false

